/* Auto-generated from gpu_sha256unsalted.cl -- do not edit */
static const char gpu_sha256unsalted_str[] =
    "/* gpu_sha256unsalted.cl — Pre-padded unsalted SHA256 with mask expansion\n"
    " *\n"
    " * Input: 4096 pre-padded 64-byte M[] blocks in passbuf (word_stride=64).\n"
    " *   Packed by gpu_try_pack_unsalted() in little-endian format:\n"
    " *   password at offset n_prepend, 0x80 padding, M[14]=bitlen (LE).\n"
    " *   Kernel byte-swaps to big-endian before SHA256 compress.\n"
    " *\n"
    " * Dispatch: num_words × num_masks threads.\n"
    " * Hit stride: 6 (word_idx, mask_idx, h0, h1, h2, h3)\n"
    " */\n"
    "\n"
    "\n"
    "uint bswap32(uint x) {\n"
    "    return ((x >> 24) & 0xffu) | ((x >> 8) & 0xff00u) |\n"
    "           ((x << 8) & 0xff0000u) | ((x << 24) & 0xff000000u);\n"
    "}\n"
    "\n"
    "__constant uint K256[64] = {\n"
    "    0x428a2f98u, 0x71374491u, 0xb5c0fbcfu, 0xe9b5dba5u,\n"
    "    0x3956c25bu, 0x59f111f1u, 0x923f82a4u, 0xab1c5ed5u,\n"
    "    0xd807aa98u, 0x12835b01u, 0x243185beu, 0x550c7dc3u,\n"
    "    0x72be5d74u, 0x80deb1feu, 0x9bdc06a7u, 0xc19bf174u,\n"
    "    0xe49b69c1u, 0xefbe4786u, 0x0fc19dc6u, 0x240ca1ccu,\n"
    "    0x2de92c6fu, 0x4a7484aau, 0x5cb0a9dcu, 0x76f988dau,\n"
    "    0x983e5152u, 0xa831c66du, 0xb00327c8u, 0xbf597fc7u,\n"
    "    0xc6e00bf3u, 0xd5a79147u, 0x06ca6351u, 0x14292967u,\n"
    "    0x27b70a85u, 0x2e1b2138u, 0x4d2c6dfcu, 0x53380d13u,\n"
    "    0x650a7354u, 0x766a0abbu, 0x81c2c92eu, 0x92722c85u,\n"
    "    0xa2bfe8a1u, 0xa81a664bu, 0xc24b8b70u, 0xc76c51a3u,\n"
    "    0xd192e819u, 0xd6990624u, 0xf40e3585u, 0x106aa070u,\n"
    "    0x19a4c116u, 0x1e376c08u, 0x2748774cu, 0x34b0bcb5u,\n"
    "    0x391c0cb3u, 0x4ed8aa4au, 0x5b9cca4fu, 0x682e6ff3u,\n"
    "    0x748f82eeu, 0x78a5636fu, 0x84c87814u, 0x8cc70208u,\n"
    "    0x90befffau, 0xa4506cebu, 0xbef9a3f7u, 0xc67178f2u\n"
    "};\n"
    "\n"
    "void sha256_compress(uint *state, uint *M) {\n"
    "    uint W[64];\n"
    "    for (int i = 0; i < 16; i++) W[i] = M[i];\n"
    "    for (int i = 16; i < 64; i++) {\n"
    "        uint s0 = rotate(W[i-15], (uint)25) ^ rotate(W[i-15], (uint)14) ^ (W[i-15] >> 3);\n"
    "        uint s1 = rotate(W[i-2], (uint)15) ^ rotate(W[i-2], (uint)13) ^ (W[i-2] >> 10);\n"
    "        W[i] = W[i-16] + s0 + W[i-7] + s1;\n"
    "    }\n"
    "\n"
    "    uint a = state[0], b = state[1], c = state[2], d = state[3];\n"
    "    uint e = state[4], f = state[5], g = state[6], h = state[7];\n"
    "\n"
    "    for (int i = 0; i < 64; i++) {\n"
    "        uint S1 = rotate(e, (uint)26) ^ rotate(e, (uint)21) ^ rotate(e, (uint)7);\n"
    "        uint ch = (e & f) ^ (~e & g);\n"
    "        uint t1 = h + S1 + ch + K256[i] + W[i];\n"
    "        uint S0 = rotate(a, (uint)30) ^ rotate(a, (uint)19) ^ rotate(a, (uint)10);\n"
    "        uint maj = (a & b) ^ (a & c) ^ (b & c);\n"
    "        uint t2 = S0 + maj;\n"
    "        h = g; g = f; f = e; e = d + t1;\n"
    "        d = c; c = b; b = a; a = t1 + t2;\n"
    "    }\n"
    "\n"
    "    state[0] += a; state[1] += b; state[2] += c; state[3] += d;\n"
    "    state[4] += e; state[5] += f; state[6] += g; state[7] += h;\n"
    "}\n"
    "\n"
    "__kernel void sha256_unsalted_batch(\n"
    "    __global const uint *words,\n"
    "    __global const ushort *unused_lens,\n"
    "    __global const uchar *mask_desc,\n"
    "    __global const uint *unused1, __global const ushort *unused2,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    uint mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    __global const uint *src = words + word_idx * 16;\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    /* Fill mask positions — LE words, same as MD5 kernel */\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint append_combos = 1;\n"
    "        for (uint i = 0; i < n_app; i++)\n"
    "            append_combos *= mask_desc[n_pre + i];\n"
    "\n"
    "        uint prepend_idx = mask_idx / append_combos;\n"
    "        uint append_idx = mask_idx % append_combos;\n"
    "\n"
    "        if (n_pre > 0) {\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uint n_total_m = n_pre + n_app;\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                M[i >> 2] = (M[i >> 2] & ~(0xFFu << ((i & 3) << 3)))\n"
    "                           | ((uint)ch << ((i & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "\n"
    "        if (n_app > 0) {\n"
    "            int total_len = M[14] >> 3;\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint aidx = append_idx;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                int pos_idx = n_pre + i;\n"
    "                uint sz = mask_desc[pos_idx];\n"
    "                uint n_total_m = n_pre + n_app;\n"
    "                uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                aidx /= sz;\n"
    "                int pos = app_start + i;\n"
    "                M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                             | ((uint)ch << ((pos & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    uint bitlen = M[14];\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap32(M[i]);\n"
    "    M[14] = 0;\n"
    "    M[15] = bitlen;\n"
    "\n"
    "    uint state[8] = {\n"
    "        0x6a09e667u, 0xbb67ae85u, 0x3c6ef372u, 0xa54ff53au,\n"
    "        0x510e527fu, 0x9b05688cu, 0x1f83d9abu, 0x5be0cd19u\n"
    "    };\n"
    "    sha256_compress(state, M);\n"
    "\n"
    "    uint hx = bswap32(state[0]), hy = bswap32(state[1]);\n"
    "    uint hz = bswap32(state[2]), hw = bswap32(state[3]);\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 6;\n"
    "            hits[base]   = word_idx;\n"
    "            hits[base+1] = mask_idx;\n"
    "            hits[base+2] = hx;\n"
    "            hits[base+3] = hy;\n"
    "            hits[base+4] = hz;\n"
    "            hits[base+5] = hw;\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* SHA224 — same compress as SHA256, different IV, truncated output (28 bytes) */\n"
    "__kernel void sha224_unsalted_batch(\n"
    "    __global const uint *words,\n"
    "    __global const ushort *unused_lens,\n"
    "    __global const uchar *mask_desc,\n"
    "    __global const uint *unused1, __global const ushort *unused2,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    uint mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    __global const uint *src = words + word_idx * 16;\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint append_combos = 1;\n"
    "        for (uint i = 0; i < n_app; i++)\n"
    "            append_combos *= mask_desc[n_pre + i];\n"
    "        uint prepend_idx = mask_idx / append_combos;\n"
    "        uint append_idx = mask_idx % append_combos;\n"
    "        if (n_pre > 0) {\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uint n_total_m = n_pre + n_app;\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                M[i >> 2] = (M[i >> 2] & ~(0xFFu << ((i & 3) << 3)))\n"
    "                           | ((uint)ch << ((i & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "        if (n_app > 0) {\n"
    "            int total_len = M[14] >> 3;\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint aidx = append_idx;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                int pos_idx = n_pre + i;\n"
    "                uint sz = mask_desc[pos_idx];\n"
    "                uint n_total_m = n_pre + n_app;\n"
    "                uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                aidx /= sz;\n"
    "                int pos = app_start + i;\n"
    "                M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                             | ((uint)ch << ((pos & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    uint bitlen = M[14];\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap32(M[i]);\n"
    "    M[14] = 0;\n"
    "    M[15] = bitlen;\n"
    "\n"
    "    uint state[8] = {\n"
    "        0xc1059ed8u, 0x367cd507u, 0x3070dd17u, 0xf70e5939u,\n"
    "        0xffc00b31u, 0x68581511u, 0x64f98fa7u, 0xbefa4fa4u\n"
    "    };\n"
    "    sha256_compress(state, M);\n"
    "\n"
    "    uint hx = bswap32(state[0]), hy = bswap32(state[1]);\n"
    "    uint hz = bswap32(state[2]), hw = bswap32(state[3]);\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 6;\n"
    "            hits[base]   = word_idx;\n"
    "            hits[base+1] = mask_idx;\n"
    "            hits[base+2] = hx;\n"
    "            hits[base+3] = hy;\n"
    "            hits[base+4] = hz;\n"
    "            hits[base+5] = hw;\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- SHA256RAW: sha256(sha256_binary(pass)) with binary iteration ----\n"
    " *\n"
    " * For hashcat modes 21400, 30420. With -i N, iterates N times on\n"
    " * binary 32-byte output: sha256(sha256(...sha256(pass)...))\n"
    " * Second+ iterations always hash exactly 32 bytes (single block, fixed padding).\n"
    " * Hit stride: 6 (word_idx, mask_idx, hx, hy, hz, hw)\n"
    " */\n"
    "__kernel void sha256raw_unsalted_batch(\n"
    "    __global const uint *words,\n"
    "    __global const ushort *unused_lens,\n"
    "    __global const uchar *mask_desc,\n"
    "    __global const uint *unused1, __global const ushort *unused2,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    uint mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    __global const uint *src = words + word_idx * 16;\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint append_combos = 1;\n"
    "        for (uint i = 0; i < n_app; i++)\n"
    "            append_combos *= mask_desc[n_pre + i];\n"
    "        uint prepend_idx = mask_idx / append_combos;\n"
    "        uint append_idx = mask_idx % append_combos;\n"
    "        if (n_pre > 0) {\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uint n_total_m = n_pre + n_app;\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                M[i >> 2] = (M[i >> 2] & ~(0xFFu << ((i & 3) << 3)))\n"
    "                           | ((uint)ch << ((i & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "        if (n_app > 0) {\n"
    "            int total_len = M[14] >> 3;\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint aidx = append_idx;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                int pos_idx = n_pre + i;\n"
    "                uint sz = mask_desc[pos_idx];\n"
    "                uint n_total_m = n_pre + n_app;\n"
    "                uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                aidx /= sz;\n"
    "                int pos = app_start + i;\n"
    "                M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                             | ((uint)ch << ((pos & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* First: SHA256(password) from pre-padded block */\n"
    "    uint bitlen_orig = M[14];\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap32(M[i]);\n"
    "    M[14] = 0; M[15] = bitlen_orig;\n"
    "\n"
    "    uint state[8] = {\n"
    "        0x6a09e667u, 0xbb67ae85u, 0x3c6ef372u, 0xa54ff53au,\n"
    "        0x510e527fu, 0x9b05688cu, 0x1f83d9abu, 0x5be0cd19u\n"
    "    };\n"
    "    sha256_compress(state, M);\n"
    "\n"
    "    /* Binary iterations: sha256(32-byte binary output).\n"
    "     * 32 bytes + 0x80 + zeros + bit-length 256 at M[15] — single block. */\n"
    "    uint max_i = params.max_iter;\n"
    "    if (max_i < 1) max_i = 1;\n"
    "    for (uint iter = 1; iter <= max_i; iter++) {\n"
    "        /* Pack state (BE) into M[] — already big-endian from compress */\n"
    "        for (int i = 0; i < 8; i++) M[i] = state[i];\n"
    "        M[8] = 0x80000000u;  /* 0x80 in high byte (BE) */\n"
    "        for (int i = 9; i < 15; i++) M[i] = 0;\n"
    "        M[15] = 256;  /* 32 bytes * 8 bits */\n"
    "\n"
    "        state[0] = 0x6a09e667u; state[1] = 0xbb67ae85u;\n"
    "        state[2] = 0x3c6ef372u; state[3] = 0xa54ff53au;\n"
    "        state[4] = 0x510e527fu; state[5] = 0x9b05688cu;\n"
    "        state[6] = 0x1f83d9abu; state[7] = 0x5be0cd19u;\n"
    "        sha256_compress(state, M);\n"
    "\n"
    "        uint hx = bswap32(state[0]), hy = bswap32(state[1]);\n"
    "        uint hz = bswap32(state[2]), hw = bswap32(state[3]);\n"
    "\n"
    "        if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                          params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                          hash_data_buf, hash_data_off,\n"
    "                          overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "            uint slot = atomic_add(hit_count, 1u);\n"
    "            if (slot < params.max_hits) {\n"
    "                uint base = slot * 6;\n"
    "                hits[base]   = word_idx;\n"
    "                hits[base+1] = mask_idx;\n"
    "                hits[base+2] = hx;\n"
    "                hits[base+3] = hy;\n"
    "                hits[base+4] = hz;\n"
    "                hits[base+5] = hw;\n"
    "                mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "}\n"
;
