/* Auto-generated from gpu_hmac_rmd160.cl -- do not edit */
static const char gpu_hmac_rmd160_str[] =
    "/* gpu_hmac_rmd160.cl -- HMAC-RIPEMD-160 GPU kernels\n"
    " *\n"
    " * hmac_rmd160_ksalt_batch: HMAC-RMD160 key=$salt (e211, hashcat 6060)\n"
    " *   Key = salt (from Typeuser), Message = password\n"
    " *\n"
    " * hmac_rmd160_kpass_batch: HMAC-RMD160 key=$pass (e798, hashcat 6050)\n"
    " *   Key = password, Message = salt (from Typesalt)\n"
    " *\n"
    " * HMAC(K, M) = RMD160((K ^ opad) || RMD160((K ^ ipad) || M))\n"
    " * Block size = 64 bytes, output = 20 bytes (5 x uint32)\n"
    " * ipad = 0x36, opad = 0x5c\n"
    " * RIPEMD-160 is little-endian -- no bswap needed for key/ipad/opad blocks.\n"
    " *\n"
    " * Hit stride: 7 (word_idx, salt_idx, iter, h0, h1, h2, h3)\n"
    " * Compact probe: h[0..3] directly (LE, no bswap)\n"
    " */\n"
    "\n"
    "/* ---- RIPEMD-160 boolean functions ---- */\n"
    "\n"
    "#define RMD_F1(x, y, z) ((x) ^ (y) ^ (z))\n"
    "#define RMD_F2(x, y, z) ((((y) ^ (z)) & (x)) ^ (z))\n"
    "#define RMD_F3(x, y, z) (((x) | ~(y)) ^ (z))\n"
    "#define RMD_F4(x, y, z) ((((x) ^ (y)) & (z)) ^ (y))\n"
    "#define RMD_F5(x, y, z) ((x) ^ ((y) | ~(z)))\n"
    "\n"
    "#define RMD_STEP(FUNC, A, B, C, D, E, X, S, K) \\\n"
    "    (A) += FUNC((B), (C), (D)) + (X) + K; \\\n"
    "    (A) = rotate((A), (uint)(S)) + (E); \\\n"
    "    (C) = rotate((C), (uint)10);\n"
    "\n"
    "/* Left-half round macros */\n"
    "#define L1(A, B, C, D, E, X, S) RMD_STEP(RMD_F1, A, B, C, D, E, X, S, 0u)\n"
    "#define L2(A, B, C, D, E, X, S) RMD_STEP(RMD_F2, A, B, C, D, E, X, S, 0x5a827999u)\n"
    "#define L3(A, B, C, D, E, X, S) RMD_STEP(RMD_F3, A, B, C, D, E, X, S, 0x6ed9eba1u)\n"
    "#define L4(A, B, C, D, E, X, S) RMD_STEP(RMD_F4, A, B, C, D, E, X, S, 0x8f1bbcdcu)\n"
    "#define L5(A, B, C, D, E, X, S) RMD_STEP(RMD_F5, A, B, C, D, E, X, S, 0xa953fd4eu)\n"
    "\n"
    "/* Right-half round macros */\n"
    "#define R1(A, B, C, D, E, X, S) RMD_STEP(RMD_F5, A, B, C, D, E, X, S, 0x50a28be6u)\n"
    "#define R2(A, B, C, D, E, X, S) RMD_STEP(RMD_F4, A, B, C, D, E, X, S, 0x5c4dd124u)\n"
    "#define R3(A, B, C, D, E, X, S) RMD_STEP(RMD_F3, A, B, C, D, E, X, S, 0x6d703ef3u)\n"
    "#define R4(A, B, C, D, E, X, S) RMD_STEP(RMD_F2, A, B, C, D, E, X, S, 0x7a6d76e9u)\n"
    "#define R5(A, B, C, D, E, X, S) RMD_STEP(RMD_F1, A, B, C, D, E, X, S, 0u)\n"
    "\n"
    "/* ---- RIPEMD-160 block compress ---- */\n"
    "\n"
    "void rmd160_block(uint *hash, const uint *X)\n"
    "{\n"
    "    uint A = hash[0], B = hash[1], C = hash[2],\n"
    "         D = hash[3], E = hash[4];\n"
    "    uint a1, b1, c1, d1, e1;\n"
    "\n"
    "    /* Left half, round 1 (F1, K=0) */\n"
    "    L1(A, B, C, D, E, X[ 0], 11);\n"
    "    L1(E, A, B, C, D, X[ 1], 14);\n"
    "    L1(D, E, A, B, C, X[ 2], 15);\n"
    "    L1(C, D, E, A, B, X[ 3], 12);\n"
    "    L1(B, C, D, E, A, X[ 4],  5);\n"
    "    L1(A, B, C, D, E, X[ 5],  8);\n"
    "    L1(E, A, B, C, D, X[ 6],  7);\n"
    "    L1(D, E, A, B, C, X[ 7],  9);\n"
    "    L1(C, D, E, A, B, X[ 8], 11);\n"
    "    L1(B, C, D, E, A, X[ 9], 13);\n"
    "    L1(A, B, C, D, E, X[10], 14);\n"
    "    L1(E, A, B, C, D, X[11], 15);\n"
    "    L1(D, E, A, B, C, X[12],  6);\n"
    "    L1(C, D, E, A, B, X[13],  7);\n"
    "    L1(B, C, D, E, A, X[14],  9);\n"
    "    L1(A, B, C, D, E, X[15],  8);\n"
    "\n"
    "    /* Left half, round 2 (F2, K=0x5a827999) */\n"
    "    L2(E, A, B, C, D, X[ 7],  7);\n"
    "    L2(D, E, A, B, C, X[ 4],  6);\n"
    "    L2(C, D, E, A, B, X[13],  8);\n"
    "    L2(B, C, D, E, A, X[ 1], 13);\n"
    "    L2(A, B, C, D, E, X[10], 11);\n"
    "    L2(E, A, B, C, D, X[ 6],  9);\n"
    "    L2(D, E, A, B, C, X[15],  7);\n"
    "    L2(C, D, E, A, B, X[ 3], 15);\n"
    "    L2(B, C, D, E, A, X[12],  7);\n"
    "    L2(A, B, C, D, E, X[ 0], 12);\n"
    "    L2(E, A, B, C, D, X[ 9], 15);\n"
    "    L2(D, E, A, B, C, X[ 5],  9);\n"
    "    L2(C, D, E, A, B, X[ 2], 11);\n"
    "    L2(B, C, D, E, A, X[14],  7);\n"
    "    L2(A, B, C, D, E, X[11], 13);\n"
    "    L2(E, A, B, C, D, X[ 8], 12);\n"
    "\n"
    "    /* Left half, round 3 (F3, K=0x6ed9eba1) */\n"
    "    L3(D, E, A, B, C, X[ 3], 11);\n"
    "    L3(C, D, E, A, B, X[10], 13);\n"
    "    L3(B, C, D, E, A, X[14],  6);\n"
    "    L3(A, B, C, D, E, X[ 4],  7);\n"
    "    L3(E, A, B, C, D, X[ 9], 14);\n"
    "    L3(D, E, A, B, C, X[15],  9);\n"
    "    L3(C, D, E, A, B, X[ 8], 13);\n"
    "    L3(B, C, D, E, A, X[ 1], 15);\n"
    "    L3(A, B, C, D, E, X[ 2], 14);\n"
    "    L3(E, A, B, C, D, X[ 7],  8);\n"
    "    L3(D, E, A, B, C, X[ 0], 13);\n"
    "    L3(C, D, E, A, B, X[ 6],  6);\n"
    "    L3(B, C, D, E, A, X[13],  5);\n"
    "    L3(A, B, C, D, E, X[11], 12);\n"
    "    L3(E, A, B, C, D, X[ 5],  7);\n"
    "    L3(D, E, A, B, C, X[12],  5);\n"
    "\n"
    "    /* Left half, round 4 (F4, K=0x8f1bbcdc) */\n"
    "    L4(C, D, E, A, B, X[ 1], 11);\n"
    "    L4(B, C, D, E, A, X[ 9], 12);\n"
    "    L4(A, B, C, D, E, X[11], 14);\n"
    "    L4(E, A, B, C, D, X[10], 15);\n"
    "    L4(D, E, A, B, C, X[ 0], 14);\n"
    "    L4(C, D, E, A, B, X[ 8], 15);\n"
    "    L4(B, C, D, E, A, X[12],  9);\n"
    "    L4(A, B, C, D, E, X[ 4],  8);\n"
    "    L4(E, A, B, C, D, X[13],  9);\n"
    "    L4(D, E, A, B, C, X[ 3], 14);\n"
    "    L4(C, D, E, A, B, X[ 7],  5);\n"
    "    L4(B, C, D, E, A, X[15],  6);\n"
    "    L4(A, B, C, D, E, X[14],  8);\n"
    "    L4(E, A, B, C, D, X[ 5],  6);\n"
    "    L4(D, E, A, B, C, X[ 6],  5);\n"
    "    L4(C, D, E, A, B, X[ 2], 12);\n"
    "\n"
    "    /* Left half, round 5 (F5, K=0xa953fd4e) */\n"
    "    L5(B, C, D, E, A, X[ 4],  9);\n"
    "    L5(A, B, C, D, E, X[ 0], 15);\n"
    "    L5(E, A, B, C, D, X[ 5],  5);\n"
    "    L5(D, E, A, B, C, X[ 9], 11);\n"
    "    L5(C, D, E, A, B, X[ 7],  6);\n"
    "    L5(B, C, D, E, A, X[12],  8);\n"
    "    L5(A, B, C, D, E, X[ 2], 13);\n"
    "    L5(E, A, B, C, D, X[10], 12);\n"
    "    L5(D, E, A, B, C, X[14],  5);\n"
    "    L5(C, D, E, A, B, X[ 1], 12);\n"
    "    L5(B, C, D, E, A, X[ 3], 13);\n"
    "    L5(A, B, C, D, E, X[ 8], 14);\n"
    "    L5(E, A, B, C, D, X[11], 11);\n"
    "    L5(D, E, A, B, C, X[ 6],  8);\n"
    "    L5(C, D, E, A, B, X[15],  5);\n"
    "    L5(B, C, D, E, A, X[13],  6);\n"
    "\n"
    "    /* Save left-half results */\n"
    "    a1 = A; b1 = B; c1 = C; d1 = D; e1 = E;\n"
    "\n"
    "    /* Reload initial state for right half */\n"
    "    A = hash[0]; B = hash[1]; C = hash[2];\n"
    "    D = hash[3]; E = hash[4];\n"
    "\n"
    "    /* Right half, round 1 (F5, K=0x50a28be6) */\n"
    "    R1(A, B, C, D, E, X[ 5],  8);\n"
    "    R1(E, A, B, C, D, X[14],  9);\n"
    "    R1(D, E, A, B, C, X[ 7],  9);\n"
    "    R1(C, D, E, A, B, X[ 0], 11);\n"
    "    R1(B, C, D, E, A, X[ 9], 13);\n"
    "    R1(A, B, C, D, E, X[ 2], 15);\n"
    "    R1(E, A, B, C, D, X[11], 15);\n"
    "    R1(D, E, A, B, C, X[ 4],  5);\n"
    "    R1(C, D, E, A, B, X[13],  7);\n"
    "    R1(B, C, D, E, A, X[ 6],  7);\n"
    "    R1(A, B, C, D, E, X[15],  8);\n"
    "    R1(E, A, B, C, D, X[ 8], 11);\n"
    "    R1(D, E, A, B, C, X[ 1], 14);\n"
    "    R1(C, D, E, A, B, X[10], 14);\n"
    "    R1(B, C, D, E, A, X[ 3], 12);\n"
    "    R1(A, B, C, D, E, X[12],  6);\n"
    "\n"
    "    /* Right half, round 2 (F4, K=0x5c4dd124) */\n"
    "    R2(E, A, B, C, D, X[ 6],  9);\n"
    "    R2(D, E, A, B, C, X[11], 13);\n"
    "    R2(C, D, E, A, B, X[ 3], 15);\n"
    "    R2(B, C, D, E, A, X[ 7],  7);\n"
    "    R2(A, B, C, D, E, X[ 0], 12);\n"
    "    R2(E, A, B, C, D, X[13],  8);\n"
    "    R2(D, E, A, B, C, X[ 5],  9);\n"
    "    R2(C, D, E, A, B, X[10], 11);\n"
    "    R2(B, C, D, E, A, X[14],  7);\n"
    "    R2(A, B, C, D, E, X[15],  7);\n"
    "    R2(E, A, B, C, D, X[ 8], 12);\n"
    "    R2(D, E, A, B, C, X[12],  7);\n"
    "    R2(C, D, E, A, B, X[ 4],  6);\n"
    "    R2(B, C, D, E, A, X[ 9], 15);\n"
    "    R2(A, B, C, D, E, X[ 1], 13);\n"
    "    R2(E, A, B, C, D, X[ 2], 11);\n"
    "\n"
    "    /* Right half, round 3 (F3, K=0x6d703ef3) */\n"
    "    R3(D, E, A, B, C, X[15],  9);\n"
    "    R3(C, D, E, A, B, X[ 5],  7);\n"
    "    R3(B, C, D, E, A, X[ 1], 15);\n"
    "    R3(A, B, C, D, E, X[ 3], 11);\n"
    "    R3(E, A, B, C, D, X[ 7],  8);\n"
    "    R3(D, E, A, B, C, X[14],  6);\n"
    "    R3(C, D, E, A, B, X[ 6],  6);\n"
    "    R3(B, C, D, E, A, X[ 9], 14);\n"
    "    R3(A, B, C, D, E, X[11], 12);\n"
    "    R3(E, A, B, C, D, X[ 8], 13);\n"
    "    R3(D, E, A, B, C, X[12],  5);\n"
    "    R3(C, D, E, A, B, X[ 2], 14);\n"
    "    R3(B, C, D, E, A, X[10], 13);\n"
    "    R3(A, B, C, D, E, X[ 0], 13);\n"
    "    R3(E, A, B, C, D, X[ 4],  7);\n"
    "    R3(D, E, A, B, C, X[13],  5);\n"
    "\n"
    "    /* Right half, round 4 (F2, K=0x7a6d76e9) */\n"
    "    R4(C, D, E, A, B, X[ 8], 15);\n"
    "    R4(B, C, D, E, A, X[ 6],  5);\n"
    "    R4(A, B, C, D, E, X[ 4],  8);\n"
    "    R4(E, A, B, C, D, X[ 1], 11);\n"
    "    R4(D, E, A, B, C, X[ 3], 14);\n"
    "    R4(C, D, E, A, B, X[11], 14);\n"
    "    R4(B, C, D, E, A, X[15],  6);\n"
    "    R4(A, B, C, D, E, X[ 0], 14);\n"
    "    R4(E, A, B, C, D, X[ 5],  6);\n"
    "    R4(D, E, A, B, C, X[12],  9);\n"
    "    R4(C, D, E, A, B, X[ 2], 12);\n"
    "    R4(B, C, D, E, A, X[13],  9);\n"
    "    R4(A, B, C, D, E, X[ 9], 12);\n"
    "    R4(E, A, B, C, D, X[ 7],  5);\n"
    "    R4(D, E, A, B, C, X[10], 15);\n"
    "    R4(C, D, E, A, B, X[14],  8);\n"
    "\n"
    "    /* Right half, round 5 (F1, K=0) */\n"
    "    R5(B, C, D, E, A, X[12],  8);\n"
    "    R5(A, B, C, D, E, X[15],  5);\n"
    "    R5(E, A, B, C, D, X[10], 12);\n"
    "    R5(D, E, A, B, C, X[ 4],  9);\n"
    "    R5(C, D, E, A, B, X[ 1], 12);\n"
    "    R5(B, C, D, E, A, X[ 5],  5);\n"
    "    R5(A, B, C, D, E, X[ 8], 14);\n"
    "    R5(E, A, B, C, D, X[ 7],  6);\n"
    "    R5(D, E, A, B, C, X[ 6],  8);\n"
    "    R5(C, D, E, A, B, X[ 2], 13);\n"
    "    R5(B, C, D, E, A, X[13],  6);\n"
    "    R5(A, B, C, D, E, X[14],  5);\n"
    "    R5(E, A, B, C, D, X[ 0], 15);\n"
    "    R5(D, E, A, B, C, X[ 3], 13);\n"
    "    R5(C, D, E, A, B, X[ 9], 11);\n"
    "    R5(B, C, D, E, A, X[11], 11);\n"
    "\n"
    "    /* Final merge */\n"
    "    D += c1 + hash[1];\n"
    "    hash[1] = hash[2] + d1 + E;\n"
    "    hash[2] = hash[3] + e1 + A;\n"
    "    hash[3] = hash[4] + a1 + B;\n"
    "    hash[4] = hash[0] + b1 + C;\n"
    "    hash[0] = D;\n"
    "}\n"
    "\n"
    "/* ---- HMAC-RMD160 key=$salt (e211, hashcat 6060) ---- */\n"
    "\n"
    "/* Key = salt, Message = password.\n"
    " * Dispatch: num_words x num_salts threads. */\n"
    "__kernel void hmac_rmd160_ksalt_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int klen = salt_lens[salt_idx];\n"
    "    __global const uchar *key = salts + soff;\n"
    "\n"
    "    /* Step 1: Prepare key block (LE uint32 words).\n"
    "     * If key > 64 bytes, hash it first with RMD160. */\n"
    "    uint key_block[16];\n"
    "    for (int i = 0; i < 16; i++) key_block[i] = 0;\n"
    "\n"
    "    if (klen > 64) {\n"
    "        /* key = RMD160(original_key) */\n"
    "        uint kh[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "        uint M[16];\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        uchar *mb = (uchar *)M;\n"
    "        for (int i = 0; i < 64; i++) mb[i] = key[i];\n"
    "        rmd160_block(kh, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        mb = (uchar *)M;\n"
    "        int rem = klen - 64;\n"
    "        if (rem > 0) for (int i = 0; i < rem; i++) mb[i] = key[64 + i];\n"
    "        mb[rem] = 0x80;\n"
    "        M[14] = klen * 8;\n"
    "        rmd160_block(kh, M);\n"
    "        /* RMD160 output is LE -- store directly */\n"
    "        for (int i = 0; i < 5; i++) key_block[i] = kh[i];\n"
    "        klen = 20;\n"
    "    } else {\n"
    "        uchar *kb = (uchar *)key_block;\n"
    "        for (int i = 0; i < klen; i++) kb[i] = key[i];\n"
    "    }\n"
    "\n"
    "    /* Step 2: Inner hash = RMD160((key ^ ipad) || message) */\n"
    "    uint ipad[16], M[16];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        ipad[i] = key_block[i] ^ 0x36363636u;\n"
    "\n"
    "    /* RMD160 is LE -- ipad goes directly into M[], no bswap */\n"
    "    for (int i = 0; i < 16; i++) M[i] = ipad[i];\n"
    "\n"
    "    uint ih[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "    rmd160_block(ih, M);  /* Process ipad block (64 bytes) */\n"
    "\n"
    "    /* Continue with message (password) + padding */\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    int mlen = plen;\n"
    "    uchar *mb = (uchar *)M;\n"
    "    if (mlen <= 55) {\n"
    "        for (int i = 0; i < mlen; i++) mb[i] = pass[i];\n"
    "        mb[mlen] = 0x80;\n"
    "        M[14] = (64 + mlen) * 8;  /* total = ipad_block + message */\n"
    "        rmd160_block(ih, M);\n"
    "    } else {\n"
    "        int copy1 = (mlen < 64) ? mlen : 64;\n"
    "        for (int i = 0; i < copy1; i++) mb[i] = pass[i];\n"
    "        if (mlen < 64) mb[mlen] = 0x80;\n"
    "        rmd160_block(ih, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        mb = (uchar *)M;\n"
    "        int rem = mlen - 64;\n"
    "        if (rem > 0) for (int i = 0; i < rem; i++) mb[i] = pass[64 + i];\n"
    "        if (mlen >= 64) mb[(rem > 0) ? rem : 0] = 0x80;\n"
    "        M[14] = (64 + mlen) * 8;\n"
    "        rmd160_block(ih, M);\n"
    "    }\n"
    "\n"
    "    /* Inner hash result: ih[0..4] (LE) */\n"
    "\n"
    "    /* Step 3: Outer hash = RMD160((key ^ opad) || inner_hash) */\n"
    "    uint opad_block[16];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        opad_block[i] = key_block[i] ^ 0x5c5c5c5cu;\n"
    "\n"
    "    for (int i = 0; i < 16; i++) M[i] = opad_block[i];\n"
    "\n"
    "    uint oh[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "    rmd160_block(oh, M);  /* Process opad block (64 bytes) */\n"
    "\n"
    "    /* Continue with inner_hash (20 bytes LE) + padding */\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    M[0] = ih[0]; M[1] = ih[1]; M[2] = ih[2]; M[3] = ih[3]; M[4] = ih[4];\n"
    "    M[5] = 0x80;  /* 0x80 at byte 20 = word 5, LE byte 0 */\n"
    "    M[14] = (64 + 20) * 8;  /* 672 bits */\n"
    "    rmd160_block(oh, M);\n"
    "\n"
    "    /* Step 4: Check result -- RMD160 is LE, no bswap needed */\n"
    "    if (probe_compact(oh[0], oh[1], oh[2], oh[3], compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 7;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx; hits[base+2] = 1;\n"
    "            hits[base+3] = oh[0]; hits[base+4] = oh[1];\n"
    "            hits[base+5] = oh[2]; hits[base+6] = oh[3];\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- HMAC-RMD160 key=$pass (e798, hashcat 6050) ---- */\n"
    "\n"
    "/* Key = password, Message = salt.\n"
    " * Dispatch: num_words x num_salts threads. */\n"
    "__kernel void hmac_rmd160_kpass_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int klen = hexlens[word_idx];  /* password = key */\n"
    "    __global const uchar *key = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int mlen = salt_lens[salt_idx];  /* salt = message */\n"
    "    __global const uchar *msg = salts + soff;\n"
    "\n"
    "    /* Step 1: Prepare key block from password */\n"
    "    uint key_block[16];\n"
    "    for (int i = 0; i < 16; i++) key_block[i] = 0;\n"
    "\n"
    "    if (klen > 64) {\n"
    "        uint kh[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "        uint M[16];\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        uchar *mb = (uchar *)M;\n"
    "        for (int i = 0; i < 64; i++) mb[i] = key[i];\n"
    "        rmd160_block(kh, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        mb = (uchar *)M;\n"
    "        int rem = klen - 64;\n"
    "        if (rem > 0) for (int i = 0; i < rem; i++) mb[i] = key[64 + i];\n"
    "        mb[rem] = 0x80;\n"
    "        M[14] = klen * 8;\n"
    "        rmd160_block(kh, M);\n"
    "        for (int i = 0; i < 5; i++) key_block[i] = kh[i];\n"
    "        klen = 20;\n"
    "    } else {\n"
    "        uchar *kb = (uchar *)key_block;\n"
    "        for (int i = 0; i < klen; i++) kb[i] = key[i];\n"
    "    }\n"
    "\n"
    "    /* Step 2: Inner hash = RMD160((key ^ ipad) || salt) */\n"
    "    uint ipad[16], M[16];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        ipad[i] = key_block[i] ^ 0x36363636u;\n"
    "\n"
    "    for (int i = 0; i < 16; i++) M[i] = ipad[i];\n"
    "\n"
    "    uint ih[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "    rmd160_block(ih, M);\n"
    "\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    uchar *mb = (uchar *)M;\n"
    "    if (mlen <= 55) {\n"
    "        for (int i = 0; i < mlen; i++) mb[i] = msg[i];\n"
    "        mb[mlen] = 0x80;\n"
    "        M[14] = (64 + mlen) * 8;\n"
    "        rmd160_block(ih, M);\n"
    "    } else {\n"
    "        int copy1 = (mlen < 64) ? mlen : 64;\n"
    "        for (int i = 0; i < copy1; i++) mb[i] = msg[i];\n"
    "        if (mlen < 64) mb[mlen] = 0x80;\n"
    "        rmd160_block(ih, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        mb = (uchar *)M;\n"
    "        int rem = mlen - 64;\n"
    "        if (rem > 0) for (int i = 0; i < rem; i++) mb[i] = msg[64 + i];\n"
    "        if (mlen >= 64) mb[(rem > 0) ? rem : 0] = 0x80;\n"
    "        M[14] = (64 + mlen) * 8;\n"
    "        rmd160_block(ih, M);\n"
    "    }\n"
    "\n"
    "    /* Step 3: Outer hash */\n"
    "    uint opad_block[16];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        opad_block[i] = key_block[i] ^ 0x5c5c5c5cu;\n"
    "\n"
    "    for (int i = 0; i < 16; i++) M[i] = opad_block[i];\n"
    "\n"
    "    uint oh[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "    rmd160_block(oh, M);\n"
    "\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    M[0] = ih[0]; M[1] = ih[1]; M[2] = ih[2]; M[3] = ih[3]; M[4] = ih[4];\n"
    "    M[5] = 0x80;\n"
    "    M[14] = (64 + 20) * 8;  /* 672 bits */\n"
    "    rmd160_block(oh, M);\n"
    "\n"
    "    if (probe_compact(oh[0], oh[1], oh[2], oh[3], compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 7;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx; hits[base+2] = 1;\n"
    "            hits[base+3] = oh[0]; hits[base+4] = oh[1];\n"
    "            hits[base+5] = oh[2]; hits[base+6] = oh[3];\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
;
