/* Auto-generated from gpu_md5salt.cl -- do not edit */
static const char gpu_md5salt_str[] =
    "__kernel void md5salt_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off, __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    uint M[16];\n"
    "    __global const uint *mwords = (__global const uint *)(hexhashes + word_idx * 256);\n"
    "    for (int i = 0; i < 8; i++) M[i] = mwords[i];\n"
    "    for (int i = 8; i < 16; i++) M[i] = 0;\n"
    "\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = 32 + slen;\n"
    "    uchar *mbytes = (uchar *)M;\n"
    "    for (int i = 0; i < slen; i++)\n"
    "        mbytes[32 + i] = salts[soff + i];\n"
    "    mbytes[total_len] = 0x80;\n"
    "    M[14] = total_len * 8;\n"
    "\n"
    "    uint hx = 0x67452301, hy = 0xEFCDAB89, hz = 0x98BADCFE, hw = 0x10325476;\n"
    "    md5_block(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        EMIT_HIT_4(hits, hit_count, params.max_hits, word_idx, salt_idx, 1u, hx, hy, hz, hw)\n"
    "    }\n"
    "}\n"
    "\n"
    "__kernel void md5salt_sub8_24(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off, __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    uint M[16];\n"
    "    __global const uint *mwords = (__global const uint *)(hexhashes + word_idx * 256);\n"
    "    for (int i = 0; i < 4; i++) M[i] = mwords[i];\n"
    "    for (int i = 4; i < 16; i++) M[i] = 0;\n"
    "\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = 16 + slen;\n"
    "    uchar *mbytes = (uchar *)M;\n"
    "    for (int i = 0; i < slen; i++) mbytes[16 + i] = salts[soff + i];\n"
    "    mbytes[total_len] = 0x80;\n"
    "    M[14] = total_len * 8;\n"
    "\n"
    "    uint hx = 0x67452301, hy = 0xEFCDAB89, hz = 0x98BADCFE, hw = 0x10325476;\n"
    "    md5_block(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        EMIT_HIT_4(hits, hit_count, params.max_hits, word_idx, salt_idx, 1u, hx, hy, hz, hw)\n"
    "    }\n"
    "}\n"
    "\n"
    "/* hex_byte_lc, md5_to_hex_lc provided by gpu_common.cl */\n"
    "\n"
    "__kernel void md5salt_iter(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off, __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    uint M[16];\n"
    "    __global const uint *mwords = (__global const uint *)(hexhashes + word_idx * 256);\n"
    "    for (int i = 0; i < 8; i++) M[i] = mwords[i];\n"
    "    for (int i = 8; i < 16; i++) M[i] = 0;\n"
    "\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = 32 + slen;\n"
    "    uchar *mbytes = (uchar *)M;\n"
    "    for (int i = 0; i < slen; i++) mbytes[32 + i] = salts[soff + i];\n"
    "    mbytes[total_len] = 0x80;\n"
    "    M[14] = total_len * 8;\n"
    "\n"
    "    uint hx = 0x67452301, hy = 0xEFCDAB89, hz = 0x98BADCFE, hw = 0x10325476;\n"
    "    md5_block(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "    for (uint iter = 0; iter < params.max_iter; iter++) {\n"
    "        if (iter > 0) {\n"
    "            uint hwords[4]; hwords[0]=hx; hwords[1]=hy; hwords[2]=hz; hwords[3]=hw;\n"
    "            uchar *hb = (uchar *)hwords;\n"
    "            uint Mi[16];\n"
    "            uchar *mb = (uchar *)Mi;\n"
    "            for (int i = 0; i < 16; i++) {\n"
    "                uchar hi = hb[i] >> 4, lo = hb[i] & 0xf;\n"
    "                mb[i*2]   = hi + (hi < 10 ? '0' : 'a' - 10);\n"
    "                mb[i*2+1] = lo + (lo < 10 ? '0' : 'a' - 10);\n"
    "            }\n"
    "            Mi[8] = 0x80; Mi[9]=0; Mi[10]=0; Mi[11]=0;\n"
    "            Mi[12]=0; Mi[13]=0; Mi[14]=256; Mi[15]=0;\n"
    "            hx = 0x67452301; hy = 0xEFCDAB89; hz = 0x98BADCFE; hw = 0x10325476;\n"
    "            md5_block(&hx, &hy, &hz, &hw, Mi);\n"
    "        }\n"
    "        if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                          params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                          hash_data_buf, hash_data_off,\n"
    "                          overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "            EMIT_HIT_4(hits, hit_count, params.max_hits, word_idx, salt_idx, iter + 1, hx, hy, hz, hw)\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* hex_byte_lc/uc, md5_to_hex_lc/uc provided by gpu_common.cl */\n"
    "\n"
    "/* gpu_hmac_md5.cl — HMAC-MD5 GPU kernels\n"
    " *\n"
    " * hmac_md5_ksalt_batch: HMAC-MD5 key=$salt (e214, hashcat 60)\n"
    " *   Key = salt (from Typeuser), Message = password\n"
    " *\n"
    " * hmac_md5_kpass_batch: HMAC-MD5 key=$pass (e792, hashcat 50)\n"
    " *   Key = password, Message = salt (from Typesalt)\n"
    " *\n"
    " * HMAC(K, M) = H((K ^ opad) || H((K ^ ipad) || M))\n"
    " * Block size = 64 bytes, ipad = 0x36, opad = 0x5c\n"
    " * MD5 is little-endian — no bswap needed for key/ipad/opad blocks.\n"
    " *\n"
    " * Hit stride: 7 (word_idx, salt_idx, iter, hx, hy, hz, hw)\n"
    " */\n"
    "\n"
    "/* HMAC-MD5 key=$salt: key=salt, message=password.\n"
    " * Dispatch: num_words x num_salts threads. */\n"
    "__kernel void hmac_md5_ksalt_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int klen = salt_lens[salt_idx];\n"
    "    __global const uchar *key = salts + soff;\n"
    "\n"
    "    /* Step 1: Prepare key block (LE uint32 words).\n"
    "     * If key > 64 bytes, hash it first. */\n"
    "    uint key_block[16];\n"
    "    for (int i = 0; i < 16; i++) key_block[i] = 0;\n"
    "\n"
    "    if (klen > 64) {\n"
    "        /* key = MD5(original_key) */\n"
    "        uint M[16];\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        uchar *mb = (uchar *)M;\n"
    "        int copy1 = (klen < 64) ? klen : 64;\n"
    "        for (int i = 0; i < copy1; i++) mb[i] = key[i];\n"
    "        if (klen <= 55) { mb[klen] = 0x80; M[14] = klen * 8; }\n"
    "        uint kx = 0x67452301u, ky = 0xEFCDAB89u, kz = 0x98BADCFEu, kw = 0x10325476u;\n"
    "        md5_block(&kx, &ky, &kz, &kw, M);\n"
    "        if (klen > 55) {\n"
    "            for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "            int rem = klen - 64;\n"
    "            mb = (uchar *)M;\n"
    "            if (rem > 0) for (int i = 0; i < rem; i++) mb[i] = key[64 + i];\n"
    "            mb[rem] = 0x80;\n"
    "            M[14] = klen * 8;\n"
    "            md5_block(&kx, &ky, &kz, &kw, M);\n"
    "        }\n"
    "        /* MD5 output is already LE — store directly */\n"
    "        key_block[0] = kx; key_block[1] = ky;\n"
    "        key_block[2] = kz; key_block[3] = kw;\n"
    "        klen = 16;\n"
    "    } else {\n"
    "        /* Copy key bytes into key_block as LE uint32 */\n"
    "        uchar *kb = (uchar *)key_block;\n"
    "        for (int i = 0; i < klen; i++) kb[i] = key[i];\n"
    "    }\n"
    "\n"
    "    /* Step 2: Inner hash = MD5((key ^ ipad) || message) */\n"
    "    uint ipad[16], M[16];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        ipad[i] = key_block[i] ^ 0x36363636u;\n"
    "\n"
    "    /* MD5 is LE — ipad goes directly into M[], no bswap */\n"
    "    for (int i = 0; i < 16; i++) M[i] = ipad[i];\n"
    "\n"
    "    uint ihx = 0x67452301u, ihy = 0xEFCDAB89u, ihz = 0x98BADCFEu, ihw = 0x10325476u;\n"
    "    md5_block(&ihx, &ihy, &ihz, &ihw, M);  /* Process ipad block (64 bytes) */\n"
    "\n"
    "    /* Continue with message (password) + padding */\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    int mlen = plen;\n"
    "    uchar *mb = (uchar *)M;\n"
    "    if (mlen <= 55) {\n"
    "        for (int i = 0; i < mlen; i++) mb[i] = pass[i];\n"
    "        mb[mlen] = 0x80;\n"
    "        M[14] = (64 + mlen) * 8;  /* total = ipad_block + message */\n"
    "        md5_block(&ihx, &ihy, &ihz, &ihw, M);\n"
    "    } else {\n"
    "        int copy1 = (mlen < 64) ? mlen : 64;\n"
    "        for (int i = 0; i < copy1; i++) mb[i] = pass[i];\n"
    "        if (mlen < 64) mb[mlen] = 0x80;\n"
    "        md5_block(&ihx, &ihy, &ihz, &ihw, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        mb = (uchar *)M;\n"
    "        int rem = mlen - 64;\n"
    "        if (rem > 0) for (int i = 0; i < rem; i++) mb[i] = pass[64 + i];\n"
    "        if (mlen >= 64) mb[(rem > 0) ? rem : 0] = 0x80;\n"
    "        M[14] = (64 + mlen) * 8;\n"
    "        md5_block(&ihx, &ihy, &ihz, &ihw, M);\n"
    "    }\n"
    "\n"
    "    /* Inner hash result: ihx, ihy, ihz, ihw (LE) */\n"
    "\n"
    "    /* Step 3: Outer hash = MD5((key ^ opad) || inner_hash) */\n"
    "    uint opad_block[16];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        opad_block[i] = key_block[i] ^ 0x5c5c5c5cu;\n"
    "\n"
    "    for (int i = 0; i < 16; i++) M[i] = opad_block[i];\n"
    "\n"
    "    uint ohx = 0x67452301u, ohy = 0xEFCDAB89u, ohz = 0x98BADCFEu, ohw = 0x10325476u;\n"
    "    md5_block(&ohx, &ohy, &ohz, &ohw, M);  /* Process opad block (64 bytes) */\n"
    "\n"
    "    /* Continue with inner_hash (16 bytes LE) + padding */\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    M[0] = ihx; M[1] = ihy; M[2] = ihz; M[3] = ihw;  /* 16 bytes LE */\n"
    "    M[4] = 0x80;  /* 0x80 at byte 16 = word 4, LE byte 0 */\n"
    "    M[14] = (64 + 16) * 8;  /* 640 bits */\n"
    "    md5_block(&ohx, &ohy, &ohz, &ohw, M);\n"
    "\n"
    "    /* Step 4: Check result — MD5 is LE, no bswap needed */\n"
    "    if (probe_compact(ohx, ohy, ohz, ohw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        EMIT_HIT_4(hits, hit_count, params.max_hits, word_idx, salt_idx, 1, ohx, ohy, ohz, ohw)\n"
    "    }\n"
    "}\n"
    "\n"
    "/* HMAC-MD5 key=$pass: key=password, message=salt.\n"
    " * Dispatch: num_words x num_salts threads. */\n"
    "__kernel void hmac_md5_kpass_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int klen = hexlens[word_idx];  /* password = key */\n"
    "    __global const uchar *key = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int mlen = salt_lens[salt_idx];  /* salt = message */\n"
    "    __global const uchar *msg = salts + soff;\n"
    "\n"
    "    /* Step 1: Prepare key block from password */\n"
    "    uint key_block[16];\n"
    "    for (int i = 0; i < 16; i++) key_block[i] = 0;\n"
    "\n"
    "    if (klen > 64) {\n"
    "        uint M[16];\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        uchar *mb = (uchar *)M;\n"
    "        int copy1 = (klen < 64) ? klen : 64;\n"
    "        for (int i = 0; i < copy1; i++) mb[i] = key[i];\n"
    "        if (klen <= 55) { mb[klen] = 0x80; M[14] = klen * 8; }\n"
    "        uint kx = 0x67452301u, ky = 0xEFCDAB89u, kz = 0x98BADCFEu, kw = 0x10325476u;\n"
    "        md5_block(&kx, &ky, &kz, &kw, M);\n"
    "        if (klen > 55) {\n"
    "            for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "            int rem = klen - 64;\n"
    "            mb = (uchar *)M;\n"
    "            if (rem > 0) for (int i = 0; i < rem; i++) mb[i] = key[64 + i];\n"
    "            mb[rem] = 0x80;\n"
    "            M[14] = klen * 8;\n"
    "            md5_block(&kx, &ky, &kz, &kw, M);\n"
    "        }\n"
    "        key_block[0] = kx; key_block[1] = ky;\n"
    "        key_block[2] = kz; key_block[3] = kw;\n"
    "        klen = 16;\n"
    "    } else {\n"
    "        uchar *kb = (uchar *)key_block;\n"
    "        for (int i = 0; i < klen; i++) kb[i] = key[i];\n"
    "    }\n"
    "\n"
    "    /* Step 2: Inner hash = MD5((key ^ ipad) || salt) */\n"
    "    uint ipad[16], M[16];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        ipad[i] = key_block[i] ^ 0x36363636u;\n"
    "\n"
    "    for (int i = 0; i < 16; i++) M[i] = ipad[i];\n"
    "\n"
    "    uint ihx = 0x67452301u, ihy = 0xEFCDAB89u, ihz = 0x98BADCFEu, ihw = 0x10325476u;\n"
    "    md5_block(&ihx, &ihy, &ihz, &ihw, M);\n"
    "\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    uchar *mb = (uchar *)M;\n"
    "    if (mlen <= 55) {\n"
    "        for (int i = 0; i < mlen; i++) mb[i] = msg[i];\n"
    "        mb[mlen] = 0x80;\n"
    "        M[14] = (64 + mlen) * 8;\n"
    "        md5_block(&ihx, &ihy, &ihz, &ihw, M);\n"
    "    } else {\n"
    "        int copy1 = (mlen < 64) ? mlen : 64;\n"
    "        for (int i = 0; i < copy1; i++) mb[i] = msg[i];\n"
    "        if (mlen < 64) mb[mlen] = 0x80;\n"
    "        md5_block(&ihx, &ihy, &ihz, &ihw, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        mb = (uchar *)M;\n"
    "        int rem = mlen - 64;\n"
    "        if (rem > 0) for (int i = 0; i < rem; i++) mb[i] = msg[64 + i];\n"
    "        if (mlen >= 64) mb[(rem > 0) ? rem : 0] = 0x80;\n"
    "        M[14] = (64 + mlen) * 8;\n"
    "        md5_block(&ihx, &ihy, &ihz, &ihw, M);\n"
    "    }\n"
    "\n"
    "    /* Step 3: Outer hash */\n"
    "    uint opad_block[16];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        opad_block[i] = key_block[i] ^ 0x5c5c5c5cu;\n"
    "\n"
    "    for (int i = 0; i < 16; i++) M[i] = opad_block[i];\n"
    "\n"
    "    uint ohx = 0x67452301u, ohy = 0xEFCDAB89u, ohz = 0x98BADCFEu, ohw = 0x10325476u;\n"
    "    md5_block(&ohx, &ohy, &ohz, &ohw, M);\n"
    "\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    M[0] = ihx; M[1] = ihy; M[2] = ihz; M[3] = ihw;\n"
    "    M[4] = 0x80;\n"
    "    M[14] = (64 + 16) * 8;  /* 640 bits */\n"
    "    md5_block(&ohx, &ohy, &ohz, &ohw, M);\n"
    "\n"
    "    if (probe_compact(ohx, ohy, ohz, ohw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        EMIT_HIT_4(hits, hit_count, params.max_hits, word_idx, salt_idx, 1, ohx, ohy, ohz, ohw)\n"
    "    }\n"
    "}\n"
;
