/* Auto-generated from gpu_sha1.cl -- do not edit */
static const char gpu_sha1_str[] =
    "/* bswap32, sha1_block, S_copy_bytes, S_set_byte all provided by gpu_common.cl */\n"
    "\n"
    "/* ---- SHA1(password + salt) kernel (e405) ---- */\n"
    "__kernel void sha1passsalt_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off, __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = plen + slen;\n"
    "\n"
    "    uint state[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "    { uint M[16];\n"
    "      for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "      if (total_len <= 55) {\n"
    "        S_copy_bytes(M, 0, pass, plen);\n"
    "        S_copy_bytes(M, plen, salts + soff, slen);\n"
    "        S_set_byte(M, total_len, 0x80);\n"
    "        M[15] = total_len * 8;\n"
    "        sha1_block(state, M);\n"
    "      } else {\n"
    "        int pass_b1 = (plen < 64) ? plen : 64;\n"
    "        S_copy_bytes(M, 0, pass, pass_b1);\n"
    "        int salt_b1 = 64 - pass_b1;\n"
    "        if (salt_b1 > slen) salt_b1 = slen;\n"
    "        if (salt_b1 > 0) S_copy_bytes(M, pass_b1, salts + soff, salt_b1);\n"
    "        if (total_len < 64) S_set_byte(M, total_len, 0x80);\n"
    "        sha1_block(state, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int pos2 = 0;\n"
    "        int pass_b2 = plen - pass_b1;\n"
    "        if (pass_b2 > 0) { S_copy_bytes(M, 0, pass + pass_b1, pass_b2); pos2 = pass_b2; }\n"
    "        int salt_b2 = slen - salt_b1;\n"
    "        if (salt_b2 > 0) { S_copy_bytes(M, pos2, salts + soff + salt_b1, salt_b2); pos2 += salt_b2; }\n"
    "        if (total_len >= 64) S_set_byte(M, pos2, 0x80);\n"
    "        M[15] = total_len * 8;\n"
    "        sha1_block(state, M);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    uint h[5];\n"
    "    for (int i = 0; i < 5; i++) h[i] = bswap32(state[i]);\n"
    "\n"
    "    if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        EMIT_HIT_5(hits, hit_count, params.max_hits, word_idx, salt_idx, 1, h)\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- SHA1(salt + password) kernel (e385) ---- */\n"
    "__kernel void sha1saltpass_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off, __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = slen + plen;\n"
    "\n"
    "    uint state[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "    { uint M[16];\n"
    "      for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "      if (total_len <= 55) {\n"
    "        S_copy_bytes(M, 0, salts + soff, slen);\n"
    "        S_copy_bytes(M, slen, pass, plen);\n"
    "        S_set_byte(M, total_len, 0x80);\n"
    "        M[15] = total_len * 8;\n"
    "        sha1_block(state, M);\n"
    "      } else {\n"
    "        int salt_b1 = (slen < 64) ? slen : 64;\n"
    "        S_copy_bytes(M, 0, salts + soff, salt_b1);\n"
    "        int pass_b1 = 64 - salt_b1;\n"
    "        if (pass_b1 > plen) pass_b1 = plen;\n"
    "        if (pass_b1 > 0) S_copy_bytes(M, salt_b1, pass, pass_b1);\n"
    "        if (total_len < 64) S_set_byte(M, total_len, 0x80);\n"
    "        sha1_block(state, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int pos2 = 0;\n"
    "        int salt_b2 = slen - salt_b1;\n"
    "        if (salt_b2 > 0) { S_copy_bytes(M, 0, salts + soff + salt_b1, salt_b2); pos2 = salt_b2; }\n"
    "        int pass_b2 = plen - pass_b1;\n"
    "        if (pass_b2 > 0) { S_copy_bytes(M, pos2, pass + pass_b1, pass_b2); pos2 += pass_b2; }\n"
    "        if (total_len >= 64) S_set_byte(M, pos2, 0x80);\n"
    "        M[15] = total_len * 8;\n"
    "        sha1_block(state, M);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    uint h[5];\n"
    "    for (int i = 0; i < 5; i++) h[i] = bswap32(state[i]);\n"
    "\n"
    "    if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        EMIT_HIT_5(hits, hit_count, params.max_hits, word_idx, salt_idx, 1, h)\n"
    "    }\n"
    "}\n"
    "\n"
    "/* Copy private-memory bytes into big-endian M[] for SHA1/SHA256 */\n"
    "void S_copy_bytes_priv(uint *M, int byte_off, const uchar *src, int nbytes) {\n"
    "    for (int i = 0; i < nbytes; i++) {\n"
    "        int wi = (byte_off + i) / 4;\n"
    "        int bi = 3 - ((byte_off + i) % 4);\n"
    "        M[wi] = (M[wi] & ~(0xffu << (bi * 8))) | ((uint)src[i] << (bi * 8));\n"
    "    }\n"
    "}\n"
    "\n"
    "void S_set_byte_priv(uint *M, int byte_off, uchar val) {\n"
    "    int wi = byte_off / 4;\n"
    "    int bi = 3 - (byte_off % 4);\n"
    "    M[wi] = (M[wi] & ~(0xffu << (bi * 8))) | ((uint)val << (bi * 8));\n"
    "}\n"
    "\n"
    "/* ---- SHA1DRU kernel (e404): SHA1 iterated 1,000,001 times ---- */\n"
    "/* SHA1(pass), then 1M iterations of SHA1(hex(hash) + pass).\n"
    " * No salts — GPU_CAT_ITER, dispatched as num_words work items. */\n"
    "__kernel void sha1dru_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off, __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    if (tid >= params.num_words) return;\n"
    "\n"
    "    /* hexhash buffer: [0..39] = hex(SHA1(pass)), [40..40+plen-1] = raw password */\n"
    "    __global const uchar *wordbuf = hexhashes + tid * 256;\n"
    "    int plen = hexlens[tid]; /* passlen stored in clen[] on host */\n"
    "\n"
    "    /* Read password length from the passbuf area — stored after hex */\n"
    "    /* Actually plen here is hexlen=40, we need the raw pass length.\n"
    "     * The raw password starts at offset 40, its length = job->clen.\n"
    "     * But we only have hexlens[] which was set to 40. We need clen.\n"
    "     * Store plen in the passlen array instead — gpujob reads it. */\n"
    "    /* For now: scan for the end of the password in the buffer */\n"
    "    /* Actually: the pass length is encoded as total - 40 where total is\n"
    "     * stored... let me use a simpler approach. The CPU packs:\n"
    "     * hexlen[idx] = 40 (the hex portion). Password is at wordbuf+40\n"
    "     * and its length is in g->passlen[idx] which maps to... we don't\n"
    "     * have a separate buffer for passlen on the GPU.\n"
    "     *\n"
    "     * Simplest: pack total length (40 + plen) in hexlens, kernel subtracts 40. */\n"
    "\n"
    "    /* hexlens[tid] = 40; password at wordbuf+40, length = clen from host */\n"
    "    /* We'll change hexlen to 40+plen so kernel can derive plen */\n"
    "    int total_packed = hexlens[tid]; /* set to 40 + plen by host */\n"
    "    plen = total_packed - 40;\n"
    "    __global const uchar *pass = wordbuf + 40;\n"
    "\n"
    "    /* SHA1(pass) already done on CPU — state is in hex at wordbuf[0..39] */\n"
    "    /* Decode hex back to 5 big-endian state words */\n"
    "    uint state[5];\n"
    "    for (int w = 0; w < 5; w++) {\n"
    "        __global const uint *hw = (__global const uint *)(wordbuf + w * 8);\n"
    "        /* hex chars are ASCII in LE uint32 words — reconstruct the big-endian SHA1 word */\n"
    "        /* Actually the hex is stored as raw ASCII bytes. Parse them. */\n"
    "        uint val = 0;\n"
    "        for (int j = 0; j < 8; j++) {\n"
    "            uchar c = wordbuf[w*8+j];\n"
    "            uint nibble = (c >= 'a') ? (c - 'a' + 10) : (c - '0');\n"
    "            val = (val << 4) | nibble;\n"
    "        }\n"
    "        state[w] = val;\n"
    "    }\n"
    "\n"
    "    uchar hexlut[16] = {'0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f'};\n"
    "\n"
    "    /* 1,000,000 iterations of SHA1(hex(hash) + pass) */\n"
    "    for (int iter = 0; iter < 1000000; iter++) {\n"
    "        uchar hexbuf[96];\n"
    "        for (int w = 0; w < 5; w++) {\n"
    "            uint sv = state[w];\n"
    "            hexbuf[w*8+0] = hexlut[(sv >> 28) & 0xf];\n"
    "            hexbuf[w*8+1] = hexlut[(sv >> 24) & 0xf];\n"
    "            hexbuf[w*8+2] = hexlut[(sv >> 20) & 0xf];\n"
    "            hexbuf[w*8+3] = hexlut[(sv >> 16) & 0xf];\n"
    "            hexbuf[w*8+4] = hexlut[(sv >> 12) & 0xf];\n"
    "            hexbuf[w*8+5] = hexlut[(sv >> 8) & 0xf];\n"
    "            hexbuf[w*8+6] = hexlut[(sv >> 4) & 0xf];\n"
    "            hexbuf[w*8+7] = hexlut[sv & 0xf];\n"
    "        }\n"
    "        for (int i = 0; i < plen; i++) hexbuf[40 + i] = pass[i];\n"
    "        int total = 40 + plen;\n"
    "\n"
    "        /* SHA1(hexbuf, total) */\n"
    "        state[0] = 0x67452301u; state[1] = 0xEFCDAB89u;\n"
    "        state[2] = 0x98BADCFEu; state[3] = 0x10325476u; state[4] = 0xC3D2E1F0u;\n"
    "        uint M[16];\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        if (total <= 55) {\n"
    "            S_copy_bytes_priv(M, 0, hexbuf, total);\n"
    "            S_set_byte_priv(M, total, 0x80);\n"
    "            M[15] = total * 8;\n"
    "            sha1_block(state, M);\n"
    "        } else {\n"
    "            /* Two blocks */\n"
    "            S_copy_bytes_priv(M, 0, hexbuf, 64);\n"
    "            sha1_block(state, M);\n"
    "            for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "            int rem = total - 64;\n"
    "            if (rem > 0) S_copy_bytes_priv(M, 0, hexbuf + 64, rem);\n"
    "            S_set_byte_priv(M, rem, 0x80);\n"
    "            M[15] = total * 8;\n"
    "            sha1_block(state, M);\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Byte-swap state for compact table probe */\n"
    "    uint h[5];\n"
    "    for (int i = 0; i < 5; i++) h[i] = bswap32(state[i]);\n"
    "\n"
    "    if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        EMIT_HIT_5(hits, hit_count, params.max_hits, tid, 0, 1, h)\n"
    "    }\n"
    "}\n"
    "\n"
    "/* gpu_hmac_sha1.cl — HMAC-SHA1 GPU kernels\n"
    " *\n"
    " * hmac_sha1_ksalt_batch: HMAC-SHA1 key=$salt (e215, hashcat 160)\n"
    " *   Key = salt (from Typeuser), Message = password\n"
    " *\n"
    " * hmac_sha1_kpass_batch: HMAC-SHA1 key=$pass (e793, hashcat 150)\n"
    " *   Key = password, Message = salt (from Typesalt)\n"
    " *\n"
    " * HMAC(K, M) = H((K ^ opad) || H((K ^ ipad) || M))\n"
    " * Block size = 64 bytes, ipad = 0x36, opad = 0x5c\n"
    " * SHA1 is big-endian — bswap needed for ipad/opad blocks.\n"
    " *\n"
    " * Hit stride: 8 (word_idx, salt_idx, iter, h[0..4])\n"
    " */\n"
    "\n"
    "/* HMAC-SHA1 key=$salt: key=salt, message=password.\n"
    " * Dispatch: num_words x num_salts threads. */\n"
    "__kernel void hmac_sha1_ksalt_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int klen = salt_lens[salt_idx];\n"
    "    __global const uchar *key = salts + soff;\n"
    "\n"
    "    /* Step 1: Prepare key block (LE byte order, will bswap for SHA1).\n"
    "     * If key > 64 bytes, hash it first. */\n"
    "    uint key_block[16];\n"
    "    for (int i = 0; i < 16; i++) key_block[i] = 0;\n"
    "\n"
    "    if (klen > 64) {\n"
    "        /* key = SHA1(original_key) */\n"
    "        uint kstate[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "        uint M[16];\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        S_copy_bytes(M, 0, key, 64);\n"
    "        sha1_block(kstate, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int rem = klen - 64;\n"
    "        if (rem > 0) S_copy_bytes(M, 0, key + 64, rem);\n"
    "        S_set_byte(M, rem, 0x80);\n"
    "        M[15] = klen * 8;\n"
    "        sha1_block(kstate, M);\n"
    "        /* Store hashed key (20 bytes BE) as LE bytes in key_block */\n"
    "        for (int i = 0; i < 5; i++) key_block[i] = bswap32(kstate[i]);\n"
    "        klen = 20;\n"
    "    } else {\n"
    "        /* Copy key bytes into key_block as little-endian uint32 */\n"
    "        for (int i = 0; i < klen; i++) {\n"
    "            int wi = i >> 2;\n"
    "            int bi = (i & 3) << 3;\n"
    "            key_block[wi] |= ((uint)key[i]) << bi;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Step 2: Inner hash = SHA1((key ^ ipad) || message) */\n"
    "    uint ipad[16], M[16];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        ipad[i] = key_block[i] ^ 0x36363636u;\n"
    "\n"
    "    /* Convert ipad from LE to BE for SHA1 */\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap32(ipad[i]);\n"
    "\n"
    "    uint istate[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "    sha1_block(istate, M);  /* Process ipad block (64 bytes) */\n"
    "\n"
    "    /* Continue with message (password) + padding */\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    int mlen = plen;\n"
    "    if (mlen <= 55) {\n"
    "        S_copy_bytes(M, 0, pass, mlen);\n"
    "        S_set_byte(M, mlen, 0x80);\n"
    "        M[15] = (64 + mlen) * 8;  /* total = ipad_block + message */\n"
    "        sha1_block(istate, M);\n"
    "    } else {\n"
    "        S_copy_bytes(M, 0, pass, (mlen < 64) ? mlen : 64);\n"
    "        if (mlen < 64) S_set_byte(M, mlen, 0x80);\n"
    "        sha1_block(istate, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int rem = mlen - 64;\n"
    "        if (rem > 0) S_copy_bytes(M, 0, pass + 64, rem);\n"
    "        if (mlen >= 64) S_set_byte(M, (rem > 0) ? rem : 0, 0x80);\n"
    "        M[15] = (64 + mlen) * 8;\n"
    "        sha1_block(istate, M);\n"
    "    }\n"
    "\n"
    "    /* Inner hash result (20 bytes, big-endian in istate) */\n"
    "\n"
    "    /* Step 3: Outer hash = SHA1((key ^ opad) || inner_hash) */\n"
    "    uint opad_block[16];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        opad_block[i] = key_block[i] ^ 0x5c5c5c5cu;\n"
    "\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap32(opad_block[i]);\n"
    "\n"
    "    uint ostate[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "    sha1_block(ostate, M);  /* Process opad block (64 bytes) */\n"
    "\n"
    "    /* Continue with inner_hash (20 bytes BE) + padding.\n"
    "     * istate[] is already in BE — copy directly into M[]. */\n"
    "    for (int i = 0; i < 5; i++) M[i] = istate[i];\n"
    "    M[5] = 0x80000000u;\n"
    "    for (int i = 6; i < 15; i++) M[i] = 0;\n"
    "    M[15] = (64 + 20) * 8;  /* opad_block(64) + inner_hash(20) = 84 bytes = 672 bits */\n"
    "    sha1_block(ostate, M);\n"
    "\n"
    "    /* Step 4: Check result — bswap for compact table (LE) */\n"
    "    uint h[5];\n"
    "    for (int i = 0; i < 5; i++) h[i] = bswap32(ostate[i]);\n"
    "\n"
    "    if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        EMIT_HIT_5(hits, hit_count, params.max_hits, word_idx, salt_idx, 1, h)\n"
    "    }\n"
    "}\n"
    "\n"
    "/* HMAC-SHA1 key=$pass: key=password, message=salt.\n"
    " * Dispatch: num_words x num_salts threads. */\n"
    "__kernel void hmac_sha1_kpass_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int klen = hexlens[word_idx];  /* password = key */\n"
    "    __global const uchar *key = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int mlen = salt_lens[salt_idx];  /* salt = message */\n"
    "    __global const uchar *msg = salts + soff;\n"
    "\n"
    "    /* Step 1: Prepare key block from password */\n"
    "    uint key_block[16];\n"
    "    for (int i = 0; i < 16; i++) key_block[i] = 0;\n"
    "\n"
    "    if (klen > 64) {\n"
    "        uint kstate[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "        uint M[16];\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        S_copy_bytes(M, 0, key, 64);\n"
    "        sha1_block(kstate, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int rem = klen - 64;\n"
    "        if (rem > 0) S_copy_bytes(M, 0, key + 64, rem);\n"
    "        S_set_byte(M, rem, 0x80);\n"
    "        M[15] = klen * 8;\n"
    "        sha1_block(kstate, M);\n"
    "        for (int i = 0; i < 5; i++) key_block[i] = bswap32(kstate[i]);\n"
    "        klen = 20;\n"
    "    } else {\n"
    "        for (int i = 0; i < klen; i++) {\n"
    "            int wi = i >> 2;\n"
    "            int bi = (i & 3) << 3;\n"
    "            key_block[wi] |= ((uint)key[i]) << bi;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Step 2: Inner hash = SHA1((key ^ ipad) || salt) */\n"
    "    uint ipad[16], M[16];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        ipad[i] = key_block[i] ^ 0x36363636u;\n"
    "\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap32(ipad[i]);\n"
    "\n"
    "    uint istate[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "    sha1_block(istate, M);\n"
    "\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    if (mlen <= 55) {\n"
    "        S_copy_bytes(M, 0, msg, mlen);\n"
    "        S_set_byte(M, mlen, 0x80);\n"
    "        M[15] = (64 + mlen) * 8;\n"
    "        sha1_block(istate, M);\n"
    "    } else {\n"
    "        S_copy_bytes(M, 0, msg, (mlen < 64) ? mlen : 64);\n"
    "        if (mlen < 64) S_set_byte(M, mlen, 0x80);\n"
    "        sha1_block(istate, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int rem = mlen - 64;\n"
    "        if (rem > 0) S_copy_bytes(M, 0, msg + 64, rem);\n"
    "        if (mlen >= 64) S_set_byte(M, (rem > 0) ? rem : 0, 0x80);\n"
    "        M[15] = (64 + mlen) * 8;\n"
    "        sha1_block(istate, M);\n"
    "    }\n"
    "\n"
    "    /* Step 3: Outer hash */\n"
    "    uint opad_block[16];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        opad_block[i] = key_block[i] ^ 0x5c5c5c5cu;\n"
    "\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap32(opad_block[i]);\n"
    "\n"
    "    uint ostate[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "    sha1_block(ostate, M);\n"
    "\n"
    "    for (int i = 0; i < 5; i++) M[i] = istate[i];\n"
    "    M[5] = 0x80000000u;\n"
    "    for (int i = 6; i < 15; i++) M[i] = 0;\n"
    "    M[15] = (64 + 20) * 8;  /* 672 bits */\n"
    "    sha1_block(ostate, M);\n"
    "\n"
    "    uint h[5];\n"
    "    for (int i = 0; i < 5; i++) h[i] = bswap32(ostate[i]);\n"
    "\n"
    "    if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        EMIT_HIT_5(hits, hit_count, params.max_hits, word_idx, salt_idx, 1, h)\n"
    "    }\n"
    "}\n"
;
