/* Auto-generated from gpu_sha256crypt.cl -- do not edit */
static const char gpu_sha256crypt_str[] =
    "/* gpu_sha256crypt.cl -- SHA256CRYPT (e512, hashcat 7400) OpenCL kernel\n"
    " *\n"
    " * glibc crypt-sha256: $5$[rounds=N$]salt$hash\n"
    " * Default 5000 rounds, salt up to 16 chars, SHA256 (32-byte digest).\n"
    " *\n"
    " * Hit stride: 11 (word_idx, salt_idx, iter, h[0..7])\n"
    " * Compact probe: first 16 bytes of 32-byte hash as 4 x uint32\n"
    " */\n"
    "\n"
    "/* SHA256 primitives (bswap32, sha256_block) provided by gpu_common.cl.\n"
    " * SC_IV aliases for sha256crypt init convenience. */\n"
    "\n"
    "#define SC_IV0 0x6a09e667u\n"
    "#define SC_IV1 0xbb67ae85u\n"
    "#define SC_IV2 0x3c6ef372u\n"
    "#define SC_IV3 0xa54ff53au\n"
    "#define SC_IV4 0x510e527fu\n"
    "#define SC_IV5 0x9b05688cu\n"
    "#define SC_IV6 0x1f83d9abu\n"
    "#define SC_IV7 0x5be0cd19u\n"
    "\n"
    "/* ---- Buffered SHA256: init / update / final ---- */\n"
    "\n"
    "void sc_sha256_init(uint *state) {\n"
    "    state[0] = SC_IV0; state[1] = SC_IV1;\n"
    "    state[2] = SC_IV2; state[3] = SC_IV3;\n"
    "    state[4] = SC_IV4; state[5] = SC_IV5;\n"
    "    state[6] = SC_IV6; state[7] = SC_IV7;\n"
    "}\n"
    "\n"
    "/* Store a byte into big-endian uint buffer at byte position pos */\n"
    "void sc_buf_set_byte(uint *buf, int pos, uchar val) {\n"
    "    int wi = pos >> 2;\n"
    "    int bi = (3 - (pos & 3)) << 3;\n"
    "    buf[wi] = (buf[wi] & ~(0xffu << bi)) | ((uint)val << bi);\n"
    "}\n"
    "\n"
    "/* Get a byte from big-endian uint buffer at byte position pos */\n"
    "uchar sc_buf_get_byte(uint *buf, int pos) {\n"
    "    int wi = pos >> 2;\n"
    "    int bi = (3 - (pos & 3)) << 3;\n"
    "    return (uchar)(buf[wi] >> bi);\n"
    "}\n"
    "\n"
    "/* Update: accumulate bytes into 64-byte buffer, compress when full.\n"
    " * buf is 16 uints (64 bytes), bufpos is current byte position,\n"
    " * counter tracks total bytes processed. Data from private memory. */\n"
    "void sc_sha256_update(uint *state, uint *buf, int *bufpos,\n"
    "                      uint *counter, const uchar *data, int len)\n"
    "{\n"
    "    *counter += (uint)len;\n"
    "    int bp = *bufpos;\n"
    "    for (int i = 0; i < len; i++) {\n"
    "        sc_buf_set_byte(buf, bp, data[i]);\n"
    "        bp++;\n"
    "        if (bp == 64) {\n"
    "            sha256_block(state, buf);\n"
    "            for (int j = 0; j < 16; j++) buf[j] = 0;\n"
    "            bp = 0;\n"
    "        }\n"
    "    }\n"
    "    *bufpos = bp;\n"
    "}\n"
    "\n"
    "/* Update from global memory */\n"
    "void sc_sha256_update_g(uint *state, uint *buf, int *bufpos,\n"
    "                        uint *counter, __global const uchar *data, int len)\n"
    "{\n"
    "    *counter += (uint)len;\n"
    "    int bp = *bufpos;\n"
    "    for (int i = 0; i < len; i++) {\n"
    "        sc_buf_set_byte(buf, bp, data[i]);\n"
    "        bp++;\n"
    "        if (bp == 64) {\n"
    "            sha256_block(state, buf);\n"
    "            for (int j = 0; j < 16; j++) buf[j] = 0;\n"
    "            bp = 0;\n"
    "        }\n"
    "    }\n"
    "    *bufpos = bp;\n"
    "}\n"
    "\n"
    "/* Final: pad and produce 32-byte digest as raw bytes (big-endian state words) */\n"
    "void sc_sha256_final(uint *state, uint *buf, int bufpos,\n"
    "                     uint counter, uchar *out)\n"
    "{\n"
    "    /* Append 0x80 */\n"
    "    sc_buf_set_byte(buf, bufpos, 0x80);\n"
    "    bufpos++;\n"
    "\n"
    "    /* If not enough room for 8-byte length (need pos <= 56), flush */\n"
    "    if (bufpos > 56) {\n"
    "        for (int i = bufpos; i < 64; i++)\n"
    "            sc_buf_set_byte(buf, i, 0);\n"
    "        sha256_block(state, buf);\n"
    "        for (int j = 0; j < 16; j++) buf[j] = 0;\n"
    "        bufpos = 0;\n"
    "    }\n"
    "\n"
    "    /* Zero remaining bytes up to length field */\n"
    "    for (int i = bufpos; i < 56; i++)\n"
    "        sc_buf_set_byte(buf, i, 0);\n"
    "\n"
    "    /* Append 64-bit length in bits (big-endian). High 32 bits = 0 for our sizes. */\n"
    "    buf[14] = 0;\n"
    "    buf[15] = counter * 8;\n"
    "\n"
    "    sha256_block(state, buf);\n"
    "\n"
    "    /* Extract 32 bytes from state (big-endian) */\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        uint w = state[i];\n"
    "        out[i*4+0] = (uchar)(w >> 24);\n"
    "        out[i*4+1] = (uchar)(w >> 16);\n"
    "        out[i*4+2] = (uchar)(w >> 8);\n"
    "        out[i*4+3] = (uchar)(w);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* Convenience: one-shot SHA256(data, len) -> out[32] from private memory */\n"
    "void sc_sha256_oneshot(const uchar *data, int len, uchar *out) {\n"
    "    uint state[8];\n"
    "    uint buf[16];\n"
    "    int bufpos = 0;\n"
    "    uint counter = 0;\n"
    "    sc_sha256_init(state);\n"
    "    for (int j = 0; j < 16; j++) buf[j] = 0;\n"
    "    sc_sha256_update(state, buf, &bufpos, &counter, data, len);\n"
    "    sc_sha256_final(state, buf, bufpos, counter, out);\n"
    "}\n"
    "\n"
    "/* ---- SHA256CRYPT kernel ---- */\n"
    "\n"
    "__kernel void sha256crypt_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "\n"
    "    /* Copy password to private memory */\n"
    "    uchar pw[256];\n"
    "    for (int i = 0; i < plen; i++) pw[i] = pass[i];\n"
    "\n"
    "    /* Read salt string */\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen_full = salt_lens[salt_idx];\n"
    "    __global const uchar *salt_str = salts + soff;\n"
    "\n"
    "    /* Parse \"$5$[rounds=N$]salt[$]\" */\n"
    "    int spos = 3; /* skip \"$5$\" */\n"
    "    int rounds = 5000;\n"
    "\n"
    "    /* Check for \"rounds=\" */\n"
    "    if (slen_full > 10 && salt_str[3] == 'r' && salt_str[4] == 'o' &&\n"
    "        salt_str[5] == 'u' && salt_str[6] == 'n' && salt_str[7] == 'd' &&\n"
    "        salt_str[8] == 's' && salt_str[9] == '=') {\n"
    "        /* Parse decimal number */\n"
    "        rounds = 0;\n"
    "        spos = 10;\n"
    "        while (spos < slen_full && salt_str[spos] >= '0' && salt_str[spos] <= '9') {\n"
    "            rounds = rounds * 10 + (salt_str[spos] - '0');\n"
    "            spos++;\n"
    "        }\n"
    "        if (rounds < 1000) rounds = 1000;\n"
    "        if (rounds > 999999999) rounds = 999999999;\n"
    "        /* Skip the '$' after the number */\n"
    "        if (spos < slen_full && salt_str[spos] == '$') spos++;\n"
    "    }\n"
    "\n"
    "    /* Extract raw salt (up to 16 chars, stop at '$' or end) */\n"
    "    uchar raw_salt[16];\n"
    "    int saltlen = 0;\n"
    "    for (int i = spos; i < slen_full && saltlen < 16; i++) {\n"
    "        if (salt_str[i] == '$') break;\n"
    "        raw_salt[saltlen++] = salt_str[i];\n"
    "    }\n"
    "    if (saltlen == 0) return;\n"
    "\n"
    "    /* Working buffers */\n"
    "    uint state[8], ctx_buf[16];\n"
    "    int ctx_bufpos;\n"
    "    uint ctx_counter;\n"
    "    uchar tmp[256]; /* scratch for building messages */\n"
    "    uchar digest_a[32]; /* Hash A = alt_result in glibc */\n"
    "    uchar digest_b[32]; /* temporary */\n"
    "\n"
    "    /* ---- Step 1: Hash A = SHA256(pass + salt + pass) ---- */\n"
    "    {\n"
    "        int tlen = 0;\n"
    "        for (int i = 0; i < plen; i++) tmp[tlen++] = pw[i];\n"
    "        for (int i = 0; i < saltlen; i++) tmp[tlen++] = raw_salt[i];\n"
    "        for (int i = 0; i < plen; i++) tmp[tlen++] = pw[i];\n"
    "        sc_sha256_oneshot(tmp, tlen, digest_a);\n"
    "    }\n"
    "\n"
    "    /* ---- Step 2: Hash B ---- */\n"
    "    /* init; update(pass + salt); for passlen bytes: update chunks of A; bit-loop; final -> curin */\n"
    "    sc_sha256_init(state);\n"
    "    for (int j = 0; j < 16; j++) ctx_buf[j] = 0;\n"
    "    ctx_bufpos = 0; ctx_counter = 0;\n"
    "\n"
    "    /* update(pass + salt) */\n"
    "    sc_sha256_update(state, ctx_buf, &ctx_bufpos, &ctx_counter, pw, plen);\n"
    "    sc_sha256_update(state, ctx_buf, &ctx_bufpos, &ctx_counter, raw_salt, saltlen);\n"
    "\n"
    "    /* For passlen bytes, update chunks of digest_a (32 bytes each) */\n"
    "    for (int x = plen; x > 32; x -= 32)\n"
    "        sc_sha256_update(state, ctx_buf, &ctx_bufpos, &ctx_counter, digest_a, 32);\n"
    "    /* Remaining bytes */\n"
    "    {\n"
    "        int x = plen;\n"
    "        while (x > 32) x -= 32;\n"
    "        sc_sha256_update(state, ctx_buf, &ctx_bufpos, &ctx_counter, digest_a, x);\n"
    "    }\n"
    "\n"
    "    /* Bit loop: for each bit of passlen (LSB to MSB) */\n"
    "    for (int x = plen; x != 0; x >>= 1) {\n"
    "        if (x & 1)\n"
    "            sc_sha256_update(state, ctx_buf, &ctx_bufpos, &ctx_counter, digest_a, 32);\n"
    "        else\n"
    "            sc_sha256_update(state, ctx_buf, &ctx_bufpos, &ctx_counter, pw, plen);\n"
    "    }\n"
    "\n"
    "    uchar curin[32];\n"
    "    sc_sha256_final(state, ctx_buf, ctx_bufpos, ctx_counter, curin);\n"
    "\n"
    "    /* ---- Step 3: Hash P = SHA256(pass repeated passlen times) ---- */\n"
    "    sc_sha256_init(state);\n"
    "    for (int j = 0; j < 16; j++) ctx_buf[j] = 0;\n"
    "    ctx_bufpos = 0; ctx_counter = 0;\n"
    "    for (int x = 0; x < plen; x++)\n"
    "        sc_sha256_update(state, ctx_buf, &ctx_bufpos, &ctx_counter, pw, plen);\n"
    "    sc_sha256_final(state, ctx_buf, ctx_bufpos, ctx_counter, digest_b);\n"
    "\n"
    "    /* P-bytes: digest_b repeated to fill passlen bytes */\n"
    "    uchar p_bytes[256];\n"
    "    for (int i = 0; i < plen; i++)\n"
    "        p_bytes[i] = digest_b[i % 32];\n"
    "\n"
    "    /* ---- Step 4: Hash S = SHA256(salt repeated 16+curin[0] times) ---- */\n"
    "    sc_sha256_init(state);\n"
    "    for (int j = 0; j < 16; j++) ctx_buf[j] = 0;\n"
    "    ctx_bufpos = 0; ctx_counter = 0;\n"
    "    int s_repeats = 16 + (uint)curin[0];\n"
    "    for (int x = 0; x < s_repeats; x++)\n"
    "        sc_sha256_update(state, ctx_buf, &ctx_bufpos, &ctx_counter, raw_salt, saltlen);\n"
    "    sc_sha256_final(state, ctx_buf, ctx_bufpos, ctx_counter, digest_b);\n"
    "\n"
    "    /* S-bytes: first saltlen bytes of digest_b */\n"
    "    uchar s_bytes[16];\n"
    "    for (int i = 0; i < saltlen; i++)\n"
    "        s_bytes[i] = digest_b[i];\n"
    "\n"
    "    /* ---- Step 5: Main loop: rounds iterations ---- */\n"
    "    for (int r = 0; r < rounds; r++) {\n"
    "        sc_sha256_init(state);\n"
    "        for (int j = 0; j < 16; j++) ctx_buf[j] = 0;\n"
    "        ctx_bufpos = 0; ctx_counter = 0;\n"
    "\n"
    "        if (r & 1)\n"
    "            sc_sha256_update(state, ctx_buf, &ctx_bufpos, &ctx_counter, p_bytes, plen);\n"
    "        else\n"
    "            sc_sha256_update(state, ctx_buf, &ctx_bufpos, &ctx_counter, curin, 32);\n"
    "\n"
    "        if (r % 3)\n"
    "            sc_sha256_update(state, ctx_buf, &ctx_bufpos, &ctx_counter, s_bytes, saltlen);\n"
    "\n"
    "        if (r % 7)\n"
    "            sc_sha256_update(state, ctx_buf, &ctx_bufpos, &ctx_counter, p_bytes, plen);\n"
    "\n"
    "        if (r & 1)\n"
    "            sc_sha256_update(state, ctx_buf, &ctx_bufpos, &ctx_counter, curin, 32);\n"
    "        else\n"
    "            sc_sha256_update(state, ctx_buf, &ctx_bufpos, &ctx_counter, p_bytes, plen);\n"
    "\n"
    "        sc_sha256_final(state, ctx_buf, ctx_bufpos, ctx_counter, curin);\n"
    "    }\n"
    "\n"
    "    /* ---- Check result against compact hash table ---- */\n"
    "    /* curin[0..31] is the raw 32-byte hash.\n"
    "     * Compact probe uses first 16 bytes as 4 x uint32 (little-endian read). */\n"
    "    uint hx = (uint)curin[0] | ((uint)curin[1] << 8) |\n"
    "              ((uint)curin[2] << 16) | ((uint)curin[3] << 24);\n"
    "    uint hy = (uint)curin[4] | ((uint)curin[5] << 8) |\n"
    "              ((uint)curin[6] << 16) | ((uint)curin[7] << 24);\n"
    "    uint hz = (uint)curin[8] | ((uint)curin[9] << 8) |\n"
    "              ((uint)curin[10] << 16) | ((uint)curin[11] << 24);\n"
    "    uint hw = (uint)curin[12] | ((uint)curin[13] << 8) |\n"
    "              ((uint)curin[14] << 16) | ((uint)curin[15] << 24);\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        { uint _h[8];\n"
    "            for (int _i = 0; _i < 8; _i++) _h[_i] = (uint)curin[_i*4] | ((uint)curin[_i*4+1] << 8) | ((uint)curin[_i*4+2] << 16) | ((uint)curin[_i*4+3] << 24);\n"
    "            EMIT_HIT_8(hits, hit_count, params.max_hits, word_idx, salt_idx, 1, _h) }\n"
    "    }\n"
    "}\n"
;
