/* Auto-generated from gpu_md5unsalted.cl -- do not edit */
static const char gpu_md5unsalted_str[] =
    "/* gpu_md5unsalted.cl — Pre-padded unsalted MD5 with mask expansion\n"
    " *\n"
    " * Input: 4096 pre-padded 64-byte M[] blocks in passbuf (word_stride=64).\n"
    " *   Each block has: password at offset n_prepend, 0x80 padding, M[14]=bitlen.\n"
    " *   Prepend/append gaps are zeroed — GPU fills them per mask combination.\n"
    " *\n"
    " * Dispatch: num_words × num_masks threads.\n"
    " *   word_idx = tid / num_masks, mask_idx = mask_start + (tid % num_masks)\n"
    " *\n"
    " * Hit stride: 6 (word_idx, mask_idx, hx, hy, hz, hw) or\n"
    " *             7 (word_idx, mask_idx, iter, hx, hy, hz, hw) when max_iter > 1\n"
    " */\n"
    "\n"
    "/* Primitives (hex_byte_lc, md5_to_hex_lc, md5_block) provided by gpu_common.cl */\n"
    "\n"
    "__kernel void md5_unsalted_batch(\n"
    "    __global const uint *words,          /* pre-padded M[] blocks, 16 uint32 each */\n"
    "    __global const ushort *unused_lens,  /* not used — total length is in M[14]/8 */\n"
    "    __global const uchar *mask_desc,     /* mask descriptor: [prepend IDs][append IDs] */\n"
    "    __global const uint *unused1, __global const ushort *unused2,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    ulong mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    /* Load pre-padded M[] block (16 uint32 = 64 bytes) */\n"
    "    __global const uint *src = words + word_idx * 16;\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    /* Fill mask positions into M[] */\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint n_total_m = n_pre + n_app;\n"
    "\n"
    "        if (n_pre > 0) {\n"
    "            /* Prepend+append: split mask_idx into prepend and append indices.\n"
    "             * append_combos fits uint32 for practical -N/-n combinations. */\n"
    "            uint append_combos = 1;\n"
    "            for (uint i = 0; i < n_app; i++)\n"
    "                append_combos *= mask_desc[n_pre + i];\n"
    "            uint prepend_idx = (uint)(mask_idx / append_combos);\n"
    "            uint append_idx = (uint)(mask_idx % append_combos);\n"
    "\n"
    "            /* Fill prepend chars at byte offset 0 */\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                M[i >> 2] = (M[i >> 2] & ~(0xFFu << ((i & 3) << 3)))\n"
    "                           | ((uint)ch << ((i & 3) << 3));\n"
    "            }\n"
    "\n"
    "            /* Fill append chars */\n"
    "            if (n_app > 0) {\n"
    "                int total_len = M[14] >> 3;\n"
    "                int app_start = total_len - (int)n_app;\n"
    "                uint aidx = append_idx;\n"
    "                for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                    int pos_idx = n_pre + i;\n"
    "                    uint sz = mask_desc[pos_idx];\n"
    "                    uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                    aidx /= sz;\n"
    "                    int pos = app_start + i;\n"
    "                    M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                                 | ((uint)ch << ((pos & 3) << 3));\n"
    "                }\n"
    "            }\n"
    "        } else {\n"
    "            /* Append-only (brute-force): host pre-decomposes mask_start into\n"
    "             * per-position base offsets. Kernel does fast uint32 local\n"
    "             * decomposition and adds to base with carry. */\n"
    "            int total_len = M[14] >> 3;\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint local_idx = tid % params.num_masks;\n"
    "            uint aidx = local_idx;\n"
    "            uint carry = 0;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uint local_digit = aidx % sz;\n"
    "                aidx /= sz;\n"
    "                uint base_digit = (i < 8)\n"
    "                    ? (uint)((params.mask_base0 >> (i * 8)) & 0xFF)\n"
    "                    : (uint)((params.mask_base1 >> ((i - 8) * 8)) & 0xFF);\n"
    "                uint sum = base_digit + local_digit + carry;\n"
    "                carry = sum / sz;\n"
    "                uint final_digit = sum % sz;\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + final_digit];\n"
    "                int pos = app_start + i;\n"
    "                M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                             | ((uint)ch << ((pos & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* MD5 compress (single block, fully unrolled) */\n"
    "    uint hx = 0x67452301u, hy = 0xEFCDAB89u, hz = 0x98BADCFEu, hw = 0x10325476u;\n"
    "    md5_block(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "    /* Probe compact table at iteration 1 and emit hit */\n"
    "    uint max_iter = params.max_iter;\n"
    "    uint hit_stride = (max_iter > 1) ? 7 : 6;\n"
    "\n"
    "    for (uint iter = 1; iter <= max_iter; iter++) {\n"
    "        if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                          params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                          hash_data_buf, hash_data_off,\n"
    "                          overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "            uint slot = atomic_add(hit_count, 1u);\n"
    "            if (slot < params.max_hits) {\n"
    "                uint base = slot * hit_stride;\n"
    "                hits[base]   = word_idx;\n"
    "                hits[base+1] = mask_idx;\n"
    "                if (hit_stride == 7) {\n"
    "                    hits[base+2] = iter;\n"
    "                    hits[base+3] = hx; hits[base+4] = hy;\n"
    "                    hits[base+5] = hz; hits[base+6] = hw;\n"
    "                } else {\n"
    "                    hits[base+2] = hx; hits[base+3] = hy;\n"
    "                    hits[base+4] = hz; hits[base+5] = hw;\n"
    "                }\n"
    "                mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "            }\n"
    "        }\n"
    "        if (iter < max_iter) {\n"
    "            /* Hex-encode hash into M[0..7], set up constant padding */\n"
    "            md5_to_hex_lc(hx, hy, hz, hw, M);\n"
    "            M[8] = 0x80;\n"
    "            for (int i = 9; i < 14; i++) M[i] = 0;\n"
    "            M[14] = 32 * 8; M[15] = 0;  /* 32 hex bytes = 256 bits */\n"
    "            hx = 0x67452301u; hy = 0xEFCDAB89u; hz = 0x98BADCFEu; hw = 0x10325476u;\n"
    "            md5_block(&hx, &hy, &hz, &hw, M);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* MD5RAW: md5(md5_binary(pass)) — binary iteration, single block.\n"
    " * Hit stride: 6 */\n"
    "__kernel void md5raw_unsalted_batch(\n"
    "    __global const uint *words, __global const ushort *unused_lens,\n"
    "    __global const uchar *mask_desc,\n"
    "    __global const uint *unused1, __global const ushort *unused2,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    ulong mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    __global const uint *src = words + word_idx * 16;\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    uint n_pre = params.n_prepend, n_app = params.n_append;\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint n_total_m = n_pre + n_app;\n"
    "        uint append_combos = 1;\n"
    "        for (uint i = 0; i < n_app; i++) append_combos *= mask_desc[n_pre + i];\n"
    "        uint prepend_idx = (uint)(mask_idx / append_combos);\n"
    "        uint append_idx = (uint)(mask_idx % append_combos);\n"
    "        if (n_pre > 0) {\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                M[i >> 2] = (M[i >> 2] & ~(0xFFu << ((i & 3) << 3))) | ((uint)ch << ((i & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "        if (n_app > 0) {\n"
    "            int total_len = M[14] >> 3;\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint aidx = append_idx;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                int pos_idx = n_pre + i;\n"
    "                uint sz = mask_desc[pos_idx];\n"
    "                uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                aidx /= sz;\n"
    "                int pos = app_start + i;\n"
    "                M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3))) | ((uint)ch << ((pos & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* First MD5 of password */\n"
    "    uint hx = 0x67452301u, hy = 0xEFCDAB89u, hz = 0x98BADCFEu, hw = 0x10325476u;\n"
    "    md5_block(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "    /* Binary iteration: md5(md5_binary(prev)) for each iteration.\n"
    "     * Set up fixed padding for 16-byte binary input once. */\n"
    "    M[4] = 0x80;\n"
    "    for (int i = 5; i < 14; i++) M[i] = 0;\n"
    "    M[14] = 128; M[15] = 0;  /* 16 bytes = 128 bits */\n"
    "\n"
    "    uint max_iter = params.max_iter;\n"
    "    uint hit_stride = (max_iter > 1) ? 7 : 6;\n"
    "\n"
    "    for (uint iter = 1; iter <= max_iter; iter++) {\n"
    "        /* Binary re-hash: md5(previous_hash_binary) */\n"
    "        M[0] = hx; M[1] = hy; M[2] = hz; M[3] = hw;\n"
    "        hx = 0x67452301u; hy = 0xEFCDAB89u; hz = 0x98BADCFEu; hw = 0x10325476u;\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "        if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                          params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                          hash_data_buf, hash_data_off,\n"
    "                          overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "            uint slot = atomic_add(hit_count, 1u);\n"
    "            if (slot < params.max_hits) {\n"
    "                uint base = slot * hit_stride;\n"
    "                hits[base]   = word_idx;\n"
    "                hits[base+1] = mask_idx;\n"
    "                if (hit_stride == 7) {\n"
    "                    hits[base+2] = iter;\n"
    "                    hits[base+3] = hx; hits[base+4] = hy;\n"
    "                    hits[base+5] = hz; hits[base+6] = hw;\n"
    "                } else {\n"
    "                    hits[base+2] = hx; hits[base+3] = hy;\n"
    "                    hits[base+4] = hz; hits[base+5] = hw;\n"
    "                }\n"
    "                mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "}\n"
;
