/* Auto-generated from gpu_hmac_blake2s.cl -- do not edit */
static const char gpu_hmac_blake2s_str[] =
    "/* gpu_hmac_blake2s.cl — HMAC-BLAKE2S GPU kernel (e828, hashcat 33300)\n"
    " * BLAKE2s: 64-byte block, 32-byte output, little-endian, no tables.\n"
    " * HMAC key=$pass: BLAKE2S((K⊕opad) || BLAKE2S((K⊕ipad) || salt))\n"
    " * Hit stride: 7 (word_idx, salt_idx, iter, hx, hy, hz, hw)\n"
    " *\n"
    " * Primitives (B2S_IV, B2S_SIGMA, b2s_compress) provided by gpu_common.cl\n"
    " */\n"
    "\n"
    "/* Full blake2s hash (no key, outlen=32) on a buffer up to 128 bytes */\n"
    "void blake2s_hash(uint *out, const uchar *data, int datalen) {\n"
    "    uint h[8];\n"
    "    for (int i = 0; i < 8; i++) h[i] = B2S_IV[i];\n"
    "    h[0] ^= 0x01010020u;  /* outlen=32, keylen=0, fanout=1, depth=1 */\n"
    "\n"
    "    uchar buf[64];\n"
    "    ulong counter = 0;\n"
    "    int pos = 0;\n"
    "    const uchar *p = data;\n"
    "    int remaining = datalen;\n"
    "\n"
    "    while (remaining > 0) {\n"
    "        if (pos == 64) {\n"
    "            counter += 64;\n"
    "            b2s_compress(h, buf, counter, 0);\n"
    "            pos = 0;\n"
    "        }\n"
    "        int take = 64 - pos;\n"
    "        if (take > remaining) take = remaining;\n"
    "        for (int i = 0; i < take; i++) buf[pos + i] = p[i];\n"
    "        pos += take; p += take; remaining -= take;\n"
    "    }\n"
    "    counter += pos;\n"
    "    for (int i = pos; i < 64; i++) buf[i] = 0;\n"
    "    b2s_compress(h, buf, counter, 1);\n"
    "    for (int i = 0; i < 8; i++) out[i] = h[i];\n"
    "}\n"
    "\n"
    "__kernel void hmac_blake2s_kpass_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int klen = hexlens[word_idx];\n"
    "    __global const uchar *key = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int mlen = salt_lens[salt_idx];\n"
    "    __global const uchar *msg = salts + soff;\n"
    "\n"
    "    /* Prepare key pad (64 bytes) */\n"
    "    uchar kpad[64];\n"
    "    if (klen > 64) {\n"
    "        uint kh[8];\n"
    "        uchar kb[256];\n"
    "        for (int i = 0; i < klen; i++) kb[i] = key[i];\n"
    "        blake2s_hash(kh, kb, klen);\n"
    "        for (int i = 0; i < 32; i++) kpad[i] = ((uchar *)kh)[i];\n"
    "        for (int i = 32; i < 64; i++) kpad[i] = 0;\n"
    "    } else {\n"
    "        for (int i = 0; i < klen; i++) kpad[i] = key[i];\n"
    "        for (int i = klen; i < 64; i++) kpad[i] = 0;\n"
    "    }\n"
    "\n"
    "    /* Inner: BLAKE2S((K ^ ipad) || salt) */\n"
    "    uchar ibuf[192];  /* max 64 + 128 bytes */\n"
    "    for (int i = 0; i < 64; i++) ibuf[i] = kpad[i] ^ 0x36;\n"
    "    for (int i = 0; i < mlen; i++) ibuf[64 + i] = msg[i];\n"
    "    uint inner[8];\n"
    "    blake2s_hash(inner, ibuf, 64 + mlen);\n"
    "\n"
    "    /* Outer: BLAKE2S((K ^ opad) || inner_hash) */\n"
    "    uchar obuf[96];\n"
    "    for (int i = 0; i < 64; i++) obuf[i] = kpad[i] ^ 0x5c;\n"
    "    for (int i = 0; i < 32; i++) obuf[64 + i] = ((uchar *)inner)[i];\n"
    "    uint outer[8];\n"
    "    blake2s_hash(outer, obuf, 96);\n"
    "\n"
    "    uint hx = outer[0], hy = outer[1], hz = outer[2], hw = outer[3];\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        EMIT_HIT_4(hits, hit_count, params.max_hits, word_idx, salt_idx, 1, hx, hy, hz, hw)\n"
    "    }\n"
    "}\n"
;
