/* Auto-generated from gpu_keccakunsalted.cl -- do not edit */
static const char gpu_keccakunsalted_str[] =
    "/* gpu_keccakunsalted.cl — Keccak-224/256/384/512 unsalted with mask expansion\n"
    " *\n"
    " * Keccak (SHA-3 competition version, without NIST 0x06 domain separator).\n"
    " * Sponge construction: XOR padded message into zero state, apply Keccak-f[1600].\n"
    " * Natively little-endian — no byte-swap needed.\n"
    " *\n"
    " * Padding: 0x01 after message, 0x80 at last rate byte.\n"
    " * Rate: 144 (224), 136 (256), 104 (384), 72 (512) bytes.\n"
    " *\n"
    " * Input: pre-padded rate-sized blocks with Keccak padding applied by host.\n"
    " * Dispatch: num_words × num_masks threads.\n"
    " * Hit stride: 6 (word_idx, mask_idx, hx, hy, hz, hw)\n"
    " */\n"
    "\n"
    "\n"
    "/* Keccak-f[1600] round constants */\n"
    "__constant ulong RC[24] = {\n"
    "    0x0000000000000001UL, 0x0000000000008082UL, 0x800000000000808aUL,\n"
    "    0x8000000080008000UL, 0x000000000000808bUL, 0x0000000080000001UL,\n"
    "    0x8000000080008081UL, 0x8000000000008009UL, 0x000000000000008aUL,\n"
    "    0x0000000000000088UL, 0x0000000080008009UL, 0x000000008000000aUL,\n"
    "    0x000000008000808bUL, 0x800000000000008bUL, 0x8000000000008089UL,\n"
    "    0x8000000000008003UL, 0x8000000000008002UL, 0x8000000000000080UL,\n"
    "    0x000000000000800aUL, 0x800000008000000aUL, 0x8000000080008081UL,\n"
    "    0x8000000000008080UL, 0x0000000080000001UL, 0x8000000080008008UL\n"
    "};\n"
    "\n"
    "/* Keccak-f[1600] rotation offsets (linearized [x][y] where index = x*5+y) */\n"
    "__constant uint ROTC[25] = {\n"
    "     0,  1, 62, 28, 27,\n"
    "    36, 44,  6, 55, 20,\n"
    "     3, 10, 43, 25, 39,\n"
    "    41, 45, 15, 21,  8,\n"
    "    18,  2, 61, 56, 14\n"
    "};\n"
    "\n"
    "/* Keccak-f[1600] permutation — 24 rounds on 5×5 state of uint64 */\n"
    "void keccak_f1600(ulong *st) {\n"
    "    for (int round = 0; round < 24; round++) {\n"
    "        /* θ (theta) */\n"
    "        ulong C[5], D[5];\n"
    "        for (int x = 0; x < 5; x++)\n"
    "            C[x] = st[x] ^ st[x+5] ^ st[x+10] ^ st[x+15] ^ st[x+20];\n"
    "        for (int x = 0; x < 5; x++) {\n"
    "            D[x] = C[(x+4) % 5] ^ rotate(C[(x+1) % 5], (ulong)1);\n"
    "            for (int y = 0; y < 25; y += 5)\n"
    "                st[x+y] ^= D[x];\n"
    "        }\n"
    "\n"
    "        /* ρ (rho) + π (pi) combined */\n"
    "        ulong B[25];\n"
    "        for (int x = 0; x < 5; x++)\n"
    "            for (int y = 0; y < 5; y++)\n"
    "                B[x + 5 * ((2*y + 3*x) % 5)] = rotate(st[x*5+y], (ulong)ROTC[x*5+y]);\n"
    "\n"
    "        /* χ (chi) */\n"
    "        for (int x = 0; x < 5; x++)\n"
    "            for (int y = 0; y < 25; y += 5)\n"
    "                st[x+y] = B[x+y] ^ (~B[((x+1)%5)+y] & B[((x+2)%5)+y]);\n"
    "\n"
    "        /* ι (iota) */\n"
    "        st[0] ^= RC[round];\n"
    "    }\n"
    "}\n"
    "\n"
    "/* Fill masks into LE uint64 block (rate_words uint64 words) */\n"
    "void keccak_fill_masks(ulong *block, uint n_pre, uint n_app, uint mask_idx,\n"
    "                       __global const uchar *mask_desc, int rate,\n"
    "                       uint num_masks, ulong mask_base0, ulong mask_base1) {\n"
    "    uint n_total_m = n_pre + n_app;\n"
    "\n"
    "    if (n_pre > 0) {\n"
    "        uint append_combos = 1;\n"
    "        for (uint i = 0; i < n_app; i++)\n"
    "            append_combos *= mask_desc[n_pre + i];\n"
    "        uint prepend_idx = (uint)(mask_idx / append_combos);\n"
    "        uint append_idx = (uint)(mask_idx % append_combos);\n"
    "\n"
    "        uint pidx = prepend_idx;\n"
    "        for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "            uint sz = mask_desc[i];\n"
    "            uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "            pidx /= sz;\n"
    "            int wi = i >> 3;\n"
    "            int bi = (i & 7) << 3;\n"
    "            block[wi] = (block[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "        }\n"
    "\n"
    "        if (n_app > 0) {\n"
    "            uchar *bp = (uchar *)block;\n"
    "            int total_len = bp[rate] | (bp[rate+1] << 8);\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint aidx = append_idx;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                int pos_idx = n_pre + i;\n"
    "                uint sz = mask_desc[pos_idx];\n"
    "                uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                aidx /= sz;\n"
    "                int pos = app_start + i;\n"
    "                int wi = pos >> 3;\n"
    "                int bi = (pos & 7) << 3;\n"
    "                block[wi] = (block[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "            }\n"
    "        }\n"
    "    } else {\n"
    "        /* Append-only (brute-force): host pre-decomposes mask_start into\n"
    "         * per-position base offsets. Kernel does fast uint32 local\n"
    "         * decomposition and adds to base with carry. */\n"
    "        uchar *bp = (uchar *)block;\n"
    "        int total_len = bp[rate] | (bp[rate+1] << 8);\n"
    "        int app_start = total_len - (int)n_app;\n"
    "        uint local_idx = mask_idx % num_masks;\n"
    "        uint aidx = local_idx;\n"
    "        uint carry = 0;\n"
    "        for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "            uint sz = mask_desc[i];\n"
    "            uint local_digit = aidx % sz;\n"
    "            aidx /= sz;\n"
    "            uint base_digit = (i < 8)\n"
    "                ? (uint)((mask_base0 >> (i * 8)) & 0xFF)\n"
    "                : (uint)((mask_base1 >> ((i - 8) * 8)) & 0xFF);\n"
    "            uint sum = base_digit + local_digit + carry;\n"
    "            carry = sum / sz;\n"
    "            uint final_digit = sum % sz;\n"
    "            uchar ch = mask_desc[n_total_m + i * 256 + final_digit];\n"
    "            int pos = app_start + i;\n"
    "            int wi = pos >> 3;\n"
    "            int bi = (pos & 7) << 3;\n"
    "            block[wi] = (block[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* Generic Keccak unsalted kernel.\n"
    " * rate_words = rate / 8.\n"
    " * hash_words = output hash size in uint32 (e.g. 7 for 224, 8 for 256, etc.)\n"
    " * hash_ulongs = number of uint64 state words containing output (ceil(hash_words/2))\n"
    " * The host packs: message in LE, 0x01 at total_len, 0x80 at rate-1.\n"
    " * total_len stored as uint16 at byte offset rate for mask append. */\n"
    "#define KECCAK_KERNEL(name, rate, rate_words, hash_words, hash_ulongs)         \\\n"
    "__kernel void name(                                                            \\\n"
    "    __global const uchar *words,                                               \\\n"
    "    __global const ushort *unused_lens,                                         \\\n"
    "    __global const uchar *mask_desc,                                           \\\n"
    "    __global const uint *unused1, __global const ushort *unused2,              \\\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,         \\\n"
    "    __global const OCLParams *params_buf,                                      \\\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off, \\\n"
    "    __global const ushort *hash_data_len,                                      \\\n"
    "    __global uint *hits, __global volatile uint *hit_count,                    \\\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\\\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths) \\\n"
    "{                                                                              \\\n"
    "    OCLParams params = *params_buf;                                            \\\n"
    "    uint tid = get_global_id(0);                                               \\\n"
    "    uint word_idx = tid / params.num_masks;                                    \\\n"
    "    ulong mask_idx = params.mask_start + (tid % params.num_masks);              \\\n"
    "    if (word_idx >= params.num_words) return;                                  \\\n"
    "                                                                               \\\n"
    "    /* Load padded block (rate bytes + 2 bytes metadata) */                    \\\n"
    "    int stride = rate + 8; /* stride includes metadata + alignment */          \\\n"
    "    __global const ulong *src = (__global const ulong *)(words + word_idx * stride); \\\n"
    "    ulong block[rate_words];                                                   \\\n"
    "    for (int i = 0; i < rate_words; i++) block[i] = src[i];                   \\\n"
    "                                                                               \\\n"
    "    /* Fill mask positions — LE byte manipulation, same approach */            \\\n"
    "    if (params.n_prepend > 0 || params.n_append > 0)                           \\\n"
    "        keccak_fill_masks(block, params.n_prepend, params.n_append,            \\\n"
    "                          mask_idx, mask_desc, rate,                            \\\n"
    "                          params.num_masks, params.mask_base0, params.mask_base1); \\\n"
    "                                                                               \\\n"
    "    /* XOR block into zero state and run Keccak-f[1600] */                     \\\n"
    "    ulong st[25];                                                              \\\n"
    "    for (int i = 0; i < 25; i++) st[i] = 0;                                   \\\n"
    "    for (int i = 0; i < rate_words; i++) st[i] = block[i];                    \\\n"
    "    keccak_f1600(st);                                                          \\\n"
    "                                                                               \\\n"
    "    /* Extract all hash words from state (LE, no swap needed) */               \\\n"
    "    uint h[hash_words];                                                        \\\n"
    "    for (int i = 0; i < hash_ulongs; i++) {                                    \\\n"
    "        h[i*2]   = (uint)st[i];                                               \\\n"
    "        if (i*2+1 < hash_words) h[i*2+1] = (uint)(st[i] >> 32);              \\\n"
    "    }                                                                          \\\n"
    "                                                                               \\\n"
    "    /* Probe compact table with first 128 bits */                              \\\n"
    "    if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,        \\\n"
    "                      params.compact_mask, params.max_probe,                   \\\n"
    "                      params.hash_data_count, hash_data_buf, hash_data_off,    \\\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets,         \\\n"
    "                      params.overflow_count)) {                                \\\n"
    "        uint slot = atomic_add(hit_count, 1u);                                 \\\n"
    "        if (slot < params.max_hits) {                                          \\\n"
    "            uint base = slot * (2 + hash_words);                               \\\n"
    "            hits[base] = word_idx; hits[base+1] = mask_idx;                    \\\n"
    "            for (int i = 0; i < hash_words; i++) hits[base+2+i] = h[i];       \\\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);                                   \\\n"
    "        }                                                                      \\\n"
    "    }                                                                          \\\n"
    "}\n"
    "\n"
    "/* Keccak-224: rate=144 bytes = 18 uint64 words, output=7 uint32 (4 uint64) (pad byte 0x01) */\n"
    "KECCAK_KERNEL(keccak224_unsalted_batch, 144, 18, 7, 4)\n"
    "\n"
    "/* Keccak-256: rate=136 bytes = 17 uint64 words, output=8 uint32 (4 uint64) (pad byte 0x01) */\n"
    "KECCAK_KERNEL(keccak256_unsalted_batch, 136, 17, 8, 4)\n"
    "\n"
    "/* Keccak-384: rate=104 bytes = 13 uint64 words, output=12 uint32 (6 uint64) (pad byte 0x01) */\n"
    "KECCAK_KERNEL(keccak384_unsalted_batch, 104, 13, 12, 6)\n"
    "\n"
    "/* Keccak-512: rate=72 bytes = 9 uint64 words, output=16 uint32 (8 uint64) (pad byte 0x01) */\n"
    "KECCAK_KERNEL(keccak512_unsalted_batch, 72, 9, 16, 8)\n"
    "\n"
    "/* SHA3-224/256/384/512: same permutation, pad byte 0x06 (applied by host packer).\n"
    " * Same rates as Keccak. Kernel is identical — only padding differs. */\n"
    "KECCAK_KERNEL(sha3_224_unsalted_batch, 144, 18, 7, 4)\n"
    "KECCAK_KERNEL(sha3_256_unsalted_batch, 136, 17, 8, 4)\n"
    "KECCAK_KERNEL(sha3_384_unsalted_batch, 104, 13, 12, 6)\n"
    "KECCAK_KERNEL(sha3_512_unsalted_batch, 72, 9, 16, 8)\n"
;
