/* Auto-generated from gpu_sha512crypt.cl -- do not edit */
static const char gpu_sha512crypt_str[] =
    "/* gpu_sha512crypt.cl -- SHA512CRYPT (e513, hashcat 1800) OpenCL kernel\n"
    " *\n"
    " * glibc crypt-sha512: $6$[rounds=N$]salt$hash\n"
    " * Default 5000 rounds, salt up to 16 chars, SHA512 (64-byte digest).\n"
    " *\n"
    " * Hit stride: 7 (word_idx, salt_idx, iter, hx, hy, hz, hw)\n"
    " * Compact probe: first 16 bytes of 64-byte hash as 4 x uint32\n"
    " */\n"
    "\n"
    "/* SHA512 primitives (bswap64, K512, rotr64, sha512_block) from gpu_common.cl.\n"
    " * SC_IV aliases for sha512crypt init convenience. */\n"
    "\n"
    "#define SC_IV0 0x6a09e667f3bcc908UL\n"
    "#define SC_IV1 0xbb67ae8584caa73bUL\n"
    "#define SC_IV2 0x3c6ef372fe94f82bUL\n"
    "#define SC_IV3 0xa54ff53a5f1d36f1UL\n"
    "#define SC_IV4 0x510e527fade682d1UL\n"
    "#define SC_IV5 0x9b05688c2b3e6c1fUL\n"
    "#define SC_IV6 0x1f83d9abfb41bd6bUL\n"
    "#define SC_IV7 0x5be0cd19137e2179UL\n"
    "\n"
    "/* ---- Buffered SHA512: init / update / final ---- */\n"
    "\n"
    "void sc_sha512_init(ulong *state) {\n"
    "    state[0] = SC_IV0; state[1] = SC_IV1;\n"
    "    state[2] = SC_IV2; state[3] = SC_IV3;\n"
    "    state[4] = SC_IV4; state[5] = SC_IV5;\n"
    "    state[6] = SC_IV6; state[7] = SC_IV7;\n"
    "}\n"
    "\n"
    "/* Store a byte into big-endian ulong buffer at byte position pos */\n"
    "void sc_buf_set_byte(ulong *buf, int pos, uchar val) {\n"
    "    int wi = pos >> 3;\n"
    "    int bi = (7 - (pos & 7)) << 3;\n"
    "    buf[wi] = (buf[wi] & ~(0xffUL << bi)) | ((ulong)val << bi);\n"
    "}\n"
    "\n"
    "/* Get a byte from big-endian ulong buffer at byte position pos */\n"
    "uchar sc_buf_get_byte(ulong *buf, int pos) {\n"
    "    int wi = pos >> 3;\n"
    "    int bi = (7 - (pos & 7)) << 3;\n"
    "    return (uchar)(buf[wi] >> bi);\n"
    "}\n"
    "\n"
    "/* Update: accumulate bytes into 128-byte buffer, compress when full.\n"
    " * buf is 16 ulongs (128 bytes), bufpos is current byte position,\n"
    " * counter tracks total bytes processed. Data from private memory. */\n"
    "void sc_sha512_update(ulong *state, ulong *buf, int *bufpos,\n"
    "                      ulong *counter, const uchar *data, int len)\n"
    "{\n"
    "    *counter += (ulong)len;\n"
    "    int bp = *bufpos;\n"
    "    for (int i = 0; i < len; i++) {\n"
    "        sc_buf_set_byte(buf, bp, data[i]);\n"
    "        bp++;\n"
    "        if (bp == 128) {\n"
    "            sha512_block(state, buf);\n"
    "            for (int j = 0; j < 16; j++) buf[j] = 0;\n"
    "            bp = 0;\n"
    "        }\n"
    "    }\n"
    "    *bufpos = bp;\n"
    "}\n"
    "\n"
    "/* Update from global memory */\n"
    "void sc_sha512_update_g(ulong *state, ulong *buf, int *bufpos,\n"
    "                        ulong *counter, __global const uchar *data, int len)\n"
    "{\n"
    "    *counter += (ulong)len;\n"
    "    int bp = *bufpos;\n"
    "    for (int i = 0; i < len; i++) {\n"
    "        sc_buf_set_byte(buf, bp, data[i]);\n"
    "        bp++;\n"
    "        if (bp == 128) {\n"
    "            sha512_block(state, buf);\n"
    "            for (int j = 0; j < 16; j++) buf[j] = 0;\n"
    "            bp = 0;\n"
    "        }\n"
    "    }\n"
    "    *bufpos = bp;\n"
    "}\n"
    "\n"
    "/* Final: pad and produce 64-byte digest as raw bytes (big-endian state words) */\n"
    "void sc_sha512_final(ulong *state, ulong *buf, int bufpos,\n"
    "                     ulong counter, uchar *out)\n"
    "{\n"
    "    /* Append 0x80 */\n"
    "    sc_buf_set_byte(buf, bufpos, 0x80);\n"
    "    bufpos++;\n"
    "\n"
    "    /* If not enough room for 16-byte length (need pos <= 112), flush */\n"
    "    if (bufpos > 112) {\n"
    "        for (int i = bufpos; i < 128; i++)\n"
    "            sc_buf_set_byte(buf, i, 0);\n"
    "        sha512_block(state, buf);\n"
    "        for (int j = 0; j < 16; j++) buf[j] = 0;\n"
    "        bufpos = 0;\n"
    "    }\n"
    "\n"
    "    /* Zero remaining bytes up to length field */\n"
    "    for (int i = bufpos; i < 112; i++)\n"
    "        sc_buf_set_byte(buf, i, 0);\n"
    "\n"
    "    /* Append 128-bit length in bits (big-endian). High 64 bits = 0 for our sizes. */\n"
    "    buf[14] = 0;\n"
    "    buf[15] = counter * 8;\n"
    "\n"
    "    sha512_block(state, buf);\n"
    "\n"
    "    /* Extract 64 bytes from state (big-endian) */\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        ulong w = state[i];\n"
    "        out[i*8+0] = (uchar)(w >> 56);\n"
    "        out[i*8+1] = (uchar)(w >> 48);\n"
    "        out[i*8+2] = (uchar)(w >> 40);\n"
    "        out[i*8+3] = (uchar)(w >> 32);\n"
    "        out[i*8+4] = (uchar)(w >> 24);\n"
    "        out[i*8+5] = (uchar)(w >> 16);\n"
    "        out[i*8+6] = (uchar)(w >> 8);\n"
    "        out[i*8+7] = (uchar)(w);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* Convenience: one-shot SHA512(data, len) -> out[64] from private memory */\n"
    "void sc_sha512_oneshot(const uchar *data, int len, uchar *out) {\n"
    "    ulong state[8];\n"
    "    ulong buf[16];\n"
    "    int bufpos = 0;\n"
    "    ulong counter = 0;\n"
    "    sc_sha512_init(state);\n"
    "    for (int j = 0; j < 16; j++) buf[j] = 0;\n"
    "    sc_sha512_update(state, buf, &bufpos, &counter, data, len);\n"
    "    sc_sha512_final(state, buf, bufpos, counter, out);\n"
    "}\n"
    "\n"
    "/* ---- SHA512CRYPT kernel ---- */\n"
    "\n"
    "__kernel void sha512crypt_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "\n"
    "    /* Copy password to private memory */\n"
    "    uchar pw[256];\n"
    "    for (int i = 0; i < plen; i++) pw[i] = pass[i];\n"
    "\n"
    "    /* Read salt string */\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen_full = salt_lens[salt_idx];\n"
    "    __global const uchar *salt_str = salts + soff;\n"
    "\n"
    "    /* Parse \"$6$[rounds=N$]salt[$]\" */\n"
    "    int spos = 3; /* skip \"$6$\" */\n"
    "    int rounds = 5000;\n"
    "\n"
    "    /* Check for \"rounds=\" */\n"
    "    if (slen_full > 10 && salt_str[3] == 'r' && salt_str[4] == 'o' &&\n"
    "        salt_str[5] == 'u' && salt_str[6] == 'n' && salt_str[7] == 'd' &&\n"
    "        salt_str[8] == 's' && salt_str[9] == '=') {\n"
    "        /* Parse decimal number */\n"
    "        rounds = 0;\n"
    "        spos = 10;\n"
    "        while (spos < slen_full && salt_str[spos] >= '0' && salt_str[spos] <= '9') {\n"
    "            rounds = rounds * 10 + (salt_str[spos] - '0');\n"
    "            spos++;\n"
    "        }\n"
    "        if (rounds < 1000) rounds = 1000;\n"
    "        if (rounds > 999999999) rounds = 999999999;\n"
    "        /* Skip the '$' after the number */\n"
    "        if (spos < slen_full && salt_str[spos] == '$') spos++;\n"
    "    }\n"
    "\n"
    "    /* Extract raw salt (up to 16 chars, stop at '$' or end) */\n"
    "    uchar raw_salt[16];\n"
    "    int saltlen = 0;\n"
    "    for (int i = spos; i < slen_full && saltlen < 16; i++) {\n"
    "        if (salt_str[i] == '$') break;\n"
    "        raw_salt[saltlen++] = salt_str[i];\n"
    "    }\n"
    "    if (saltlen == 0) return;\n"
    "\n"
    "    /* Working buffers */\n"
    "    ulong state[8], ctx_buf[16];\n"
    "    int ctx_bufpos;\n"
    "    ulong ctx_counter;\n"
    "    uchar tmp[256]; /* scratch for building messages */\n"
    "    uchar digest_a[64]; /* Hash A = alt_result in glibc */\n"
    "    uchar digest_b[64]; /* temporary */\n"
    "\n"
    "    /* ---- Step 1: Hash A = SHA512(pass + salt + pass) ---- */\n"
    "    {\n"
    "        int tlen = 0;\n"
    "        for (int i = 0; i < plen; i++) tmp[tlen++] = pw[i];\n"
    "        for (int i = 0; i < saltlen; i++) tmp[tlen++] = raw_salt[i];\n"
    "        for (int i = 0; i < plen; i++) tmp[tlen++] = pw[i];\n"
    "        sc_sha512_oneshot(tmp, tlen, digest_a);\n"
    "    }\n"
    "\n"
    "    /* ---- Step 2: Hash B ---- */\n"
    "    /* init; update(pass + salt); for passlen bytes: update chunks of A; bit-loop; final -> curin */\n"
    "    sc_sha512_init(state);\n"
    "    for (int j = 0; j < 16; j++) ctx_buf[j] = 0;\n"
    "    ctx_bufpos = 0; ctx_counter = 0;\n"
    "\n"
    "    /* update(pass + salt) */\n"
    "    sc_sha512_update(state, ctx_buf, &ctx_bufpos, &ctx_counter, pw, plen);\n"
    "    sc_sha512_update(state, ctx_buf, &ctx_bufpos, &ctx_counter, raw_salt, saltlen);\n"
    "\n"
    "    /* For passlen bytes, update chunks of digest_a (64 bytes each) */\n"
    "    for (int x = plen; x > 64; x -= 64)\n"
    "        sc_sha512_update(state, ctx_buf, &ctx_bufpos, &ctx_counter, digest_a, 64);\n"
    "    /* Remaining x bytes (x = plen % 64, but actually plen - (full blocks)*64) */\n"
    "    {\n"
    "        int x = plen;\n"
    "        while (x > 64) x -= 64;\n"
    "        sc_sha512_update(state, ctx_buf, &ctx_bufpos, &ctx_counter, digest_a, x);\n"
    "    }\n"
    "\n"
    "    /* Bit loop: for each bit of passlen (LSB to MSB) */\n"
    "    for (int x = plen; x != 0; x >>= 1) {\n"
    "        if (x & 1)\n"
    "            sc_sha512_update(state, ctx_buf, &ctx_bufpos, &ctx_counter, digest_a, 64);\n"
    "        else\n"
    "            sc_sha512_update(state, ctx_buf, &ctx_bufpos, &ctx_counter, pw, plen);\n"
    "    }\n"
    "\n"
    "    uchar curin[64];\n"
    "    sc_sha512_final(state, ctx_buf, ctx_bufpos, ctx_counter, curin);\n"
    "\n"
    "    /* ---- Step 3: Hash P = SHA512(pass repeated passlen times) ---- */\n"
    "    sc_sha512_init(state);\n"
    "    for (int j = 0; j < 16; j++) ctx_buf[j] = 0;\n"
    "    ctx_bufpos = 0; ctx_counter = 0;\n"
    "    for (int x = 0; x < plen; x++)\n"
    "        sc_sha512_update(state, ctx_buf, &ctx_bufpos, &ctx_counter, pw, plen);\n"
    "    sc_sha512_final(state, ctx_buf, ctx_bufpos, ctx_counter, digest_b);\n"
    "\n"
    "    /* P-bytes: digest_b repeated to fill passlen bytes */\n"
    "    uchar p_bytes[256];\n"
    "    for (int i = 0; i < plen; i++)\n"
    "        p_bytes[i] = digest_b[i % 64];\n"
    "\n"
    "    /* ---- Step 4: Hash S = SHA512(salt repeated 16+curin[0] times) ---- */\n"
    "    sc_sha512_init(state);\n"
    "    for (int j = 0; j < 16; j++) ctx_buf[j] = 0;\n"
    "    ctx_bufpos = 0; ctx_counter = 0;\n"
    "    int s_repeats = 16 + (uint)curin[0];\n"
    "    for (int x = 0; x < s_repeats; x++)\n"
    "        sc_sha512_update(state, ctx_buf, &ctx_bufpos, &ctx_counter, raw_salt, saltlen);\n"
    "    sc_sha512_final(state, ctx_buf, ctx_bufpos, ctx_counter, digest_b);\n"
    "\n"
    "    /* S-bytes: first saltlen bytes of digest_b */\n"
    "    uchar s_bytes[16];\n"
    "    for (int i = 0; i < saltlen; i++)\n"
    "        s_bytes[i] = digest_b[i];\n"
    "\n"
    "    /* ---- Step 5: Main loop: rounds iterations ---- */\n"
    "    for (int r = 0; r < rounds; r++) {\n"
    "        sc_sha512_init(state);\n"
    "        for (int j = 0; j < 16; j++) ctx_buf[j] = 0;\n"
    "        ctx_bufpos = 0; ctx_counter = 0;\n"
    "\n"
    "        if (r & 1)\n"
    "            sc_sha512_update(state, ctx_buf, &ctx_bufpos, &ctx_counter, p_bytes, plen);\n"
    "        else\n"
    "            sc_sha512_update(state, ctx_buf, &ctx_bufpos, &ctx_counter, curin, 64);\n"
    "\n"
    "        if (r % 3)\n"
    "            sc_sha512_update(state, ctx_buf, &ctx_bufpos, &ctx_counter, s_bytes, saltlen);\n"
    "\n"
    "        if (r % 7)\n"
    "            sc_sha512_update(state, ctx_buf, &ctx_bufpos, &ctx_counter, p_bytes, plen);\n"
    "\n"
    "        if (r & 1)\n"
    "            sc_sha512_update(state, ctx_buf, &ctx_bufpos, &ctx_counter, curin, 64);\n"
    "        else\n"
    "            sc_sha512_update(state, ctx_buf, &ctx_bufpos, &ctx_counter, p_bytes, plen);\n"
    "\n"
    "        sc_sha512_final(state, ctx_buf, ctx_bufpos, ctx_counter, curin);\n"
    "    }\n"
    "\n"
    "    /* ---- Check result against compact hash table ---- */\n"
    "    /* curin[0..63] is the raw 64-byte hash.\n"
    "     * Compact probe uses first 16 bytes as 4 x uint32 (little-endian read). */\n"
    "    uint hx = (uint)curin[0] | ((uint)curin[1] << 8) |\n"
    "              ((uint)curin[2] << 16) | ((uint)curin[3] << 24);\n"
    "    uint hy = (uint)curin[4] | ((uint)curin[5] << 8) |\n"
    "              ((uint)curin[6] << 16) | ((uint)curin[7] << 24);\n"
    "    uint hz = (uint)curin[8] | ((uint)curin[9] << 8) |\n"
    "              ((uint)curin[10] << 16) | ((uint)curin[11] << 24);\n"
    "    uint hw = (uint)curin[12] | ((uint)curin[13] << 8) |\n"
    "              ((uint)curin[14] << 16) | ((uint)curin[15] << 24);\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 7;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx; hits[base+2] = 1;\n"
    "            hits[base+3] = hx; hits[base+4] = hy;\n"
    "            hits[base+5] = hz; hits[base+6] = hw;\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
;
