/* Auto-generated from gpu_blake2s256unsalted.cl -- do not edit */
static const char gpu_blake2s256unsalted_str[] =
    "/* gpu_blake2s256unsalted.cl — Pre-padded unsalted BLAKE2S-256 with mask expansion\n"
    " *\n"
    " * Input: 4096 pre-padded 64-byte blocks in passbuf (word_stride=64).\n"
    " *   Packed by gpu_try_pack_unsalted(): password bytes at offset n_prepend,\n"
    " *   total_len stored as uint16 at bytes [56..57] (after the password area).\n"
    " *   BLAKE2S uses its own padding (no 0x80/bitlen), so the packer just stores\n"
    " *   the password and length — the kernel handles BLAKE2S-specific finalization.\n"
    " *\n"
    " * Dispatch: num_words × num_masks threads.\n"
    " * Hit stride: 6 (word_idx, mask_idx, h0, h1, h2, h3)\n"
    " *\n"
    " * Primitives (B2S_IV, B2S_SIGMA, b2s_compress) provided by gpu_common.cl\n"
    " */\n"
    "\n"
    "__kernel void blake2s256_unsalted_batch(\n"
    "    __global const uint *words,\n"
    "    __global const ushort *unused_lens,\n"
    "    __global const uchar *mask_desc,\n"
    "    __global const uint *unused1, __global const ushort *unused2,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    uint mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    /* Load pre-packed block (16 uint32 = 64 bytes).\n"
    "     * Password bytes start at n_prepend. Total length at M[14] bits [7:0] and [15:8]. */\n"
    "    __global const uint *src = words + word_idx * 16;\n"
    "    uchar buf[64];\n"
    "    for (int i = 0; i < 64; i++)\n"
    "        buf[i] = ((__global const uchar *)src)[i];\n"
    "\n"
    "    /* Fill mask positions */\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "\n"
    "    /* Read total_len from packed M[14] (stored as bitlen by packer, extract byte len) */\n"
    "    uint M14 = src[14];\n"
    "    int total_len = M14 >> 3;\n"
    "\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint append_combos = 1;\n"
    "        for (uint i = 0; i < n_app; i++)\n"
    "            append_combos *= mask_desc[n_pre + i];\n"
    "\n"
    "        uint prepend_idx = mask_idx / append_combos;\n"
    "        uint append_idx = mask_idx % append_combos;\n"
    "\n"
    "        if (n_pre > 0) {\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uint n_total_m = n_pre + n_app;\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                buf[i] = ch;\n"
    "            }\n"
    "        }\n"
    "\n"
    "        if (n_app > 0) {\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint aidx = append_idx;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                int pos_idx = n_pre + i;\n"
    "                uint sz = mask_desc[pos_idx];\n"
    "                uint n_total_m = n_pre + n_app;\n"
    "                uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                aidx /= sz;\n"
    "                buf[app_start + i] = ch;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* BLAKE2S-256: single-block hash (password <= 55 bytes fits in one 64-byte block).\n"
    "     * Init: IV ^ parameter block (outlen=32, keylen=0, fanout=1, depth=1). */\n"
    "    uint h[8];\n"
    "    for (int i = 0; i < 8; i++) h[i] = B2S_IV[i];\n"
    "    h[0] ^= 0x01010020u;\n"
    "\n"
    "    /* Zero bytes after password */\n"
    "    for (int i = total_len; i < 64; i++) buf[i] = 0;\n"
    "\n"
    "    /* Single compress with last=1, counter=total_len */\n"
    "    b2s_compress(h, buf, (ulong)total_len, 1);\n"
    "\n"
    "    /* BLAKE2S output is LE — no bswap */\n"
    "    uint hx = h[0], hy = h[1], hz = h[2], hw = h[3];\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 6;\n"
    "            hits[base]   = word_idx;\n"
    "            hits[base+1] = mask_idx;\n"
    "            hits[base+2] = hx;\n"
    "            hits[base+3] = hy;\n"
    "            hits[base+4] = hz;\n"
    "            hits[base+5] = hw;\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
;
