/* Auto-generated from gpu_sha256unsalted.cl -- do not edit */
static const char gpu_sha256unsalted_str[] =
    "/* gpu_sha256unsalted.cl — Pre-padded unsalted SHA256 with mask expansion\n"
    " *\n"
    " * Input: 4096 pre-padded 64-byte M[] blocks in passbuf (word_stride=64).\n"
    " *   Packed by gpu_try_pack_unsalted() in little-endian format:\n"
    " *   password at offset n_prepend, 0x80 padding, M[14]=bitlen (LE).\n"
    " *   Kernel byte-swaps to big-endian before SHA256 compress.\n"
    " *\n"
    " * Dispatch: num_words × num_masks threads.\n"
    " * Hit stride: 10 (word_idx, mask_idx, h0..h7) or\n"
    " *             11 (word_idx, mask_idx, iter, h0..h7) when max_iter > 1\n"
    " */\n"
    "\n"
    "\n"
    "/* bswap32, SHA256_K[], sha256_block(), hex_byte_be64() provided by gpu_common.cl */\n"
    "\n"
    "/* Convert one byte to 2 packed hex chars (lowercase, BE word packing) */\n"
    "uint hex_byte_be(uint b) {\n"
    "    uint hi = (b >> 4) & 0xf;\n"
    "    uint lo = b & 0xf;\n"
    "    return ((hi + ((hi < 10) ? '0' : ('a' - 10))) << 8)\n"
    "         |  (lo + ((lo < 10) ? '0' : ('a' - 10)));\n"
    "}\n"
    "\n"
    "/* Convert 8 SHA256 BE state words to 16 BE M[] words of hex text (lowercase) */\n"
    "void sha256_to_hex_lc(uint *state, uint *M) {\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        uint s = state[i];\n"
    "        uint b0 = (s >> 24) & 0xff, b1 = (s >> 16) & 0xff;\n"
    "        uint b2 = (s >> 8)  & 0xff, b3 = s & 0xff;\n"
    "        M[i*2]   = (hex_byte_be(b0) << 16) | hex_byte_be(b1);\n"
    "        M[i*2+1] = (hex_byte_be(b2) << 16) | hex_byte_be(b3);\n"
    "    }\n"
    "}\n"
    "\n"
    "#define sha256_compress sha256_block\n"
    "\n"
    "__kernel void sha256_unsalted_batch(\n"
    "    __global const uint *words,\n"
    "    __global const ushort *unused_lens,\n"
    "    __global const uchar *mask_desc,\n"
    "    __global const uint *unused1, __global const ushort *unused2,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    ulong mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    __global const uint *src = words + word_idx * 16;\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    /* Fill mask positions — LE words, same as MD5 kernel */\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint n_total_m = n_pre + n_app;\n"
    "\n"
    "        if (n_pre > 0) {\n"
    "            uint append_combos = 1;\n"
    "            for (uint i = 0; i < n_app; i++)\n"
    "                append_combos *= mask_desc[n_pre + i];\n"
    "            uint prepend_idx = (uint)(mask_idx / append_combos);\n"
    "            uint append_idx = (uint)(mask_idx % append_combos);\n"
    "\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                M[i >> 2] = (M[i >> 2] & ~(0xFFu << ((i & 3) << 3)))\n"
    "                           | ((uint)ch << ((i & 3) << 3));\n"
    "            }\n"
    "\n"
    "            if (n_app > 0) {\n"
    "                int total_len = M[14] >> 3;\n"
    "                int app_start = total_len - (int)n_app;\n"
    "                uint aidx = append_idx;\n"
    "                for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                    int pos_idx = n_pre + i;\n"
    "                    uint sz = mask_desc[pos_idx];\n"
    "                    uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                    aidx /= sz;\n"
    "                    int pos = app_start + i;\n"
    "                    M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                                 | ((uint)ch << ((pos & 3) << 3));\n"
    "                }\n"
    "            }\n"
    "        } else {\n"
    "            /* Append-only (brute-force): host pre-decomposes mask_start into\n"
    "             * per-position base offsets. Kernel does fast uint32 local\n"
    "             * decomposition and adds to base with carry. */\n"
    "            int total_len = M[14] >> 3;\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint local_idx = tid % params.num_masks;\n"
    "            uint aidx = local_idx;\n"
    "            uint carry = 0;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uint local_digit = aidx % sz;\n"
    "                aidx /= sz;\n"
    "                uint base_digit = (i < 8)\n"
    "                    ? (uint)((params.mask_base0 >> (i * 8)) & 0xFF)\n"
    "                    : (uint)((params.mask_base1 >> ((i - 8) * 8)) & 0xFF);\n"
    "                uint sum = base_digit + local_digit + carry;\n"
    "                carry = sum / sz;\n"
    "                uint final_digit = sum % sz;\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + final_digit];\n"
    "                int pos = app_start + i;\n"
    "                M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                             | ((uint)ch << ((pos & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    uint bitlen = M[14];\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap32(M[i]);\n"
    "    M[14] = 0;\n"
    "    M[15] = bitlen;\n"
    "\n"
    "    uint state[8] = {\n"
    "        0x6a09e667u, 0xbb67ae85u, 0x3c6ef372u, 0xa54ff53au,\n"
    "        0x510e527fu, 0x9b05688cu, 0x1f83d9abu, 0x5be0cd19u\n"
    "    };\n"
    "    sha256_compress(state, M);\n"
    "\n"
    "    uint max_iter = params.max_iter;\n"
    "\n"
    "    for (uint iter = 1; iter <= max_iter; iter++) {\n"
    "        uint h[8];\n"
    "        for (int i = 0; i < 8; i++) h[i] = bswap32(state[i]);\n"
    "\n"
    "        if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                          params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                          hash_data_buf, hash_data_off,\n"
    "                          overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "            EMIT_HIT_8(hits, hit_count, params.max_hits, word_idx, mask_idx, 1u, h)\n"
    "        }\n"
    "        if (iter < max_iter) {\n"
    "            /* Hex-encode 8 BE state words into M[0..15] (64 hex chars = full block) */\n"
    "            sha256_to_hex_lc(state, M);\n"
    "            /* First compress: data block (no room for padding) */\n"
    "            state[0] = 0x6a09e667u; state[1] = 0xbb67ae85u;\n"
    "            state[2] = 0x3c6ef372u; state[3] = 0xa54ff53au;\n"
    "            state[4] = 0x510e527fu; state[5] = 0x9b05688cu;\n"
    "            state[6] = 0x1f83d9abu; state[7] = 0x5be0cd19u;\n"
    "            sha256_compress(state, M);\n"
    "            /* Second compress: padding block */\n"
    "            M[0] = 0x80000000u;\n"
    "            for (int i = 1; i < 15; i++) M[i] = 0;\n"
    "            M[15] = 64 * 8;  /* 64 hex bytes = 512 bits */\n"
    "            sha256_compress(state, M);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* SHA224 — same compress as SHA256, different IV, truncated output (28 bytes) */\n"
    "__kernel void sha224_unsalted_batch(\n"
    "    __global const uint *words,\n"
    "    __global const ushort *unused_lens,\n"
    "    __global const uchar *mask_desc,\n"
    "    __global const uint *unused1, __global const ushort *unused2,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    ulong mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    __global const uint *src = words + word_idx * 16;\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint n_total_m = n_pre + n_app;\n"
    "\n"
    "        if (n_pre > 0) {\n"
    "            uint append_combos = 1;\n"
    "            for (uint i = 0; i < n_app; i++)\n"
    "                append_combos *= mask_desc[n_pre + i];\n"
    "            uint prepend_idx = (uint)(mask_idx / append_combos);\n"
    "            uint append_idx = (uint)(mask_idx % append_combos);\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                M[i >> 2] = (M[i >> 2] & ~(0xFFu << ((i & 3) << 3)))\n"
    "                           | ((uint)ch << ((i & 3) << 3));\n"
    "            }\n"
    "            if (n_app > 0) {\n"
    "                int total_len = M[14] >> 3;\n"
    "                int app_start = total_len - (int)n_app;\n"
    "                uint aidx = append_idx;\n"
    "                for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                    int pos_idx = n_pre + i;\n"
    "                    uint sz = mask_desc[pos_idx];\n"
    "                    uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                    aidx /= sz;\n"
    "                    int pos = app_start + i;\n"
    "                    M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                                 | ((uint)ch << ((pos & 3) << 3));\n"
    "                }\n"
    "            }\n"
    "        } else {\n"
    "            /* Append-only (brute-force): host pre-decomposes mask_start into\n"
    "             * per-position base offsets. Kernel does fast uint32 local\n"
    "             * decomposition and adds to base with carry. */\n"
    "            int total_len = M[14] >> 3;\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint local_idx = tid % params.num_masks;\n"
    "            uint aidx = local_idx;\n"
    "            uint carry = 0;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uint local_digit = aidx % sz;\n"
    "                aidx /= sz;\n"
    "                uint base_digit = (i < 8)\n"
    "                    ? (uint)((params.mask_base0 >> (i * 8)) & 0xFF)\n"
    "                    : (uint)((params.mask_base1 >> ((i - 8) * 8)) & 0xFF);\n"
    "                uint sum = base_digit + local_digit + carry;\n"
    "                carry = sum / sz;\n"
    "                uint final_digit = sum % sz;\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + final_digit];\n"
    "                int pos = app_start + i;\n"
    "                M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                             | ((uint)ch << ((pos & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    uint bitlen = M[14];\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap32(M[i]);\n"
    "    M[14] = 0;\n"
    "    M[15] = bitlen;\n"
    "\n"
    "    uint state[8] = {\n"
    "        0xc1059ed8u, 0x367cd507u, 0x3070dd17u, 0xf70e5939u,\n"
    "        0xffc00b31u, 0x68581511u, 0x64f98fa7u, 0xbefa4fa4u\n"
    "    };\n"
    "    sha256_compress(state, M);\n"
    "\n"
    "    /* SHA224: 7 hash words */\n"
    "    uint h[7];\n"
    "    for (int i = 0; i < 7; i++) h[i] = bswap32(state[i]);\n"
    "\n"
    "    if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        EMIT_HIT_7(hits, hit_count, params.max_hits, word_idx, mask_idx, 1u, h)\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- SHA256RAW: sha256(sha256_binary(pass)) with binary iteration ----\n"
    " *\n"
    " * For hashcat modes 21400, 30420. With -i N, iterates N times on\n"
    " * binary 32-byte output: sha256(sha256(...sha256(pass)...))\n"
    " * Second+ iterations always hash exactly 32 bytes (single block, fixed padding).\n"
    " * Hit stride: 10 (word_idx, mask_idx, h0..h7) or\n"
    " *             11 (word_idx, mask_idx, iter, h0..h7) when max_iter > 1\n"
    " */\n"
    "__kernel void sha256raw_unsalted_batch(\n"
    "    __global const uint *words,\n"
    "    __global const ushort *unused_lens,\n"
    "    __global const uchar *mask_desc,\n"
    "    __global const uint *unused1, __global const ushort *unused2,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    ulong mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    __global const uint *src = words + word_idx * 16;\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint n_total_m = n_pre + n_app;\n"
    "\n"
    "        if (n_pre > 0) {\n"
    "            uint append_combos = 1;\n"
    "            for (uint i = 0; i < n_app; i++)\n"
    "                append_combos *= mask_desc[n_pre + i];\n"
    "            uint prepend_idx = (uint)(mask_idx / append_combos);\n"
    "            uint append_idx = (uint)(mask_idx % append_combos);\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                M[i >> 2] = (M[i >> 2] & ~(0xFFu << ((i & 3) << 3)))\n"
    "                           | ((uint)ch << ((i & 3) << 3));\n"
    "            }\n"
    "            if (n_app > 0) {\n"
    "                int total_len = M[14] >> 3;\n"
    "                int app_start = total_len - (int)n_app;\n"
    "                uint aidx = append_idx;\n"
    "                for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                    int pos_idx = n_pre + i;\n"
    "                    uint sz = mask_desc[pos_idx];\n"
    "                    uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                    aidx /= sz;\n"
    "                    int pos = app_start + i;\n"
    "                    M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                                 | ((uint)ch << ((pos & 3) << 3));\n"
    "                }\n"
    "            }\n"
    "        } else {\n"
    "            /* Append-only (brute-force): host pre-decomposes mask_start into\n"
    "             * per-position base offsets. Kernel does fast uint32 local\n"
    "             * decomposition and adds to base with carry. */\n"
    "            int total_len = M[14] >> 3;\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint local_idx = tid % params.num_masks;\n"
    "            uint aidx = local_idx;\n"
    "            uint carry = 0;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uint local_digit = aidx % sz;\n"
    "                aidx /= sz;\n"
    "                uint base_digit = (i < 8)\n"
    "                    ? (uint)((params.mask_base0 >> (i * 8)) & 0xFF)\n"
    "                    : (uint)((params.mask_base1 >> ((i - 8) * 8)) & 0xFF);\n"
    "                uint sum = base_digit + local_digit + carry;\n"
    "                carry = sum / sz;\n"
    "                uint final_digit = sum % sz;\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + final_digit];\n"
    "                int pos = app_start + i;\n"
    "                M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                             | ((uint)ch << ((pos & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* First: SHA256(password) from pre-padded block */\n"
    "    uint bitlen_orig = M[14];\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap32(M[i]);\n"
    "    M[14] = 0; M[15] = bitlen_orig;\n"
    "\n"
    "    uint state[8] = {\n"
    "        0x6a09e667u, 0xbb67ae85u, 0x3c6ef372u, 0xa54ff53au,\n"
    "        0x510e527fu, 0x9b05688cu, 0x1f83d9abu, 0x5be0cd19u\n"
    "    };\n"
    "    sha256_compress(state, M);\n"
    "\n"
    "    /* Binary iteration: sha256(32-byte binary output).\n"
    "     * Set up fixed padding for 32-byte binary input once. */\n"
    "    M[8] = 0x80000000u;  /* 0x80 in high byte (BE) */\n"
    "    for (int i = 9; i < 15; i++) M[i] = 0;\n"
    "    M[15] = 256;  /* 32 bytes * 8 bits */\n"
    "\n"
    "    uint max_iter = params.max_iter;\n"
    "\n"
    "    for (uint iter = 1; iter <= max_iter; iter++) {\n"
    "\n"
    "        uint h[8];\n"
    "        for (int i = 0; i < 8; i++) h[i] = bswap32(state[i]);\n"
    "\n"
    "        if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                          params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                          hash_data_buf, hash_data_off,\n"
    "                          overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "            EMIT_HIT_8(hits, hit_count, params.max_hits, word_idx, mask_idx, 1u, h)\n"
    "        }\n"
    "        if (iter < max_iter) {\n"
    "            for (int i = 0; i < 8; i++) M[i] = state[i];\n"
    "            state[0] = 0x6a09e667u; state[1] = 0xbb67ae85u;\n"
    "            state[2] = 0x3c6ef372u; state[3] = 0xa54ff53au;\n"
    "            state[4] = 0x510e527fu; state[5] = 0x9b05688cu;\n"
    "            state[6] = 0x1f83d9abu; state[7] = 0x5be0cd19u;\n"
    "            sha256_compress(state, M);\n"
    "        }\n"
    "    }\n"
    "}\n"
;
