/* Auto-generated from gpu_md5crypt.cl -- do not edit */
static const char gpu_md5crypt_str[] =
    "/* M_copy_bytes, M_set_byte provided by gpu_common.cl */\n"
    "\n"
    "/* ---- MD5CRYPT kernel (e511): $1$salt$hash, 1000 MD5 iterations ---- */\n"
    "/* Salt buffer contains \"$1$salt$\" from Typesalt. Kernel extracts raw salt. */\n"
    "\n"
    "/* Helper: build MD5 message block from a byte buffer, with padding */\n"
    "void md5_oneshot(const uchar *data, int len, uint *out) {\n"
    "    uint M[16];\n"
    "    out[0] = 0x67452301u; out[1] = 0xEFCDAB89u;\n"
    "    out[2] = 0x98BADCFEu; out[3] = 0x10325476u;\n"
    "\n"
    "    int pos = 0;\n"
    "    /* Process full 64-byte blocks */\n"
    "    while (pos + 64 <= len) {\n"
    "        for (int i = 0; i < 16; i++)\n"
    "            M[i] = (uint)data[pos+i*4] | ((uint)data[pos+i*4+1]<<8) |\n"
    "                   ((uint)data[pos+i*4+2]<<16) | ((uint)data[pos+i*4+3]<<24);\n"
    "        md5_block(&out[0], &out[1], &out[2], &out[3], M);\n"
    "        pos += 64;\n"
    "    }\n"
    "    /* Final block(s) with padding */\n"
    "    int rem = len - pos;\n"
    "    uchar pad[128];\n"
    "    for (int i = 0; i < 128; i++) pad[i] = 0;\n"
    "    for (int i = 0; i < rem; i++) pad[i] = data[pos + i];\n"
    "    pad[rem] = 0x80;\n"
    "    int blocks = (rem < 56) ? 1 : 2;\n"
    "    int lenoff = (blocks == 1) ? 56 : 120;\n"
    "    pad[lenoff] = (len * 8) & 0xff;\n"
    "    pad[lenoff+1] = ((len * 8) >> 8) & 0xff;\n"
    "    pad[lenoff+2] = ((len * 8) >> 16) & 0xff;\n"
    "    pad[lenoff+3] = ((len * 8) >> 24) & 0xff;\n"
    "    for (int b = 0; b < blocks; b++) {\n"
    "        for (int i = 0; i < 16; i++)\n"
    "            M[i] = (uint)pad[b*64+i*4] | ((uint)pad[b*64+i*4+1]<<8) |\n"
    "                   ((uint)pad[b*64+i*4+2]<<16) | ((uint)pad[b*64+i*4+3]<<24);\n"
    "        md5_block(&out[0], &out[1], &out[2], &out[3], M);\n"
    "    }\n"
    "}\n"
    "\n"
    "__kernel void md5crypt_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen_full = salt_lens[salt_idx];\n"
    "\n"
    "    /* Salt buffer has \"$1$salt$\" — extract raw salt (skip \"$1$\", stop before trailing \"$\") */\n"
    "    __global const uchar *salt_raw = salts + soff + 3; /* skip \"$1$\" */\n"
    "    int saltlen = slen_full - 4; /* remove \"$1$\" prefix and trailing \"$\" */\n"
    "    if (saltlen < 0) saltlen = 0;\n"
    "    if (saltlen > 8) saltlen = 8;\n"
    "\n"
    "    /* Local buffers */\n"
    "    uchar buf[256]; /* working buffer for MD5 input */\n"
    "    uint digest[4]; /* current MD5 state */\n"
    "\n"
    "    /* Step 1: digest_b = MD5(password + salt + password) */\n"
    "    int blen = 0;\n"
    "    for (int i = 0; i < plen; i++) buf[blen++] = pass[i];\n"
    "    for (int i = 0; i < saltlen; i++) buf[blen++] = salt_raw[i];\n"
    "    for (int i = 0; i < plen; i++) buf[blen++] = pass[i];\n"
    "    md5_oneshot(buf, blen, digest);\n"
    "    uchar digest_b[16];\n"
    "    for (int i = 0; i < 4; i++) {\n"
    "        digest_b[i*4]   = digest[i] & 0xff;\n"
    "        digest_b[i*4+1] = (digest[i] >> 8) & 0xff;\n"
    "        digest_b[i*4+2] = (digest[i] >> 16) & 0xff;\n"
    "        digest_b[i*4+3] = (digest[i] >> 24) & 0xff;\n"
    "    }\n"
    "\n"
    "    /* Step 2: digest_a = MD5(password + \"$1$\" + salt + digest_b_chunks + bit_bytes) */\n"
    "    blen = 0;\n"
    "    for (int i = 0; i < plen; i++) buf[blen++] = pass[i];\n"
    "    buf[blen++] = '$'; buf[blen++] = '1'; buf[blen++] = '$';\n"
    "    for (int i = 0; i < saltlen; i++) buf[blen++] = salt_raw[i];\n"
    "    /* Append digest_b for password length bytes */\n"
    "    for (int x = plen; x > 0; x -= 16) {\n"
    "        int n = (x > 16) ? 16 : x;\n"
    "        for (int i = 0; i < n; i++) buf[blen++] = digest_b[i];\n"
    "    }\n"
    "    /* Bit-dependent bytes */\n"
    "    for (int x = plen; x != 0; x >>= 1)\n"
    "        buf[blen++] = (x & 1) ? 0 : pass[0];\n"
    "    md5_oneshot(buf, blen, digest);\n"
    "\n"
    "    /* Step 3: 1000 iterations */\n"
    "    uchar dig[16];\n"
    "    for (int i = 0; i < 4; i++) {\n"
    "        dig[i*4]   = digest[i] & 0xff;\n"
    "        dig[i*4+1] = (digest[i] >> 8) & 0xff;\n"
    "        dig[i*4+2] = (digest[i] >> 16) & 0xff;\n"
    "        dig[i*4+3] = (digest[i] >> 24) & 0xff;\n"
    "    }\n"
    "    for (int x = 0; x < 1000; x++) {\n"
    "        blen = 0;\n"
    "        if (x & 1) { for (int i = 0; i < plen; i++) buf[blen++] = pass[i]; }\n"
    "        else       { for (int i = 0; i < 16; i++) buf[blen++] = dig[i]; }\n"
    "        if (x % 3) { for (int i = 0; i < saltlen; i++) buf[blen++] = salt_raw[i]; }\n"
    "        if (x % 7) { for (int i = 0; i < plen; i++) buf[blen++] = pass[i]; }\n"
    "        if (x & 1) { for (int i = 0; i < 16; i++) buf[blen++] = dig[i]; }\n"
    "        else       { for (int i = 0; i < plen; i++) buf[blen++] = pass[i]; }\n"
    "        md5_oneshot(buf, blen, digest);\n"
    "        for (int i = 0; i < 4; i++) {\n"
    "            dig[i*4]   = digest[i] & 0xff;\n"
    "            dig[i*4+1] = (digest[i] >> 8) & 0xff;\n"
    "            dig[i*4+2] = (digest[i] >> 16) & 0xff;\n"
    "            dig[i*4+3] = (digest[i] >> 24) & 0xff;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Probe compact table with 16-byte binary result */\n"
    "    uint hx = digest[0], hy = digest[1], hz = digest[2], hw = digest[3];\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        EMIT_HIT_4(hits, hit_count, params.max_hits, word_idx, salt_idx, 1u, hx, hy, hz, hw)\n"
    "    }\n"
    "}\n"
;
