/* Auto-generated from gpu_hmac_blake2s.cl -- do not edit */
static const char gpu_hmac_blake2s_str[] =
    "/* gpu_hmac_blake2s.cl — HMAC-BLAKE2S GPU kernel (e828, hashcat 33300)\n"
    " * BLAKE2s: 64-byte block, 32-byte output, little-endian, no tables.\n"
    " * HMAC key=$pass: BLAKE2S((K⊕opad) || BLAKE2S((K⊕ipad) || salt))\n"
    " * Hit stride: 7 (word_idx, salt_idx, iter, hx, hy, hz, hw)\n"
    " */\n"
    "\n"
    "__constant uint B2S_IV[8] = {\n"
    "    0x6A09E667u, 0xBB67AE85u, 0x3C6EF372u, 0xA54FF53Au,\n"
    "    0x510E527Fu, 0x9B05688Cu, 0x1F83D9ABu, 0x5BE0CD19u\n"
    "};\n"
    "\n"
    "__constant uchar B2S_SIGMA[10][16] = {\n"
    "    { 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15 },\n"
    "    { 14,10,4,8,9,15,13,6,1,12,0,2,11,7,5,3 },\n"
    "    { 11,8,12,0,5,2,15,13,10,14,3,6,7,1,9,4 },\n"
    "    { 7,9,3,1,13,12,11,14,2,6,5,10,4,0,15,8 },\n"
    "    { 9,0,5,7,2,4,10,15,14,1,11,12,6,8,3,13 },\n"
    "    { 2,12,6,10,0,11,8,3,4,13,7,5,15,14,1,9 },\n"
    "    { 12,5,1,15,14,13,4,10,0,7,6,3,9,2,8,11 },\n"
    "    { 13,11,7,14,12,1,3,9,5,0,15,4,8,6,2,10 },\n"
    "    { 6,15,14,9,11,3,0,8,12,2,13,7,1,4,10,5 },\n"
    "    { 10,2,8,4,7,6,1,5,15,11,9,14,3,12,13,0 }\n"
    "};\n"
    "\n"
    "void b2s_compress(uint *h, const uchar *block, ulong counter, int last) {\n"
    "    uint v[16], m[16];\n"
    "    for (int i = 0; i < 8; i++) { v[i] = h[i]; v[i+8] = B2S_IV[i]; }\n"
    "    v[12] ^= (uint)counter;\n"
    "    v[13] ^= (uint)(counter >> 32);\n"
    "    if (last) v[14] = ~v[14];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        m[i] = ((uint)block[i*4]) | ((uint)block[i*4+1]<<8) |\n"
    "               ((uint)block[i*4+2]<<16) | ((uint)block[i*4+3]<<24);\n"
    "    for (int r = 0; r < 10; r++) {\n"
    "        __constant const uchar *s = B2S_SIGMA[r];\n"
    "        /* Column step */\n"
    "        v[0]+=v[4]+m[s[0]]; v[12]=rotate(v[12]^v[0],16u); v[8]+=v[12]; v[4]=rotate(v[4]^v[8],20u);\n"
    "        v[0]+=v[4]+m[s[1]]; v[12]=rotate(v[12]^v[0],24u); v[8]+=v[12]; v[4]=rotate(v[4]^v[8],25u);\n"
    "        v[1]+=v[5]+m[s[2]]; v[13]=rotate(v[13]^v[1],16u); v[9]+=v[13]; v[5]=rotate(v[5]^v[9],20u);\n"
    "        v[1]+=v[5]+m[s[3]]; v[13]=rotate(v[13]^v[1],24u); v[9]+=v[13]; v[5]=rotate(v[5]^v[9],25u);\n"
    "        v[2]+=v[6]+m[s[4]]; v[14]=rotate(v[14]^v[2],16u); v[10]+=v[14]; v[6]=rotate(v[6]^v[10],20u);\n"
    "        v[2]+=v[6]+m[s[5]]; v[14]=rotate(v[14]^v[2],24u); v[10]+=v[14]; v[6]=rotate(v[6]^v[10],25u);\n"
    "        v[3]+=v[7]+m[s[6]]; v[15]=rotate(v[15]^v[3],16u); v[11]+=v[15]; v[7]=rotate(v[7]^v[11],20u);\n"
    "        v[3]+=v[7]+m[s[7]]; v[15]=rotate(v[15]^v[3],24u); v[11]+=v[15]; v[7]=rotate(v[7]^v[11],25u);\n"
    "        /* Diagonal step */\n"
    "        v[0]+=v[5]+m[s[8]]; v[15]=rotate(v[15]^v[0],16u); v[10]+=v[15]; v[5]=rotate(v[5]^v[10],20u);\n"
    "        v[0]+=v[5]+m[s[9]]; v[15]=rotate(v[15]^v[0],24u); v[10]+=v[15]; v[5]=rotate(v[5]^v[10],25u);\n"
    "        v[1]+=v[6]+m[s[10]]; v[12]=rotate(v[12]^v[1],16u); v[11]+=v[12]; v[6]=rotate(v[6]^v[11],20u);\n"
    "        v[1]+=v[6]+m[s[11]]; v[12]=rotate(v[12]^v[1],24u); v[11]+=v[12]; v[6]=rotate(v[6]^v[11],25u);\n"
    "        v[2]+=v[7]+m[s[12]]; v[13]=rotate(v[13]^v[2],16u); v[8]+=v[13]; v[7]=rotate(v[7]^v[8],20u);\n"
    "        v[2]+=v[7]+m[s[13]]; v[13]=rotate(v[13]^v[2],24u); v[8]+=v[13]; v[7]=rotate(v[7]^v[8],25u);\n"
    "        v[3]+=v[4]+m[s[14]]; v[14]=rotate(v[14]^v[3],16u); v[9]+=v[14]; v[4]=rotate(v[4]^v[9],20u);\n"
    "        v[3]+=v[4]+m[s[15]]; v[14]=rotate(v[14]^v[3],24u); v[9]+=v[14]; v[4]=rotate(v[4]^v[9],25u);\n"
    "    }\n"
    "    for (int i = 0; i < 8; i++) h[i] ^= v[i] ^ v[i+8];\n"
    "}\n"
    "\n"
    "/* Full blake2s hash (no key, outlen=32) on a buffer up to 128 bytes */\n"
    "void blake2s_hash(uint *out, const uchar *data, int datalen) {\n"
    "    uint h[8];\n"
    "    for (int i = 0; i < 8; i++) h[i] = B2S_IV[i];\n"
    "    h[0] ^= 0x01010020u;  /* outlen=32, keylen=0, fanout=1, depth=1 */\n"
    "\n"
    "    uchar buf[64];\n"
    "    ulong counter = 0;\n"
    "    int pos = 0;\n"
    "    const uchar *p = data;\n"
    "    int remaining = datalen;\n"
    "\n"
    "    while (remaining > 0) {\n"
    "        if (pos == 64) {\n"
    "            counter += 64;\n"
    "            b2s_compress(h, buf, counter, 0);\n"
    "            pos = 0;\n"
    "        }\n"
    "        int take = 64 - pos;\n"
    "        if (take > remaining) take = remaining;\n"
    "        for (int i = 0; i < take; i++) buf[pos + i] = p[i];\n"
    "        pos += take; p += take; remaining -= take;\n"
    "    }\n"
    "    counter += pos;\n"
    "    for (int i = pos; i < 64; i++) buf[i] = 0;\n"
    "    b2s_compress(h, buf, counter, 1);\n"
    "    for (int i = 0; i < 8; i++) out[i] = h[i];\n"
    "}\n"
    "\n"
    "__kernel void hmac_blake2s_kpass_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int klen = hexlens[word_idx];\n"
    "    __global const uchar *key = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int mlen = salt_lens[salt_idx];\n"
    "    __global const uchar *msg = salts + soff;\n"
    "\n"
    "    /* Prepare key pad (64 bytes) */\n"
    "    uchar kpad[64];\n"
    "    if (klen > 64) {\n"
    "        uint kh[8];\n"
    "        uchar kb[256];\n"
    "        for (int i = 0; i < klen; i++) kb[i] = key[i];\n"
    "        blake2s_hash(kh, kb, klen);\n"
    "        for (int i = 0; i < 32; i++) kpad[i] = ((uchar *)kh)[i];\n"
    "        for (int i = 32; i < 64; i++) kpad[i] = 0;\n"
    "    } else {\n"
    "        for (int i = 0; i < klen; i++) kpad[i] = key[i];\n"
    "        for (int i = klen; i < 64; i++) kpad[i] = 0;\n"
    "    }\n"
    "\n"
    "    /* Inner: BLAKE2S((K ^ ipad) || salt) */\n"
    "    uchar ibuf[192];  /* max 64 + 128 bytes */\n"
    "    for (int i = 0; i < 64; i++) ibuf[i] = kpad[i] ^ 0x36;\n"
    "    for (int i = 0; i < mlen; i++) ibuf[64 + i] = msg[i];\n"
    "    uint inner[8];\n"
    "    blake2s_hash(inner, ibuf, 64 + mlen);\n"
    "\n"
    "    /* Outer: BLAKE2S((K ^ opad) || inner_hash) */\n"
    "    uchar obuf[96];\n"
    "    for (int i = 0; i < 64; i++) obuf[i] = kpad[i] ^ 0x5c;\n"
    "    for (int i = 0; i < 32; i++) obuf[64 + i] = ((uchar *)inner)[i];\n"
    "    uint outer[8];\n"
    "    blake2s_hash(outer, obuf, 96);\n"
    "\n"
    "    uint hx = outer[0], hy = outer[1], hz = outer[2], hw = outer[3];\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 7;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx; hits[base+2] = 1;\n"
    "            hits[base+3] = hx; hits[base+4] = hy;\n"
    "            hits[base+5] = hz; hits[base+6] = hw;\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
;
