/* Auto-generated from gpu_md4unsalted.cl -- do not edit */
static const char gpu_md4unsalted_str[] =
    "/* gpu_md4unsalted.cl — Pre-padded unsalted MD4 with mask expansion\n"
    " *\n"
    " * Input: 4096 pre-padded 64-byte M[] blocks in passbuf (word_stride=64).\n"
    " *   Each block has: password at offset n_prepend, 0x80 padding, M[14]=bitlen.\n"
    " *   Prepend/append gaps are zeroed — GPU fills them per mask combination.\n"
    " *\n"
    " * Dispatch: num_words × num_masks threads.\n"
    " *   word_idx = tid / num_masks, mask_idx = mask_start + (tid % num_masks)\n"
    " *\n"
    " * Hit stride: 6 (word_idx, mask_idx, hx, hy, hz, hw)\n"
    " */\n"
    "\n"
    "/* hex_byte_lc, md5_to_hex_lc provided by gpu_common.cl\n"
    " * (md5_to_hex_lc works for MD4 too — same LE 128-bit output format) */\n"
    "\n"
    "/* Fully unrolled MD4 compress — single block, M[] already in little-endian uint32\n"
    " * RFC 1320: 3 rounds × 16 steps = 48 operations (vs MD5's 64)\n"
    " * Round 1: F(b,c,d) = (b&c)|(~b&d),       no constant\n"
    " * Round 2: G(b,c,d) = (b&c)|(b&d)|(c&d),  constant 0x5A827999\n"
    " * Round 3: H(b,c,d) = b^c^d,               constant 0x6ED9EBA1\n"
    " */\n"
    "void md4_compress(uint *hx, uint *hy, uint *hz, uint *hw, uint *M) {\n"
    "    uint a = *hx, b = *hy, c = *hz, d = *hw;\n"
    "    /* Round 1: F(b,c,d) = (b&c)|(~b&d), rotations: 3,7,11,19 */\n"
    "    a += ((b&c)|(~b&d)) + M[ 0]; a = ((a<< 3)|(a>>29));\n"
    "    d += ((a&b)|(~a&c)) + M[ 1]; d = ((d<< 7)|(d>>25));\n"
    "    c += ((d&a)|(~d&b)) + M[ 2]; c = ((c<<11)|(c>>21));\n"
    "    b += ((c&d)|(~c&a)) + M[ 3]; b = ((b<<19)|(b>>13));\n"
    "    a += ((b&c)|(~b&d)) + M[ 4]; a = ((a<< 3)|(a>>29));\n"
    "    d += ((a&b)|(~a&c)) + M[ 5]; d = ((d<< 7)|(d>>25));\n"
    "    c += ((d&a)|(~d&b)) + M[ 6]; c = ((c<<11)|(c>>21));\n"
    "    b += ((c&d)|(~c&a)) + M[ 7]; b = ((b<<19)|(b>>13));\n"
    "    a += ((b&c)|(~b&d)) + M[ 8]; a = ((a<< 3)|(a>>29));\n"
    "    d += ((a&b)|(~a&c)) + M[ 9]; d = ((d<< 7)|(d>>25));\n"
    "    c += ((d&a)|(~d&b)) + M[10]; c = ((c<<11)|(c>>21));\n"
    "    b += ((c&d)|(~c&a)) + M[11]; b = ((b<<19)|(b>>13));\n"
    "    a += ((b&c)|(~b&d)) + M[12]; a = ((a<< 3)|(a>>29));\n"
    "    d += ((a&b)|(~a&c)) + M[13]; d = ((d<< 7)|(d>>25));\n"
    "    c += ((d&a)|(~d&b)) + M[14]; c = ((c<<11)|(c>>21));\n"
    "    b += ((c&d)|(~c&a)) + M[15]; b = ((b<<19)|(b>>13));\n"
    "    /* Round 2: G(b,c,d) = (b&c)|(b&d)|(c&d), constant 0x5A827999\n"
    "     * Message order: 0,4,8,12,1,5,9,13,2,6,10,14,3,7,11,15 */\n"
    "    a += ((b&c)|(b&d)|(c&d)) + M[ 0] + 0x5A827999u; a = ((a<< 3)|(a>>29));\n"
    "    d += ((a&b)|(a&c)|(b&c)) + M[ 4] + 0x5A827999u; d = ((d<< 5)|(d>>27));\n"
    "    c += ((d&a)|(d&b)|(a&b)) + M[ 8] + 0x5A827999u; c = ((c<< 9)|(c>>23));\n"
    "    b += ((c&d)|(c&a)|(d&a)) + M[12] + 0x5A827999u; b = ((b<<13)|(b>>19));\n"
    "    a += ((b&c)|(b&d)|(c&d)) + M[ 1] + 0x5A827999u; a = ((a<< 3)|(a>>29));\n"
    "    d += ((a&b)|(a&c)|(b&c)) + M[ 5] + 0x5A827999u; d = ((d<< 5)|(d>>27));\n"
    "    c += ((d&a)|(d&b)|(a&b)) + M[ 9] + 0x5A827999u; c = ((c<< 9)|(c>>23));\n"
    "    b += ((c&d)|(c&a)|(d&a)) + M[13] + 0x5A827999u; b = ((b<<13)|(b>>19));\n"
    "    a += ((b&c)|(b&d)|(c&d)) + M[ 2] + 0x5A827999u; a = ((a<< 3)|(a>>29));\n"
    "    d += ((a&b)|(a&c)|(b&c)) + M[ 6] + 0x5A827999u; d = ((d<< 5)|(d>>27));\n"
    "    c += ((d&a)|(d&b)|(a&b)) + M[10] + 0x5A827999u; c = ((c<< 9)|(c>>23));\n"
    "    b += ((c&d)|(c&a)|(d&a)) + M[14] + 0x5A827999u; b = ((b<<13)|(b>>19));\n"
    "    a += ((b&c)|(b&d)|(c&d)) + M[ 3] + 0x5A827999u; a = ((a<< 3)|(a>>29));\n"
    "    d += ((a&b)|(a&c)|(b&c)) + M[ 7] + 0x5A827999u; d = ((d<< 5)|(d>>27));\n"
    "    c += ((d&a)|(d&b)|(a&b)) + M[11] + 0x5A827999u; c = ((c<< 9)|(c>>23));\n"
    "    b += ((c&d)|(c&a)|(d&a)) + M[15] + 0x5A827999u; b = ((b<<13)|(b>>19));\n"
    "    /* Round 3: H(b,c,d) = b^c^d, constant 0x6ED9EBA1\n"
    "     * Message order: 0,8,4,12,2,10,6,14,1,9,5,13,3,11,7,15 */\n"
    "    a += (b^c^d) + M[ 0] + 0x6ED9EBA1u; a = ((a<< 3)|(a>>29));\n"
    "    d += (a^b^c) + M[ 8] + 0x6ED9EBA1u; d = ((d<< 9)|(d>>23));\n"
    "    c += (d^a^b) + M[ 4] + 0x6ED9EBA1u; c = ((c<<11)|(c>>21));\n"
    "    b += (c^d^a) + M[12] + 0x6ED9EBA1u; b = ((b<<15)|(b>>17));\n"
    "    a += (b^c^d) + M[ 2] + 0x6ED9EBA1u; a = ((a<< 3)|(a>>29));\n"
    "    d += (a^b^c) + M[10] + 0x6ED9EBA1u; d = ((d<< 9)|(d>>23));\n"
    "    c += (d^a^b) + M[ 6] + 0x6ED9EBA1u; c = ((c<<11)|(c>>21));\n"
    "    b += (c^d^a) + M[14] + 0x6ED9EBA1u; b = ((b<<15)|(b>>17));\n"
    "    a += (b^c^d) + M[ 1] + 0x6ED9EBA1u; a = ((a<< 3)|(a>>29));\n"
    "    d += (a^b^c) + M[ 9] + 0x6ED9EBA1u; d = ((d<< 9)|(d>>23));\n"
    "    c += (d^a^b) + M[ 5] + 0x6ED9EBA1u; c = ((c<<11)|(c>>21));\n"
    "    b += (c^d^a) + M[13] + 0x6ED9EBA1u; b = ((b<<15)|(b>>17));\n"
    "    a += (b^c^d) + M[ 3] + 0x6ED9EBA1u; a = ((a<< 3)|(a>>29));\n"
    "    d += (a^b^c) + M[11] + 0x6ED9EBA1u; d = ((d<< 9)|(d>>23));\n"
    "    c += (d^a^b) + M[ 7] + 0x6ED9EBA1u; c = ((c<<11)|(c>>21));\n"
    "    b += (c^d^a) + M[15] + 0x6ED9EBA1u; b = ((b<<15)|(b>>17));\n"
    "    *hx += a; *hy += b; *hz += c; *hw += d;\n"
    "}\n"
    "\n"
    "__kernel void md4_unsalted_batch(\n"
    "    __global const uint *words,          /* pre-padded M[] blocks, 16 uint32 each */\n"
    "    __global const ushort *unused_lens,  /* not used — total length is in M[14]/8 */\n"
    "    __global const uchar *mask_desc,     /* mask descriptor: [prepend IDs][append IDs] */\n"
    "    __global const uint *unused1, __global const ushort *unused2,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    uint mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    /* Load pre-padded M[] block (16 uint32 = 64 bytes) */\n"
    "    __global const uint *src = words + word_idx * 16;\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    /* Fill mask positions into M[] */\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        /* Compute append_combos for index decomposition */\n"
    "        uint append_combos = 1;\n"
    "        for (uint i = 0; i < n_app; i++)\n"
    "            append_combos *= mask_desc[n_pre + i];\n"
    "\n"
    "        uint prepend_idx = mask_idx / append_combos;\n"
    "        uint append_idx = mask_idx % append_combos;\n"
    "\n"
    "        /* Fill prepend chars at byte offset 0 */\n"
    "        if (n_pre > 0) {\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uint n_total_m = n_pre + n_app;\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                /* Set byte i in M[] (little-endian uint32) */\n"
    "                M[i >> 2] = (M[i >> 2] & ~(0xFFu << ((i & 3) << 3)))\n"
    "                           | ((uint)ch << ((i & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "\n"
    "        /* Fill append chars — total length from M[14]/8, append starts at total - n_app */\n"
    "        if (n_app > 0) {\n"
    "            int total_len = M[14] >> 3;  /* bit-length / 8 */\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint aidx = append_idx;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                int pos_idx = n_pre + i;\n"
    "                uint sz = mask_desc[pos_idx];\n"
    "                uint n_total_m = n_pre + n_app;\n"
    "                uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                aidx /= sz;\n"
    "                int pos = app_start + i;\n"
    "                M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                             | ((uint)ch << ((pos & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* MD4 compress (single block, fully unrolled) */\n"
    "    uint hx = 0x67452301u, hy = 0xEFCDAB89u, hz = 0x98BADCFEu, hw = 0x10325476u;\n"
    "    md4_compress(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "    uint max_iter = params.max_iter;\n"
    "    uint hit_stride = (max_iter > 1) ? 7 : 6;\n"
    "\n"
    "    for (uint iter = 1; iter <= max_iter; iter++) {\n"
    "        if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                          params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                          hash_data_buf, hash_data_off,\n"
    "                          overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "            uint slot = atomic_add(hit_count, 1u);\n"
    "            if (slot < params.max_hits) {\n"
    "                uint base = slot * hit_stride;\n"
    "                hits[base]   = word_idx;\n"
    "                hits[base+1] = mask_idx;\n"
    "                if (hit_stride == 7) {\n"
    "                    hits[base+2] = iter;\n"
    "                    hits[base+3] = hx; hits[base+4] = hy;\n"
    "                    hits[base+5] = hz; hits[base+6] = hw;\n"
    "                } else {\n"
    "                    hits[base+2] = hx; hits[base+3] = hy;\n"
    "                    hits[base+4] = hz; hits[base+5] = hw;\n"
    "                }\n"
    "                mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "            }\n"
    "        }\n"
    "        if (iter < max_iter) {\n"
    "            md5_to_hex_lc(hx, hy, hz, hw, M);\n"
    "            M[8] = 0x80;\n"
    "            for (int i = 9; i < 14; i++) M[i] = 0;\n"
    "            M[14] = 32 * 8; M[15] = 0;\n"
    "            hx = 0x67452301u; hy = 0xEFCDAB89u; hz = 0x98BADCFEu; hw = 0x10325476u;\n"
    "            md4_compress(&hx, &hy, &hz, &hw, M);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* MD4UTF16 (NTLM-style): MD4 of UTF-16LE zero-extended password.\n"
    " * Host packs UTF-16LE (each byte → byte,0x00) with doubled offsets.\n"
    " * Mask positions are doubled: logical char i → byte 2*i in the block.\n"
    " * Hit stride: 6 (word_idx, mask_idx, hx, hy, hz, hw) */\n"
    "__kernel void md4utf16_unsalted_batch(\n"
    "    __global const uint *words,\n"
    "    __global const ushort *unused_lens,\n"
    "    __global const uchar *mask_desc,\n"
    "    __global const uint *unused1, __global const ushort *unused2,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    uint mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    __global const uint *src = words + word_idx * 16;\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint append_combos = 1;\n"
    "        for (uint i = 0; i < n_app; i++)\n"
    "            append_combos *= mask_desc[n_pre + i];\n"
    "\n"
    "        uint prepend_idx = mask_idx / append_combos;\n"
    "        uint append_idx = mask_idx % append_combos;\n"
    "\n"
    "        /* Fill prepend: logical char i → UTF-16LE byte 2*i */\n"
    "        if (n_pre > 0) {\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uint n_total_m = n_pre + n_app;\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                int pos = 2 * i;\n"
    "                M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                             | ((uint)ch << ((pos & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "\n"
    "        /* Fill append: total UTF-16LE byte length from M[14]/8,\n"
    "         * append starts at total_bytes - 2*n_app */\n"
    "        if (n_app > 0) {\n"
    "            int total_bytes = M[14] >> 3;\n"
    "            int app_start = total_bytes - 2 * (int)n_app;\n"
    "            uint aidx = append_idx;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                int pos_idx = n_pre + i;\n"
    "                uint sz = mask_desc[pos_idx];\n"
    "                uint n_total_m = n_pre + n_app;\n"
    "                uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                aidx /= sz;\n"
    "                int pos = app_start + 2 * i;\n"
    "                M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                             | ((uint)ch << ((pos & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    uint hx = 0x67452301u, hy = 0xEFCDAB89u, hz = 0x98BADCFEu, hw = 0x10325476u;\n"
    "    md4_compress(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "    uint max_iter = params.max_iter;\n"
    "    uint hit_stride = (max_iter > 1) ? 7 : 6;\n"
    "\n"
    "    for (uint iter = 1; iter <= max_iter; iter++) {\n"
    "        if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                          params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                          hash_data_buf, hash_data_off,\n"
    "                          overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "            uint slot = atomic_add(hit_count, 1u);\n"
    "            if (slot < params.max_hits) {\n"
    "                uint base = slot * hit_stride;\n"
    "                hits[base]   = word_idx;\n"
    "                hits[base+1] = mask_idx;\n"
    "                if (hit_stride == 7) {\n"
    "                    hits[base+2] = iter;\n"
    "                    hits[base+3] = hx; hits[base+4] = hy;\n"
    "                    hits[base+5] = hz; hits[base+6] = hw;\n"
    "                } else {\n"
    "                    hits[base+2] = hx; hits[base+3] = hy;\n"
    "                    hits[base+4] = hz; hits[base+5] = hw;\n"
    "                }\n"
    "                mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "            }\n"
    "        }\n"
    "        if (iter < max_iter) {\n"
    "            /* Iteration uses plain MD4 on hex text (not UTF16) */\n"
    "            md5_to_hex_lc(hx, hy, hz, hw, M);\n"
    "            M[8] = 0x80;\n"
    "            for (int i = 9; i < 14; i++) M[i] = 0;\n"
    "            M[14] = 32 * 8; M[15] = 0;\n"
    "            hx = 0x67452301u; hy = 0xEFCDAB89u; hz = 0x98BADCFEu; hw = 0x10325476u;\n"
    "            md4_compress(&hx, &hy, &hz, &hw, M);\n"
    "        }\n"
    "    }\n"
    "}\n"
;
