/* Auto-generated from gpu_kernels.cl -- do not edit */
static const char gpu_kernels_str[] =
    "/* md5salt.cl — OpenCL kernels for mdxfind MD5SALT GPU acceleration */\n"
    "\n"
    "typedef struct {\n"
    "    ulong compact_mask;\n"
    "    uint num_words;\n"
    "    uint num_salts;\n"
    "    uint salt_start;\n"
    "    uint max_probe;\n"
    "    uint hash_data_count;\n"
    "    uint max_hits;\n"
    "    uint overflow_count;\n"
    "    uint max_iter;\n"
    "    uint num_masks;     /* mask combinations per chunk (0 = not mask mode) */\n"
    "    uint mask_start;    /* offset for mask chunking */\n"
    "    uint n_prepend;     /* number of prepend mask positions */\n"
    "    uint n_append;      /* number of append mask positions */\n"
    "} OCLParams;\n"
    "\n"
    "__constant uint K[64] = {\n"
    "    0xd76aa478,0xe8c7b756,0x242070db,0xc1bdceee,0xf57c0faf,0x4787c62a,0xa8304613,0xfd469501,\n"
    "    0x698098d8,0x8b44f7af,0xffff5bb1,0x895cd7be,0x6b901122,0xfd987193,0xa679438e,0x49b40821,\n"
    "    0xf61e2562,0xc040b340,0x265e5a51,0xe9b6c7aa,0xd62f105d,0x02441453,0xd8a1e681,0xe7d3fbc8,\n"
    "    0x21e1cde6,0xc33707d6,0xf4d50d87,0x455a14ed,0xa9e3e905,0xfcefa3f8,0x676f02d9,0x8d2a4c8a,\n"
    "    0xfffa3942,0x8771f681,0x6d9d6122,0xfde5380c,0xa4beea44,0x4bdecfa9,0xf6bb4b60,0xbebfbc70,\n"
    "    0x289b7ec6,0xeaa127fa,0xd4ef3085,0x04881d05,0xd9d4d039,0xe6db99e5,0x1fa27cf8,0xc4ac5665,\n"
    "    0xf4292244,0x432aff97,0xab9423a7,0xfc93a039,0x655b59c3,0x8f0ccc92,0xffeff47d,0x85845dd1,\n"
    "    0x6fa87e4f,0xfe2ce6e0,0xa3014314,0x4e0811a1,0xf7537e82,0xbd3af235,0x2ad7d2bb,0xeb86d391\n"
    "};\n"
    "\n"
    "#define FF(a,b,c,d,m,s,k) { a += ((b&c)|(~b&d)) + m + k; a = b + rotate(a,s); }\n"
    "#define GG(a,b,c,d,m,s,k) { a += ((d&b)|(~d&c)) + m + k; a = b + rotate(a,s); }\n"
    "#define HH(a,b,c,d,m,s,k) { a += (b^c^d) + m + k; a = b + rotate(a,s); }\n"
    "#define II(a,b,c,d,m,s,k) { a += (c^(~d|b)) + m + k; a = b + rotate(a,s); }\n"
    "\n"
    "void md5_block(uint *h0, uint *h1, uint *h2, uint *h3, uint *M) {\n"
    "    uint a = *h0, b = *h1, c = *h2, d = *h3;\n"
    "    FF(a,b,c,d,M[0],(uint)7,0xd76aa478u);  FF(d,a,b,c,M[1],(uint)12,0xe8c7b756u);\n"
    "    FF(c,d,a,b,M[2],(uint)17,0x242070dbu);  FF(b,c,d,a,M[3],(uint)22,0xc1bdceeeu);\n"
    "    FF(a,b,c,d,M[4],(uint)7,0xf57c0fafu);   FF(d,a,b,c,M[5],(uint)12,0x4787c62au);\n"
    "    FF(c,d,a,b,M[6],(uint)17,0xa8304613u);  FF(b,c,d,a,M[7],(uint)22,0xfd469501u);\n"
    "    FF(a,b,c,d,M[8],(uint)7,0x698098d8u);   FF(d,a,b,c,M[9],(uint)12,0x8b44f7afu);\n"
    "    FF(c,d,a,b,M[10],(uint)17,0xffff5bb1u); FF(b,c,d,a,M[11],(uint)22,0x895cd7beu);\n"
    "    FF(a,b,c,d,M[12],(uint)7,0x6b901122u);  FF(d,a,b,c,M[13],(uint)12,0xfd987193u);\n"
    "    FF(c,d,a,b,M[14],(uint)17,0xa679438eu); FF(b,c,d,a,M[15],(uint)22,0x49b40821u);\n"
    "    GG(a,b,c,d,M[1],(uint)5,0xf61e2562u);   GG(d,a,b,c,M[6],(uint)9,0xc040b340u);\n"
    "    GG(c,d,a,b,M[11],(uint)14,0x265e5a51u); GG(b,c,d,a,M[0],(uint)20,0xe9b6c7aau);\n"
    "    GG(a,b,c,d,M[5],(uint)5,0xd62f105du);   GG(d,a,b,c,M[10],(uint)9,0x02441453u);\n"
    "    GG(c,d,a,b,M[15],(uint)14,0xd8a1e681u); GG(b,c,d,a,M[4],(uint)20,0xe7d3fbc8u);\n"
    "    GG(a,b,c,d,M[9],(uint)5,0x21e1cde6u);   GG(d,a,b,c,M[14],(uint)9,0xc33707d6u);\n"
    "    GG(c,d,a,b,M[3],(uint)14,0xf4d50d87u);  GG(b,c,d,a,M[8],(uint)20,0x455a14edu);\n"
    "    GG(a,b,c,d,M[13],(uint)5,0xa9e3e905u);  GG(d,a,b,c,M[2],(uint)9,0xfcefa3f8u);\n"
    "    GG(c,d,a,b,M[7],(uint)14,0x676f02d9u);  GG(b,c,d,a,M[12],(uint)20,0x8d2a4c8au);\n"
    "    HH(a,b,c,d,M[5],(uint)4,0xfffa3942u);   HH(d,a,b,c,M[8],(uint)11,0x8771f681u);\n"
    "    HH(c,d,a,b,M[11],(uint)16,0x6d9d6122u); HH(b,c,d,a,M[14],(uint)23,0xfde5380cu);\n"
    "    HH(a,b,c,d,M[1],(uint)4,0xa4beea44u);   HH(d,a,b,c,M[4],(uint)11,0x4bdecfa9u);\n"
    "    HH(c,d,a,b,M[7],(uint)16,0xf6bb4b60u);  HH(b,c,d,a,M[10],(uint)23,0xbebfbc70u);\n"
    "    HH(a,b,c,d,M[13],(uint)4,0x289b7ec6u);  HH(d,a,b,c,M[0],(uint)11,0xeaa127fau);\n"
    "    HH(c,d,a,b,M[3],(uint)16,0xd4ef3085u);  HH(b,c,d,a,M[6],(uint)23,0x04881d05u);\n"
    "    HH(a,b,c,d,M[9],(uint)4,0xd9d4d039u);   HH(d,a,b,c,M[12],(uint)11,0xe6db99e5u);\n"
    "    HH(c,d,a,b,M[15],(uint)16,0x1fa27cf8u); HH(b,c,d,a,M[2],(uint)23,0xc4ac5665u);\n"
    "    II(a,b,c,d,M[0],(uint)6,0xf4292244u);   II(d,a,b,c,M[7],(uint)10,0x432aff97u);\n"
    "    II(c,d,a,b,M[14],(uint)15,0xab9423a7u); II(b,c,d,a,M[5],(uint)21,0xfc93a039u);\n"
    "    II(a,b,c,d,M[12],(uint)6,0x655b59c3u);  II(d,a,b,c,M[3],(uint)10,0x8f0ccc92u);\n"
    "    II(c,d,a,b,M[10],(uint)15,0xffeff47du); II(b,c,d,a,M[1],(uint)21,0x85845dd1u);\n"
    "    II(a,b,c,d,M[8],(uint)6,0x6fa87e4fu);   II(d,a,b,c,M[15],(uint)10,0xfe2ce6e0u);\n"
    "    II(c,d,a,b,M[6],(uint)15,0xa3014314u);  II(b,c,d,a,M[13],(uint)21,0x4e0811a1u);\n"
    "    II(a,b,c,d,M[4],(uint)6,0xf7537e82u);   II(d,a,b,c,M[11],(uint)10,0xbd3af235u);\n"
    "    II(c,d,a,b,M[2],(uint)15,0x2ad7d2bbu);  II(b,c,d,a,M[9],(uint)21,0xeb86d391u);\n"
    "    *h0 += a; *h1 += b; *h2 += c; *h3 += d;\n"
    "}\n"
    "\n"
    "/* ---- SHA1 block function ---- */\n"
    "/* SHA1 processes big-endian uint32 words. M[] must be pre-swapped by caller. */\n"
    "void sha1_block(uint *state, uint *M) {\n"
    "    uint W[80];\n"
    "    for (int i = 0; i < 16; i++) W[i] = M[i];\n"
    "    for (int i = 16; i < 80; i++)\n"
    "        W[i] = rotate(W[i-3] ^ W[i-8] ^ W[i-14] ^ W[i-16], (uint)1);\n"
    "\n"
    "    uint a = state[0], b = state[1], c = state[2], d = state[3], e = state[4];\n"
    "    uint t;\n"
    "    for (int i = 0; i < 20; i++) {\n"
    "        t = rotate(a, (uint)5) + ((b & c) | (~b & d)) + e + 0x5A827999u + W[i];\n"
    "        e = d; d = c; c = rotate(b, (uint)30); b = a; a = t;\n"
    "    }\n"
    "    for (int i = 20; i < 40; i++) {\n"
    "        t = rotate(a, (uint)5) + (b ^ c ^ d) + e + 0x6ED9EBA1u + W[i];\n"
    "        e = d; d = c; c = rotate(b, (uint)30); b = a; a = t;\n"
    "    }\n"
    "    for (int i = 40; i < 60; i++) {\n"
    "        t = rotate(a, (uint)5) + ((b & c) | (b & d) | (c & d)) + e + 0x8F1BBCDCu + W[i];\n"
    "        e = d; d = c; c = rotate(b, (uint)30); b = a; a = t;\n"
    "    }\n"
    "    for (int i = 60; i < 80; i++) {\n"
    "        t = rotate(a, (uint)5) + (b ^ c ^ d) + e + 0xCA62C1D6u + W[i];\n"
    "        e = d; d = c; c = rotate(b, (uint)30); b = a; a = t;\n"
    "    }\n"
    "    state[0] += a; state[1] += b; state[2] += c; state[3] += d; state[4] += e;\n"
    "}\n"
    "\n"
    "/* ---- SHA256 block function ---- */\n"
    "__constant uint SHA256_K[64] = {\n"
    "    0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,\n"
    "    0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,\n"
    "    0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,\n"
    "    0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,\n"
    "    0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,\n"
    "    0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,\n"
    "    0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,\n"
    "    0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2\n"
    "};\n"
    "\n"
    "#define S256_ROTR(x,n) rotate((x),(uint)(32-(n)))\n"
    "#define S256_CH(x,y,z)  ((x & y) ^ (~x & z))\n"
    "#define S256_MAJ(x,y,z) ((x & y) ^ (x & z) ^ (y & z))\n"
    "#define S256_EP0(x)  (S256_ROTR(x,2)  ^ S256_ROTR(x,13) ^ S256_ROTR(x,22))\n"
    "#define S256_EP1(x)  (S256_ROTR(x,6)  ^ S256_ROTR(x,11) ^ S256_ROTR(x,25))\n"
    "#define S256_SIG0(x) (S256_ROTR(x,7)  ^ S256_ROTR(x,18) ^ (x >> 3))\n"
    "#define S256_SIG1(x) (S256_ROTR(x,17) ^ S256_ROTR(x,19) ^ (x >> 10))\n"
    "\n"
    "/* SHA256 processes big-endian uint32 words. M[] must be pre-swapped by caller. */\n"
    "void sha256_block(uint *state, uint *M) {\n"
    "    uint W[64];\n"
    "    for (int i = 0; i < 16; i++) W[i] = M[i];\n"
    "    for (int i = 16; i < 64; i++)\n"
    "        W[i] = S256_SIG1(W[i-2]) + W[i-7] + S256_SIG0(W[i-15]) + W[i-16];\n"
    "\n"
    "    uint a = state[0], b = state[1], c = state[2], d = state[3];\n"
    "    uint e = state[4], f = state[5], g = state[6], h = state[7];\n"
    "\n"
    "    for (int i = 0; i < 64; i++) {\n"
    "        uint t1 = h + S256_EP1(e) + S256_CH(e,f,g) + SHA256_K[i] + W[i];\n"
    "        uint t2 = S256_EP0(a) + S256_MAJ(a,b,c);\n"
    "        h = g; g = f; f = e; e = d + t1;\n"
    "        d = c; c = b; b = a; a = t1 + t2;\n"
    "    }\n"
    "\n"
    "    state[0] += a; state[1] += b; state[2] += c; state[3] += d;\n"
    "    state[4] += e; state[5] += f; state[6] += g; state[7] += h;\n"
    "}\n"
    "\n"
    "/* Byte-swap a uint32 (for SHA256 big-endian <-> little-endian conversion) */\n"
    "uint bswap32(uint x) {\n"
    "    return ((x >> 24) & 0xff) | ((x >> 8) & 0xff00) |\n"
    "           ((x << 8) & 0xff0000) | ((x << 24) & 0xff000000u);\n"
    "}\n"
    "\n"
    "/* Copy bytes into a big-endian M[] array for SHA256.\n"
    " * SHA256 M[] words are big-endian, so byte 0 goes into bits 31:24 of M[0]. */\n"
    "void S_copy_bytes(uint *M, int byte_off, __global const uchar *src, int nbytes) {\n"
    "    for (int i = 0; i < nbytes; i++) {\n"
    "        int wi = (byte_off + i) / 4;\n"
    "        int bi = 3 - ((byte_off + i) % 4);  /* big-endian: byte 0 = shift 24 */\n"
    "        M[wi] = (M[wi] & ~(0xffu << (bi * 8))) | ((uint)src[i] << (bi * 8));\n"
    "    }\n"
    "}\n"
    "\n"
    "void S_set_byte(uint *M, int byte_off, uchar val) {\n"
    "    int wi = byte_off / 4;\n"
    "    int bi = 3 - (byte_off % 4);\n"
    "    M[wi] = (M[wi] & ~(0xffu << (bi * 8))) | ((uint)val << (bi * 8));\n"
    "}\n"
    "\n"
    "ulong compact_mix(ulong k) { return k ^ (k >> 32); }\n"
    "\n"
    "int probe_compact(uint hx, uint hy, uint hz, uint hw,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count)\n"
    "{\n"
    "    ulong key = ((ulong)hy << 32) | hx;\n"
    "    uint fp = (uint)(key >> 32);\n"
    "    if (fp == 0) fp = 1;\n"
    "    ulong pos = compact_mix(key) & compact_mask;\n"
    "    for (int p = 0; p < (int)max_probe; p++) {\n"
    "        uint cfp = compact_fp[pos];\n"
    "        if (cfp == 0) break;\n"
    "        if (cfp == fp) {\n"
    "            uint idx = compact_idx[pos];\n"
    "            if (idx < hash_data_count) {\n"
    "                ulong off = hash_data_off[idx];\n"
    "                __global const uint *ref = (__global const uint *)(hash_data_buf + off);\n"
    "                if (hx == ref[0] && hy == ref[1] && hz == ref[2] && hw == ref[3])\n"
    "                    return 1;\n"
    "            }\n"
    "        }\n"
    "        pos = (pos + 1) & compact_mask;\n"
    "    }\n"
    "    if (overflow_count > 0) {\n"
    "        int lo = 0, hi = (int)overflow_count - 1;\n"
    "        while (lo <= hi) {\n"
    "            int mid = (lo + hi) / 2;\n"
    "            ulong mkey = overflow_keys[mid];\n"
    "            if (key < mkey) hi = mid - 1;\n"
    "            else if (key > mkey) lo = mid + 1;\n"
    "            else {\n"
    "                uint ooff = overflow_offsets[mid];\n"
    "                __global const uint *oref = (__global const uint *)(overflow_hashes + ooff);\n"
    "                if (hx == oref[0] && hy == oref[1] && hz == oref[2] && hw == oref[3]) return 1;\n"
    "                for (int d = mid-1; d >= 0 && overflow_keys[d] == key; d--) {\n"
    "                    oref = (__global const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (hx == oref[0] && hy == oref[1] && hz == oref[2] && hw == oref[3]) return 1;\n"
    "                }\n"
    "                for (int d = mid+1; d < (int)overflow_count && overflow_keys[d] == key; d++) {\n"
    "                    oref = (__global const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (hx == oref[0] && hy == oref[1] && hz == oref[2] && hw == oref[3]) return 1;\n"
    "                }\n"
    "                break;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "    return 0;\n"
    "}\n"
    "\n"
    "__kernel void md5salt_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off, __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    uint M[16];\n"
    "    __global const uint *mwords = (__global const uint *)(hexhashes + word_idx * 256);\n"
    "    for (int i = 0; i < 8; i++) M[i] = mwords[i];\n"
    "    for (int i = 8; i < 16; i++) M[i] = 0;\n"
    "\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = 32 + slen;\n"
    "    uchar *mbytes = (uchar *)M;\n"
    "    for (int i = 0; i < slen; i++)\n"
    "        mbytes[32 + i] = salts[soff + i];\n"
    "    mbytes[total_len] = 0x80;\n"
    "    M[14] = total_len * 8;\n"
    "\n"
    "    uint hx = 0x67452301, hy = 0xEFCDAB89, hz = 0x98BADCFE, hw = 0x10325476;\n"
    "    md5_block(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 6;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx;\n"
    "            hits[base+2] = hx; hits[base+3] = hy;\n"
    "            hits[base+4] = hz; hits[base+5] = hw;\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "__kernel void md5salt_sub8_24(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off, __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    uint M[16];\n"
    "    __global const uint *mwords = (__global const uint *)(hexhashes + word_idx * 256);\n"
    "    for (int i = 0; i < 4; i++) M[i] = mwords[i];\n"
    "    for (int i = 4; i < 16; i++) M[i] = 0;\n"
    "\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = 16 + slen;\n"
    "    uchar *mbytes = (uchar *)M;\n"
    "    for (int i = 0; i < slen; i++) mbytes[16 + i] = salts[soff + i];\n"
    "    mbytes[total_len] = 0x80;\n"
    "    M[14] = total_len * 8;\n"
    "\n"
    "    uint hx = 0x67452301, hy = 0xEFCDAB89, hz = 0x98BADCFE, hw = 0x10325476;\n"
    "    md5_block(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 6;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx;\n"
    "            hits[base+2] = hx; hits[base+3] = hy;\n"
    "            hits[base+4] = hz; hits[base+5] = hw;\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* Forward declarations for hex conversion (defined below) */\n"
    "uint hex_byte_lc(uint b);\n"
    "void md5_to_hex_lc(uint hx, uint hy, uint hz, uint hw, uint *M);\n"
    "\n"
    "__kernel void md5salt_iter(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off, __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    uint M[16];\n"
    "    __global const uint *mwords = (__global const uint *)(hexhashes + word_idx * 256);\n"
    "    for (int i = 0; i < 8; i++) M[i] = mwords[i];\n"
    "    for (int i = 8; i < 16; i++) M[i] = 0;\n"
    "\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = 32 + slen;\n"
    "    uchar *mbytes = (uchar *)M;\n"
    "    for (int i = 0; i < slen; i++) mbytes[32 + i] = salts[soff + i];\n"
    "    mbytes[total_len] = 0x80;\n"
    "    M[14] = total_len * 8;\n"
    "\n"
    "    uint hx = 0x67452301, hy = 0xEFCDAB89, hz = 0x98BADCFE, hw = 0x10325476;\n"
    "    md5_block(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "    for (uint iter = 0; iter < params.max_iter; iter++) {\n"
    "        if (iter > 0) {\n"
    "            uint hwords[4]; hwords[0]=hx; hwords[1]=hy; hwords[2]=hz; hwords[3]=hw;\n"
    "            uchar *hb = (uchar *)hwords;\n"
    "            uint Mi[16];\n"
    "            uchar *mb = (uchar *)Mi;\n"
    "            for (int i = 0; i < 16; i++) {\n"
    "                uchar hi = hb[i] >> 4, lo = hb[i] & 0xf;\n"
    "                mb[i*2]   = hi + (hi < 10 ? '0' : 'a' - 10);\n"
    "                mb[i*2+1] = lo + (lo < 10 ? '0' : 'a' - 10);\n"
    "            }\n"
    "            Mi[8] = 0x80; Mi[9]=0; Mi[10]=0; Mi[11]=0;\n"
    "            Mi[12]=0; Mi[13]=0; Mi[14]=256; Mi[15]=0;\n"
    "            hx = 0x67452301; hy = 0xEFCDAB89; hz = 0x98BADCFE; hw = 0x10325476;\n"
    "            md5_block(&hx, &hy, &hz, &hw, Mi);\n"
    "        }\n"
    "        if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                          params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                          hash_data_buf, hash_data_off,\n"
    "                          overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "            uint slot = atomic_add(hit_count, 1u);\n"
    "            if (slot < params.max_hits) {\n"
    "                uint base = slot * 7;\n"
    "                hits[base] = word_idx; hits[base+1] = salt_idx;\n"
    "                hits[base+2] = iter + 1;\n"
    "                hits[base+3] = hx; hits[base+4] = hy;\n"
    "                hits[base+5] = hz; hits[base+6] = hw;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- Hex conversion for MD5 iteration ---- */\n"
    "\n"
    "/* Convert one byte to 2 packed hex chars (lowercase) */\n"
    "uint hex_byte_lc(uint b) {\n"
    "    uint hi = (b >> 4) & 0xf;\n"
    "    uint lo = b & 0xf;\n"
    "    uint hc = hi + ((hi < 10) ? '0' : ('a' - 10));\n"
    "    uint lc = lo + ((lo < 10) ? '0' : ('a' - 10));\n"
    "    return hc | (lc << 8);\n"
    "}\n"
    "\n"
    "/* Convert one byte to 2 packed hex chars (uppercase) */\n"
    "uint hex_byte_uc(uint b) {\n"
    "    uint hi = (b >> 4) & 0xf;\n"
    "    uint lo = b & 0xf;\n"
    "    uint hc = hi + ((hi < 10) ? '0' : ('A' - 10));\n"
    "    uint lc = lo + ((lo < 10) ? '0' : ('A' - 10));\n"
    "    return hc | (lc << 8);\n"
    "}\n"
    "\n"
    "/* Convert 4 MD5 uint32s to 8 M[] words of hex text (lowercase) */\n"
    "void md5_to_hex_lc(uint hx, uint hy, uint hz, uint hw, uint *M) {\n"
    "    uint v[4]; v[0]=hx; v[1]=hy; v[2]=hz; v[3]=hw;\n"
    "    for (int i = 0; i < 4; i++) {\n"
    "        uint b0 = v[i] & 0xff, b1 = (v[i]>>8) & 0xff;\n"
    "        uint b2 = (v[i]>>16) & 0xff, b3 = (v[i]>>24) & 0xff;\n"
    "        M[i*2]   = hex_byte_lc(b0) | (hex_byte_lc(b1) << 16);\n"
    "        M[i*2+1] = hex_byte_lc(b2) | (hex_byte_lc(b3) << 16);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* Convert 4 MD5 uint32s to 8 M[] words of hex text (uppercase) */\n"
    "void md5_to_hex_uc(uint hx, uint hy, uint hz, uint hw, uint *M) {\n"
    "    uint v[4]; v[0]=hx; v[1]=hy; v[2]=hz; v[3]=hw;\n"
    "    for (int i = 0; i < 4; i++) {\n"
    "        uint b0 = v[i] & 0xff, b1 = (v[i]>>8) & 0xff;\n"
    "        uint b2 = (v[i]>>16) & 0xff, b3 = (v[i]>>24) & 0xff;\n"
    "        M[i*2]   = hex_byte_uc(b0) | (hex_byte_uc(b1) << 16);\n"
    "        M[i*2+1] = hex_byte_uc(b2) | (hex_byte_uc(b3) << 16);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- Bare MD5 iteration kernel (e1 lowercase, e2 uppercase) ----\n"
    " *\n"
    " * Input: hex(MD5(password)) pre-packed by CPU into M[] words.\n"
    " * GPU iterates: MD5(hex) -> check -> hex(result) -> MD5(hex) -> ...\n"
    " * One work item per word (no salt dimension).\n"
    " * Hit stride is always 7 (includes iteration number).\n"
    " */\n"
    "__kernel void md5_iter_lc(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts_unused, __global const uint *salt_off_unused,\n"
    "    __global const ushort *salt_len_unused,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    if (tid >= params.num_words) return;\n"
    "\n"
    "    uint M[16];\n"
    "    __global const uint *mwords = (__global const uint *)(hexhashes + tid * 256);\n"
    "    for (int i = 0; i < 8; i++) M[i] = mwords[i];\n"
    "\n"
    "    /* MD5 padding for 32-byte input -- constant across all iterations */\n"
    "    for (int i = 8; i < 16; i++) M[i] = 0;\n"
    "    M[8] = 0x80;\n"
    "    M[14] = 32 * 8;\n"
    "\n"
    "    for (uint iter = 1; iter <= params.max_iter; iter++) {\n"
    "        uint hx = 0x67452301, hy = 0xEFCDAB89, hz = 0x98BADCFE, hw = 0x10325476;\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "        if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                          params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                          hash_data_buf, hash_data_off,\n"
    "                          overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "            uint slot = atomic_add(hit_count, 1u);\n"
    "            if (slot < params.max_hits) {\n"
    "                uint base = slot * 7;\n"
    "                hits[base] = tid; hits[base+1] = 0;\n"
    "                hits[base+2] = iter + 1; /* +1: GPU iter 1 = mdxfind iter 2 */\n"
    "                hits[base+3] = hx; hits[base+4] = hy;\n"
    "                hits[base+5] = hz; hits[base+6] = hw;\n"
    "            }\n"
    "        }\n"
    "\n"
    "        if (iter < params.max_iter) {\n"
    "            md5_to_hex_lc(hx, hy, hz, hw, M);\n"
    "            /* M[8..15] unchanged: padding for 32-byte input */\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "__kernel void md5_iter_uc(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts_unused, __global const uint *salt_off_unused,\n"
    "    __global const ushort *salt_len_unused,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    if (tid >= params.num_words) return;\n"
    "\n"
    "    uint M[16];\n"
    "    __global const uint *mwords = (__global const uint *)(hexhashes + tid * 256);\n"
    "    for (int i = 0; i < 8; i++) M[i] = mwords[i];\n"
    "\n"
    "    for (int i = 8; i < 16; i++) M[i] = 0;\n"
    "    M[8] = 0x80;\n"
    "    M[14] = 32 * 8;\n"
    "\n"
    "    for (uint iter = 1; iter <= params.max_iter; iter++) {\n"
    "        uint hx = 0x67452301, hy = 0xEFCDAB89, hz = 0x98BADCFE, hw = 0x10325476;\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "        if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                          params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                          hash_data_buf, hash_data_off,\n"
    "                          overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "            uint slot = atomic_add(hit_count, 1u);\n"
    "            if (slot < params.max_hits) {\n"
    "                uint base = slot * 7;\n"
    "                hits[base] = tid; hits[base+1] = 0;\n"
    "                hits[base+2] = iter + 1; /* +1: GPU iter 1 = mdxfind iter 2 */\n"
    "                hits[base+3] = hx; hits[base+4] = hy;\n"
    "                hits[base+5] = hz; hits[base+6] = hw;\n"
    "            }\n"
    "        }\n"
    "\n"
    "        if (iter < params.max_iter) {\n"
    "            md5_to_hex_uc(hx, hy, hz, hw, M);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- Build M[] from byte stream ----\n"
    " * Copy 'len' bytes from global source into M[], starting at byte offset 'off'.\n"
    " * M[] must be pre-zeroed. Works by accumulating bytes into uint32 words. */\n"
    "void M_copy_bytes(uint *M, int off, __global const uchar *src, int len) {\n"
    "    for (int i = 0; i < len; i++) {\n"
    "        int pos = off + i;\n"
    "        int word = pos >> 2;\n"
    "        int shift = (pos & 3) << 3;\n"
    "        M[word] |= ((uint)src[i]) << shift;\n"
    "    }\n"
    "}\n"
    "\n"
    "/* Set a single byte in M[] */\n"
    "void M_set_byte(uint *M, int pos, uint val) {\n"
    "    M[pos >> 2] |= val << ((pos & 3) << 3);\n"
    "}\n"
    "\n"
    "/* ---- MD5(salt + password) kernel ----\n"
    " *\n"
    " * Input: raw password bytes in hexhashes buffer, length in hexlens.\n"
    " * GPU constructs salt + password, computes MD5, checks compact table.\n"
    " * Handles 1-block (total <= 55) and 2-block (55 < total <= 119) dynamically.\n"
    " * Hit stride is 7 (includes iteration number).\n"
    " */\n"
    "__kernel void md5saltpass_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    /* Read password bytes and length */\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "\n"
    "    /* Read salt offset and length */\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = slen + plen;\n"
    "\n"
    "    /* Build message = salt + password, compute MD5 */\n"
    "    uint hx = 0x67452301, hy = 0xEFCDAB89, hz = 0x98BADCFE, hw = 0x10325476;\n"
    "\n"
    "    { uint M[16];\n"
    "      for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "\n"
    "      if (total_len <= 55) {\n"
    "        M_copy_bytes(M, 0, salts + soff, slen);\n"
    "        M_copy_bytes(M, slen, pass, plen);\n"
    "        M_set_byte(M, total_len, 0x80);\n"
    "        M[14] = total_len * 8;\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "      } else {\n"
    "        /* Two blocks: fill first 64 bytes from salt+pass */\n"
    "        int salt_b1 = (slen < 64) ? slen : 64;\n"
    "        M_copy_bytes(M, 0, salts + soff, salt_b1);\n"
    "        int pass_b1 = 64 - salt_b1;\n"
    "        if (pass_b1 > plen) pass_b1 = plen;\n"
    "        if (pass_b1 > 0)\n"
    "            M_copy_bytes(M, salt_b1, pass, pass_b1);\n"
    "        if (total_len < 64)\n"
    "            M_set_byte(M, total_len, 0x80);\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "        /* Second block */\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int pos2 = 0;\n"
    "        int salt_b2 = slen - salt_b1;\n"
    "        if (salt_b2 > 0) {\n"
    "            M_copy_bytes(M, 0, salts + soff + salt_b1, salt_b2);\n"
    "            pos2 = salt_b2;\n"
    "        }\n"
    "        int pass_b2 = plen - pass_b1;\n"
    "        if (pass_b2 > 0) {\n"
    "            M_copy_bytes(M, pos2, pass + pass_b1, pass_b2);\n"
    "            pos2 += pass_b2;\n"
    "        }\n"
    "        if (total_len >= 64)\n"
    "            M_set_byte(M, pos2, 0x80);\n"
    "        M[14] = total_len * 8;\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 7;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx;\n"
    "            hits[base+2] = 1;\n"
    "            hits[base+3] = hx; hits[base+4] = hy;\n"
    "            hits[base+5] = hz; hits[base+6] = hw;\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- MD5(password + salt) kernel ---- */\n"
    "__kernel void md5passsalt_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = plen + slen;\n"
    "\n"
    "    uint hx = 0x67452301, hy = 0xEFCDAB89, hz = 0x98BADCFE, hw = 0x10325476;\n"
    "    { uint M[16];\n"
    "      for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "\n"
    "      if (total_len <= 55) {\n"
    "        M_copy_bytes(M, 0, pass, plen);\n"
    "        M_copy_bytes(M, plen, salts + soff, slen);\n"
    "        M_set_byte(M, total_len, 0x80);\n"
    "        M[14] = total_len * 8;\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "      } else {\n"
    "        /* Two blocks: fill first 64 bytes from pass+salt */\n"
    "        int pass_b1 = (plen < 64) ? plen : 64;\n"
    "        M_copy_bytes(M, 0, pass, pass_b1);\n"
    "        int salt_b1 = 64 - pass_b1;\n"
    "        if (salt_b1 > slen) salt_b1 = slen;\n"
    "        if (salt_b1 > 0)\n"
    "            M_copy_bytes(M, pass_b1, salts + soff, salt_b1);\n"
    "        /* If all data fits in block 1, put 0x80 here */\n"
    "        if (total_len < 64)\n"
    "            M_set_byte(M, total_len, 0x80);\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "        /* Second block: remaining data + padding */\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int pos2 = 0;\n"
    "        int pass_b2 = plen - pass_b1;\n"
    "        if (pass_b2 > 0) {\n"
    "            M_copy_bytes(M, 0, pass + pass_b1, pass_b2);\n"
    "            pos2 = pass_b2;\n"
    "        }\n"
    "        int salt_b2 = slen - salt_b1;\n"
    "        if (salt_b2 > 0) {\n"
    "            M_copy_bytes(M, pos2, salts + soff + salt_b1, salt_b2);\n"
    "            pos2 += salt_b2;\n"
    "        }\n"
    "        if (total_len >= 64)\n"
    "            M_set_byte(M, pos2, 0x80);\n"
    "        M[14] = total_len * 8;\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 7;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx;\n"
    "            hits[base+2] = 1;\n"
    "            hits[base+3] = hx; hits[base+4] = hy;\n"
    "            hits[base+5] = hz; hits[base+6] = hw;\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- SHA1(password + salt) kernel (e405) ---- */\n"
    "__kernel void sha1passsalt_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off, __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = plen + slen;\n"
    "\n"
    "    uint state[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "    { uint M[16];\n"
    "      for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "      if (total_len <= 55) {\n"
    "        S_copy_bytes(M, 0, pass, plen);\n"
    "        S_copy_bytes(M, plen, salts + soff, slen);\n"
    "        S_set_byte(M, total_len, 0x80);\n"
    "        M[15] = total_len * 8;\n"
    "        sha1_block(state, M);\n"
    "      } else {\n"
    "        int pass_b1 = (plen < 64) ? plen : 64;\n"
    "        S_copy_bytes(M, 0, pass, pass_b1);\n"
    "        int salt_b1 = 64 - pass_b1;\n"
    "        if (salt_b1 > slen) salt_b1 = slen;\n"
    "        if (salt_b1 > 0) S_copy_bytes(M, pass_b1, salts + soff, salt_b1);\n"
    "        if (total_len < 64) S_set_byte(M, total_len, 0x80);\n"
    "        sha1_block(state, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int pos2 = 0;\n"
    "        int pass_b2 = plen - pass_b1;\n"
    "        if (pass_b2 > 0) { S_copy_bytes(M, 0, pass + pass_b1, pass_b2); pos2 = pass_b2; }\n"
    "        int salt_b2 = slen - salt_b1;\n"
    "        if (salt_b2 > 0) { S_copy_bytes(M, pos2, salts + soff + salt_b1, salt_b2); pos2 += salt_b2; }\n"
    "        if (total_len >= 64) S_set_byte(M, pos2, 0x80);\n"
    "        M[15] = total_len * 8;\n"
    "        sha1_block(state, M);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    uint h[5];\n"
    "    for (int i = 0; i < 5; i++) h[i] = bswap32(state[i]);\n"
    "\n"
    "    if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 8;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx; hits[base+2] = 1;\n"
    "            for (int i = 0; i < 5; i++) hits[base+3+i] = h[i];\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- SHA1(salt + password) kernel (e385) ---- */\n"
    "__kernel void sha1saltpass_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off, __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = slen + plen;\n"
    "\n"
    "    uint state[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "    { uint M[16];\n"
    "      for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "      if (total_len <= 55) {\n"
    "        S_copy_bytes(M, 0, salts + soff, slen);\n"
    "        S_copy_bytes(M, slen, pass, plen);\n"
    "        S_set_byte(M, total_len, 0x80);\n"
    "        M[15] = total_len * 8;\n"
    "        sha1_block(state, M);\n"
    "      } else {\n"
    "        int salt_b1 = (slen < 64) ? slen : 64;\n"
    "        S_copy_bytes(M, 0, salts + soff, salt_b1);\n"
    "        int pass_b1 = 64 - salt_b1;\n"
    "        if (pass_b1 > plen) pass_b1 = plen;\n"
    "        if (pass_b1 > 0) S_copy_bytes(M, salt_b1, pass, pass_b1);\n"
    "        if (total_len < 64) S_set_byte(M, total_len, 0x80);\n"
    "        sha1_block(state, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int pos2 = 0;\n"
    "        int salt_b2 = slen - salt_b1;\n"
    "        if (salt_b2 > 0) { S_copy_bytes(M, 0, salts + soff + salt_b1, salt_b2); pos2 = salt_b2; }\n"
    "        int pass_b2 = plen - pass_b1;\n"
    "        if (pass_b2 > 0) { S_copy_bytes(M, pos2, pass + pass_b1, pass_b2); pos2 += pass_b2; }\n"
    "        if (total_len >= 64) S_set_byte(M, pos2, 0x80);\n"
    "        M[15] = total_len * 8;\n"
    "        sha1_block(state, M);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    uint h[5];\n"
    "    for (int i = 0; i < 5; i++) h[i] = bswap32(state[i]);\n"
    "\n"
    "    if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 8;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx; hits[base+2] = 1;\n"
    "            for (int i = 0; i < 5; i++) hits[base+3+i] = h[i];\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* Copy private-memory bytes into big-endian M[] for SHA1/SHA256 */\n"
    "void S_copy_bytes_priv(uint *M, int byte_off, const uchar *src, int nbytes) {\n"
    "    for (int i = 0; i < nbytes; i++) {\n"
    "        int wi = (byte_off + i) / 4;\n"
    "        int bi = 3 - ((byte_off + i) % 4);\n"
    "        M[wi] = (M[wi] & ~(0xffu << (bi * 8))) | ((uint)src[i] << (bi * 8));\n"
    "    }\n"
    "}\n"
    "\n"
    "void S_set_byte_priv(uint *M, int byte_off, uchar val) {\n"
    "    int wi = byte_off / 4;\n"
    "    int bi = 3 - (byte_off % 4);\n"
    "    M[wi] = (M[wi] & ~(0xffu << (bi * 8))) | ((uint)val << (bi * 8));\n"
    "}\n"
    "\n"
    "/* ---- PHPBB3/phpass kernel (e455): MD5 iterated 2^N times ---- */\n"
    "/* Salt buffer has \"$H$Csalt8chr\" (12 bytes). Iteration count from salt[3].\n"
    " * Algorithm: MD5(salt + pass), then N iterations of MD5(hash_binary + pass).\n"
    " * Password max 39 bytes (single MD5 block for 16 + 39 = 55). */\n"
    "__constant uchar phpitoa64_k[] = \"./0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz\";\n"
    "\n"
    "__kernel void phpbb3_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off, __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    __global const uchar *salt_data = salts + soff;\n"
    "\n"
    "    /* Decode iteration count from salt[3] */\n"
    "    uchar ic = salt_data[3];\n"
    "    int log2count = 0;\n"
    "    for (int k = 0; k < 64; k++) { if (phpitoa64_k[k] == ic) { log2count = k; break; } }\n"
    "    uint count = 1u << log2count;\n"
    "\n"
    "    /* Step 1: MD5(salt[4..11] + password) — salt is 8 bytes */\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    M_copy_bytes(M, 0, salt_data + 4, 8);\n"
    "    M_copy_bytes(M, 8, pass, plen);\n"
    "    int total = 8 + plen;\n"
    "    M_set_byte(M, total, 0x80);\n"
    "    M[14] = total * 8;\n"
    "    uint hx = 0x67452301, hy = 0xEFCDAB89, hz = 0x98BADCFE, hw = 0x10325476;\n"
    "    md5_block(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "    /* Step 2: N iterations of MD5(hash_binary[16] + password[plen]) */\n"
    "    /* Pre-pack M[] with password, padding, length — constant across iterations */\n"
    "    total = 16 + plen;\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    M_copy_bytes(M, 16, pass, plen);\n"
    "    M_set_byte(M, total, 0x80);\n"
    "    M[14] = total * 8;\n"
    "    /* Iteration loop: only M[0..3] change (the hash digest) */\n"
    "    for (uint ic2 = 0; ic2 < count; ic2++) {\n"
    "        M[0] = hx; M[1] = hy; M[2] = hz; M[3] = hw;\n"
    "        hx = 0x67452301; hy = 0xEFCDAB89; hz = 0x98BADCFE; hw = 0x10325476;\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "    }\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 6;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx;\n"
    "            hits[base+2] = hx; hits[base+3] = hy;\n"
    "            hits[base+4] = hz; hits[base+5] = hw;\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- SHA1DRU kernel (e404): SHA1 iterated 1,000,001 times ---- */\n"
    "/* SHA1(pass), then 1M iterations of SHA1(hex(hash) + pass).\n"
    " * No salts — GPU_CAT_ITER, dispatched as num_words work items. */\n"
    "__kernel void sha1dru_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off, __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    if (tid >= params.num_words) return;\n"
    "\n"
    "    /* hexhash buffer: [0..39] = hex(SHA1(pass)), [40..40+plen-1] = raw password */\n"
    "    __global const uchar *wordbuf = hexhashes + tid * 256;\n"
    "    int plen = hexlens[tid]; /* passlen stored in clen[] on host */\n"
    "\n"
    "    /* Read password length from the passbuf area — stored after hex */\n"
    "    /* Actually plen here is hexlen=40, we need the raw pass length.\n"
    "     * The raw password starts at offset 40, its length = job->clen.\n"
    "     * But we only have hexlens[] which was set to 40. We need clen.\n"
    "     * Store plen in the passlen array instead — gpujob reads it. */\n"
    "    /* For now: scan for the end of the password in the buffer */\n"
    "    /* Actually: the pass length is encoded as total - 40 where total is\n"
    "     * stored... let me use a simpler approach. The CPU packs:\n"
    "     * hexlen[idx] = 40 (the hex portion). Password is at wordbuf+40\n"
    "     * and its length is in g->passlen[idx] which maps to... we don't\n"
    "     * have a separate buffer for passlen on the GPU.\n"
    "     *\n"
    "     * Simplest: pack total length (40 + plen) in hexlens, kernel subtracts 40. */\n"
    "\n"
    "    /* hexlens[tid] = 40; password at wordbuf+40, length = clen from host */\n"
    "    /* We'll change hexlen to 40+plen so kernel can derive plen */\n"
    "    int total_packed = hexlens[tid]; /* set to 40 + plen by host */\n"
    "    plen = total_packed - 40;\n"
    "    __global const uchar *pass = wordbuf + 40;\n"
    "\n"
    "    /* SHA1(pass) already done on CPU — state is in hex at wordbuf[0..39] */\n"
    "    /* Decode hex back to 5 big-endian state words */\n"
    "    uint state[5];\n"
    "    for (int w = 0; w < 5; w++) {\n"
    "        __global const uint *hw = (__global const uint *)(wordbuf + w * 8);\n"
    "        /* hex chars are ASCII in LE uint32 words — reconstruct the big-endian SHA1 word */\n"
    "        /* Actually the hex is stored as raw ASCII bytes. Parse them. */\n"
    "        uint val = 0;\n"
    "        for (int j = 0; j < 8; j++) {\n"
    "            uchar c = wordbuf[w*8+j];\n"
    "            uint nibble = (c >= 'a') ? (c - 'a' + 10) : (c - '0');\n"
    "            val = (val << 4) | nibble;\n"
    "        }\n"
    "        state[w] = val;\n"
    "    }\n"
    "\n"
    "    uchar hexlut[16] = {'0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f'};\n"
    "\n"
    "    /* 1,000,000 iterations of SHA1(hex(hash) + pass) */\n"
    "    for (int iter = 0; iter < 1000000; iter++) {\n"
    "        uchar hexbuf[96];\n"
    "        for (int w = 0; w < 5; w++) {\n"
    "            uint sv = state[w];\n"
    "            hexbuf[w*8+0] = hexlut[(sv >> 28) & 0xf];\n"
    "            hexbuf[w*8+1] = hexlut[(sv >> 24) & 0xf];\n"
    "            hexbuf[w*8+2] = hexlut[(sv >> 20) & 0xf];\n"
    "            hexbuf[w*8+3] = hexlut[(sv >> 16) & 0xf];\n"
    "            hexbuf[w*8+4] = hexlut[(sv >> 12) & 0xf];\n"
    "            hexbuf[w*8+5] = hexlut[(sv >> 8) & 0xf];\n"
    "            hexbuf[w*8+6] = hexlut[(sv >> 4) & 0xf];\n"
    "            hexbuf[w*8+7] = hexlut[sv & 0xf];\n"
    "        }\n"
    "        for (int i = 0; i < plen; i++) hexbuf[40 + i] = pass[i];\n"
    "        int total = 40 + plen;\n"
    "\n"
    "        /* SHA1(hexbuf, total) */\n"
    "        state[0] = 0x67452301u; state[1] = 0xEFCDAB89u;\n"
    "        state[2] = 0x98BADCFEu; state[3] = 0x10325476u; state[4] = 0xC3D2E1F0u;\n"
    "        uint M[16];\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        if (total <= 55) {\n"
    "            S_copy_bytes_priv(M, 0, hexbuf, total);\n"
    "            S_set_byte_priv(M, total, 0x80);\n"
    "            M[15] = total * 8;\n"
    "            sha1_block(state, M);\n"
    "        } else {\n"
    "            /* Two blocks */\n"
    "            S_copy_bytes_priv(M, 0, hexbuf, 64);\n"
    "            sha1_block(state, M);\n"
    "            for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "            int rem = total - 64;\n"
    "            if (rem > 0) S_copy_bytes_priv(M, 0, hexbuf + 64, rem);\n"
    "            S_set_byte_priv(M, rem, 0x80);\n"
    "            M[15] = total * 8;\n"
    "            sha1_block(state, M);\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Byte-swap state for compact table probe */\n"
    "    uint h[5];\n"
    "    for (int i = 0; i < 5; i++) h[i] = bswap32(state[i]);\n"
    "\n"
    "    if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 8;\n"
    "            hits[base] = tid; hits[base+1] = 0; hits[base+2] = 1;\n"
    "            for (int i = 0; i < 5; i++) hits[base+3+i] = h[i];\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- MD5 with mask expansion (GPU_CAT_MASK) ---- */\n"
    "/* Mask descriptor buffer: [n_prepend charset IDs] [n_append charset IDs]\n"
    " * Charset IDs: 0=?d(10) 1=?l(26) 2=?u(26) 3=?s(33) 4=?a(95) 5=?b(256)\n"
    " * Each work item: tid / num_masks = word_idx, tid % num_masks = mask_idx\n"
    " * mask_idx is decomposed: prepend_idx × append_combos + append_idx */\n"
    "\n"
    "/* cs_a and cs_b built dynamically to save constant memory */\n"
    "\n"
    "__kernel void md5_mask_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *mask_desc, __global const uint *unused1, __global const ushort *unused2,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off, __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    uint mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int baselen = hexlens[word_idx];\n"
    "    __global const uchar *base = hexhashes + word_idx * 256;\n"
    "\n"
    "    /* Build candidate: [prepend chars] [base word] [append chars] */\n"
    "    uchar cand[128];\n"
    "    int clen = 0;\n"
    "\n"
    "    /* Decode prepend: mask_idx split into prepend_idx and append_idx */\n"
    "    uint n_total = params.n_prepend + params.n_append;\n"
    "    uint append_combos = 1;\n"
    "    for (uint i = 0; i < params.n_append; i++)\n"
    "        append_combos *= mask_desc[params.n_prepend + i];\n"
    "\n"
    "    uint prepend_idx = mask_idx / append_combos;\n"
    "    uint append_idx = mask_idx % append_combos;\n"
    "\n"
    "    /* Generate prepend chars (right to left in the index, left to right in output) */\n"
    "    if (params.n_prepend > 0) {\n"
    "        uint pidx = prepend_idx;\n"
    "        for (int i = params.n_prepend - 1; i >= 0; i--) {\n"
    "            uint sz = mask_desc[i];\n"
    "            cand[i] = mask_desc[n_total + i * 256 + (pidx % sz)];\n"
    "            pidx /= sz;\n"
    "        }\n"
    "        clen = params.n_prepend;\n"
    "    }\n"
    "\n"
    "    /* Copy base word */\n"
    "    for (int i = 0; i < baselen; i++)\n"
    "        cand[clen + i] = base[i];\n"
    "    clen += baselen;\n"
    "\n"
    "    /* Generate append chars */\n"
    "    if (params.n_append > 0) {\n"
    "        uint aidx = append_idx;\n"
    "        for (int i = params.n_append - 1; i >= 0; i--) {\n"
    "            int pos_idx = params.n_prepend + i;\n"
    "            uint sz = mask_desc[pos_idx];\n"
    "            cand[clen + i] = mask_desc[n_total + pos_idx * 256 + (aidx % sz)];\n"
    "            aidx /= sz;\n"
    "        }\n"
    "        clen += params.n_append;\n"
    "    }\n"
    "\n"
    "    /* MD5(candidate) */\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    uint hx = 0x67452301, hy = 0xEFCDAB89, hz = 0x98BADCFE, hw = 0x10325476;\n"
    "\n"
    "    if (clen <= 55) {\n"
    "        /* Single block */\n"
    "        for (int i = 0; i < clen; i++)\n"
    "            M[i >> 2] |= ((uint)cand[i]) << ((i & 3) << 3);\n"
    "        M[clen >> 2] |= 0x80u << ((clen & 3) << 3);\n"
    "        M[14] = clen * 8;\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "    } else {\n"
    "        /* Two blocks */\n"
    "        for (int i = 0; i < 64 && i < clen; i++)\n"
    "            M[i >> 2] |= ((uint)cand[i]) << ((i & 3) << 3);\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        for (int i = 64; i < clen; i++) {\n"
    "            int j = i - 64;\n"
    "            M[j >> 2] |= ((uint)cand[i]) << ((j & 3) << 3);\n"
    "        }\n"
    "        int rem = clen - 64;\n"
    "        M[rem >> 2] |= 0x80u << ((rem & 3) << 3);\n"
    "        M[14] = clen * 8;\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "    }\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base2 = slot * 6;\n"
    "            hits[base2] = word_idx; hits[base2+1] = mask_idx;\n"
    "            hits[base2+2] = hx; hits[base2+3] = hy;\n"
    "            hits[base2+4] = hz; hits[base2+5] = hw;\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- MD5(MD5(salt).MD5(pass)) kernel (e367) ---- */\n"
    "/* Salt buffer has hex(MD5(salt)) [32 bytes], hexhash buffer has hex(MD5(pass)) [32 bytes].\n"
    " * Total input is always exactly 64 bytes → deterministic 2-block MD5. */\n"
    "__kernel void md5_md5saltmd5pass_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off, __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    /* Load hex(MD5(salt)) [32 bytes] into M[0..7] as LE uint32 words */\n"
    "    uint M[16];\n"
    "    { __global const uint *sw = (__global const uint *)(salts + salt_offsets[salt_idx]);\n"
    "      for (int i = 0; i < 8; i++) M[i] = sw[i];\n"
    "    }\n"
    "\n"
    "    /* Load hex(MD5(pass)) [32 bytes] into M[8..15] */\n"
    "    __global const uint *pass_words = (__global const uint *)(hexhashes + word_idx * 256);\n"
    "    for (int i = 0; i < 8; i++) M[8 + i] = pass_words[i];\n"
    "\n"
    "    /* Block 1: MD5 of the 64 data bytes (no padding in this block) */\n"
    "    uint hx = 0x67452301, hy = 0xEFCDAB89, hz = 0x98BADCFE, hw = 0x10325476;\n"
    "    md5_block(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "    /* Block 2: padding only — 0x80 at byte 0, length 512 bits at M[14] */\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    M[0] = 0x00000080u;\n"
    "    M[14] = 64 * 8;  /* 512 bits */\n"
    "    md5_block(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 6;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx;\n"
    "            hits[base+2] = hx; hits[base+3] = hy;\n"
    "            hits[base+4] = hz; hits[base+5] = hw;\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- MD5CRYPT kernel (e511): $1$salt$hash, 1000 MD5 iterations ---- */\n"
    "/* Salt buffer contains \"$1$salt$\" from Typesalt. Kernel extracts raw salt. */\n"
    "\n"
    "/* Helper: build MD5 message block from a byte buffer, with padding */\n"
    "void md5_oneshot(const uchar *data, int len, uint *out) {\n"
    "    uint M[16];\n"
    "    out[0] = 0x67452301u; out[1] = 0xEFCDAB89u;\n"
    "    out[2] = 0x98BADCFEu; out[3] = 0x10325476u;\n"
    "\n"
    "    int pos = 0;\n"
    "    /* Process full 64-byte blocks */\n"
    "    while (pos + 64 <= len) {\n"
    "        for (int i = 0; i < 16; i++)\n"
    "            M[i] = (uint)data[pos+i*4] | ((uint)data[pos+i*4+1]<<8) |\n"
    "                   ((uint)data[pos+i*4+2]<<16) | ((uint)data[pos+i*4+3]<<24);\n"
    "        md5_block(&out[0], &out[1], &out[2], &out[3], M);\n"
    "        pos += 64;\n"
    "    }\n"
    "    /* Final block(s) with padding */\n"
    "    int rem = len - pos;\n"
    "    uchar pad[128];\n"
    "    for (int i = 0; i < 128; i++) pad[i] = 0;\n"
    "    for (int i = 0; i < rem; i++) pad[i] = data[pos + i];\n"
    "    pad[rem] = 0x80;\n"
    "    int blocks = (rem < 56) ? 1 : 2;\n"
    "    int lenoff = (blocks == 1) ? 56 : 120;\n"
    "    pad[lenoff] = (len * 8) & 0xff;\n"
    "    pad[lenoff+1] = ((len * 8) >> 8) & 0xff;\n"
    "    pad[lenoff+2] = ((len * 8) >> 16) & 0xff;\n"
    "    pad[lenoff+3] = ((len * 8) >> 24) & 0xff;\n"
    "    for (int b = 0; b < blocks; b++) {\n"
    "        for (int i = 0; i < 16; i++)\n"
    "            M[i] = (uint)pad[b*64+i*4] | ((uint)pad[b*64+i*4+1]<<8) |\n"
    "                   ((uint)pad[b*64+i*4+2]<<16) | ((uint)pad[b*64+i*4+3]<<24);\n"
    "        md5_block(&out[0], &out[1], &out[2], &out[3], M);\n"
    "    }\n"
    "}\n"
    "\n"
    "__kernel void md5crypt_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen_full = salt_lens[salt_idx];\n"
    "\n"
    "    /* Salt buffer has \"$1$salt$\" — extract raw salt (skip \"$1$\", stop before trailing \"$\") */\n"
    "    __global const uchar *salt_raw = salts + soff + 3; /* skip \"$1$\" */\n"
    "    int saltlen = slen_full - 4; /* remove \"$1$\" prefix and trailing \"$\" */\n"
    "    if (saltlen < 0) saltlen = 0;\n"
    "    if (saltlen > 8) saltlen = 8;\n"
    "\n"
    "    /* Local buffers */\n"
    "    uchar buf[256]; /* working buffer for MD5 input */\n"
    "    uint digest[4]; /* current MD5 state */\n"
    "\n"
    "    /* Step 1: digest_b = MD5(password + salt + password) */\n"
    "    int blen = 0;\n"
    "    for (int i = 0; i < plen; i++) buf[blen++] = pass[i];\n"
    "    for (int i = 0; i < saltlen; i++) buf[blen++] = salt_raw[i];\n"
    "    for (int i = 0; i < plen; i++) buf[blen++] = pass[i];\n"
    "    md5_oneshot(buf, blen, digest);\n"
    "    uchar digest_b[16];\n"
    "    for (int i = 0; i < 4; i++) {\n"
    "        digest_b[i*4]   = digest[i] & 0xff;\n"
    "        digest_b[i*4+1] = (digest[i] >> 8) & 0xff;\n"
    "        digest_b[i*4+2] = (digest[i] >> 16) & 0xff;\n"
    "        digest_b[i*4+3] = (digest[i] >> 24) & 0xff;\n"
    "    }\n"
    "\n"
    "    /* Step 2: digest_a = MD5(password + \"$1$\" + salt + digest_b_chunks + bit_bytes) */\n"
    "    blen = 0;\n"
    "    for (int i = 0; i < plen; i++) buf[blen++] = pass[i];\n"
    "    buf[blen++] = '$'; buf[blen++] = '1'; buf[blen++] = '$';\n"
    "    for (int i = 0; i < saltlen; i++) buf[blen++] = salt_raw[i];\n"
    "    /* Append digest_b for password length bytes */\n"
    "    for (int x = plen; x > 0; x -= 16) {\n"
    "        int n = (x > 16) ? 16 : x;\n"
    "        for (int i = 0; i < n; i++) buf[blen++] = digest_b[i];\n"
    "    }\n"
    "    /* Bit-dependent bytes */\n"
    "    for (int x = plen; x != 0; x >>= 1)\n"
    "        buf[blen++] = (x & 1) ? 0 : pass[0];\n"
    "    md5_oneshot(buf, blen, digest);\n"
    "\n"
    "    /* Step 3: 1000 iterations */\n"
    "    uchar dig[16];\n"
    "    for (int i = 0; i < 4; i++) {\n"
    "        dig[i*4]   = digest[i] & 0xff;\n"
    "        dig[i*4+1] = (digest[i] >> 8) & 0xff;\n"
    "        dig[i*4+2] = (digest[i] >> 16) & 0xff;\n"
    "        dig[i*4+3] = (digest[i] >> 24) & 0xff;\n"
    "    }\n"
    "    for (int x = 0; x < 1000; x++) {\n"
    "        blen = 0;\n"
    "        if (x & 1) { for (int i = 0; i < plen; i++) buf[blen++] = pass[i]; }\n"
    "        else       { for (int i = 0; i < 16; i++) buf[blen++] = dig[i]; }\n"
    "        if (x % 3) { for (int i = 0; i < saltlen; i++) buf[blen++] = salt_raw[i]; }\n"
    "        if (x % 7) { for (int i = 0; i < plen; i++) buf[blen++] = pass[i]; }\n"
    "        if (x & 1) { for (int i = 0; i < 16; i++) buf[blen++] = dig[i]; }\n"
    "        else       { for (int i = 0; i < plen; i++) buf[blen++] = pass[i]; }\n"
    "        md5_oneshot(buf, blen, digest);\n"
    "        for (int i = 0; i < 4; i++) {\n"
    "            dig[i*4]   = digest[i] & 0xff;\n"
    "            dig[i*4+1] = (digest[i] >> 8) & 0xff;\n"
    "            dig[i*4+2] = (digest[i] >> 16) & 0xff;\n"
    "            dig[i*4+3] = (digest[i] >> 24) & 0xff;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Probe compact table with 16-byte binary result */\n"
    "    uint hx = digest[0], hy = digest[1], hz = digest[2], hw = digest[3];\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 6;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx;\n"
    "            hits[base+2] = hx; hits[base+3] = hy;\n"
    "            hits[base+4] = hz; hits[base+5] = hw;\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- SHA256(password + salt) kernel (e413) ---- */\n"
    "__kernel void sha256passsalt_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = plen + slen;\n"
    "\n"
    "    uint state[8] = { 0x6a09e667u, 0xbb67ae85u, 0x3c6ef372u, 0xa54ff53au,\n"
    "                      0x510e527fu, 0x9b05688cu, 0x1f83d9abu, 0x5be0cd19u };\n"
    "    { uint M[16];\n"
    "      for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "\n"
    "      if (total_len <= 55) {\n"
    "        S_copy_bytes(M, 0, pass, plen);\n"
    "        S_copy_bytes(M, plen, salts + soff, slen);\n"
    "        S_set_byte(M, total_len, 0x80);\n"
    "        M[15] = total_len * 8;  /* big-endian length in bits */\n"
    "        sha256_block(state, M);\n"
    "      } else {\n"
    "        int pass_b1 = (plen < 64) ? plen : 64;\n"
    "        S_copy_bytes(M, 0, pass, pass_b1);\n"
    "        int salt_b1 = 64 - pass_b1;\n"
    "        if (salt_b1 > slen) salt_b1 = slen;\n"
    "        if (salt_b1 > 0)\n"
    "            S_copy_bytes(M, pass_b1, salts + soff, salt_b1);\n"
    "        if (total_len < 64)\n"
    "            S_set_byte(M, total_len, 0x80);\n"
    "        sha256_block(state, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int pos2 = 0;\n"
    "        int pass_b2 = plen - pass_b1;\n"
    "        if (pass_b2 > 0) { S_copy_bytes(M, 0, pass + pass_b1, pass_b2); pos2 = pass_b2; }\n"
    "        int salt_b2 = slen - salt_b1;\n"
    "        if (salt_b2 > 0) { S_copy_bytes(M, pos2, salts + soff + salt_b1, salt_b2); pos2 += salt_b2; }\n"
    "        if (total_len >= 64)\n"
    "            S_set_byte(M, pos2, 0x80);\n"
    "        M[15] = total_len * 8;\n"
    "        sha256_block(state, M);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    /* Byte-swap all 8 state words to match host's big-endian storage */\n"
    "    uint h[8];\n"
    "    for (int i = 0; i < 8; i++) h[i] = bswap32(state[i]);\n"
    "\n"
    "    if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            /* SHA256 hit: stride 11 = widx + sidx + iter + 8 hash words */\n"
    "            uint base = slot * 11;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx; hits[base+2] = 1;\n"
    "            for (int i = 0; i < 8; i++) hits[base+3+i] = h[i];\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- SHA256(salt + password) kernel (e412) ---- */\n"
    "__kernel void sha256saltpass_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = slen + plen;\n"
    "\n"
    "    uint state[8] = { 0x6a09e667u, 0xbb67ae85u, 0x3c6ef372u, 0xa54ff53au,\n"
    "                      0x510e527fu, 0x9b05688cu, 0x1f83d9abu, 0x5be0cd19u };\n"
    "    { uint M[16];\n"
    "      for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "\n"
    "      if (total_len <= 55) {\n"
    "        S_copy_bytes(M, 0, salts + soff, slen);\n"
    "        S_copy_bytes(M, slen, pass, plen);\n"
    "        S_set_byte(M, total_len, 0x80);\n"
    "        M[15] = total_len * 8;\n"
    "        sha256_block(state, M);\n"
    "      } else {\n"
    "        int salt_b1 = (slen < 64) ? slen : 64;\n"
    "        S_copy_bytes(M, 0, salts + soff, salt_b1);\n"
    "        int pass_b1 = 64 - salt_b1;\n"
    "        if (pass_b1 > plen) pass_b1 = plen;\n"
    "        if (pass_b1 > 0)\n"
    "            S_copy_bytes(M, salt_b1, pass, pass_b1);\n"
    "        if (total_len < 64)\n"
    "            S_set_byte(M, total_len, 0x80);\n"
    "        sha256_block(state, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int pos2 = 0;\n"
    "        int salt_b2 = slen - salt_b1;\n"
    "        if (salt_b2 > 0) { S_copy_bytes(M, 0, salts + soff + salt_b1, salt_b2); pos2 = salt_b2; }\n"
    "        int pass_b2 = plen - pass_b1;\n"
    "        if (pass_b2 > 0) { S_copy_bytes(M, pos2, pass + pass_b1, pass_b2); pos2 += pass_b2; }\n"
    "        if (total_len >= 64)\n"
    "            S_set_byte(M, pos2, 0x80);\n"
    "        M[15] = total_len * 8;\n"
    "        sha256_block(state, M);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    uint h[8];\n"
    "    for (int i = 0; i < 8; i++) h[i] = bswap32(state[i]);\n"
    "\n"
    "    if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 11;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx; hits[base+2] = 1;\n"
    "            for (int i = 0; i < 8; i++) hits[base+3+i] = h[i];\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* Self-test kernel: each work item computes MD5(\"test\"), writes 1 if correct, 0 if not.\n"
    " * Used at init to probe the maximum reliable dispatch size for this GPU. */\n"
    "__kernel void gpu_selftest(__global uint *results) {\n"
    "    uint tid = get_global_id(0);\n"
    "    uint M[16];\n"
    "    M[0] = 0x74736574u;  /* \"test\" LE */\n"
    "    M[1] = 0x00000080u;  /* padding byte */\n"
    "    for (int i = 2; i < 14; i++) M[i] = 0;\n"
    "    M[14] = 32u;         /* 4 bytes * 8 bits */\n"
    "    M[15] = 0;\n"
    "    uint hx = 0x67452301u, hy = 0xEFCDAB89u, hz = 0x98BADCFEu, hw = 0x10325476u;\n"
    "    md5_block(&hx, &hy, &hz, &hw, M);\n"
    "    /* MD5(\"test\") = 098f6bcd... -> LE word0 = 0xcd6b8f09 */\n"
    "    results[tid] = (hx == 0xcd6b8f09u && hy == 0x73d32146u) ? 1u : 0u;\n"
    "}\n"
;
