/* Auto-generated from gpu_md5mask.cl -- do not edit */
static const char gpu_md5mask_str[] =
    "/* ---- MD5 with mask expansion (GPU_CAT_MASK) ---- */\n"
    "/* Mask descriptor buffer: [n_prepend charset IDs] [n_append charset IDs]\n"
    " * Charset IDs: 0=?d(10) 1=?l(26) 2=?u(26) 3=?s(33) 4=?a(95) 5=?b(256)\n"
    " * Each work item: tid / num_masks = word_idx, tid % num_masks = mask_idx\n"
    " * mask_idx is decomposed: prepend_idx × append_combos + append_idx */\n"
    "\n"
    "/* cs_a and cs_b built dynamically to save constant memory */\n"
    "\n"
    "__kernel void md5_mask_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *mask_desc, __global const uint *unused1, __global const ushort *unused2,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off, __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    uint mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int baselen = hexlens[word_idx];\n"
    "    __global const uchar *base = hexhashes + word_idx * 256;\n"
    "\n"
    "    /* Build candidate: [prepend chars] [base word] [append chars] */\n"
    "    uchar cand[128];\n"
    "    int clen = 0;\n"
    "\n"
    "    /* Decode prepend: mask_idx split into prepend_idx and append_idx */\n"
    "    uint n_total = params.n_prepend + params.n_append;\n"
    "    uint append_combos = 1;\n"
    "    for (uint i = 0; i < params.n_append; i++)\n"
    "        append_combos *= mask_desc[params.n_prepend + i];\n"
    "\n"
    "    uint prepend_idx = mask_idx / append_combos;\n"
    "    uint append_idx = mask_idx % append_combos;\n"
    "\n"
    "    /* Generate prepend chars (right to left in the index, left to right in output) */\n"
    "    if (params.n_prepend > 0) {\n"
    "        uint pidx = prepend_idx;\n"
    "        for (int i = params.n_prepend - 1; i >= 0; i--) {\n"
    "            uint sz = mask_desc[i];\n"
    "            cand[i] = mask_desc[n_total + i * 256 + (pidx % sz)];\n"
    "            pidx /= sz;\n"
    "        }\n"
    "        clen = params.n_prepend;\n"
    "    }\n"
    "\n"
    "    /* Copy base word */\n"
    "    for (int i = 0; i < baselen; i++)\n"
    "        cand[clen + i] = base[i];\n"
    "    clen += baselen;\n"
    "\n"
    "    /* Generate append chars */\n"
    "    if (params.n_append > 0) {\n"
    "        uint aidx = append_idx;\n"
    "        for (int i = params.n_append - 1; i >= 0; i--) {\n"
    "            int pos_idx = params.n_prepend + i;\n"
    "            uint sz = mask_desc[pos_idx];\n"
    "            cand[clen + i] = mask_desc[n_total + pos_idx * 256 + (aidx % sz)];\n"
    "            aidx /= sz;\n"
    "        }\n"
    "        clen += params.n_append;\n"
    "    }\n"
    "\n"
    "    /* MD5(candidate) */\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    uint hx = 0x67452301, hy = 0xEFCDAB89, hz = 0x98BADCFE, hw = 0x10325476;\n"
    "\n"
    "    if (clen <= 55) {\n"
    "        /* Single block */\n"
    "        for (int i = 0; i < clen; i++)\n"
    "            M[i >> 2] |= ((uint)cand[i]) << ((i & 3) << 3);\n"
    "        M[clen >> 2] |= 0x80u << ((clen & 3) << 3);\n"
    "        M[14] = clen * 8;\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "    } else {\n"
    "        /* Two blocks */\n"
    "        for (int i = 0; i < 64 && i < clen; i++)\n"
    "            M[i >> 2] |= ((uint)cand[i]) << ((i & 3) << 3);\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        for (int i = 64; i < clen; i++) {\n"
    "            int j = i - 64;\n"
    "            M[j >> 2] |= ((uint)cand[i]) << ((j & 3) << 3);\n"
    "        }\n"
    "        int rem = clen - 64;\n"
    "        M[rem >> 2] |= 0x80u << ((rem & 3) << 3);\n"
    "        M[14] = clen * 8;\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "    }\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base2 = slot * 6;\n"
    "            hits[base2] = word_idx; hits[base2+1] = mask_idx;\n"
    "            hits[base2+2] = hx; hits[base2+3] = hy;\n"
    "            hits[base2+4] = hz; hits[base2+5] = hw;\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
;
