/* Auto-generated from gpu_md5saltpass.cl -- do not edit */
static const char gpu_md5saltpass_str[] =
    "/* M_copy_bytes, M_set_byte provided by gpu_common.cl */\n"
    "\n"
    "/* ---- MD5(salt + password) kernel ----\n"
    " *\n"
    " * Input: raw password bytes in hexhashes buffer, length in hexlens.\n"
    " * GPU constructs salt + password, computes MD5, checks compact table.\n"
    " * Handles 1-block (total <= 55) and 2-block (55 < total <= 119) dynamically.\n"
    " * Hit stride is 7 (includes iteration number).\n"
    " */\n"
    "__kernel void md5saltpass_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    /* Read password bytes and length */\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "\n"
    "    /* Read salt offset and length */\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = slen + plen;\n"
    "\n"
    "    /* Build message = salt + password, compute MD5 */\n"
    "    uint hx = 0x67452301, hy = 0xEFCDAB89, hz = 0x98BADCFE, hw = 0x10325476;\n"
    "\n"
    "    { uint M[16];\n"
    "      for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "\n"
    "      if (total_len <= 55) {\n"
    "        M_copy_bytes(M, 0, salts + soff, slen);\n"
    "        M_copy_bytes(M, slen, pass, plen);\n"
    "        M_set_byte(M, total_len, 0x80);\n"
    "        M[14] = total_len * 8;\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "      } else {\n"
    "        /* Two blocks: fill first 64 bytes from salt+pass */\n"
    "        int salt_b1 = (slen < 64) ? slen : 64;\n"
    "        M_copy_bytes(M, 0, salts + soff, salt_b1);\n"
    "        int pass_b1 = 64 - salt_b1;\n"
    "        if (pass_b1 > plen) pass_b1 = plen;\n"
    "        if (pass_b1 > 0)\n"
    "            M_copy_bytes(M, salt_b1, pass, pass_b1);\n"
    "        if (total_len < 64)\n"
    "            M_set_byte(M, total_len, 0x80);\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "        /* Second block */\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int pos2 = 0;\n"
    "        int salt_b2 = slen - salt_b1;\n"
    "        if (salt_b2 > 0) {\n"
    "            M_copy_bytes(M, 0, salts + soff + salt_b1, salt_b2);\n"
    "            pos2 = salt_b2;\n"
    "        }\n"
    "        int pass_b2 = plen - pass_b1;\n"
    "        if (pass_b2 > 0) {\n"
    "            M_copy_bytes(M, pos2, pass + pass_b1, pass_b2);\n"
    "            pos2 += pass_b2;\n"
    "        }\n"
    "        if (total_len >= 64)\n"
    "            M_set_byte(M, pos2, 0x80);\n"
    "        M[14] = total_len * 8;\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        EMIT_HIT_4(hits, hit_count, params.max_hits, word_idx, salt_idx, 1, hx, hy, hz, hw)\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- MD5(password + salt) kernel ---- */\n"
    "__kernel void md5passsalt_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = plen + slen;\n"
    "\n"
    "    uint hx = 0x67452301, hy = 0xEFCDAB89, hz = 0x98BADCFE, hw = 0x10325476;\n"
    "    { uint M[16];\n"
    "      for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "\n"
    "      if (total_len <= 55) {\n"
    "        M_copy_bytes(M, 0, pass, plen);\n"
    "        M_copy_bytes(M, plen, salts + soff, slen);\n"
    "        M_set_byte(M, total_len, 0x80);\n"
    "        M[14] = total_len * 8;\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "      } else {\n"
    "        /* Two blocks: fill first 64 bytes from pass+salt */\n"
    "        int pass_b1 = (plen < 64) ? plen : 64;\n"
    "        M_copy_bytes(M, 0, pass, pass_b1);\n"
    "        int salt_b1 = 64 - pass_b1;\n"
    "        if (salt_b1 > slen) salt_b1 = slen;\n"
    "        if (salt_b1 > 0)\n"
    "            M_copy_bytes(M, pass_b1, salts + soff, salt_b1);\n"
    "        /* If all data fits in block 1, put 0x80 here */\n"
    "        if (total_len < 64)\n"
    "            M_set_byte(M, total_len, 0x80);\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "        /* Second block: remaining data + padding */\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int pos2 = 0;\n"
    "        int pass_b2 = plen - pass_b1;\n"
    "        if (pass_b2 > 0) {\n"
    "            M_copy_bytes(M, 0, pass + pass_b1, pass_b2);\n"
    "            pos2 = pass_b2;\n"
    "        }\n"
    "        int salt_b2 = slen - salt_b1;\n"
    "        if (salt_b2 > 0) {\n"
    "            M_copy_bytes(M, pos2, salts + soff + salt_b1, salt_b2);\n"
    "            pos2 += salt_b2;\n"
    "        }\n"
    "        if (total_len >= 64)\n"
    "            M_set_byte(M, pos2, 0x80);\n"
    "        M[14] = total_len * 8;\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        EMIT_HIT_4(hits, hit_count, params.max_hits, word_idx, salt_idx, 1, hx, hy, hz, hw)\n"
    "    }\n"
    "}\n"
;
