/* Auto-generated from gpu_keccakunsalted.cl -- do not edit */
static const char gpu_keccakunsalted_str[] =
    "/* gpu_keccakunsalted.cl — Keccak-224/256/384/512 unsalted with mask expansion\n"
    " *\n"
    " * Keccak (SHA-3 competition version, without NIST 0x06 domain separator).\n"
    " * Sponge construction: XOR padded message into zero state, apply Keccak-f[1600].\n"
    " * Natively little-endian — no byte-swap needed.\n"
    " *\n"
    " * Padding: 0x01 after message, 0x80 at last rate byte.\n"
    " * Rate: 144 (224), 136 (256), 104 (384), 72 (512) bytes.\n"
    " *\n"
    " * Input: pre-padded rate-sized blocks with Keccak padding applied by host.\n"
    " * Dispatch: num_words × num_masks threads.\n"
    " * Hit stride: 6 (word_idx, mask_idx, hx, hy, hz, hw)\n"
    " */\n"
    "\n"
    "\n"
    "/* Keccak-f[1600] round constants */\n"
    "__constant ulong RC[24] = {\n"
    "    0x0000000000000001UL, 0x0000000000008082UL, 0x800000000000808aUL,\n"
    "    0x8000000080008000UL, 0x000000000000808bUL, 0x0000000080000001UL,\n"
    "    0x8000000080008081UL, 0x8000000000008009UL, 0x000000000000008aUL,\n"
    "    0x0000000000000088UL, 0x0000000080008009UL, 0x000000008000000aUL,\n"
    "    0x000000008000808bUL, 0x800000000000008bUL, 0x8000000000008089UL,\n"
    "    0x8000000000008003UL, 0x8000000000008002UL, 0x8000000000000080UL,\n"
    "    0x000000000000800aUL, 0x800000008000000aUL, 0x8000000080008081UL,\n"
    "    0x8000000000008080UL, 0x0000000080000001UL, 0x8000000080008008UL\n"
    "};\n"
    "\n"
    "/* Keccak-f[1600] rotation offsets (linearized [x][y] where index = x*5+y) */\n"
    "__constant uint ROTC[25] = {\n"
    "     0,  1, 62, 28, 27,\n"
    "    36, 44,  6, 55, 20,\n"
    "     3, 10, 43, 25, 39,\n"
    "    41, 45, 15, 21,  8,\n"
    "    18,  2, 61, 56, 14\n"
    "};\n"
    "\n"
    "/* Keccak-f[1600] permutation — 24 rounds on 5×5 state of uint64 */\n"
    "void keccak_f1600(ulong *st) {\n"
    "    for (int round = 0; round < 24; round++) {\n"
    "        /* θ (theta) */\n"
    "        ulong C[5], D[5];\n"
    "        for (int x = 0; x < 5; x++)\n"
    "            C[x] = st[x] ^ st[x+5] ^ st[x+10] ^ st[x+15] ^ st[x+20];\n"
    "        for (int x = 0; x < 5; x++) {\n"
    "            D[x] = C[(x+4) % 5] ^ rotate(C[(x+1) % 5], (ulong)1);\n"
    "            for (int y = 0; y < 25; y += 5)\n"
    "                st[x+y] ^= D[x];\n"
    "        }\n"
    "\n"
    "        /* ρ (rho) + π (pi) combined */\n"
    "        ulong B[25];\n"
    "        for (int x = 0; x < 5; x++)\n"
    "            for (int y = 0; y < 5; y++)\n"
    "                B[y*5 + ((2*x + 3*y) % 5)] = rotate(st[x*5+y], (ulong)ROTC[x*5+y]);\n"
    "\n"
    "        /* χ (chi) */\n"
    "        for (int x = 0; x < 5; x++)\n"
    "            for (int y = 0; y < 25; y += 5)\n"
    "                st[x+y] = B[x+y] ^ (~B[((x+1)%5)+y] & B[((x+2)%5)+y]);\n"
    "\n"
    "        /* ι (iota) */\n"
    "        st[0] ^= RC[round];\n"
    "    }\n"
    "}\n"
    "\n"
    "/* Fill masks into LE uint64 block (rate_words uint64 words) */\n"
    "void keccak_fill_masks(ulong *block, uint n_pre, uint n_app, uint mask_idx,\n"
    "                       __global const uchar *mask_desc, int rate) {\n"
    "    uint append_combos = 1;\n"
    "    for (uint i = 0; i < n_app; i++)\n"
    "        append_combos *= mask_desc[n_pre + i];\n"
    "    uint prepend_idx = mask_idx / append_combos;\n"
    "    uint append_idx = mask_idx % append_combos;\n"
    "\n"
    "    /* Fill prepend: byte i → block[i/8], LE bit position (i%8)*8 */\n"
    "    if (n_pre > 0) {\n"
    "        uint pidx = prepend_idx;\n"
    "        for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "            uint sz = mask_desc[i];\n"
    "            uint n_total_m = n_pre + n_app;\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "            pidx /= sz;\n"
    "            int wi = i >> 3;\n"
    "            int bi = (i & 7) << 3;\n"
    "            block[wi] = (block[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Fill append: message length stored as low byte of last rate word's unused area.\n"
    "     * Actually, for Keccak the total length is encoded in the padding position.\n"
    "     * We find the 0x01 pad byte to determine total_len. But simpler: the host\n"
    "     * stores total_len in the hexlen metadata. For GPU, we can scan for 0x01.\n"
    "     * Even simpler: since the block is zeroed except for password + 0x01 + 0x80,\n"
    "     * the 0x01 byte position IS total_len (unless it overlaps with 0x80).\n"
    "     *\n"
    "     * Use params for the message length instead. The host stores total_len\n"
    "     * in params through a convention. For now, derive from the pad byte position.\n"
    "     *\n"
    "     * Actually, for Keccak, host packs: slot[total] = 0x01, slot[rate-1] |= 0x80.\n"
    "     * We need total_len to compute append position. Store it in a deterministic\n"
    "     * place. Reuse: the byte right after the last rate word (stride > rate).\n"
    "     * Or: store as a uint32 at a known offset in the block.\n"
    "     *\n"
    "     * Simplest: host stores total_len as uint32 at block byte offset (rate).\n"
    "     * This is past the rate data but within the stride allocation.\n"
    "     */\n"
    "    if (n_app > 0) {\n"
    "        /* total_len stored by host as uint32 at byte offset rate */\n"
    "        __global const uint *meta = (__global const uint *)0; /* placeholder — see below */\n"
    "        /* Actually, we can derive total_len from the rate and pad positions.\n"
    "         * The host packs: slot[total] = 0x01 (or 0x81 if total==rate-1).\n"
    "         * For the GPU kernel, we pass total_len via params. Let's use\n"
    "         * params.iter_count as the message total length. */\n"
    "        int total_len = 0;\n"
    "        /* Scan for the 0x01 pad byte — it's at position total_len.\n"
    "         * The block has password + 0x01 + zeros + 0x80 at end.\n"
    "         * The password doesn't contain 0x01 (mask chars are printable).\n"
    "         * But this isn't reliable for ?b masks. */\n"
    "        /* Better approach: host stores total_len in the first 2 bytes past\n"
    "         * the rate data. stride > rate, so there's room. */\n"
    "        uchar *bp = (uchar *)block;\n"
    "        total_len = bp[rate] | (bp[rate+1] << 8);\n"
    "\n"
    "        int app_start = total_len - (int)n_app;\n"
    "        uint aidx = append_idx;\n"
    "        for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "            int pos_idx = n_pre + i;\n"
    "                uint sz = mask_desc[pos_idx];\n"
    "                uint n_total_m = n_pre + n_app;\n"
    "                uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "            aidx /= sz;\n"
    "            int pos = app_start + i;\n"
    "            int wi = pos >> 3;\n"
    "            int bi = (pos & 7) << 3;\n"
    "            block[wi] = (block[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* Generic Keccak unsalted kernel.\n"
    " * rate_words = rate / 8.\n"
    " * The host packs: message in LE, 0x01 at total_len, 0x80 at rate-1.\n"
    " * total_len stored as uint16 at byte offset rate for mask append. */\n"
    "#define KECCAK_KERNEL(name, rate, rate_words)                                  \\\n"
    "__kernel void name(                                                            \\\n"
    "    __global const uchar *words,                                               \\\n"
    "    __global const ushort *unused_lens,                                         \\\n"
    "    __global const uchar *mask_desc,                                           \\\n"
    "    __global const uint *unused1, __global const ushort *unused2,              \\\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,         \\\n"
    "    __global const OCLParams *params_buf,                                      \\\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off, \\\n"
    "    __global const ushort *hash_data_len,                                      \\\n"
    "    __global uint *hits, __global volatile uint *hit_count,                    \\\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\\\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths) \\\n"
    "{                                                                              \\\n"
    "    OCLParams params = *params_buf;                                            \\\n"
    "    uint tid = get_global_id(0);                                               \\\n"
    "    uint word_idx = tid / params.num_masks;                                    \\\n"
    "    uint mask_idx = params.mask_start + (tid % params.num_masks);              \\\n"
    "    if (word_idx >= params.num_words) return;                                  \\\n"
    "                                                                               \\\n"
    "    /* Load padded block (rate bytes + 2 bytes metadata) */                    \\\n"
    "    int stride = rate + 8; /* stride includes metadata + alignment */          \\\n"
    "    __global const ulong *src = (__global const ulong *)(words + word_idx * stride); \\\n"
    "    ulong block[rate_words];                                                   \\\n"
    "    for (int i = 0; i < rate_words; i++) block[i] = src[i];                   \\\n"
    "                                                                               \\\n"
    "    /* Fill mask positions — LE byte manipulation, same approach */            \\\n"
    "    if (params.n_prepend > 0 || params.n_append > 0)                           \\\n"
    "        keccak_fill_masks(block, params.n_prepend, params.n_append,            \\\n"
    "                          mask_idx, mask_desc, rate);                           \\\n"
    "                                                                               \\\n"
    "    /* XOR block into zero state and run Keccak-f[1600] */                     \\\n"
    "    ulong st[25];                                                              \\\n"
    "    for (int i = 0; i < 25; i++) st[i] = 0;                                   \\\n"
    "    for (int i = 0; i < rate_words; i++) st[i] = block[i];                    \\\n"
    "    keccak_f1600(st);                                                          \\\n"
    "                                                                               \\\n"
    "    /* Probe compact table with first 16 bytes of state (LE, no swap) */       \\\n"
    "    uint hx = (uint)st[0], hy = (uint)(st[0] >> 32);                          \\\n"
    "    uint hz = (uint)st[1], hw = (uint)(st[1] >> 32);                           \\\n"
    "                                                                               \\\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,                \\\n"
    "                      params.compact_mask, params.max_probe,                   \\\n"
    "                      params.hash_data_count, hash_data_buf, hash_data_off,    \\\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets,         \\\n"
    "                      params.overflow_count)) {                                \\\n"
    "        uint slot = atomic_add(hit_count, 1u);                                 \\\n"
    "        if (slot < params.max_hits) {                                          \\\n"
    "            uint base = slot * 6;                                              \\\n"
    "            hits[base] = word_idx; hits[base+1] = mask_idx;                    \\\n"
    "            hits[base+2] = hx; hits[base+3] = hy;                             \\\n"
    "            hits[base+4] = hz; hits[base+5] = hw;                             \\\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);                                   \\\n"
    "        }                                                                      \\\n"
    "    }                                                                          \\\n"
    "}\n"
    "\n"
    "/* Keccak-224: rate=144 bytes = 18 uint64 words (pad byte 0x01) */\n"
    "KECCAK_KERNEL(keccak224_unsalted_batch, 144, 18)\n"
    "\n"
    "/* Keccak-256: rate=136 bytes = 17 uint64 words (pad byte 0x01) */\n"
    "KECCAK_KERNEL(keccak256_unsalted_batch, 136, 17)\n"
    "\n"
    "/* Keccak-384: rate=104 bytes = 13 uint64 words (pad byte 0x01) */\n"
    "KECCAK_KERNEL(keccak384_unsalted_batch, 104, 13)\n"
    "\n"
    "/* Keccak-512: rate=72 bytes = 9 uint64 words (pad byte 0x01) */\n"
    "KECCAK_KERNEL(keccak512_unsalted_batch, 72, 9)\n"
    "\n"
    "/* SHA3-224/256/384/512: same permutation, pad byte 0x06 (applied by host packer).\n"
    " * Same rates as Keccak. Kernel is identical — only padding differs. */\n"
    "KECCAK_KERNEL(sha3_224_unsalted_batch, 144, 18)\n"
    "KECCAK_KERNEL(sha3_256_unsalted_batch, 136, 17)\n"
    "KECCAK_KERNEL(sha3_384_unsalted_batch, 104, 13)\n"
    "KECCAK_KERNEL(sha3_512_unsalted_batch, 72, 9)\n"
;
