/* Auto-generated from gpu_sha256.cl -- do not edit */
static const char gpu_sha256_str[] =
    "/* SHA256_K[], S256_* macros, sha256_block(), bswap32(), S_copy_bytes(),\n"
    " * S_set_byte(), M_copy_bytes(), M_set_byte() all provided by gpu_common.cl */\n"
    "\n"
    "/* ---- SHA256(password + salt) kernel (e413) ---- */\n"
    "__kernel void sha256passsalt_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = plen + slen;\n"
    "\n"
    "    uint state[8] = { 0x6a09e667u, 0xbb67ae85u, 0x3c6ef372u, 0xa54ff53au,\n"
    "                      0x510e527fu, 0x9b05688cu, 0x1f83d9abu, 0x5be0cd19u };\n"
    "    { uint M[16];\n"
    "      for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "\n"
    "      if (total_len <= 55) {\n"
    "        S_copy_bytes(M, 0, pass, plen);\n"
    "        S_copy_bytes(M, plen, salts + soff, slen);\n"
    "        S_set_byte(M, total_len, 0x80);\n"
    "        M[15] = total_len * 8;  /* big-endian length in bits */\n"
    "        sha256_block(state, M);\n"
    "      } else {\n"
    "        int pass_b1 = (plen < 64) ? plen : 64;\n"
    "        S_copy_bytes(M, 0, pass, pass_b1);\n"
    "        int salt_b1 = 64 - pass_b1;\n"
    "        if (salt_b1 > slen) salt_b1 = slen;\n"
    "        if (salt_b1 > 0)\n"
    "            S_copy_bytes(M, pass_b1, salts + soff, salt_b1);\n"
    "        if (total_len < 64)\n"
    "            S_set_byte(M, total_len, 0x80);\n"
    "        sha256_block(state, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int pos2 = 0;\n"
    "        int pass_b2 = plen - pass_b1;\n"
    "        if (pass_b2 > 0) { S_copy_bytes(M, 0, pass + pass_b1, pass_b2); pos2 = pass_b2; }\n"
    "        int salt_b2 = slen - salt_b1;\n"
    "        if (salt_b2 > 0) { S_copy_bytes(M, pos2, salts + soff + salt_b1, salt_b2); pos2 += salt_b2; }\n"
    "        if (total_len >= 64)\n"
    "            S_set_byte(M, pos2, 0x80);\n"
    "        M[15] = total_len * 8;\n"
    "        sha256_block(state, M);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    /* Byte-swap all 8 state words to match host's big-endian storage */\n"
    "    uint h[8];\n"
    "    for (int i = 0; i < 8; i++) h[i] = bswap32(state[i]);\n"
    "\n"
    "    if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            /* SHA256 hit: stride 11 = widx + sidx + iter + 8 hash words */\n"
    "            uint base = slot * 11;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx; hits[base+2] = 1;\n"
    "            for (int i = 0; i < 8; i++) hits[base+3+i] = h[i];\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- SHA256(salt + password) kernel (e412) ---- */\n"
    "__kernel void sha256saltpass_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = slen + plen;\n"
    "\n"
    "    uint state[8] = { 0x6a09e667u, 0xbb67ae85u, 0x3c6ef372u, 0xa54ff53au,\n"
    "                      0x510e527fu, 0x9b05688cu, 0x1f83d9abu, 0x5be0cd19u };\n"
    "    { uint M[16];\n"
    "      for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "\n"
    "      if (total_len <= 55) {\n"
    "        S_copy_bytes(M, 0, salts + soff, slen);\n"
    "        S_copy_bytes(M, slen, pass, plen);\n"
    "        S_set_byte(M, total_len, 0x80);\n"
    "        M[15] = total_len * 8;\n"
    "        sha256_block(state, M);\n"
    "      } else {\n"
    "        int salt_b1 = (slen < 64) ? slen : 64;\n"
    "        S_copy_bytes(M, 0, salts + soff, salt_b1);\n"
    "        int pass_b1 = 64 - salt_b1;\n"
    "        if (pass_b1 > plen) pass_b1 = plen;\n"
    "        if (pass_b1 > 0)\n"
    "            S_copy_bytes(M, salt_b1, pass, pass_b1);\n"
    "        if (total_len < 64)\n"
    "            S_set_byte(M, total_len, 0x80);\n"
    "        sha256_block(state, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int pos2 = 0;\n"
    "        int salt_b2 = slen - salt_b1;\n"
    "        if (salt_b2 > 0) { S_copy_bytes(M, 0, salts + soff + salt_b1, salt_b2); pos2 = salt_b2; }\n"
    "        int pass_b2 = plen - pass_b1;\n"
    "        if (pass_b2 > 0) { S_copy_bytes(M, pos2, pass + pass_b1, pass_b2); pos2 += pass_b2; }\n"
    "        if (total_len >= 64)\n"
    "            S_set_byte(M, pos2, 0x80);\n"
    "        M[15] = total_len * 8;\n"
    "        sha256_block(state, M);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    uint h[8];\n"
    "    for (int i = 0; i < 8; i++) h[i] = bswap32(state[i]);\n"
    "\n"
    "    if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 11;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx; hits[base+2] = 1;\n"
    "            for (int i = 0; i < 8; i++) hits[base+3+i] = h[i];\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "/* gpu_hmac_sha256.cl — HMAC-SHA256 GPU kernels\n"
    " *\n"
    " * hmac_sha256_ksalt_batch: HMAC-SHA256 key=$salt (e217, hashcat 1460)\n"
    " *   Key = salt (from Typeuser), Message = password\n"
    " *\n"
    " * hmac_sha256_kpass_batch: HMAC-SHA256 key=$pass (e795, hashcat 1450)\n"
    " *   Key = password, Message = salt (from Typesalt)\n"
    " *\n"
    " * HMAC(K, M) = H((K ⊕ opad) || H((K ⊕ ipad) || M))\n"
    " * Block size = 64 bytes, ipad = 0x36, opad = 0x5c\n"
    " *\n"
    " * Hit stride: 11 (word_idx, salt_idx, iter, h[0..7])\n"
    " */\n"
    "\n"
    "/* HMAC-SHA256 key=$salt: key=salt, message=password.\n"
    " * Dispatch: num_words × num_salts threads. */\n"
    "__kernel void hmac_sha256_ksalt_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int klen = salt_lens[salt_idx];\n"
    "    __global const uchar *key = salts + soff;\n"
    "\n"
    "    /* Step 1: Prepare key block.\n"
    "     * If key > 64 bytes, hash it. For typical salts this won't happen. */\n"
    "    uint key_block[16];  /* 64 bytes as uint32 */\n"
    "    for (int i = 0; i < 16; i++) key_block[i] = 0;\n"
    "\n"
    "    if (klen > 64) {\n"
    "        /* key = SHA256(original_key) */\n"
    "        uint kstate[8] = { 0x6a09e667u, 0xbb67ae85u, 0x3c6ef372u, 0xa54ff53au,\n"
    "                           0x510e527fu, 0x9b05688cu, 0x1f83d9abu, 0x5be0cd19u };\n"
    "        uint M[16];\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        S_copy_bytes(M, 0, key, (klen < 64) ? klen : 64);\n"
    "        if (klen <= 55) { S_set_byte(M, klen, 0x80); M[15] = klen * 8; }\n"
    "        sha256_block(kstate, M);\n"
    "        if (klen > 55) {\n"
    "            for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "            int rem = klen - 64;\n"
    "            if (rem > 0) S_copy_bytes(M, 0, key + 64, rem);\n"
    "            S_set_byte(M, rem, 0x80);\n"
    "            M[15] = klen * 8;\n"
    "            sha256_block(kstate, M);\n"
    "        }\n"
    "        /* Store hashed key (32 bytes BE) as LE bytes in key_block */\n"
    "        for (int i = 0; i < 8; i++) key_block[i] = bswap32(kstate[i]);\n"
    "        klen = 32;\n"
    "    } else {\n"
    "        /* Copy key bytes into key_block as little-endian uint32 */\n"
    "        for (int i = 0; i < klen; i++) {\n"
    "            int wi = i >> 2;\n"
    "            int bi = (i & 3) << 3;\n"
    "            key_block[wi] |= ((uint)key[i]) << bi;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Step 2: Inner hash = SHA256((key ⊕ ipad) || message) */\n"
    "    uint ipad[16], M[16];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        ipad[i] = key_block[i] ^ 0x36363636u;\n"
    "\n"
    "    /* Convert ipad to big-endian for SHA256 */\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap32(ipad[i]);\n"
    "\n"
    "    uint istate[8] = { 0x6a09e667u, 0xbb67ae85u, 0x3c6ef372u, 0xa54ff53au,\n"
    "                       0x510e527fu, 0x9b05688cu, 0x1f83d9abu, 0x5be0cd19u };\n"
    "    sha256_block(istate, M);  /* Process ipad block (64 bytes) */\n"
    "\n"
    "    /* Continue with message (password) + padding */\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    int mlen = plen;\n"
    "    if (mlen <= 55) {\n"
    "        S_copy_bytes(M, 0, pass, mlen);\n"
    "        S_set_byte(M, mlen, 0x80);\n"
    "        M[15] = (64 + mlen) * 8;  /* total = ipad_block + message */\n"
    "        sha256_block(istate, M);\n"
    "    } else {\n"
    "        S_copy_bytes(M, 0, pass, (mlen < 64) ? mlen : 64);\n"
    "        if (mlen < 64) S_set_byte(M, mlen, 0x80);\n"
    "        sha256_block(istate, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int rem = mlen - 64;\n"
    "        if (rem > 0) S_copy_bytes(M, 0, pass + 64, rem);\n"
    "        if (mlen >= 64) S_set_byte(M, (rem > 0) ? rem : 0, 0x80);\n"
    "        M[15] = (64 + mlen) * 8;\n"
    "        sha256_block(istate, M);\n"
    "    }\n"
    "\n"
    "    /* Inner hash result (32 bytes, big-endian in istate) */\n"
    "\n"
    "    /* Step 3: Outer hash = SHA256((key ⊕ opad) || inner_hash) */\n"
    "    uint opad_block[16];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        opad_block[i] = key_block[i] ^ 0x5c5c5c5cu;\n"
    "\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap32(opad_block[i]);\n"
    "\n"
    "    uint ostate[8] = { 0x6a09e667u, 0xbb67ae85u, 0x3c6ef372u, 0xa54ff53au,\n"
    "                       0x510e527fu, 0x9b05688cu, 0x1f83d9abu, 0x5be0cd19u };\n"
    "    sha256_block(ostate, M);  /* Process opad block (64 bytes) */\n"
    "\n"
    "    /* Continue with inner_hash (32 bytes BE) + padding.\n"
    "     * istate[] is already in BE — copy directly into M[]. */\n"
    "    for (int i = 0; i < 8; i++) M[i] = istate[i];\n"
    "    M[8] = 0x80000000u;\n"
    "    for (int i = 9; i < 15; i++) M[i] = 0;\n"
    "    M[15] = (64 + 32) * 8;  /* opad_block(64) + inner_hash(32) = 96 bytes */\n"
    "    sha256_block(ostate, M);\n"
    "\n"
    "    /* Step 4: Check result */\n"
    "    uint h[8];\n"
    "    for (int i = 0; i < 8; i++) h[i] = bswap32(ostate[i]);\n"
    "\n"
    "    if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 11;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx; hits[base+2] = 1;\n"
    "            for (int i = 0; i < 8; i++) hits[base+3+i] = h[i];\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* HMAC-SHA256 key=$pass: key=password, message=salt.\n"
    " * Dispatch: num_words × num_salts threads. */\n"
    "__kernel void hmac_sha256_kpass_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int klen = hexlens[word_idx];  /* password = key */\n"
    "    __global const uchar *key = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int mlen = salt_lens[salt_idx];  /* salt = message */\n"
    "    __global const uchar *msg = salts + soff;\n"
    "\n"
    "    /* Step 1: Prepare key block from password */\n"
    "    uint key_block[16];\n"
    "    for (int i = 0; i < 16; i++) key_block[i] = 0;\n"
    "\n"
    "    if (klen > 64) {\n"
    "        uint kstate[8] = { 0x6a09e667u, 0xbb67ae85u, 0x3c6ef372u, 0xa54ff53au,\n"
    "                           0x510e527fu, 0x9b05688cu, 0x1f83d9abu, 0x5be0cd19u };\n"
    "        uint M[16];\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        S_copy_bytes(M, 0, key, (klen < 64) ? klen : 64);\n"
    "        if (klen <= 55) { S_set_byte(M, klen, 0x80); M[15] = klen * 8; }\n"
    "        sha256_block(kstate, M);\n"
    "        if (klen > 55) {\n"
    "            for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "            int rem = klen - 64;\n"
    "            if (rem > 0) S_copy_bytes(M, 0, key + 64, rem);\n"
    "            S_set_byte(M, rem, 0x80);\n"
    "            M[15] = klen * 8;\n"
    "            sha256_block(kstate, M);\n"
    "        }\n"
    "        for (int i = 0; i < 8; i++) key_block[i] = bswap32(kstate[i]);\n"
    "        klen = 32;\n"
    "    } else {\n"
    "        for (int i = 0; i < klen; i++) {\n"
    "            int wi = i >> 2;\n"
    "            int bi = (i & 3) << 3;\n"
    "            key_block[wi] |= ((uint)key[i]) << bi;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Step 2: Inner hash = SHA256((key ⊕ ipad) || salt) */\n"
    "    uint ipad[16], M[16];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        ipad[i] = key_block[i] ^ 0x36363636u;\n"
    "\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap32(ipad[i]);\n"
    "\n"
    "    uint istate[8] = { 0x6a09e667u, 0xbb67ae85u, 0x3c6ef372u, 0xa54ff53au,\n"
    "                       0x510e527fu, 0x9b05688cu, 0x1f83d9abu, 0x5be0cd19u };\n"
    "    sha256_block(istate, M);\n"
    "\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    if (mlen <= 55) {\n"
    "        S_copy_bytes(M, 0, msg, mlen);\n"
    "        S_set_byte(M, mlen, 0x80);\n"
    "        M[15] = (64 + mlen) * 8;\n"
    "        sha256_block(istate, M);\n"
    "    } else {\n"
    "        S_copy_bytes(M, 0, msg, (mlen < 64) ? mlen : 64);\n"
    "        if (mlen < 64) S_set_byte(M, mlen, 0x80);\n"
    "        sha256_block(istate, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int rem = mlen - 64;\n"
    "        if (rem > 0) S_copy_bytes(M, 0, msg + 64, rem);\n"
    "        if (mlen >= 64) S_set_byte(M, (rem > 0) ? rem : 0, 0x80);\n"
    "        M[15] = (64 + mlen) * 8;\n"
    "        sha256_block(istate, M);\n"
    "    }\n"
    "\n"
    "    /* Step 3: Outer hash */\n"
    "    uint opad_block[16];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        opad_block[i] = key_block[i] ^ 0x5c5c5c5cu;\n"
    "\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap32(opad_block[i]);\n"
    "\n"
    "    uint ostate[8] = { 0x6a09e667u, 0xbb67ae85u, 0x3c6ef372u, 0xa54ff53au,\n"
    "                       0x510e527fu, 0x9b05688cu, 0x1f83d9abu, 0x5be0cd19u };\n"
    "    sha256_block(ostate, M);\n"
    "\n"
    "    for (int i = 0; i < 8; i++) M[i] = istate[i];\n"
    "    M[8] = 0x80000000u;\n"
    "    for (int i = 9; i < 15; i++) M[i] = 0;\n"
    "    M[15] = (64 + 32) * 8;\n"
    "    sha256_block(ostate, M);\n"
    "\n"
    "    uint h[8];\n"
    "    for (int i = 0; i < 8; i++) h[i] = bswap32(ostate[i]);\n"
    "\n"
    "    if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 11;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx; hits[base+2] = 1;\n"
    "            for (int i = 0; i < 8; i++) hits[base+3+i] = h[i];\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* HMAC-SHA224 key=$salt (e216, hashcat na) and key=$pass (e794, hashcat na)\n"
    " * Same compress as SHA256, SHA224 IV, inner hash = 28 bytes.\n"
    " * Hit stride: 11 (reuse SHA256 stride, extra word unused) */\n"
    "\n"
    "#define SHA224_IV0 0xc1059ed8u\n"
    "#define SHA224_IV1 0x367cd507u\n"
    "#define SHA224_IV2 0x3070dd17u\n"
    "#define SHA224_IV3 0xf70e5939u\n"
    "#define SHA224_IV4 0xffc00b31u\n"
    "#define SHA224_IV5 0x68581511u\n"
    "#define SHA224_IV6 0x64f98fa7u\n"
    "#define SHA224_IV7 0xbefa4fa4u\n"
    "\n"
    "__kernel void hmac_sha224_ksalt_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int klen = salt_lens[salt_idx];\n"
    "    __global const uchar *key = salts + soff;\n"
    "\n"
    "    uint key_block[16];\n"
    "    for (int i = 0; i < 16; i++) key_block[i] = 0;\n"
    "    if (klen > 64) {\n"
    "        uint kstate[8] = { SHA224_IV0,SHA224_IV1,SHA224_IV2,SHA224_IV3,\n"
    "                           SHA224_IV4,SHA224_IV5,SHA224_IV6,SHA224_IV7 };\n"
    "        uint M[16]; for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        S_copy_bytes(M, 0, key, (klen < 64) ? klen : 64);\n"
    "        if (klen <= 55) { S_set_byte(M, klen, 0x80); M[15] = klen * 8; }\n"
    "        sha256_block(kstate, M);\n"
    "        if (klen > 55) {\n"
    "            for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "            S_copy_bytes(M, 0, key + 64, klen - 64);\n"
    "            S_set_byte(M, klen - 64, 0x80);\n"
    "            M[15] = klen * 8;\n"
    "            sha256_block(kstate, M);\n"
    "        }\n"
    "        for (int i = 0; i < 7; i++) key_block[i] = bswap32(kstate[i]);\n"
    "        klen = 28;\n"
    "    } else {\n"
    "        for (int i = 0; i < klen; i++)\n"
    "            key_block[i >> 2] |= ((uint)key[i]) << ((i & 3) << 3);\n"
    "    }\n"
    "\n"
    "    uint ipad[16], M[16];\n"
    "    for (int i = 0; i < 16; i++) ipad[i] = key_block[i] ^ 0x36363636u;\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap32(ipad[i]);\n"
    "    uint istate[8] = { SHA224_IV0,SHA224_IV1,SHA224_IV2,SHA224_IV3,\n"
    "                       SHA224_IV4,SHA224_IV5,SHA224_IV6,SHA224_IV7 };\n"
    "    sha256_block(istate, M);\n"
    "\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    if (plen <= 55) {\n"
    "        S_copy_bytes(M, 0, pass, plen);\n"
    "        S_set_byte(M, plen, 0x80);\n"
    "        M[15] = (64 + plen) * 8;\n"
    "        sha256_block(istate, M);\n"
    "    } else {\n"
    "        S_copy_bytes(M, 0, pass, (plen < 64) ? plen : 64);\n"
    "        if (plen < 64) S_set_byte(M, plen, 0x80);\n"
    "        sha256_block(istate, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int rem = plen - 64;\n"
    "        if (rem > 0) S_copy_bytes(M, 0, pass + 64, rem);\n"
    "        if (plen >= 64) S_set_byte(M, (rem > 0) ? rem : 0, 0x80);\n"
    "        M[15] = (64 + plen) * 8;\n"
    "        sha256_block(istate, M);\n"
    "    }\n"
    "\n"
    "    /* Outer: SHA224(opad || 28-byte inner_hash) */\n"
    "    uint opad_block[16];\n"
    "    for (int i = 0; i < 16; i++) opad_block[i] = key_block[i] ^ 0x5c5c5c5cu;\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap32(opad_block[i]);\n"
    "    uint ostate[8] = { SHA224_IV0,SHA224_IV1,SHA224_IV2,SHA224_IV3,\n"
    "                       SHA224_IV4,SHA224_IV5,SHA224_IV6,SHA224_IV7 };\n"
    "    sha256_block(ostate, M);\n"
    "\n"
    "    for (int i = 0; i < 7; i++) M[i] = istate[i];  /* 28 bytes BE */\n"
    "    M[7] = 0x80000000u;  /* 0x80 at byte 28 */\n"
    "    for (int i = 8; i < 15; i++) M[i] = 0;\n"
    "    M[15] = (64 + 28) * 8;  /* 736 */\n"
    "    sha256_block(ostate, M);\n"
    "\n"
    "    uint h[8];\n"
    "    for (int i = 0; i < 8; i++) h[i] = bswap32(ostate[i]);\n"
    "\n"
    "    if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 11;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx; hits[base+2] = 1;\n"
    "            for (int i = 0; i < 8; i++) hits[base+3+i] = h[i];\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "__kernel void hmac_sha224_kpass_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int klen = hexlens[word_idx];\n"
    "    __global const uchar *key = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int mlen = salt_lens[salt_idx];\n"
    "    __global const uchar *msg = salts + soff;\n"
    "\n"
    "    uint key_block[16];\n"
    "    for (int i = 0; i < 16; i++) key_block[i] = 0;\n"
    "    if (klen > 64) {\n"
    "        uint kstate[8] = { SHA224_IV0,SHA224_IV1,SHA224_IV2,SHA224_IV3,\n"
    "                           SHA224_IV4,SHA224_IV5,SHA224_IV6,SHA224_IV7 };\n"
    "        uint M[16]; for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        S_copy_bytes(M, 0, key, (klen < 64) ? klen : 64);\n"
    "        if (klen <= 55) { S_set_byte(M, klen, 0x80); M[15] = klen * 8; }\n"
    "        sha256_block(kstate, M);\n"
    "        if (klen > 55) {\n"
    "            for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "            S_copy_bytes(M, 0, key + 64, klen - 64);\n"
    "            S_set_byte(M, klen - 64, 0x80);\n"
    "            M[15] = klen * 8;\n"
    "            sha256_block(kstate, M);\n"
    "        }\n"
    "        for (int i = 0; i < 7; i++) key_block[i] = bswap32(kstate[i]);\n"
    "        klen = 28;\n"
    "    } else {\n"
    "        for (int i = 0; i < klen; i++)\n"
    "            key_block[i >> 2] |= ((uint)key[i]) << ((i & 3) << 3);\n"
    "    }\n"
    "\n"
    "    uint ipad[16], M[16];\n"
    "    for (int i = 0; i < 16; i++) ipad[i] = key_block[i] ^ 0x36363636u;\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap32(ipad[i]);\n"
    "    uint istate[8] = { SHA224_IV0,SHA224_IV1,SHA224_IV2,SHA224_IV3,\n"
    "                       SHA224_IV4,SHA224_IV5,SHA224_IV6,SHA224_IV7 };\n"
    "    sha256_block(istate, M);\n"
    "\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    if (mlen <= 55) {\n"
    "        S_copy_bytes(M, 0, msg, mlen);\n"
    "        S_set_byte(M, mlen, 0x80);\n"
    "        M[15] = (64 + mlen) * 8;\n"
    "        sha256_block(istate, M);\n"
    "    } else {\n"
    "        S_copy_bytes(M, 0, msg, (mlen < 64) ? mlen : 64);\n"
    "        if (mlen < 64) S_set_byte(M, mlen, 0x80);\n"
    "        sha256_block(istate, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int rem = mlen - 64;\n"
    "        if (rem > 0) S_copy_bytes(M, 0, msg + 64, rem);\n"
    "        if (mlen >= 64) S_set_byte(M, (rem > 0) ? rem : 0, 0x80);\n"
    "        M[15] = (64 + mlen) * 8;\n"
    "        sha256_block(istate, M);\n"
    "    }\n"
    "\n"
    "    uint opad_block[16];\n"
    "    for (int i = 0; i < 16; i++) opad_block[i] = key_block[i] ^ 0x5c5c5c5cu;\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap32(opad_block[i]);\n"
    "    uint ostate[8] = { SHA224_IV0,SHA224_IV1,SHA224_IV2,SHA224_IV3,\n"
    "                       SHA224_IV4,SHA224_IV5,SHA224_IV6,SHA224_IV7 };\n"
    "    sha256_block(ostate, M);\n"
    "\n"
    "    for (int i = 0; i < 7; i++) M[i] = istate[i];\n"
    "    M[7] = 0x80000000u;\n"
    "    for (int i = 8; i < 15; i++) M[i] = 0;\n"
    "    M[15] = (64 + 28) * 8;\n"
    "    sha256_block(ostate, M);\n"
    "\n"
    "    uint h[8];\n"
    "    for (int i = 0; i < 8; i++) h[i] = bswap32(ostate[i]);\n"
    "\n"
    "    if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 11;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx; hits[base+2] = 1;\n"
    "            for (int i = 0; i < 8; i++) hits[base+3+i] = h[i];\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
;
