/* Auto-generated from gpu_rmd160unsalted.cl -- do not edit */
static const char gpu_rmd160unsalted_str[] =
    "/* gpu_rmd160unsalted.cl — Pre-padded unsalted RIPEMD-160 with mask expansion\n"
    " *\n"
    " * Input: 4096 pre-padded 64-byte M[] blocks in passbuf (word_stride=64).\n"
    " *   Packed by gpu_try_pack_unsalted() in little-endian format:\n"
    " *   password at offset n_prepend, 0x80 padding, M[14]=bitlen (LE).\n"
    " *   RIPEMD-160 is native little-endian — no byte-swap needed.\n"
    " *\n"
    " * Dispatch: num_words × num_masks threads.\n"
    " *   word_idx = tid / num_masks, mask_idx = mask_start + (tid % num_masks)\n"
    " *\n"
    " * Hit stride: 6 (word_idx, mask_idx, h0, h1, h2, h3)\n"
    " */\n"
    "\n"
    "/* ---- RIPEMD-160 boolean functions ---- */\n"
    "\n"
    "#define RMD_F1(x, y, z) ((x) ^ (y) ^ (z))\n"
    "#define RMD_F2(x, y, z) ((((y) ^ (z)) & (x)) ^ (z))\n"
    "#define RMD_F3(x, y, z) (((x) | ~(y)) ^ (z))\n"
    "#define RMD_F4(x, y, z) ((((x) ^ (y)) & (z)) ^ (y))\n"
    "#define RMD_F5(x, y, z) ((x) ^ ((y) | ~(z)))\n"
    "\n"
    "#define RMD_STEP(FUNC, A, B, C, D, E, X, S, K) \\\n"
    "    (A) += FUNC((B), (C), (D)) + (X) + K; \\\n"
    "    (A) = rotate((A), (uint)(S)) + (E); \\\n"
    "    (C) = rotate((C), (uint)10);\n"
    "\n"
    "#define L1(A, B, C, D, E, X, S) RMD_STEP(RMD_F1, A, B, C, D, E, X, S, 0u)\n"
    "#define L2(A, B, C, D, E, X, S) RMD_STEP(RMD_F2, A, B, C, D, E, X, S, 0x5a827999u)\n"
    "#define L3(A, B, C, D, E, X, S) RMD_STEP(RMD_F3, A, B, C, D, E, X, S, 0x6ed9eba1u)\n"
    "#define L4(A, B, C, D, E, X, S) RMD_STEP(RMD_F4, A, B, C, D, E, X, S, 0x8f1bbcdcu)\n"
    "#define L5(A, B, C, D, E, X, S) RMD_STEP(RMD_F5, A, B, C, D, E, X, S, 0xa953fd4eu)\n"
    "\n"
    "#define R1(A, B, C, D, E, X, S) RMD_STEP(RMD_F5, A, B, C, D, E, X, S, 0x50a28be6u)\n"
    "#define R2(A, B, C, D, E, X, S) RMD_STEP(RMD_F4, A, B, C, D, E, X, S, 0x5c4dd124u)\n"
    "#define R3(A, B, C, D, E, X, S) RMD_STEP(RMD_F3, A, B, C, D, E, X, S, 0x6d703ef3u)\n"
    "#define R4(A, B, C, D, E, X, S) RMD_STEP(RMD_F2, A, B, C, D, E, X, S, 0x7a6d76e9u)\n"
    "#define R5(A, B, C, D, E, X, S) RMD_STEP(RMD_F1, A, B, C, D, E, X, S, 0u)\n"
    "\n"
    "void rmd160_block(uint *hash, const uint *X)\n"
    "{\n"
    "    uint A = hash[0], B = hash[1], C = hash[2],\n"
    "         D = hash[3], E = hash[4];\n"
    "    uint a1, b1, c1, d1, e1;\n"
    "\n"
    "    L1(A, B, C, D, E, X[ 0], 11); L1(E, A, B, C, D, X[ 1], 14);\n"
    "    L1(D, E, A, B, C, X[ 2], 15); L1(C, D, E, A, B, X[ 3], 12);\n"
    "    L1(B, C, D, E, A, X[ 4],  5); L1(A, B, C, D, E, X[ 5],  8);\n"
    "    L1(E, A, B, C, D, X[ 6],  7); L1(D, E, A, B, C, X[ 7],  9);\n"
    "    L1(C, D, E, A, B, X[ 8], 11); L1(B, C, D, E, A, X[ 9], 13);\n"
    "    L1(A, B, C, D, E, X[10], 14); L1(E, A, B, C, D, X[11], 15);\n"
    "    L1(D, E, A, B, C, X[12],  6); L1(C, D, E, A, B, X[13],  7);\n"
    "    L1(B, C, D, E, A, X[14],  9); L1(A, B, C, D, E, X[15],  8);\n"
    "\n"
    "    L2(E, A, B, C, D, X[ 7],  7); L2(D, E, A, B, C, X[ 4],  6);\n"
    "    L2(C, D, E, A, B, X[13],  8); L2(B, C, D, E, A, X[ 1], 13);\n"
    "    L2(A, B, C, D, E, X[10], 11); L2(E, A, B, C, D, X[ 6],  9);\n"
    "    L2(D, E, A, B, C, X[15],  7); L2(C, D, E, A, B, X[ 3], 15);\n"
    "    L2(B, C, D, E, A, X[12],  7); L2(A, B, C, D, E, X[ 0], 12);\n"
    "    L2(E, A, B, C, D, X[ 9], 15); L2(D, E, A, B, C, X[ 5],  9);\n"
    "    L2(C, D, E, A, B, X[ 2], 11); L2(B, C, D, E, A, X[14],  7);\n"
    "    L2(A, B, C, D, E, X[11], 13); L2(E, A, B, C, D, X[ 8], 12);\n"
    "\n"
    "    L3(D, E, A, B, C, X[ 3], 11); L3(C, D, E, A, B, X[10], 13);\n"
    "    L3(B, C, D, E, A, X[14],  6); L3(A, B, C, D, E, X[ 4],  7);\n"
    "    L3(E, A, B, C, D, X[ 9], 14); L3(D, E, A, B, C, X[15],  9);\n"
    "    L3(C, D, E, A, B, X[ 8], 13); L3(B, C, D, E, A, X[ 1], 15);\n"
    "    L3(A, B, C, D, E, X[ 2], 14); L3(E, A, B, C, D, X[ 7],  8);\n"
    "    L3(D, E, A, B, C, X[ 0], 13); L3(C, D, E, A, B, X[ 6],  6);\n"
    "    L3(B, C, D, E, A, X[13],  5); L3(A, B, C, D, E, X[11], 12);\n"
    "    L3(E, A, B, C, D, X[ 5],  7); L3(D, E, A, B, C, X[12],  5);\n"
    "\n"
    "    L4(C, D, E, A, B, X[ 1], 11); L4(B, C, D, E, A, X[ 9], 12);\n"
    "    L4(A, B, C, D, E, X[11], 14); L4(E, A, B, C, D, X[10], 15);\n"
    "    L4(D, E, A, B, C, X[ 0], 14); L4(C, D, E, A, B, X[ 8], 15);\n"
    "    L4(B, C, D, E, A, X[12],  9); L4(A, B, C, D, E, X[ 4],  8);\n"
    "    L4(E, A, B, C, D, X[13],  9); L4(D, E, A, B, C, X[ 3], 14);\n"
    "    L4(C, D, E, A, B, X[ 7],  5); L4(B, C, D, E, A, X[15],  6);\n"
    "    L4(A, B, C, D, E, X[14],  8); L4(E, A, B, C, D, X[ 5],  6);\n"
    "    L4(D, E, A, B, C, X[ 6],  5); L4(C, D, E, A, B, X[ 2], 12);\n"
    "\n"
    "    L5(B, C, D, E, A, X[ 4],  9); L5(A, B, C, D, E, X[ 0], 15);\n"
    "    L5(E, A, B, C, D, X[ 5],  5); L5(D, E, A, B, C, X[ 9], 11);\n"
    "    L5(C, D, E, A, B, X[ 7],  6); L5(B, C, D, E, A, X[12],  8);\n"
    "    L5(A, B, C, D, E, X[ 2], 13); L5(E, A, B, C, D, X[10], 12);\n"
    "    L5(D, E, A, B, C, X[14],  5); L5(C, D, E, A, B, X[ 1], 12);\n"
    "    L5(B, C, D, E, A, X[ 3], 13); L5(A, B, C, D, E, X[ 8], 14);\n"
    "    L5(E, A, B, C, D, X[11], 11); L5(D, E, A, B, C, X[ 6],  8);\n"
    "    L5(C, D, E, A, B, X[15],  5); L5(B, C, D, E, A, X[13],  6);\n"
    "\n"
    "    a1 = A; b1 = B; c1 = C; d1 = D; e1 = E;\n"
    "\n"
    "    A = hash[0]; B = hash[1]; C = hash[2]; D = hash[3]; E = hash[4];\n"
    "\n"
    "    R1(A, B, C, D, E, X[ 5],  8); R1(E, A, B, C, D, X[14],  9);\n"
    "    R1(D, E, A, B, C, X[ 7],  9); R1(C, D, E, A, B, X[ 0], 11);\n"
    "    R1(B, C, D, E, A, X[ 9], 13); R1(A, B, C, D, E, X[ 2], 15);\n"
    "    R1(E, A, B, C, D, X[11], 15); R1(D, E, A, B, C, X[ 4],  5);\n"
    "    R1(C, D, E, A, B, X[13],  7); R1(B, C, D, E, A, X[ 6],  7);\n"
    "    R1(A, B, C, D, E, X[15],  8); R1(E, A, B, C, D, X[ 8], 11);\n"
    "    R1(D, E, A, B, C, X[ 1], 14); R1(C, D, E, A, B, X[10], 14);\n"
    "    R1(B, C, D, E, A, X[ 3], 12); R1(A, B, C, D, E, X[12],  6);\n"
    "\n"
    "    R2(E, A, B, C, D, X[ 6],  9); R2(D, E, A, B, C, X[11], 13);\n"
    "    R2(C, D, E, A, B, X[ 3], 15); R2(B, C, D, E, A, X[ 7],  7);\n"
    "    R2(A, B, C, D, E, X[ 0], 12); R2(E, A, B, C, D, X[13],  8);\n"
    "    R2(D, E, A, B, C, X[ 5],  9); R2(C, D, E, A, B, X[10], 11);\n"
    "    R2(B, C, D, E, A, X[14],  7); R2(A, B, C, D, E, X[15],  7);\n"
    "    R2(E, A, B, C, D, X[ 8], 12); R2(D, E, A, B, C, X[12],  7);\n"
    "    R2(C, D, E, A, B, X[ 4],  6); R2(B, C, D, E, A, X[ 9], 15);\n"
    "    R2(A, B, C, D, E, X[ 1], 13); R2(E, A, B, C, D, X[ 2], 11);\n"
    "\n"
    "    R3(D, E, A, B, C, X[15],  9); R3(C, D, E, A, B, X[ 5],  7);\n"
    "    R3(B, C, D, E, A, X[ 1], 15); R3(A, B, C, D, E, X[ 3], 11);\n"
    "    R3(E, A, B, C, D, X[ 7],  8); R3(D, E, A, B, C, X[14],  6);\n"
    "    R3(C, D, E, A, B, X[ 6],  6); R3(B, C, D, E, A, X[ 9], 14);\n"
    "    R3(A, B, C, D, E, X[11], 12); R3(E, A, B, C, D, X[ 8], 13);\n"
    "    R3(D, E, A, B, C, X[12],  5); R3(C, D, E, A, B, X[ 2], 14);\n"
    "    R3(B, C, D, E, A, X[10], 13); R3(A, B, C, D, E, X[ 0], 13);\n"
    "    R3(E, A, B, C, D, X[ 4],  7); R3(D, E, A, B, C, X[13],  5);\n"
    "\n"
    "    R4(C, D, E, A, B, X[ 8], 15); R4(B, C, D, E, A, X[ 6],  5);\n"
    "    R4(A, B, C, D, E, X[ 4],  8); R4(E, A, B, C, D, X[ 1], 11);\n"
    "    R4(D, E, A, B, C, X[ 3], 14); R4(C, D, E, A, B, X[11], 14);\n"
    "    R4(B, C, D, E, A, X[15],  6); R4(A, B, C, D, E, X[ 0], 14);\n"
    "    R4(E, A, B, C, D, X[ 5],  6); R4(D, E, A, B, C, X[12],  9);\n"
    "    R4(C, D, E, A, B, X[ 2], 12); R4(B, C, D, E, A, X[13],  9);\n"
    "    R4(A, B, C, D, E, X[ 9], 12); R4(E, A, B, C, D, X[ 7],  5);\n"
    "    R4(D, E, A, B, C, X[10], 15); R4(C, D, E, A, B, X[14],  8);\n"
    "\n"
    "    R5(B, C, D, E, A, X[12],  8); R5(A, B, C, D, E, X[15],  5);\n"
    "    R5(E, A, B, C, D, X[10], 12); R5(D, E, A, B, C, X[ 4],  9);\n"
    "    R5(C, D, E, A, B, X[ 1], 12); R5(B, C, D, E, A, X[ 5],  5);\n"
    "    R5(A, B, C, D, E, X[ 8], 14); R5(E, A, B, C, D, X[ 7],  6);\n"
    "    R5(D, E, A, B, C, X[ 6],  8); R5(C, D, E, A, B, X[ 2], 13);\n"
    "    R5(B, C, D, E, A, X[13],  6); R5(A, B, C, D, E, X[14],  5);\n"
    "    R5(E, A, B, C, D, X[ 0], 15); R5(D, E, A, B, C, X[ 3], 13);\n"
    "    R5(C, D, E, A, B, X[ 9], 11); R5(B, C, D, E, A, X[11], 11);\n"
    "\n"
    "    D += c1 + hash[1];\n"
    "    hash[1] = hash[2] + d1 + E;\n"
    "    hash[2] = hash[3] + e1 + A;\n"
    "    hash[3] = hash[4] + a1 + B;\n"
    "    hash[4] = hash[0] + b1 + C;\n"
    "    hash[0] = D;\n"
    "}\n"
    "\n"
    "__kernel void rmd160_unsalted_batch(\n"
    "    __global const uint *words,\n"
    "    __global const ushort *unused_lens,\n"
    "    __global const uchar *mask_desc,\n"
    "    __global const uint *unused1, __global const ushort *unused2,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    uint mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    /* Load pre-padded M[] block (16 uint32 = 64 bytes, LE from host) */\n"
    "    __global const uint *src = words + word_idx * 16;\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    /* Fill mask positions into M[] — LE words */\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint append_combos = 1;\n"
    "        for (uint i = 0; i < n_app; i++)\n"
    "            append_combos *= mask_desc[n_pre + i];\n"
    "\n"
    "        uint prepend_idx = mask_idx / append_combos;\n"
    "        uint append_idx = mask_idx % append_combos;\n"
    "\n"
    "        if (n_pre > 0) {\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uint n_total_m = n_pre + n_app;\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                M[i >> 2] = (M[i >> 2] & ~(0xFFu << ((i & 3) << 3)))\n"
    "                           | ((uint)ch << ((i & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "\n"
    "        if (n_app > 0) {\n"
    "            int total_len = M[14] >> 3;\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint aidx = append_idx;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                int pos_idx = n_pre + i;\n"
    "                uint sz = mask_desc[pos_idx];\n"
    "                uint n_total_m = n_pre + n_app;\n"
    "                uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                aidx /= sz;\n"
    "                int pos = app_start + i;\n"
    "                M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                             | ((uint)ch << ((pos & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* RIPEMD-160 is native LE — M[] is already in correct byte order.\n"
    "     * Padding: 0x80 after message, bit-length at M[14] (LE) — same as MD5. */\n"
    "    uint state[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "    rmd160_block(state, M);\n"
    "\n"
    "    /* RMD160 output is LE — no bswap needed for compact table probe */\n"
    "    uint hx = state[0], hy = state[1], hz = state[2], hw = state[3];\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 6;\n"
    "            hits[base]   = word_idx;\n"
    "            hits[base+1] = mask_idx;\n"
    "            hits[base+2] = hx;\n"
    "            hits[base+3] = hy;\n"
    "            hits[base+4] = hz;\n"
    "            hits[base+5] = hw;\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
;
