/* Auto-generated from gpu_sha1unsalted.cl -- do not edit */
static const char gpu_sha1unsalted_str[] =
    "/* gpu_sha1unsalted.cl — Pre-padded unsalted SHA1 with mask expansion\n"
    " *\n"
    " * Input: 4096 pre-padded 64-byte M[] blocks in passbuf (word_stride=64).\n"
    " *   Packed by gpu_try_pack_unsalted() in little-endian format:\n"
    " *   password at offset n_prepend, 0x80 padding, M[14]=bitlen (LE).\n"
    " *   Kernel byte-swaps to big-endian before SHA1 compress.\n"
    " *\n"
    " * Dispatch: num_words × num_masks threads.\n"
    " *   word_idx = tid / num_masks, mask_idx = mask_start + (tid % num_masks)\n"
    " *\n"
    " * Hit stride: 6 (word_idx, mask_idx, h0, h1, h2, h3)\n"
    " */\n"
    "\n"
    "/* Charset tables for mask expansion */\n"
    "\n"
    "uint bswap32(uint x) {\n"
    "    return ((x >> 24) & 0xffu) | ((x >> 8) & 0xff00u) |\n"
    "           ((x << 8) & 0xff0000u) | ((x << 24) & 0xff000000u);\n"
    "}\n"
    "\n"
    "/* SHA1 block function — M[] must be big-endian uint32 words */\n"
    "void sha1_compress(uint *state, uint *M) {\n"
    "    uint W[80];\n"
    "    for (int i = 0; i < 16; i++) W[i] = M[i];\n"
    "    for (int i = 16; i < 80; i++)\n"
    "        W[i] = rotate(W[i-3] ^ W[i-8] ^ W[i-14] ^ W[i-16], (uint)1);\n"
    "\n"
    "    uint a = state[0], b = state[1], c = state[2], d = state[3], e = state[4];\n"
    "    uint t;\n"
    "    for (int i = 0; i < 20; i++) {\n"
    "        t = rotate(a, (uint)5) + ((b & c) | (~b & d)) + e + 0x5A827999u + W[i];\n"
    "        e = d; d = c; c = rotate(b, (uint)30); b = a; a = t;\n"
    "    }\n"
    "    for (int i = 20; i < 40; i++) {\n"
    "        t = rotate(a, (uint)5) + (b ^ c ^ d) + e + 0x6ED9EBA1u + W[i];\n"
    "        e = d; d = c; c = rotate(b, (uint)30); b = a; a = t;\n"
    "    }\n"
    "    for (int i = 40; i < 60; i++) {\n"
    "        t = rotate(a, (uint)5) + ((b & c) | (b & d) | (c & d)) + e + 0x8F1BBCDCu + W[i];\n"
    "        e = d; d = c; c = rotate(b, (uint)30); b = a; a = t;\n"
    "    }\n"
    "    for (int i = 60; i < 80; i++) {\n"
    "        t = rotate(a, (uint)5) + (b ^ c ^ d) + e + 0xCA62C1D6u + W[i];\n"
    "        e = d; d = c; c = rotate(b, (uint)30); b = a; a = t;\n"
    "    }\n"
    "    state[0] += a; state[1] += b; state[2] += c; state[3] += d; state[4] += e;\n"
    "}\n"
    "\n"
    "__kernel void sha1_unsalted_batch(\n"
    "    __global const uint *words,          /* pre-padded M[] blocks, 16 uint32 each */\n"
    "    __global const ushort *unused_lens,  /* not used — total length is in M[14]/8 */\n"
    "    __global const uchar *mask_desc,     /* mask descriptor: [prepend IDs][append IDs] */\n"
    "    __global const uint *unused1, __global const ushort *unused2,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    uint mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    /* Load pre-padded M[] block (16 uint32 = 64 bytes, little-endian from host) */\n"
    "    __global const uint *src = words + word_idx * 16;\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    /* Fill mask positions into M[] — operates on LE words (same as MD5 kernel) */\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint append_combos = 1;\n"
    "        for (uint i = 0; i < n_app; i++)\n"
    "            append_combos *= mask_desc[n_pre + i];\n"
    "\n"
    "        uint prepend_idx = mask_idx / append_combos;\n"
    "        uint append_idx = mask_idx % append_combos;\n"
    "\n"
    "        if (n_pre > 0) {\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uint n_total_m = n_pre + n_app;\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                M[i >> 2] = (M[i >> 2] & ~(0xFFu << ((i & 3) << 3)))\n"
    "                           | ((uint)ch << ((i & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "\n"
    "        if (n_app > 0) {\n"
    "            int total_len = M[14] >> 3;\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint aidx = append_idx;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                int pos_idx = n_pre + i;\n"
    "                uint sz = mask_desc[pos_idx];\n"
    "                uint n_total_m = n_pre + n_app;\n"
    "                uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                aidx /= sz;\n"
    "                int pos = app_start + i;\n"
    "                M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                             | ((uint)ch << ((pos & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Save bit-length from LE M[14] before byte-swap */\n"
    "    uint bitlen = M[14];\n"
    "\n"
    "    /* Convert M[] from little-endian to big-endian for SHA1 */\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap32(M[i]);\n"
    "\n"
    "    /* Fix up padding: SHA1 stores 64-bit big-endian bit count at M[14..15] */\n"
    "    M[14] = 0;\n"
    "    M[15] = bitlen;\n"
    "\n"
    "    /* SHA1 compress */\n"
    "    uint state[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "    sha1_compress(state, M);\n"
    "\n"
    "    /* Byte-swap state to LE for compact table probe */\n"
    "    uint hx = bswap32(state[0]), hy = bswap32(state[1]);\n"
    "    uint hz = bswap32(state[2]), hw = bswap32(state[3]);\n"
    "\n"
    "    /* Probe compact table (first 128 bits sufficient) */\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 6;\n"
    "            hits[base]   = word_idx;\n"
    "            hits[base+1] = mask_idx;\n"
    "            hits[base+2] = hx;\n"
    "            hits[base+3] = hy;\n"
    "            hits[base+4] = hz;\n"
    "            hits[base+5] = hw;\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- SQL5: sha1(sha1(pass)) — hashcat mode 300 ----\n"
    " * Double SHA1 with binary iteration. Same pre-padded block for first SHA1,\n"
    " * then SHA1 of 20-byte binary result (fixed single-block padding).\n"
    " * Hit stride: 6 (word_idx, mask_idx, hx, hy, hz, hw)\n"
    " */\n"
    "__kernel void sql5_unsalted_batch(\n"
    "    __global const uint *words,\n"
    "    __global const ushort *unused_lens,\n"
    "    __global const uchar *mask_desc,\n"
    "    __global const uint *unused1, __global const ushort *unused2,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    uint mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    __global const uint *src = words + word_idx * 16;\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint append_combos = 1;\n"
    "        for (uint i = 0; i < n_app; i++)\n"
    "            append_combos *= mask_desc[n_pre + i];\n"
    "        uint prepend_idx = mask_idx / append_combos;\n"
    "        uint append_idx = mask_idx % append_combos;\n"
    "        if (n_pre > 0) {\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uint n_total_m = n_pre + n_app;\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                M[i >> 2] = (M[i >> 2] & ~(0xFFu << ((i & 3) << 3)))\n"
    "                           | ((uint)ch << ((i & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "        if (n_app > 0) {\n"
    "            int total_len = M[14] >> 3;\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint aidx = append_idx;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                int pos_idx = n_pre + i;\n"
    "                uint sz = mask_desc[pos_idx];\n"
    "                uint n_total_m = n_pre + n_app;\n"
    "                uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                aidx /= sz;\n"
    "                int pos = app_start + i;\n"
    "                M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                             | ((uint)ch << ((pos & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* First SHA1(password) */\n"
    "    uint bitlen = M[14];\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap32(M[i]);\n"
    "    M[14] = 0; M[15] = bitlen;\n"
    "\n"
    "    uint state[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "    sha1_compress(state, M);\n"
    "\n"
    "    /* Second SHA1(20-byte binary): fixed padding block */\n"
    "    for (int i = 0; i < 5; i++) M[i] = state[i];  /* already BE */\n"
    "    M[5] = 0x80000000u;\n"
    "    for (int i = 6; i < 15; i++) M[i] = 0;\n"
    "    M[15] = 160;  /* 20 bytes * 8 bits */\n"
    "\n"
    "    state[0] = 0x67452301u; state[1] = 0xEFCDAB89u;\n"
    "    state[2] = 0x98BADCFEu; state[3] = 0x10325476u; state[4] = 0xC3D2E1F0u;\n"
    "    sha1_compress(state, M);\n"
    "\n"
    "    uint hx = bswap32(state[0]), hy = bswap32(state[1]);\n"
    "    uint hz = bswap32(state[2]), hw = bswap32(state[3]);\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 6;\n"
    "            hits[base]   = word_idx;\n"
    "            hits[base+1] = mask_idx;\n"
    "            hits[base+2] = hx;\n"
    "            hits[base+3] = hy;\n"
    "            hits[base+4] = hz;\n"
    "            hits[base+5] = hw;\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
;
