/* Auto-generated from gpu_phpbb3.cl -- do not edit */
static const char gpu_phpbb3_str[] =
    "/* M_copy_bytes, M_set_byte provided by gpu_common.cl */\n"
    "\n"
    "/* ---- PHPBB3/phpass kernel (e455): MD5 iterated 2^N times ---- */\n"
    "/* Salt buffer has \"$H$Csalt8chr\" (12 bytes). Iteration count from salt[3].\n"
    " * Algorithm: MD5(salt + pass), then N iterations of MD5(hash_binary + pass).\n"
    " * Password max 39 bytes (single MD5 block for 16 + 39 = 55). */\n"
    "__constant uchar phpitoa64_k[] = \"./0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz\";\n"
    "\n"
    "__kernel void phpbb3_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off, __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    __global const uchar *salt_data = salts + soff;\n"
    "\n"
    "    /* Decode iteration count from salt[3] */\n"
    "    uchar ic = salt_data[3];\n"
    "    int log2count = 0;\n"
    "    for (int k = 0; k < 64; k++) { if (phpitoa64_k[k] == ic) { log2count = k; break; } }\n"
    "    uint count = 1u << log2count;\n"
    "\n"
    "    /* Step 1: MD5(salt[4..11] + password) — salt is 8 bytes */\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    M_copy_bytes(M, 0, salt_data + 4, 8);\n"
    "    M_copy_bytes(M, 8, pass, plen);\n"
    "    int total = 8 + plen;\n"
    "    M_set_byte(M, total, 0x80);\n"
    "    M[14] = total * 8;\n"
    "    uint hx = 0x67452301, hy = 0xEFCDAB89, hz = 0x98BADCFE, hw = 0x10325476;\n"
    "    md5_block(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "    /* Step 2: N iterations of MD5(hash_binary[16] + password[plen]) */\n"
    "    /* Pre-pack M[] with password, padding, length — constant across iterations */\n"
    "    total = 16 + plen;\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    M_copy_bytes(M, 16, pass, plen);\n"
    "    M_set_byte(M, total, 0x80);\n"
    "    M[14] = total * 8;\n"
    "    /* Iteration loop: only M[0..3] change (the hash digest) */\n"
    "    for (uint ic2 = 0; ic2 < count; ic2++) {\n"
    "        M[0] = hx; M[1] = hy; M[2] = hz; M[3] = hw;\n"
    "        hx = 0x67452301; hy = 0xEFCDAB89; hz = 0x98BADCFE; hw = 0x10325476;\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "    }\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        EMIT_HIT_4(hits, hit_count, params.max_hits, word_idx, salt_idx, 1u, hx, hy, hz, hw)\n"
    "    }\n"
    "}\n"
;
