/* Auto-generated from gpu_sha512unsalted.cl -- do not edit */
static const char gpu_sha512unsalted_str[] =
    "/* gpu_sha512unsalted.cl — Pre-padded unsalted SHA512 with mask expansion\n"
    " *\n"
    " * Input: 2048 pre-padded 128-byte blocks in passbuf (word_stride=128).\n"
    " *   Packed by gpu_try_pack_unsalted() in little-endian format:\n"
    " *   password at offset n_prepend, 0x80 padding, bitlen as uint32 at byte offset 120.\n"
    " *   Kernel byte-swaps 16 × uint64 words to big-endian before SHA512 compress.\n"
    " *\n"
    " * Dispatch: num_words × num_masks threads.\n"
    " * Hit stride: 6 (word_idx, mask_idx, h0_lo, h0_hi, h1_lo, h1_hi)\n"
    " *\n"
    " * Primitives (hex_byte_be64, sha512_to_hex_lc, bswap64, K512, rotr64,\n"
    " * sha512_block) provided by gpu_common.cl\n"
    " */\n"
    "\n"
    "__kernel void sha512_unsalted_batch(\n"
    "    __global const uchar *words,         /* pre-padded 128-byte blocks */\n"
    "    __global const ushort *unused_lens,\n"
    "    __global const uchar *mask_desc,\n"
    "    __global const uint *unused1, __global const ushort *unused2,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    ulong mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    /* Load pre-padded block (16 uint64 = 128 bytes, little-endian from host) */\n"
    "    __global const ulong *src = (__global const ulong *)(words + word_idx * 128);\n"
    "    ulong M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    /* Fill mask positions — LE bytes within uint64 words */\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint n_total_m = n_pre + n_app;\n"
    "\n"
    "        if (n_pre > 0) {\n"
    "            uint append_combos = 1;\n"
    "            for (uint i = 0; i < n_app; i++)\n"
    "                append_combos *= mask_desc[n_pre + i];\n"
    "            uint prepend_idx = (uint)(mask_idx / append_combos);\n"
    "            uint append_idx = (uint)(mask_idx % append_combos);\n"
    "\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                int wi = i >> 3;\n"
    "                int bi = (i & 7) << 3;\n"
    "                M[wi] = (M[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "            }\n"
    "\n"
    "            if (n_app > 0) {\n"
    "                int total_len = (int)(M[15] & 0xFFFFFFFFUL);\n"
    "                int app_start = total_len - (int)n_app;\n"
    "                uint aidx = append_idx;\n"
    "                for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                    int pos_idx = n_pre + i;\n"
    "                    uint sz = mask_desc[pos_idx];\n"
    "                    uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                    aidx /= sz;\n"
    "                    int pos = app_start + i;\n"
    "                    int wi = pos >> 3;\n"
    "                    int bi = (pos & 7) << 3;\n"
    "                    M[wi] = (M[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "                }\n"
    "            }\n"
    "        } else {\n"
    "            /* Append-only (brute-force): host pre-decomposes mask_start into\n"
    "             * per-position base offsets. Kernel does fast uint32 local\n"
    "             * decomposition and adds to base with carry. */\n"
    "            int total_len = (int)(M[15] & 0xFFFFFFFFUL);\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint local_idx = tid % params.num_masks;\n"
    "            uint aidx = local_idx;\n"
    "            uint carry = 0;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uint local_digit = aidx % sz;\n"
    "                aidx /= sz;\n"
    "                uint base_digit = (i < 8)\n"
    "                    ? (uint)((params.mask_base0 >> (i * 8)) & 0xFF)\n"
    "                    : (uint)((params.mask_base1 >> ((i - 8) * 8)) & 0xFF);\n"
    "                uint sum = base_digit + local_digit + carry;\n"
    "                carry = sum / sz;\n"
    "                uint final_digit = sum % sz;\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + final_digit];\n"
    "                int pos = app_start + i;\n"
    "                int wi = pos >> 3;\n"
    "                int bi = (pos & 7) << 3;\n"
    "                M[wi] = (M[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Save bit-length before byte-swap.\n"
    "     * Host stores bitlen as uint32 at byte offset 120 = low 32 bits of M[15] (LE). */\n"
    "    uint bitlen = (uint)(M[15] & 0xFFFFFFFFUL);\n"
    "\n"
    "    /* Convert M[] from little-endian to big-endian for SHA512 */\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap64(M[i]);\n"
    "\n"
    "    /* Fix up padding: SHA512 stores 128-bit big-endian bit count at M[14..15] */\n"
    "    M[14] = 0;\n"
    "    M[15] = (ulong)bitlen;\n"
    "\n"
    "    /* SHA512 compress */\n"
    "    ulong state[8] = {\n"
    "        0x6a09e667f3bcc908UL, 0xbb67ae8584caa73bUL,\n"
    "        0x3c6ef372fe94f82bUL, 0xa54ff53a5f1d36f1UL,\n"
    "        0x510e527fade682d1UL, 0x9b05688c2b3e6c1fUL,\n"
    "        0x1f83d9abfb41bd6bUL, 0x5be0cd19137e2179UL\n"
    "    };\n"
    "    sha512_block(state, M);\n"
    "\n"
    "    uint max_iter = params.max_iter;\n"
    "    /* SHA512: 16 hash words (8 x uint64 -> 16 x uint32).\n"
    "     * hit_stride = 2 + 16 = 18, or 3 + 16 = 19 with iter */\n"
    "    uint hit_stride = (max_iter > 1) ? 19 : 18;\n"
    "\n"
    "    for (uint iter = 1; iter <= max_iter; iter++) {\n"
    "        /* Byte-swap all 8 state words to LE, split into 16 uint32 */\n"
    "        uint h[16];\n"
    "        for (int i = 0; i < 8; i++) {\n"
    "            ulong s = bswap64(state[i]);\n"
    "            h[i*2]   = (uint)s;\n"
    "            h[i*2+1] = (uint)(s >> 32);\n"
    "        }\n"
    "\n"
    "        if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                          params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                          hash_data_buf, hash_data_off,\n"
    "                          overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "            uint slot = atomic_add(hit_count, 1u);\n"
    "            if (slot < params.max_hits) {\n"
    "                uint base = slot * hit_stride;\n"
    "                hits[base]   = word_idx;\n"
    "                hits[base+1] = mask_idx;\n"
    "                int offset = 2;\n"
    "                if (max_iter > 1) { hits[base+2] = iter; offset = 3; }\n"
    "                for (int i = 0; i < 16; i++) hits[base+offset+i] = h[i];\n"
    "                mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "            }\n"
    "        }\n"
    "        if (iter < max_iter) {\n"
    "            /* Hex-encode 8 BE state words into M[0..15] (128 hex chars = full block) */\n"
    "            sha512_to_hex_lc(state, M);\n"
    "            /* First compress: data block */\n"
    "            state[0] = 0x6a09e667f3bcc908UL; state[1] = 0xbb67ae8584caa73bUL;\n"
    "            state[2] = 0x3c6ef372fe94f82bUL; state[3] = 0xa54ff53a5f1d36f1UL;\n"
    "            state[4] = 0x510e527fade682d1UL; state[5] = 0x9b05688c2b3e6c1fUL;\n"
    "            state[6] = 0x1f83d9abfb41bd6bUL; state[7] = 0x5be0cd19137e2179UL;\n"
    "            sha512_block(state, M);\n"
    "            /* Second compress: padding block */\n"
    "            M[0] = 0x8000000000000000UL;\n"
    "            for (int i = 1; i < 15; i++) M[i] = 0;\n"
    "            M[15] = 128 * 8;  /* 128 hex bytes = 1024 bits */\n"
    "            sha512_block(state, M);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* SHA384 — same compress as SHA512, different IV, truncated output (48 bytes) */\n"
    "__kernel void sha384_unsalted_batch(\n"
    "    __global const uchar *words,\n"
    "    __global const ushort *unused_lens,\n"
    "    __global const uchar *mask_desc,\n"
    "    __global const uint *unused1, __global const ushort *unused2,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    ulong mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    __global const ulong *src = (__global const ulong *)(words + word_idx * 128);\n"
    "    ulong M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint n_total_m = n_pre + n_app;\n"
    "\n"
    "        if (n_pre > 0) {\n"
    "            uint append_combos = 1;\n"
    "            for (uint i = 0; i < n_app; i++)\n"
    "                append_combos *= mask_desc[n_pre + i];\n"
    "            uint prepend_idx = (uint)(mask_idx / append_combos);\n"
    "            uint append_idx = (uint)(mask_idx % append_combos);\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                int wi = i >> 3;\n"
    "                int bi = (i & 7) << 3;\n"
    "                M[wi] = (M[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "            }\n"
    "            if (n_app > 0) {\n"
    "                int total_len = (int)(M[15] & 0xFFFFFFFFUL);\n"
    "                int app_start = total_len - (int)n_app;\n"
    "                uint aidx = append_idx;\n"
    "                for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                    int pos_idx = n_pre + i;\n"
    "                    uint sz = mask_desc[pos_idx];\n"
    "                    uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                    aidx /= sz;\n"
    "                    int pos = app_start + i;\n"
    "                    int wi = pos >> 3;\n"
    "                    int bi = (pos & 7) << 3;\n"
    "                    M[wi] = (M[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "                }\n"
    "            }\n"
    "        } else {\n"
    "            /* Append-only (brute-force): host pre-decomposes mask_start into\n"
    "             * per-position base offsets. Kernel does fast uint32 local\n"
    "             * decomposition and adds to base with carry. */\n"
    "            int total_len = (int)(M[15] & 0xFFFFFFFFUL);\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint local_idx = tid % params.num_masks;\n"
    "            uint aidx = local_idx;\n"
    "            uint carry = 0;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uint local_digit = aidx % sz;\n"
    "                aidx /= sz;\n"
    "                uint base_digit = (i < 8)\n"
    "                    ? (uint)((params.mask_base0 >> (i * 8)) & 0xFF)\n"
    "                    : (uint)((params.mask_base1 >> ((i - 8) * 8)) & 0xFF);\n"
    "                uint sum = base_digit + local_digit + carry;\n"
    "                carry = sum / sz;\n"
    "                uint final_digit = sum % sz;\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + final_digit];\n"
    "                int pos = app_start + i;\n"
    "                int wi = pos >> 3;\n"
    "                int bi = (pos & 7) << 3;\n"
    "                M[wi] = (M[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    uint bitlen = (uint)(M[15] & 0xFFFFFFFFUL);\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap64(M[i]);\n"
    "    M[14] = 0;\n"
    "    M[15] = (ulong)bitlen;\n"
    "\n"
    "    ulong state[8] = {\n"
    "        0xcbbb9d5dc1059ed8UL, 0x629a292a367cd507UL,\n"
    "        0x9159015a3070dd17UL, 0x152fecd8f70e5939UL,\n"
    "        0x67332667ffc00b31UL, 0x8eb44a8768581511UL,\n"
    "        0xdb0c2e0d64f98fa7UL, 0x47b5481dbefa4fa4UL\n"
    "    };\n"
    "    sha512_block(state, M);\n"
    "\n"
    "    /* SHA384: 12 hash words (6 x uint64 -> 12 x uint32) */\n"
    "    uint h[12];\n"
    "    for (int i = 0; i < 6; i++) {\n"
    "        ulong s = bswap64(state[i]);\n"
    "        h[i*2]   = (uint)s;\n"
    "        h[i*2+1] = (uint)(s >> 32);\n"
    "    }\n"
    "\n"
    "    if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 14;  /* 2 + 12 */\n"
    "            hits[base]   = word_idx;\n"
    "            hits[base+1] = mask_idx;\n"
    "            for (int i = 0; i < 12; i++) hits[base+2+i] = h[i];\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* SHA384RAW: sha384(sha384_binary(pass)) — binary iteration.\n"
    " * First SHA384(pass), then iterate sha384(48-byte binary).\n"
    " * Hit stride: 14 (word_idx, mask_idx, h0..h11) or\n"
    " *             15 (word_idx, mask_idx, iter, h0..h11) when max_iter > 1\n"
    " */\n"
    "__kernel void sha384raw_unsalted_batch(\n"
    "    __global const uchar *words, __global const ushort *unused_lens,\n"
    "    __global const uchar *mask_desc,\n"
    "    __global const uint *unused1, __global const ushort *unused2,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    ulong mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    __global const ulong *src = (__global const ulong *)(words + word_idx * 128);\n"
    "    ulong M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    uint n_pre = params.n_prepend, n_app = params.n_append;\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint n_total_m = n_pre + n_app;\n"
    "\n"
    "        if (n_pre > 0) {\n"
    "            uint append_combos = 1;\n"
    "            for (uint i = 0; i < n_app; i++) append_combos *= mask_desc[n_pre + i];\n"
    "            uint prepend_idx = (uint)(mask_idx / append_combos);\n"
    "            uint append_idx = (uint)(mask_idx % append_combos);\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                int wi = i >> 3; int bi = (i & 7) << 3;\n"
    "                M[wi] = (M[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "            }\n"
    "            if (n_app > 0) {\n"
    "                int total_len = (int)(M[15] & 0xFFFFFFFFUL);\n"
    "                int app_start = total_len - (int)n_app;\n"
    "                uint aidx = append_idx;\n"
    "                for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                    int pos_idx = n_pre + i;\n"
    "                    uint sz = mask_desc[pos_idx];\n"
    "                    uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                    aidx /= sz;\n"
    "                    int pos = app_start + i;\n"
    "                    int wi = pos >> 3; int bi = (pos & 7) << 3;\n"
    "                    M[wi] = (M[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "                }\n"
    "            }\n"
    "        } else {\n"
    "            /* Append-only (brute-force): host pre-decomposes mask_start into\n"
    "             * per-position base offsets. Kernel does fast uint32 local\n"
    "             * decomposition and adds to base with carry. */\n"
    "            int total_len = (int)(M[15] & 0xFFFFFFFFUL);\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint local_idx = tid % params.num_masks;\n"
    "            uint aidx = local_idx;\n"
    "            uint carry = 0;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uint local_digit = aidx % sz;\n"
    "                aidx /= sz;\n"
    "                uint base_digit = (i < 8)\n"
    "                    ? (uint)((params.mask_base0 >> (i * 8)) & 0xFF)\n"
    "                    : (uint)((params.mask_base1 >> ((i - 8) * 8)) & 0xFF);\n"
    "                uint sum = base_digit + local_digit + carry;\n"
    "                carry = sum / sz;\n"
    "                uint final_digit = sum % sz;\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + final_digit];\n"
    "                int pos = app_start + i;\n"
    "                int wi = pos >> 3; int bi = (pos & 7) << 3;\n"
    "                M[wi] = (M[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    uint bitlen = (uint)(M[15] & 0xFFFFFFFFUL);\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap64(M[i]);\n"
    "    M[14] = 0; M[15] = (ulong)bitlen;\n"
    "\n"
    "    /* SHA384 IV */\n"
    "    ulong state[8] = {\n"
    "        0xcbbb9d5dc1059ed8UL, 0x629a292a367cd507UL,\n"
    "        0x9159015a3070dd17UL, 0x152fecd8f70e5939UL,\n"
    "        0x67332667ffc00b31UL, 0x8eb44a8768581511UL,\n"
    "        0xdb0c2e0d64f98fa7UL, 0x47b5481dbefa4fa4UL\n"
    "    };\n"
    "    sha512_block(state, M);\n"
    "\n"
    "    /* Binary iteration: probe first, then sha384(48-byte binary) for next iter.\n"
    "     * Set up fixed padding for 48-byte binary input once. */\n"
    "    M[6] = 0x8000000000000000UL;\n"
    "    for (int i = 7; i < 15; i++) M[i] = 0;\n"
    "    M[15] = 384;  /* 48 bytes * 8 bits */\n"
    "\n"
    "    uint max_iter = params.max_iter;\n"
    "    /* SHA384RAW: 12 hash words. hit_stride = 2 + 12 = 14, or 3 + 12 = 15 with iter */\n"
    "    uint hit_stride = (max_iter > 1) ? 15 : 14;\n"
    "\n"
    "    for (uint iter = 1; iter <= max_iter; iter++) {\n"
    "        uint h[12];\n"
    "        for (int i = 0; i < 6; i++) {\n"
    "            ulong s = bswap64(state[i]);\n"
    "            h[i*2]   = (uint)s;\n"
    "            h[i*2+1] = (uint)(s >> 32);\n"
    "        }\n"
    "\n"
    "        if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                          params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                          hash_data_buf, hash_data_off,\n"
    "                          overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "            uint slot = atomic_add(hit_count, 1u);\n"
    "            if (slot < params.max_hits) {\n"
    "                uint base = slot * hit_stride;\n"
    "                hits[base]   = word_idx;\n"
    "                hits[base+1] = mask_idx;\n"
    "                int offset = 2;\n"
    "                if (max_iter > 1) { hits[base+2] = iter; offset = 3; }\n"
    "                for (int i = 0; i < 12; i++) hits[base+offset+i] = h[i];\n"
    "                mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "            }\n"
    "        }\n"
    "        if (iter < max_iter) {\n"
    "            for (int i = 0; i < 6; i++) M[i] = state[i];\n"
    "            state[0] = 0xcbbb9d5dc1059ed8UL; state[1] = 0x629a292a367cd507UL;\n"
    "            state[2] = 0x9159015a3070dd17UL; state[3] = 0x152fecd8f70e5939UL;\n"
    "            state[4] = 0x67332667ffc00b31UL; state[5] = 0x8eb44a8768581511UL;\n"
    "            state[6] = 0xdb0c2e0d64f98fa7UL; state[7] = 0x47b5481dbefa4fa4UL;\n"
    "            sha512_block(state, M);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* SHA512RAW: sha512(sha512_binary(pass)) — binary iteration.\n"
    " * First SHA512(pass), then iterate sha512(64-byte binary).\n"
    " * Hit stride: 18 (word_idx, mask_idx, h0..h15) or\n"
    " *             19 (word_idx, mask_idx, iter, h0..h15) when max_iter > 1\n"
    " */\n"
    "__kernel void sha512raw_unsalted_batch(\n"
    "    __global const uchar *words, __global const ushort *unused_lens,\n"
    "    __global const uchar *mask_desc,\n"
    "    __global const uint *unused1, __global const ushort *unused2,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    ulong mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    __global const ulong *src = (__global const ulong *)(words + word_idx * 128);\n"
    "    ulong M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    uint n_pre = params.n_prepend, n_app = params.n_append;\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint n_total_m = n_pre + n_app;\n"
    "\n"
    "        if (n_pre > 0) {\n"
    "            uint append_combos = 1;\n"
    "            for (uint i = 0; i < n_app; i++) append_combos *= mask_desc[n_pre + i];\n"
    "            uint prepend_idx = (uint)(mask_idx / append_combos);\n"
    "            uint append_idx = (uint)(mask_idx % append_combos);\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                int wi = i >> 3; int bi = (i & 7) << 3;\n"
    "                M[wi] = (M[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "            }\n"
    "            if (n_app > 0) {\n"
    "                int total_len = (int)(M[15] & 0xFFFFFFFFUL);\n"
    "                int app_start = total_len - (int)n_app;\n"
    "                uint aidx = append_idx;\n"
    "                for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                    int pos_idx = n_pre + i;\n"
    "                    uint sz = mask_desc[pos_idx];\n"
    "                    uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                    aidx /= sz;\n"
    "                    int pos = app_start + i;\n"
    "                    int wi = pos >> 3; int bi = (pos & 7) << 3;\n"
    "                    M[wi] = (M[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "                }\n"
    "            }\n"
    "        } else {\n"
    "            /* Append-only (brute-force): host pre-decomposes mask_start into\n"
    "             * per-position base offsets. Kernel does fast uint32 local\n"
    "             * decomposition and adds to base with carry. */\n"
    "            int total_len = (int)(M[15] & 0xFFFFFFFFUL);\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint local_idx = tid % params.num_masks;\n"
    "            uint aidx = local_idx;\n"
    "            uint carry = 0;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uint local_digit = aidx % sz;\n"
    "                aidx /= sz;\n"
    "                uint base_digit = (i < 8)\n"
    "                    ? (uint)((params.mask_base0 >> (i * 8)) & 0xFF)\n"
    "                    : (uint)((params.mask_base1 >> ((i - 8) * 8)) & 0xFF);\n"
    "                uint sum = base_digit + local_digit + carry;\n"
    "                carry = sum / sz;\n"
    "                uint final_digit = sum % sz;\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + final_digit];\n"
    "                int pos = app_start + i;\n"
    "                int wi = pos >> 3; int bi = (pos & 7) << 3;\n"
    "                M[wi] = (M[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    uint bitlen = (uint)(M[15] & 0xFFFFFFFFUL);\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap64(M[i]);\n"
    "    M[14] = 0; M[15] = (ulong)bitlen;\n"
    "\n"
    "    ulong state[8] = {\n"
    "        0x6a09e667f3bcc908UL, 0xbb67ae8584caa73bUL,\n"
    "        0x3c6ef372fe94f82bUL, 0xa54ff53a5f1d36f1UL,\n"
    "        0x510e527fade682d1UL, 0x9b05688c2b3e6c1fUL,\n"
    "        0x1f83d9abfb41bd6bUL, 0x5be0cd19137e2179UL\n"
    "    };\n"
    "    sha512_block(state, M);\n"
    "\n"
    "    /* Binary iteration: probe at each iteration, then sha512(binary_output).\n"
    "     * Set up fixed padding for 64-byte binary input once. */\n"
    "    M[8] = 0x8000000000000000UL;\n"
    "    for (int i = 9; i < 15; i++) M[i] = 0;\n"
    "    M[15] = 512;  /* 64 bytes * 8 bits */\n"
    "\n"
    "    uint max_iter = params.max_iter;\n"
    "    /* SHA512RAW: 16 hash words. hit_stride = 2 + 16 = 18, or 3 + 16 = 19 with iter */\n"
    "    uint hit_stride = (max_iter > 1) ? 19 : 18;\n"
    "\n"
    "    for (uint iter = 1; iter <= max_iter; iter++) {\n"
    "        uint h[16];\n"
    "        for (int i = 0; i < 8; i++) {\n"
    "            ulong s = bswap64(state[i]);\n"
    "            h[i*2]   = (uint)s;\n"
    "            h[i*2+1] = (uint)(s >> 32);\n"
    "        }\n"
    "\n"
    "        if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                          params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                          hash_data_buf, hash_data_off,\n"
    "                          overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "            uint slot = atomic_add(hit_count, 1u);\n"
    "            if (slot < params.max_hits) {\n"
    "                uint base = slot * hit_stride;\n"
    "                hits[base]   = word_idx;\n"
    "                hits[base+1] = mask_idx;\n"
    "                int offset = 2;\n"
    "                if (max_iter > 1) { hits[base+2] = iter; offset = 3; }\n"
    "                for (int i = 0; i < 16; i++) hits[base+offset+i] = h[i];\n"
    "                mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "            }\n"
    "        }\n"
    "        if (iter < max_iter) {\n"
    "            for (int i = 0; i < 8; i++) M[i] = state[i];\n"
    "            state[0] = 0x6a09e667f3bcc908UL; state[1] = 0xbb67ae8584caa73bUL;\n"
    "            state[2] = 0x3c6ef372fe94f82bUL; state[3] = 0xa54ff53a5f1d36f1UL;\n"
    "            state[4] = 0x510e527fade682d1UL; state[5] = 0x9b05688c2b3e6c1fUL;\n"
    "            state[6] = 0x1f83d9abfb41bd6bUL; state[7] = 0x5be0cd19137e2179UL;\n"
    "            sha512_block(state, M);\n"
    "        }\n"
    "    }\n"
    "}\n"
;
