/* Auto-generated from gpu_hmac_sha512.cl -- do not edit */
static const char gpu_hmac_sha512_str[] =
    "/* gpu_hmac_sha512.cl — HMAC-SHA512 GPU kernels\n"
    " *\n"
    " * hmac_sha512_ksalt_batch: key=$salt (e218, hashcat 1760)\n"
    " * hmac_sha512_kpass_batch: key=$pass (e797, hashcat 1750)\n"
    " *\n"
    " * SHA512 block size = 128 bytes, output = 64 bytes.\n"
    " * HMAC = SHA512((K⊕opad) || SHA512((K⊕ipad) || M))\n"
    " *\n"
    " * Hit stride: 7 (word_idx, salt_idx, iter, hx, hy, hz, hw)\n"
    " * Compact probe: first 16 bytes of 64-byte hash\n"
    " */\n"
    "\n"
    "ulong bswap64(ulong x) {\n"
    "    return ((x >> 56) & 0xffUL) | ((x >> 40) & 0xff00UL) |\n"
    "           ((x >> 24) & 0xff0000UL) | ((x >> 8) & 0xff000000UL) |\n"
    "           ((x << 8) & 0xff00000000UL) | ((x << 24) & 0xff0000000000UL) |\n"
    "           ((x << 40) & 0xff000000000000UL) | ((x << 56) & 0xff00000000000000UL);\n"
    "}\n"
    "\n"
    "__constant ulong K512[80] = {\n"
    "    0x428a2f98d728ae22UL, 0x7137449123ef65cdUL, 0xb5c0fbcfec4d3b2fUL, 0xe9b5dba58189dbbcUL,\n"
    "    0x3956c25bf348b538UL, 0x59f111f1b605d019UL, 0x923f82a4af194f9bUL, 0xab1c5ed5da6d8118UL,\n"
    "    0xd807aa98a3030242UL, 0x12835b0145706fbeUL, 0x243185be4ee4b28cUL, 0x550c7dc3d5ffb4e2UL,\n"
    "    0x72be5d74f27b896fUL, 0x80deb1fe3b1696b1UL, 0x9bdc06a725c71235UL, 0xc19bf174cf692694UL,\n"
    "    0xe49b69c19ef14ad2UL, 0xefbe4786384f25e3UL, 0x0fc19dc68b8cd5b5UL, 0x240ca1cc77ac9c65UL,\n"
    "    0x2de92c6f592b0275UL, 0x4a7484aa6ea6e483UL, 0x5cb0a9dcbd41fbd4UL, 0x76f988da831153b5UL,\n"
    "    0x983e5152ee66dfabUL, 0xa831c66d2db43210UL, 0xb00327c898fb213fUL, 0xbf597fc7beef0ee4UL,\n"
    "    0xc6e00bf33da88fc2UL, 0xd5a79147930aa725UL, 0x06ca6351e003826fUL, 0x142929670a0e6e70UL,\n"
    "    0x27b70a8546d22ffcUL, 0x2e1b21385c26c926UL, 0x4d2c6dfc5ac42aedUL, 0x53380d139d95b3dfUL,\n"
    "    0x650a73548baf63deUL, 0x766a0abb3c77b2a8UL, 0x81c2c92e47edaee6UL, 0x92722c851482353bUL,\n"
    "    0xa2bfe8a14cf10364UL, 0xa81a664bbc423001UL, 0xc24b8b70d0f89791UL, 0xc76c51a30654be30UL,\n"
    "    0xd192e819d6ef5218UL, 0xd69906245565a910UL, 0xf40e35855771202aUL, 0x106aa07032bbd1b8UL,\n"
    "    0x19a4c116b8d2d0c8UL, 0x1e376c085141ab53UL, 0x2748774cdf8eeb99UL, 0x34b0bcb5e19b48a8UL,\n"
    "    0x391c0cb3c5c95a63UL, 0x4ed8aa4ae3418acbUL, 0x5b9cca4f7763e373UL, 0x682e6ff3d6b2b8a3UL,\n"
    "    0x748f82ee5defb2fcUL, 0x78a5636f43172f60UL, 0x84c87814a1f0ab72UL, 0x8cc702081a6439ecUL,\n"
    "    0x90befffa23631e28UL, 0xa4506cebde82bde9UL, 0xbef9a3f7b2c67915UL, 0xc67178f2e372532bUL,\n"
    "    0xca273eceea26619cUL, 0xd186b8c721c0c207UL, 0xeada7dd6cde0eb1eUL, 0xf57d4f7fee6ed178UL,\n"
    "    0x06f067aa72176fbaUL, 0x0a637dc5a2c898a6UL, 0x113f9804bef90daeUL, 0x1b710b35131c471bUL,\n"
    "    0x28db77f523047d84UL, 0x32caab7b40c72493UL, 0x3c9ebe0a15c9bebcUL, 0x431d67c49c100d4cUL,\n"
    "    0x4cc5d4becb3e42b6UL, 0x597f299cfc657e2aUL, 0x5fcb6fab3ad6faecUL, 0x6c44198c4a475817UL\n"
    "};\n"
    "\n"
    "ulong rotr64(ulong x, uint n) { return (x >> n) | (x << (64 - n)); }\n"
    "\n"
    "void sha512_block(ulong *state, ulong *M) {\n"
    "    ulong W[80];\n"
    "    for (int i = 0; i < 16; i++) W[i] = M[i];\n"
    "    for (int i = 16; i < 80; i++) {\n"
    "        ulong s0 = rotr64(W[i-15], 1) ^ rotr64(W[i-15], 8) ^ (W[i-15] >> 7);\n"
    "        ulong s1 = rotr64(W[i-2], 19) ^ rotr64(W[i-2], 61) ^ (W[i-2] >> 6);\n"
    "        W[i] = W[i-16] + s0 + W[i-7] + s1;\n"
    "    }\n"
    "    ulong a = state[0], b = state[1], c = state[2], d = state[3];\n"
    "    ulong e = state[4], f = state[5], g = state[6], h = state[7];\n"
    "    for (int i = 0; i < 80; i++) {\n"
    "        ulong S1 = rotr64(e, 14) ^ rotr64(e, 18) ^ rotr64(e, 41);\n"
    "        ulong ch = (e & f) ^ (~e & g);\n"
    "        ulong t1 = h + S1 + ch + K512[i] + W[i];\n"
    "        ulong S0 = rotr64(a, 28) ^ rotr64(a, 34) ^ rotr64(a, 39);\n"
    "        ulong maj = (a & b) ^ (a & c) ^ (b & c);\n"
    "        ulong t2 = S0 + maj;\n"
    "        h = g; g = f; f = e; e = d + t1;\n"
    "        d = c; c = b; b = a; a = t1 + t2;\n"
    "    }\n"
    "    state[0] += a; state[1] += b; state[2] += c; state[3] += d;\n"
    "    state[4] += e; state[5] += f; state[6] += g; state[7] += h;\n"
    "}\n"
    "\n"
    "/* Copy bytes into big-endian ulong M[] */\n"
    "void S512_copy_bytes(ulong *M, int byte_off, __global const uchar *src, int nbytes) {\n"
    "    for (int i = 0; i < nbytes; i++) {\n"
    "        int wi = (byte_off + i) / 8;\n"
    "        int bi = 7 - ((byte_off + i) % 8);\n"
    "        M[wi] = (M[wi] & ~(0xffUL << (bi * 8))) | ((ulong)src[i] << (bi * 8));\n"
    "    }\n"
    "}\n"
    "\n"
    "void S512_set_byte(ulong *M, int byte_off, uchar val) {\n"
    "    int wi = byte_off / 8;\n"
    "    int bi = 7 - (byte_off % 8);\n"
    "    M[wi] = (M[wi] & ~(0xffUL << (bi * 8))) | ((ulong)val << (bi * 8));\n"
    "}\n"
    "\n"
    "#define SHA512_IV0 0x6a09e667f3bcc908UL\n"
    "#define SHA512_IV1 0xbb67ae8584caa73bUL\n"
    "#define SHA512_IV2 0x3c6ef372fe94f82bUL\n"
    "#define SHA512_IV3 0xa54ff53a5f1d36f1UL\n"
    "#define SHA512_IV4 0x510e527fade682d1UL\n"
    "#define SHA512_IV5 0x9b05688c2b3e6c1fUL\n"
    "#define SHA512_IV6 0x1f83d9abfb41bd6bUL\n"
    "#define SHA512_IV7 0x5be0cd19137e2179UL\n"
    "\n"
    "/* HMAC-SHA512 key=$salt: key=salt, message=password */\n"
    "__kernel void hmac_sha512_ksalt_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int klen = salt_lens[salt_idx];\n"
    "    __global const uchar *key = salts + soff;\n"
    "\n"
    "    /* key_block: 128 bytes as LE for XOR, then bswap to BE for SHA512 */\n"
    "    ulong key_block[16];\n"
    "    for (int i = 0; i < 16; i++) key_block[i] = 0;\n"
    "\n"
    "    if (klen > 128) {\n"
    "        /* key = SHA512(original_key) — rare for salts */\n"
    "        ulong kst[8] = { SHA512_IV0, SHA512_IV1, SHA512_IV2, SHA512_IV3,\n"
    "                         SHA512_IV4, SHA512_IV5, SHA512_IV6, SHA512_IV7 };\n"
    "        ulong M[16];\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        S512_copy_bytes(M, 0, key, (klen < 128) ? klen : 128);\n"
    "        if (klen <= 111) { S512_set_byte(M, klen, 0x80); M[15] = (ulong)klen * 8; }\n"
    "        sha512_block(kst, M);\n"
    "        if (klen > 111) {\n"
    "            for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "            int rem = klen - 128;\n"
    "            if (rem > 0) S512_copy_bytes(M, 0, key + 128, rem);\n"
    "            S512_set_byte(M, rem, 0x80);\n"
    "            M[15] = (ulong)klen * 8;\n"
    "            sha512_block(kst, M);\n"
    "        }\n"
    "        for (int i = 0; i < 8; i++) key_block[i] = bswap64(kst[i]);\n"
    "        klen = 64;\n"
    "    } else {\n"
    "        for (int i = 0; i < klen; i++) {\n"
    "            int wi = i >> 3;\n"
    "            int bi = (i & 7) << 3;\n"
    "            key_block[wi] |= ((ulong)key[i]) << bi;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Inner hash: SHA512((key ⊕ ipad) || message) */\n"
    "    ulong ipad[16], M[16];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        ipad[i] = key_block[i] ^ 0x3636363636363636UL;\n"
    "\n"
    "    /* bswap ipad to BE for SHA512 */\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap64(ipad[i]);\n"
    "\n"
    "    ulong istate[8] = { SHA512_IV0, SHA512_IV1, SHA512_IV2, SHA512_IV3,\n"
    "                         SHA512_IV4, SHA512_IV5, SHA512_IV6, SHA512_IV7 };\n"
    "    sha512_block(istate, M);  /* 128-byte ipad block */\n"
    "\n"
    "    /* Continue with message (password) + padding */\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    if (plen <= 111) {\n"
    "        S512_copy_bytes(M, 0, pass, plen);\n"
    "        S512_set_byte(M, plen, 0x80);\n"
    "        M[15] = (ulong)(128 + plen) * 8;\n"
    "        sha512_block(istate, M);\n"
    "    } else {\n"
    "        S512_copy_bytes(M, 0, pass, (plen < 128) ? plen : 128);\n"
    "        if (plen < 128) S512_set_byte(M, plen, 0x80);\n"
    "        sha512_block(istate, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int rem = plen - 128;\n"
    "        if (rem > 0) S512_copy_bytes(M, 0, pass + 128, rem);\n"
    "        if (plen >= 128) S512_set_byte(M, (rem > 0) ? rem : 0, 0x80);\n"
    "        M[15] = (ulong)(128 + plen) * 8;\n"
    "        sha512_block(istate, M);\n"
    "    }\n"
    "\n"
    "    /* Outer hash: SHA512((key ⊕ opad) || inner_hash) */\n"
    "    ulong opad[16];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        opad[i] = key_block[i] ^ 0x5c5c5c5c5c5c5c5cUL;\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap64(opad[i]);\n"
    "\n"
    "    ulong ostate[8] = { SHA512_IV0, SHA512_IV1, SHA512_IV2, SHA512_IV3,\n"
    "                         SHA512_IV4, SHA512_IV5, SHA512_IV6, SHA512_IV7 };\n"
    "    sha512_block(ostate, M);  /* 128-byte opad block */\n"
    "\n"
    "    /* inner hash (64 bytes BE) + padding.\n"
    "     * Fits in one 128-byte block: 64 bytes data + 0x80 + zeros + 128-bit length. */\n"
    "    for (int i = 0; i < 8; i++) M[i] = istate[i];  /* already BE */\n"
    "    M[8] = 0x8000000000000000UL;\n"
    "    for (int i = 9; i < 15; i++) M[i] = 0;\n"
    "    M[15] = (ulong)(128 + 64) * 8;  /* 192 bytes total */\n"
    "    sha512_block(ostate, M);\n"
    "\n"
    "    /* Check result: first 16 bytes as 4 × uint32 */\n"
    "    ulong s0 = bswap64(ostate[0]), s1 = bswap64(ostate[1]);\n"
    "    uint hx = (uint)s0, hy = (uint)(s0 >> 32);\n"
    "    uint hz = (uint)s1, hw = (uint)(s1 >> 32);\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 7;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx; hits[base+2] = 1;\n"
    "            hits[base+3] = hx; hits[base+4] = hy;\n"
    "            hits[base+5] = hz; hits[base+6] = hw;\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* HMAC-SHA512 key=$pass: key=password, message=salt */\n"
    "__kernel void hmac_sha512_kpass_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int klen = hexlens[word_idx];\n"
    "    __global const uchar *key = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int mlen = salt_lens[salt_idx];\n"
    "    __global const uchar *msg = salts + soff;\n"
    "\n"
    "    ulong key_block[16];\n"
    "    for (int i = 0; i < 16; i++) key_block[i] = 0;\n"
    "\n"
    "    if (klen > 128) {\n"
    "        ulong kst[8] = { SHA512_IV0, SHA512_IV1, SHA512_IV2, SHA512_IV3,\n"
    "                         SHA512_IV4, SHA512_IV5, SHA512_IV6, SHA512_IV7 };\n"
    "        ulong M[16];\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        S512_copy_bytes(M, 0, key, (klen < 128) ? klen : 128);\n"
    "        if (klen <= 111) { S512_set_byte(M, klen, 0x80); M[15] = (ulong)klen * 8; }\n"
    "        sha512_block(kst, M);\n"
    "        if (klen > 111) {\n"
    "            for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "            int rem = klen - 128;\n"
    "            if (rem > 0) S512_copy_bytes(M, 0, key + 128, rem);\n"
    "            S512_set_byte(M, rem, 0x80);\n"
    "            M[15] = (ulong)klen * 8;\n"
    "            sha512_block(kst, M);\n"
    "        }\n"
    "        for (int i = 0; i < 8; i++) key_block[i] = bswap64(kst[i]);\n"
    "        klen = 64;\n"
    "    } else {\n"
    "        for (int i = 0; i < klen; i++) {\n"
    "            int wi = i >> 3;\n"
    "            int bi = (i & 7) << 3;\n"
    "            key_block[wi] |= ((ulong)key[i]) << bi;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    ulong ipad[16], M[16];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        ipad[i] = key_block[i] ^ 0x3636363636363636UL;\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap64(ipad[i]);\n"
    "\n"
    "    ulong istate[8] = { SHA512_IV0, SHA512_IV1, SHA512_IV2, SHA512_IV3,\n"
    "                         SHA512_IV4, SHA512_IV5, SHA512_IV6, SHA512_IV7 };\n"
    "    sha512_block(istate, M);\n"
    "\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    if (mlen <= 111) {\n"
    "        S512_copy_bytes(M, 0, msg, mlen);\n"
    "        S512_set_byte(M, mlen, 0x80);\n"
    "        M[15] = (ulong)(128 + mlen) * 8;\n"
    "        sha512_block(istate, M);\n"
    "    } else {\n"
    "        S512_copy_bytes(M, 0, msg, (mlen < 128) ? mlen : 128);\n"
    "        if (mlen < 128) S512_set_byte(M, mlen, 0x80);\n"
    "        sha512_block(istate, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int rem = mlen - 128;\n"
    "        if (rem > 0) S512_copy_bytes(M, 0, msg + 128, rem);\n"
    "        if (mlen >= 128) S512_set_byte(M, (rem > 0) ? rem : 0, 0x80);\n"
    "        M[15] = (ulong)(128 + mlen) * 8;\n"
    "        sha512_block(istate, M);\n"
    "    }\n"
    "\n"
    "    ulong opad[16];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        opad[i] = key_block[i] ^ 0x5c5c5c5c5c5c5c5cUL;\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap64(opad[i]);\n"
    "\n"
    "    ulong ostate[8] = { SHA512_IV0, SHA512_IV1, SHA512_IV2, SHA512_IV3,\n"
    "                         SHA512_IV4, SHA512_IV5, SHA512_IV6, SHA512_IV7 };\n"
    "    sha512_block(ostate, M);\n"
    "\n"
    "    for (int i = 0; i < 8; i++) M[i] = istate[i];\n"
    "    M[8] = 0x8000000000000000UL;\n"
    "    for (int i = 9; i < 15; i++) M[i] = 0;\n"
    "    M[15] = (ulong)(128 + 64) * 8;\n"
    "    sha512_block(ostate, M);\n"
    "\n"
    "    ulong s0 = bswap64(ostate[0]), s1 = bswap64(ostate[1]);\n"
    "    uint hx = (uint)s0, hy = (uint)(s0 >> 32);\n"
    "    uint hz = (uint)s1, hw = (uint)(s1 >> 32);\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 7;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx; hits[base+2] = 1;\n"
    "            hits[base+3] = hx; hits[base+4] = hy;\n"
    "            hits[base+5] = hz; hits[base+6] = hw;\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* HMAC-SHA384: same compress as SHA512, SHA384 IV, inner hash = 48 bytes */\n"
    "\n"
    "#define SHA384_IV0 0xcbbb9d5dc1059ed8UL\n"
    "#define SHA384_IV1 0x629a292a367cd507UL\n"
    "#define SHA384_IV2 0x9159015a3070dd17UL\n"
    "#define SHA384_IV3 0x152fecd8f70e5939UL\n"
    "#define SHA384_IV4 0x67332667ffc00b31UL\n"
    "#define SHA384_IV5 0x8eb44a8768581511UL\n"
    "#define SHA384_IV6 0xdb0c2e0d64f98fa7UL\n"
    "#define SHA384_IV7 0x47b5481dbefa4fa4UL\n"
    "\n"
    "__kernel void hmac_sha384_ksalt_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int klen = salt_lens[salt_idx];\n"
    "    __global const uchar *key = salts + soff;\n"
    "\n"
    "    ulong key_block[16];\n"
    "    for (int i = 0; i < 16; i++) key_block[i] = 0;\n"
    "    if (klen > 128) {\n"
    "        ulong kst[8] = { SHA384_IV0,SHA384_IV1,SHA384_IV2,SHA384_IV3,\n"
    "                         SHA384_IV4,SHA384_IV5,SHA384_IV6,SHA384_IV7 };\n"
    "        ulong M[16]; for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        S512_copy_bytes(M, 0, key, (klen < 128) ? klen : 128);\n"
    "        if (klen <= 111) { S512_set_byte(M, klen, 0x80); M[15] = (ulong)klen * 8; }\n"
    "        sha512_block(kst, M);\n"
    "        if (klen > 111) {\n"
    "            for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "            S512_copy_bytes(M, 0, key + 128, klen - 128);\n"
    "            S512_set_byte(M, klen - 128, 0x80);\n"
    "            M[15] = (ulong)klen * 8;\n"
    "            sha512_block(kst, M);\n"
    "        }\n"
    "        for (int i = 0; i < 6; i++) key_block[i] = bswap64(kst[i]);\n"
    "        klen = 48;\n"
    "    } else {\n"
    "        for (int i = 0; i < klen; i++)\n"
    "            key_block[i >> 3] |= ((ulong)key[i]) << ((i & 7) << 3);\n"
    "    }\n"
    "\n"
    "    ulong ipad[16], M[16];\n"
    "    for (int i = 0; i < 16; i++) ipad[i] = key_block[i] ^ 0x3636363636363636UL;\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap64(ipad[i]);\n"
    "    ulong istate[8] = { SHA384_IV0,SHA384_IV1,SHA384_IV2,SHA384_IV3,\n"
    "                         SHA384_IV4,SHA384_IV5,SHA384_IV6,SHA384_IV7 };\n"
    "    sha512_block(istate, M);\n"
    "\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    if (plen <= 111) {\n"
    "        S512_copy_bytes(M, 0, pass, plen);\n"
    "        S512_set_byte(M, plen, 0x80);\n"
    "        M[15] = (ulong)(128 + plen) * 8;\n"
    "        sha512_block(istate, M);\n"
    "    } else {\n"
    "        S512_copy_bytes(M, 0, pass, (plen < 128) ? plen : 128);\n"
    "        if (plen < 128) S512_set_byte(M, plen, 0x80);\n"
    "        sha512_block(istate, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int rem = plen - 128;\n"
    "        if (rem > 0) S512_copy_bytes(M, 0, pass + 128, rem);\n"
    "        if (plen >= 128) S512_set_byte(M, (rem > 0) ? rem : 0, 0x80);\n"
    "        M[15] = (ulong)(128 + plen) * 8;\n"
    "        sha512_block(istate, M);\n"
    "    }\n"
    "\n"
    "    /* Outer: SHA384(opad || 48-byte inner_hash) */\n"
    "    ulong opad[16];\n"
    "    for (int i = 0; i < 16; i++) opad[i] = key_block[i] ^ 0x5c5c5c5c5c5c5c5cUL;\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap64(opad[i]);\n"
    "    ulong ostate[8] = { SHA384_IV0,SHA384_IV1,SHA384_IV2,SHA384_IV3,\n"
    "                         SHA384_IV4,SHA384_IV5,SHA384_IV6,SHA384_IV7 };\n"
    "    sha512_block(ostate, M);\n"
    "\n"
    "    /* 48 bytes (6 ulong) inner hash + padding */\n"
    "    for (int i = 0; i < 6; i++) M[i] = istate[i];\n"
    "    M[6] = 0x8000000000000000UL;  /* 0x80 at byte 48 */\n"
    "    for (int i = 7; i < 15; i++) M[i] = 0;\n"
    "    M[15] = (ulong)(128 + 48) * 8;  /* 1408 */\n"
    "    sha512_block(ostate, M);\n"
    "\n"
    "    ulong s0 = bswap64(ostate[0]), s1 = bswap64(ostate[1]);\n"
    "    uint hx = (uint)s0, hy = (uint)(s0 >> 32);\n"
    "    uint hz = (uint)s1, hw = (uint)(s1 >> 32);\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 7;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx; hits[base+2] = 1;\n"
    "            hits[base+3] = hx; hits[base+4] = hy;\n"
    "            hits[base+5] = hz; hits[base+6] = hw;\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "__kernel void hmac_sha384_kpass_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int klen = hexlens[word_idx];\n"
    "    __global const uchar *key = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int mlen = salt_lens[salt_idx];\n"
    "    __global const uchar *msg = salts + soff;\n"
    "\n"
    "    ulong key_block[16];\n"
    "    for (int i = 0; i < 16; i++) key_block[i] = 0;\n"
    "    if (klen > 128) {\n"
    "        ulong kst[8] = { SHA384_IV0,SHA384_IV1,SHA384_IV2,SHA384_IV3,\n"
    "                         SHA384_IV4,SHA384_IV5,SHA384_IV6,SHA384_IV7 };\n"
    "        ulong M[16]; for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        S512_copy_bytes(M, 0, key, (klen < 128) ? klen : 128);\n"
    "        if (klen <= 111) { S512_set_byte(M, klen, 0x80); M[15] = (ulong)klen * 8; }\n"
    "        sha512_block(kst, M);\n"
    "        if (klen > 111) {\n"
    "            for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "            S512_copy_bytes(M, 0, key + 128, klen - 128);\n"
    "            S512_set_byte(M, klen - 128, 0x80);\n"
    "            M[15] = (ulong)klen * 8;\n"
    "            sha512_block(kst, M);\n"
    "        }\n"
    "        for (int i = 0; i < 6; i++) key_block[i] = bswap64(kst[i]);\n"
    "        klen = 48;\n"
    "    } else {\n"
    "        for (int i = 0; i < klen; i++)\n"
    "            key_block[i >> 3] |= ((ulong)key[i]) << ((i & 7) << 3);\n"
    "    }\n"
    "\n"
    "    ulong ipad[16], M[16];\n"
    "    for (int i = 0; i < 16; i++) ipad[i] = key_block[i] ^ 0x3636363636363636UL;\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap64(ipad[i]);\n"
    "    ulong istate[8] = { SHA384_IV0,SHA384_IV1,SHA384_IV2,SHA384_IV3,\n"
    "                         SHA384_IV4,SHA384_IV5,SHA384_IV6,SHA384_IV7 };\n"
    "    sha512_block(istate, M);\n"
    "\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    if (mlen <= 111) {\n"
    "        S512_copy_bytes(M, 0, msg, mlen);\n"
    "        S512_set_byte(M, mlen, 0x80);\n"
    "        M[15] = (ulong)(128 + mlen) * 8;\n"
    "        sha512_block(istate, M);\n"
    "    } else {\n"
    "        S512_copy_bytes(M, 0, msg, (mlen < 128) ? mlen : 128);\n"
    "        if (mlen < 128) S512_set_byte(M, mlen, 0x80);\n"
    "        sha512_block(istate, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int rem = mlen - 128;\n"
    "        if (rem > 0) S512_copy_bytes(M, 0, msg + 128, rem);\n"
    "        if (mlen >= 128) S512_set_byte(M, (rem > 0) ? rem : 0, 0x80);\n"
    "        M[15] = (ulong)(128 + mlen) * 8;\n"
    "        sha512_block(istate, M);\n"
    "    }\n"
    "\n"
    "    ulong opad[16];\n"
    "    for (int i = 0; i < 16; i++) opad[i] = key_block[i] ^ 0x5c5c5c5c5c5c5c5cUL;\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap64(opad[i]);\n"
    "    ulong ostate[8] = { SHA384_IV0,SHA384_IV1,SHA384_IV2,SHA384_IV3,\n"
    "                         SHA384_IV4,SHA384_IV5,SHA384_IV6,SHA384_IV7 };\n"
    "    sha512_block(ostate, M);\n"
    "\n"
    "    for (int i = 0; i < 6; i++) M[i] = istate[i];\n"
    "    M[6] = 0x8000000000000000UL;\n"
    "    for (int i = 7; i < 15; i++) M[i] = 0;\n"
    "    M[15] = (ulong)(128 + 48) * 8;\n"
    "    sha512_block(ostate, M);\n"
    "\n"
    "    ulong s0 = bswap64(ostate[0]), s1 = bswap64(ostate[1]);\n"
    "    uint hx = (uint)s0, hy = (uint)(s0 >> 32);\n"
    "    uint hz = (uint)s1, hw = (uint)(s1 >> 32);\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 7;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx; hits[base+2] = 1;\n"
    "            hits[base+3] = hx; hits[base+4] = hy;\n"
    "            hits[base+5] = hz; hits[base+6] = hw;\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- SHA512(pass + salt) kernel (e386, hashcat 1710) ---- */\n"
    "__kernel void sha512passsalt_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = plen + slen;\n"
    "\n"
    "    ulong state[8] = { SHA512_IV0, SHA512_IV1, SHA512_IV2, SHA512_IV3,\n"
    "                        SHA512_IV4, SHA512_IV5, SHA512_IV6, SHA512_IV7 };\n"
    "    { ulong M[16];\n"
    "      for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "\n"
    "      if (total_len <= 111) {\n"
    "        S512_copy_bytes(M, 0, pass, plen);\n"
    "        S512_copy_bytes(M, plen, salts + soff, slen);\n"
    "        S512_set_byte(M, total_len, 0x80);\n"
    "        M[15] = (ulong)total_len * 8;\n"
    "        sha512_block(state, M);\n"
    "      } else {\n"
    "        int pass_b1 = (plen < 128) ? plen : 128;\n"
    "        S512_copy_bytes(M, 0, pass, pass_b1);\n"
    "        int salt_b1 = 128 - pass_b1;\n"
    "        if (salt_b1 > slen) salt_b1 = slen;\n"
    "        if (salt_b1 > 0)\n"
    "            S512_copy_bytes(M, pass_b1, salts + soff, salt_b1);\n"
    "        if (total_len < 128)\n"
    "            S512_set_byte(M, total_len, 0x80);\n"
    "        sha512_block(state, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int pos2 = 0;\n"
    "        int pass_b2 = plen - pass_b1;\n"
    "        if (pass_b2 > 0) { S512_copy_bytes(M, 0, pass + pass_b1, pass_b2); pos2 = pass_b2; }\n"
    "        int salt_b2 = slen - salt_b1;\n"
    "        if (salt_b2 > 0) { S512_copy_bytes(M, pos2, salts + soff + salt_b1, salt_b2); pos2 += salt_b2; }\n"
    "        if (total_len >= 128)\n"
    "            S512_set_byte(M, pos2, 0x80);\n"
    "        M[15] = (ulong)total_len * 8;\n"
    "        sha512_block(state, M);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    ulong s0 = bswap64(state[0]), s1 = bswap64(state[1]);\n"
    "    uint hx = (uint)s0, hy = (uint)(s0 >> 32);\n"
    "    uint hz = (uint)s1, hw = (uint)(s1 >> 32);\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 7;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx; hits[base+2] = 1;\n"
    "            hits[base+3] = hx; hits[base+4] = hy;\n"
    "            hits[base+5] = hz; hits[base+6] = hw;\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- SHA512(salt + pass) kernel (e388, hashcat 1720) ---- */\n"
    "__kernel void sha512saltpass_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = slen + plen;\n"
    "\n"
    "    ulong state[8] = { SHA512_IV0, SHA512_IV1, SHA512_IV2, SHA512_IV3,\n"
    "                        SHA512_IV4, SHA512_IV5, SHA512_IV6, SHA512_IV7 };\n"
    "    { ulong M[16];\n"
    "      for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "\n"
    "      if (total_len <= 111) {\n"
    "        S512_copy_bytes(M, 0, salts + soff, slen);\n"
    "        S512_copy_bytes(M, slen, pass, plen);\n"
    "        S512_set_byte(M, total_len, 0x80);\n"
    "        M[15] = (ulong)total_len * 8;\n"
    "        sha512_block(state, M);\n"
    "      } else {\n"
    "        int salt_b1 = (slen < 128) ? slen : 128;\n"
    "        S512_copy_bytes(M, 0, salts + soff, salt_b1);\n"
    "        int pass_b1 = 128 - salt_b1;\n"
    "        if (pass_b1 > plen) pass_b1 = plen;\n"
    "        if (pass_b1 > 0)\n"
    "            S512_copy_bytes(M, salt_b1, pass, pass_b1);\n"
    "        if (total_len < 128)\n"
    "            S512_set_byte(M, total_len, 0x80);\n"
    "        sha512_block(state, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int pos2 = 0;\n"
    "        int salt_b2 = slen - salt_b1;\n"
    "        if (salt_b2 > 0) { S512_copy_bytes(M, 0, salts + soff + salt_b1, salt_b2); pos2 = salt_b2; }\n"
    "        int pass_b2 = plen - pass_b1;\n"
    "        if (pass_b2 > 0) { S512_copy_bytes(M, pos2, pass + pass_b1, pass_b2); pos2 += pass_b2; }\n"
    "        if (total_len >= 128)\n"
    "            S512_set_byte(M, pos2, 0x80);\n"
    "        M[15] = (ulong)total_len * 8;\n"
    "        sha512_block(state, M);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    ulong s0 = bswap64(state[0]), s1 = bswap64(state[1]);\n"
    "    uint hx = (uint)s0, hy = (uint)(s0 >> 32);\n"
    "    uint hz = (uint)s1, hw = (uint)(s1 >> 32);\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 7;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx; hits[base+2] = 1;\n"
    "            hits[base+3] = hx; hits[base+4] = hy;\n"
    "            hits[base+5] = hz; hits[base+6] = hw;\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
;
