/* Auto-generated from gpu_hmac_sha512.cl -- do not edit */
static const char gpu_hmac_sha512_str[] =
    "/* gpu_hmac_sha512.cl — HMAC-SHA512 GPU kernels\n"
    " *\n"
    " * hmac_sha512_ksalt_batch: key=$salt (e218, hashcat 1760)\n"
    " * hmac_sha512_kpass_batch: key=$pass (e797, hashcat 1750)\n"
    " *\n"
    " * SHA512 block size = 128 bytes, output = 64 bytes.\n"
    " * HMAC = SHA512((K⊕opad) || SHA512((K⊕ipad) || M))\n"
    " *\n"
    " * Hit stride: 7 (word_idx, salt_idx, iter, hx, hy, hz, hw)\n"
    " * Compact probe: first 16 bytes of 64-byte hash\n"
    " *\n"
    " * Primitives (bswap64, K512, rotr64, sha512_block, S512_copy_bytes,\n"
    " * S512_set_byte) provided by gpu_common.cl\n"
    " */\n"
    "\n"
    "#define SHA512_IV0 0x6a09e667f3bcc908UL\n"
    "#define SHA512_IV1 0xbb67ae8584caa73bUL\n"
    "#define SHA512_IV2 0x3c6ef372fe94f82bUL\n"
    "#define SHA512_IV3 0xa54ff53a5f1d36f1UL\n"
    "#define SHA512_IV4 0x510e527fade682d1UL\n"
    "#define SHA512_IV5 0x9b05688c2b3e6c1fUL\n"
    "#define SHA512_IV6 0x1f83d9abfb41bd6bUL\n"
    "#define SHA512_IV7 0x5be0cd19137e2179UL\n"
    "\n"
    "/* HMAC-SHA512 key=$salt: key=salt, message=password */\n"
    "__kernel void hmac_sha512_ksalt_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int klen = salt_lens[salt_idx];\n"
    "    __global const uchar *key = salts + soff;\n"
    "\n"
    "    /* key_block: 128 bytes as LE for XOR, then bswap to BE for SHA512 */\n"
    "    ulong key_block[16];\n"
    "    for (int i = 0; i < 16; i++) key_block[i] = 0;\n"
    "\n"
    "    if (klen > 128) {\n"
    "        /* key = SHA512(original_key) — rare for salts */\n"
    "        ulong kst[8] = { SHA512_IV0, SHA512_IV1, SHA512_IV2, SHA512_IV3,\n"
    "                         SHA512_IV4, SHA512_IV5, SHA512_IV6, SHA512_IV7 };\n"
    "        ulong M[16];\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        S512_copy_bytes(M, 0, key, (klen < 128) ? klen : 128);\n"
    "        if (klen <= 111) { S512_set_byte(M, klen, 0x80); M[15] = (ulong)klen * 8; }\n"
    "        sha512_block(kst, M);\n"
    "        if (klen > 111) {\n"
    "            for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "            int rem = klen - 128;\n"
    "            if (rem > 0) S512_copy_bytes(M, 0, key + 128, rem);\n"
    "            S512_set_byte(M, rem, 0x80);\n"
    "            M[15] = (ulong)klen * 8;\n"
    "            sha512_block(kst, M);\n"
    "        }\n"
    "        for (int i = 0; i < 8; i++) key_block[i] = bswap64(kst[i]);\n"
    "        klen = 64;\n"
    "    } else {\n"
    "        for (int i = 0; i < klen; i++) {\n"
    "            int wi = i >> 3;\n"
    "            int bi = (i & 7) << 3;\n"
    "            key_block[wi] |= ((ulong)key[i]) << bi;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Inner hash: SHA512((key ⊕ ipad) || message) */\n"
    "    ulong ipad[16], M[16];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        ipad[i] = key_block[i] ^ 0x3636363636363636UL;\n"
    "\n"
    "    /* bswap ipad to BE for SHA512 */\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap64(ipad[i]);\n"
    "\n"
    "    ulong istate[8] = { SHA512_IV0, SHA512_IV1, SHA512_IV2, SHA512_IV3,\n"
    "                         SHA512_IV4, SHA512_IV5, SHA512_IV6, SHA512_IV7 };\n"
    "    sha512_block(istate, M);  /* 128-byte ipad block */\n"
    "\n"
    "    /* Continue with message (password) + padding */\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    if (plen <= 111) {\n"
    "        S512_copy_bytes(M, 0, pass, plen);\n"
    "        S512_set_byte(M, plen, 0x80);\n"
    "        M[15] = (ulong)(128 + plen) * 8;\n"
    "        sha512_block(istate, M);\n"
    "    } else {\n"
    "        S512_copy_bytes(M, 0, pass, (plen < 128) ? plen : 128);\n"
    "        if (plen < 128) S512_set_byte(M, plen, 0x80);\n"
    "        sha512_block(istate, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int rem = plen - 128;\n"
    "        if (rem > 0) S512_copy_bytes(M, 0, pass + 128, rem);\n"
    "        if (plen >= 128) S512_set_byte(M, (rem > 0) ? rem : 0, 0x80);\n"
    "        M[15] = (ulong)(128 + plen) * 8;\n"
    "        sha512_block(istate, M);\n"
    "    }\n"
    "\n"
    "    /* Outer hash: SHA512((key ⊕ opad) || inner_hash) */\n"
    "    ulong opad[16];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        opad[i] = key_block[i] ^ 0x5c5c5c5c5c5c5c5cUL;\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap64(opad[i]);\n"
    "\n"
    "    ulong ostate[8] = { SHA512_IV0, SHA512_IV1, SHA512_IV2, SHA512_IV3,\n"
    "                         SHA512_IV4, SHA512_IV5, SHA512_IV6, SHA512_IV7 };\n"
    "    sha512_block(ostate, M);  /* 128-byte opad block */\n"
    "\n"
    "    /* inner hash (64 bytes BE) + padding.\n"
    "     * Fits in one 128-byte block: 64 bytes data + 0x80 + zeros + 128-bit length. */\n"
    "    for (int i = 0; i < 8; i++) M[i] = istate[i];  /* already BE */\n"
    "    M[8] = 0x8000000000000000UL;\n"
    "    for (int i = 9; i < 15; i++) M[i] = 0;\n"
    "    M[15] = (ulong)(128 + 64) * 8;  /* 192 bytes total */\n"
    "    sha512_block(ostate, M);\n"
    "\n"
    "    /* HMAC-SHA512: 16 hash words (8 x uint64 -> 16 x uint32) */\n"
    "    uint h[16];\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        ulong s = bswap64(ostate[i]);\n"
    "        h[i*2]   = (uint)s;\n"
    "        h[i*2+1] = (uint)(s >> 32);\n"
    "    }\n"
    "\n"
    "    if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        EMIT_HIT_16(hits, hit_count, params.max_hits, word_idx, salt_idx, 1, h)\n"
    "    }\n"
    "}\n"
    "\n"
    "/* HMAC-SHA512 key=$pass: key=password, message=salt */\n"
    "__kernel void hmac_sha512_kpass_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int klen = hexlens[word_idx];\n"
    "    __global const uchar *key = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int mlen = salt_lens[salt_idx];\n"
    "    __global const uchar *msg = salts + soff;\n"
    "\n"
    "    ulong key_block[16];\n"
    "    for (int i = 0; i < 16; i++) key_block[i] = 0;\n"
    "\n"
    "    if (klen > 128) {\n"
    "        ulong kst[8] = { SHA512_IV0, SHA512_IV1, SHA512_IV2, SHA512_IV3,\n"
    "                         SHA512_IV4, SHA512_IV5, SHA512_IV6, SHA512_IV7 };\n"
    "        ulong M[16];\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        S512_copy_bytes(M, 0, key, (klen < 128) ? klen : 128);\n"
    "        if (klen <= 111) { S512_set_byte(M, klen, 0x80); M[15] = (ulong)klen * 8; }\n"
    "        sha512_block(kst, M);\n"
    "        if (klen > 111) {\n"
    "            for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "            int rem = klen - 128;\n"
    "            if (rem > 0) S512_copy_bytes(M, 0, key + 128, rem);\n"
    "            S512_set_byte(M, rem, 0x80);\n"
    "            M[15] = (ulong)klen * 8;\n"
    "            sha512_block(kst, M);\n"
    "        }\n"
    "        for (int i = 0; i < 8; i++) key_block[i] = bswap64(kst[i]);\n"
    "        klen = 64;\n"
    "    } else {\n"
    "        for (int i = 0; i < klen; i++) {\n"
    "            int wi = i >> 3;\n"
    "            int bi = (i & 7) << 3;\n"
    "            key_block[wi] |= ((ulong)key[i]) << bi;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    ulong ipad[16], M[16];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        ipad[i] = key_block[i] ^ 0x3636363636363636UL;\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap64(ipad[i]);\n"
    "\n"
    "    ulong istate[8] = { SHA512_IV0, SHA512_IV1, SHA512_IV2, SHA512_IV3,\n"
    "                         SHA512_IV4, SHA512_IV5, SHA512_IV6, SHA512_IV7 };\n"
    "    sha512_block(istate, M);\n"
    "\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    if (mlen <= 111) {\n"
    "        S512_copy_bytes(M, 0, msg, mlen);\n"
    "        S512_set_byte(M, mlen, 0x80);\n"
    "        M[15] = (ulong)(128 + mlen) * 8;\n"
    "        sha512_block(istate, M);\n"
    "    } else {\n"
    "        S512_copy_bytes(M, 0, msg, (mlen < 128) ? mlen : 128);\n"
    "        if (mlen < 128) S512_set_byte(M, mlen, 0x80);\n"
    "        sha512_block(istate, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int rem = mlen - 128;\n"
    "        if (rem > 0) S512_copy_bytes(M, 0, msg + 128, rem);\n"
    "        if (mlen >= 128) S512_set_byte(M, (rem > 0) ? rem : 0, 0x80);\n"
    "        M[15] = (ulong)(128 + mlen) * 8;\n"
    "        sha512_block(istate, M);\n"
    "    }\n"
    "\n"
    "    ulong opad[16];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        opad[i] = key_block[i] ^ 0x5c5c5c5c5c5c5c5cUL;\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap64(opad[i]);\n"
    "\n"
    "    ulong ostate[8] = { SHA512_IV0, SHA512_IV1, SHA512_IV2, SHA512_IV3,\n"
    "                         SHA512_IV4, SHA512_IV5, SHA512_IV6, SHA512_IV7 };\n"
    "    sha512_block(ostate, M);\n"
    "\n"
    "    for (int i = 0; i < 8; i++) M[i] = istate[i];\n"
    "    M[8] = 0x8000000000000000UL;\n"
    "    for (int i = 9; i < 15; i++) M[i] = 0;\n"
    "    M[15] = (ulong)(128 + 64) * 8;\n"
    "    sha512_block(ostate, M);\n"
    "\n"
    "    /* HMAC-SHA512: 16 hash words */\n"
    "    uint h[16];\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        ulong s = bswap64(ostate[i]);\n"
    "        h[i*2]   = (uint)s;\n"
    "        h[i*2+1] = (uint)(s >> 32);\n"
    "    }\n"
    "\n"
    "    if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        EMIT_HIT_16(hits, hit_count, params.max_hits, word_idx, salt_idx, 1, h)\n"
    "    }\n"
    "}\n"
    "\n"
    "/* HMAC-SHA384: same compress as SHA512, SHA384 IV, inner hash = 48 bytes */\n"
    "\n"
    "#define SHA384_IV0 0xcbbb9d5dc1059ed8UL\n"
    "#define SHA384_IV1 0x629a292a367cd507UL\n"
    "#define SHA384_IV2 0x9159015a3070dd17UL\n"
    "#define SHA384_IV3 0x152fecd8f70e5939UL\n"
    "#define SHA384_IV4 0x67332667ffc00b31UL\n"
    "#define SHA384_IV5 0x8eb44a8768581511UL\n"
    "#define SHA384_IV6 0xdb0c2e0d64f98fa7UL\n"
    "#define SHA384_IV7 0x47b5481dbefa4fa4UL\n"
    "\n"
    "__kernel void hmac_sha384_ksalt_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int klen = salt_lens[salt_idx];\n"
    "    __global const uchar *key = salts + soff;\n"
    "\n"
    "    ulong key_block[16];\n"
    "    for (int i = 0; i < 16; i++) key_block[i] = 0;\n"
    "    if (klen > 128) {\n"
    "        ulong kst[8] = { SHA384_IV0,SHA384_IV1,SHA384_IV2,SHA384_IV3,\n"
    "                         SHA384_IV4,SHA384_IV5,SHA384_IV6,SHA384_IV7 };\n"
    "        ulong M[16]; for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        S512_copy_bytes(M, 0, key, (klen < 128) ? klen : 128);\n"
    "        if (klen <= 111) { S512_set_byte(M, klen, 0x80); M[15] = (ulong)klen * 8; }\n"
    "        sha512_block(kst, M);\n"
    "        if (klen > 111) {\n"
    "            for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "            S512_copy_bytes(M, 0, key + 128, klen - 128);\n"
    "            S512_set_byte(M, klen - 128, 0x80);\n"
    "            M[15] = (ulong)klen * 8;\n"
    "            sha512_block(kst, M);\n"
    "        }\n"
    "        for (int i = 0; i < 6; i++) key_block[i] = bswap64(kst[i]);\n"
    "        klen = 48;\n"
    "    } else {\n"
    "        for (int i = 0; i < klen; i++)\n"
    "            key_block[i >> 3] |= ((ulong)key[i]) << ((i & 7) << 3);\n"
    "    }\n"
    "\n"
    "    ulong ipad[16], M[16];\n"
    "    for (int i = 0; i < 16; i++) ipad[i] = key_block[i] ^ 0x3636363636363636UL;\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap64(ipad[i]);\n"
    "    ulong istate[8] = { SHA384_IV0,SHA384_IV1,SHA384_IV2,SHA384_IV3,\n"
    "                         SHA384_IV4,SHA384_IV5,SHA384_IV6,SHA384_IV7 };\n"
    "    sha512_block(istate, M);\n"
    "\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    if (plen <= 111) {\n"
    "        S512_copy_bytes(M, 0, pass, plen);\n"
    "        S512_set_byte(M, plen, 0x80);\n"
    "        M[15] = (ulong)(128 + plen) * 8;\n"
    "        sha512_block(istate, M);\n"
    "    } else {\n"
    "        S512_copy_bytes(M, 0, pass, (plen < 128) ? plen : 128);\n"
    "        if (plen < 128) S512_set_byte(M, plen, 0x80);\n"
    "        sha512_block(istate, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int rem = plen - 128;\n"
    "        if (rem > 0) S512_copy_bytes(M, 0, pass + 128, rem);\n"
    "        if (plen >= 128) S512_set_byte(M, (rem > 0) ? rem : 0, 0x80);\n"
    "        M[15] = (ulong)(128 + plen) * 8;\n"
    "        sha512_block(istate, M);\n"
    "    }\n"
    "\n"
    "    /* Outer: SHA384(opad || 48-byte inner_hash) */\n"
    "    ulong opad[16];\n"
    "    for (int i = 0; i < 16; i++) opad[i] = key_block[i] ^ 0x5c5c5c5c5c5c5c5cUL;\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap64(opad[i]);\n"
    "    ulong ostate[8] = { SHA384_IV0,SHA384_IV1,SHA384_IV2,SHA384_IV3,\n"
    "                         SHA384_IV4,SHA384_IV5,SHA384_IV6,SHA384_IV7 };\n"
    "    sha512_block(ostate, M);\n"
    "\n"
    "    /* 48 bytes (6 ulong) inner hash + padding */\n"
    "    for (int i = 0; i < 6; i++) M[i] = istate[i];\n"
    "    M[6] = 0x8000000000000000UL;  /* 0x80 at byte 48 */\n"
    "    for (int i = 7; i < 15; i++) M[i] = 0;\n"
    "    M[15] = (ulong)(128 + 48) * 8;  /* 1408 */\n"
    "    sha512_block(ostate, M);\n"
    "\n"
    "    /* HMAC-SHA384: 12 hash words (6 x uint64 -> 12 x uint32) */\n"
    "    uint h[12];\n"
    "    for (int i = 0; i < 6; i++) {\n"
    "        ulong s = bswap64(ostate[i]);\n"
    "        h[i*2]   = (uint)s;\n"
    "        h[i*2+1] = (uint)(s >> 32);\n"
    "    }\n"
    "\n"
    "    if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        EMIT_HIT_12(hits, hit_count, params.max_hits, word_idx, salt_idx, 1, h)\n"
    "    }\n"
    "}\n"
    "\n"
    "__kernel void hmac_sha384_kpass_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int klen = hexlens[word_idx];\n"
    "    __global const uchar *key = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int mlen = salt_lens[salt_idx];\n"
    "    __global const uchar *msg = salts + soff;\n"
    "\n"
    "    ulong key_block[16];\n"
    "    for (int i = 0; i < 16; i++) key_block[i] = 0;\n"
    "    if (klen > 128) {\n"
    "        ulong kst[8] = { SHA384_IV0,SHA384_IV1,SHA384_IV2,SHA384_IV3,\n"
    "                         SHA384_IV4,SHA384_IV5,SHA384_IV6,SHA384_IV7 };\n"
    "        ulong M[16]; for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        S512_copy_bytes(M, 0, key, (klen < 128) ? klen : 128);\n"
    "        if (klen <= 111) { S512_set_byte(M, klen, 0x80); M[15] = (ulong)klen * 8; }\n"
    "        sha512_block(kst, M);\n"
    "        if (klen > 111) {\n"
    "            for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "            S512_copy_bytes(M, 0, key + 128, klen - 128);\n"
    "            S512_set_byte(M, klen - 128, 0x80);\n"
    "            M[15] = (ulong)klen * 8;\n"
    "            sha512_block(kst, M);\n"
    "        }\n"
    "        for (int i = 0; i < 6; i++) key_block[i] = bswap64(kst[i]);\n"
    "        klen = 48;\n"
    "    } else {\n"
    "        for (int i = 0; i < klen; i++)\n"
    "            key_block[i >> 3] |= ((ulong)key[i]) << ((i & 7) << 3);\n"
    "    }\n"
    "\n"
    "    ulong ipad[16], M[16];\n"
    "    for (int i = 0; i < 16; i++) ipad[i] = key_block[i] ^ 0x3636363636363636UL;\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap64(ipad[i]);\n"
    "    ulong istate[8] = { SHA384_IV0,SHA384_IV1,SHA384_IV2,SHA384_IV3,\n"
    "                         SHA384_IV4,SHA384_IV5,SHA384_IV6,SHA384_IV7 };\n"
    "    sha512_block(istate, M);\n"
    "\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    if (mlen <= 111) {\n"
    "        S512_copy_bytes(M, 0, msg, mlen);\n"
    "        S512_set_byte(M, mlen, 0x80);\n"
    "        M[15] = (ulong)(128 + mlen) * 8;\n"
    "        sha512_block(istate, M);\n"
    "    } else {\n"
    "        S512_copy_bytes(M, 0, msg, (mlen < 128) ? mlen : 128);\n"
    "        if (mlen < 128) S512_set_byte(M, mlen, 0x80);\n"
    "        sha512_block(istate, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int rem = mlen - 128;\n"
    "        if (rem > 0) S512_copy_bytes(M, 0, msg + 128, rem);\n"
    "        if (mlen >= 128) S512_set_byte(M, (rem > 0) ? rem : 0, 0x80);\n"
    "        M[15] = (ulong)(128 + mlen) * 8;\n"
    "        sha512_block(istate, M);\n"
    "    }\n"
    "\n"
    "    ulong opad[16];\n"
    "    for (int i = 0; i < 16; i++) opad[i] = key_block[i] ^ 0x5c5c5c5c5c5c5c5cUL;\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap64(opad[i]);\n"
    "    ulong ostate[8] = { SHA384_IV0,SHA384_IV1,SHA384_IV2,SHA384_IV3,\n"
    "                         SHA384_IV4,SHA384_IV5,SHA384_IV6,SHA384_IV7 };\n"
    "    sha512_block(ostate, M);\n"
    "\n"
    "    for (int i = 0; i < 6; i++) M[i] = istate[i];\n"
    "    M[6] = 0x8000000000000000UL;\n"
    "    for (int i = 7; i < 15; i++) M[i] = 0;\n"
    "    M[15] = (ulong)(128 + 48) * 8;\n"
    "    sha512_block(ostate, M);\n"
    "\n"
    "    /* HMAC-SHA384: 12 hash words */\n"
    "    uint h[12];\n"
    "    for (int i = 0; i < 6; i++) {\n"
    "        ulong s = bswap64(ostate[i]);\n"
    "        h[i*2]   = (uint)s;\n"
    "        h[i*2+1] = (uint)(s >> 32);\n"
    "    }\n"
    "\n"
    "    if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        EMIT_HIT_12(hits, hit_count, params.max_hits, word_idx, salt_idx, 1, h)\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- SHA512(pass + salt) kernel (e386, hashcat 1710) ---- */\n"
    "__kernel void sha512passsalt_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = plen + slen;\n"
    "\n"
    "    ulong state[8] = { SHA512_IV0, SHA512_IV1, SHA512_IV2, SHA512_IV3,\n"
    "                        SHA512_IV4, SHA512_IV5, SHA512_IV6, SHA512_IV7 };\n"
    "    { ulong M[16];\n"
    "      for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "\n"
    "      if (total_len <= 111) {\n"
    "        S512_copy_bytes(M, 0, pass, plen);\n"
    "        S512_copy_bytes(M, plen, salts + soff, slen);\n"
    "        S512_set_byte(M, total_len, 0x80);\n"
    "        M[15] = (ulong)total_len * 8;\n"
    "        sha512_block(state, M);\n"
    "      } else {\n"
    "        int pass_b1 = (plen < 128) ? plen : 128;\n"
    "        S512_copy_bytes(M, 0, pass, pass_b1);\n"
    "        int salt_b1 = 128 - pass_b1;\n"
    "        if (salt_b1 > slen) salt_b1 = slen;\n"
    "        if (salt_b1 > 0)\n"
    "            S512_copy_bytes(M, pass_b1, salts + soff, salt_b1);\n"
    "        if (total_len < 128)\n"
    "            S512_set_byte(M, total_len, 0x80);\n"
    "        sha512_block(state, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int pos2 = 0;\n"
    "        int pass_b2 = plen - pass_b1;\n"
    "        if (pass_b2 > 0) { S512_copy_bytes(M, 0, pass + pass_b1, pass_b2); pos2 = pass_b2; }\n"
    "        int salt_b2 = slen - salt_b1;\n"
    "        if (salt_b2 > 0) { S512_copy_bytes(M, pos2, salts + soff + salt_b1, salt_b2); pos2 += salt_b2; }\n"
    "        if (total_len >= 128)\n"
    "            S512_set_byte(M, pos2, 0x80);\n"
    "        M[15] = (ulong)total_len * 8;\n"
    "        sha512_block(state, M);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    /* SHA512PASSSALT: 16 hash words */\n"
    "    uint h[16];\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        ulong s = bswap64(state[i]);\n"
    "        h[i*2]   = (uint)s;\n"
    "        h[i*2+1] = (uint)(s >> 32);\n"
    "    }\n"
    "\n"
    "    if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        EMIT_HIT_16(hits, hit_count, params.max_hits, word_idx, salt_idx, 1, h)\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- SHA512(salt + pass) kernel (e388, hashcat 1720) ---- */\n"
    "__kernel void sha512saltpass_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = slen + plen;\n"
    "\n"
    "    ulong state[8] = { SHA512_IV0, SHA512_IV1, SHA512_IV2, SHA512_IV3,\n"
    "                        SHA512_IV4, SHA512_IV5, SHA512_IV6, SHA512_IV7 };\n"
    "    { ulong M[16];\n"
    "      for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "\n"
    "      if (total_len <= 111) {\n"
    "        S512_copy_bytes(M, 0, salts + soff, slen);\n"
    "        S512_copy_bytes(M, slen, pass, plen);\n"
    "        S512_set_byte(M, total_len, 0x80);\n"
    "        M[15] = (ulong)total_len * 8;\n"
    "        sha512_block(state, M);\n"
    "      } else {\n"
    "        int salt_b1 = (slen < 128) ? slen : 128;\n"
    "        S512_copy_bytes(M, 0, salts + soff, salt_b1);\n"
    "        int pass_b1 = 128 - salt_b1;\n"
    "        if (pass_b1 > plen) pass_b1 = plen;\n"
    "        if (pass_b1 > 0)\n"
    "            S512_copy_bytes(M, salt_b1, pass, pass_b1);\n"
    "        if (total_len < 128)\n"
    "            S512_set_byte(M, total_len, 0x80);\n"
    "        sha512_block(state, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int pos2 = 0;\n"
    "        int salt_b2 = slen - salt_b1;\n"
    "        if (salt_b2 > 0) { S512_copy_bytes(M, 0, salts + soff + salt_b1, salt_b2); pos2 = salt_b2; }\n"
    "        int pass_b2 = plen - pass_b1;\n"
    "        if (pass_b2 > 0) { S512_copy_bytes(M, pos2, pass + pass_b1, pass_b2); pos2 += pass_b2; }\n"
    "        if (total_len >= 128)\n"
    "            S512_set_byte(M, pos2, 0x80);\n"
    "        M[15] = (ulong)total_len * 8;\n"
    "        sha512_block(state, M);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    /* SHA512SALTPASS: 16 hash words */\n"
    "    uint h[16];\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        ulong s = bswap64(state[i]);\n"
    "        h[i*2]   = (uint)s;\n"
    "        h[i*2+1] = (uint)(s >> 32);\n"
    "    }\n"
    "\n"
    "    if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        EMIT_HIT_16(hits, hit_count, params.max_hits, word_idx, salt_idx, 1, h)\n"
    "    }\n"
    "}\n"
;
