/* Auto-generated from gpu_mysql3unsalted.cl -- do not edit */
static const char gpu_mysql3unsalted_str[] =
    "/* gpu_mysql3unsalted.cl — MySQL OLD_PASSWORD() hash (e456, hashcat 200)\n"
    " *\n"
    " * Simple arithmetic hash: nr/nr2 accumulator loop over password bytes.\n"
    " * Uses pre-padded 64-byte block for consistent mask fill — password length\n"
    " * from M[14]/8, password bytes at LE offsets 0..total-1.\n"
    " * Skips spaces and tabs (matching CPU behavior).\n"
    " *\n"
    " * Output: 8 bytes (nr[31:0] || nr2[31:0]), big-endian.\n"
    " * Compact probe: first 4 bytes split into 2 × uint32 (nr_hi, nr_lo, nr2_hi, nr2_lo)\n"
    " * Actually: output is only 64 bits so we use nr and nr2 as the 4 probe words.\n"
    " *\n"
    " * Hit stride: 6 (word_idx, mask_idx, hx, hy, hz, hw)\n"
    " */\n"
    "\n"
    "\n"
    "__kernel void mysql3_unsalted_batch(\n"
    "    __global const uint *words,\n"
    "    __global const ushort *unused_lens,\n"
    "    __global const uchar *mask_desc,\n"
    "    __global const uint *unused1, __global const ushort *unused2,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    ulong mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    /* Load pre-padded block */\n"
    "    __global const uint *src = words + word_idx * 16;\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    /* Fill mask positions — same LE byte manipulation */\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint n_total_m = n_pre + n_app;\n"
    "\n"
    "        if (n_pre > 0) {\n"
    "            uint append_combos = 1;\n"
    "            for (uint i = 0; i < n_app; i++)\n"
    "                append_combos *= mask_desc[n_pre + i];\n"
    "            uint prepend_idx = (uint)(mask_idx / append_combos);\n"
    "            uint append_idx = (uint)(mask_idx % append_combos);\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                M[i >> 2] = (M[i >> 2] & ~(0xFFu << ((i & 3) << 3)))\n"
    "                           | ((uint)ch << ((i & 3) << 3));\n"
    "            }\n"
    "            if (n_app > 0) {\n"
    "                int total_len = M[14] >> 3;\n"
    "                int app_start = total_len - (int)n_app;\n"
    "                uint aidx = append_idx;\n"
    "                for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                    int pos_idx = n_pre + i;\n"
    "                    uint sz = mask_desc[pos_idx];\n"
    "                    uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                    aidx /= sz;\n"
    "                    int pos = app_start + i;\n"
    "                    M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                                 | ((uint)ch << ((pos & 3) << 3));\n"
    "                }\n"
    "            }\n"
    "        } else {\n"
    "            /* Append-only (brute-force): host pre-decomposes mask_start into\n"
    "             * per-position base offsets. Kernel does fast uint32 local\n"
    "             * decomposition and adds to base with carry. */\n"
    "            int total_len = M[14] >> 3;\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint local_idx = tid % params.num_masks;\n"
    "            uint aidx = local_idx;\n"
    "            uint carry = 0;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uint local_digit = aidx % sz;\n"
    "                aidx /= sz;\n"
    "                uint base_digit = (i < 8)\n"
    "                    ? (uint)((params.mask_base0 >> (i * 8)) & 0xFF)\n"
    "                    : (uint)((params.mask_base1 >> ((i - 8) * 8)) & 0xFF);\n"
    "                uint sum = base_digit + local_digit + carry;\n"
    "                carry = sum / sz;\n"
    "                uint final_digit = sum % sz;\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + final_digit];\n"
    "                int pos = app_start + i;\n"
    "                M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                             | ((uint)ch << ((pos & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* MySQL3 hash: arithmetic loop over password bytes */\n"
    "    int passlen = M[14] >> 3;  /* total length from bit-length field */\n"
    "    uint nr = 1345345333u, add = 7u, nr2 = 0x12345671u;\n"
    "\n"
    "    for (int i = 0; i < passlen; i++) {\n"
    "        /* Extract byte i from LE M[] */\n"
    "        uchar c = (uchar)((M[i >> 2] >> ((i & 3) << 3)) & 0xFFu);\n"
    "        if (c == ' ' || c == '\\t') continue;\n"
    "        uint tmp = (uint)c;\n"
    "        nr ^= (((nr & 63u) + add) * tmp) + (nr << 8);\n"
    "        nr2 += (nr2 << 8) ^ nr;\n"
    "        add += tmp;\n"
    "    }\n"
    "    nr &= 0x7fffffffu;\n"
    "    nr2 &= 0x7fffffffu;\n"
    "\n"
    "    /* Output: 8 bytes BE = nr(4 bytes) || nr2(4 bytes)\n"
    "     * For compact table probe, we need 4 × uint32.\n"
    "     * Hash is only 64 bits; store nr and nr2 in LE byte order\n"
    "     * to match how mdxfind stores 16-hex hashes in the compact table. */\n"
    "    uint hx = ((nr >> 24) & 0xff) | ((nr >> 8) & 0xff00) |\n"
    "              ((nr << 8) & 0xff0000) | ((nr << 24) & 0xff000000u);\n"
    "    uint hy = ((nr2 >> 24) & 0xff) | ((nr2 >> 8) & 0xff00) |\n"
    "              ((nr2 << 8) & 0xff0000) | ((nr2 << 24) & 0xff000000u);\n"
    "    uint hz = 0, hw = 0;\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 6;\n"
    "            hits[base]   = word_idx;\n"
    "            hits[base+1] = mask_idx;\n"
    "            hits[base+2] = hx;\n"
    "            hits[base+3] = hy;\n"
    "            hits[base+4] = hz;\n"
    "            hits[base+5] = hw;\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
;
