/* Auto-generated from gpu_kernels.cl -- do not edit */
static const char gpu_kernels_str[] =
    "/* md5salt.cl — OpenCL kernels for mdxfind MD5SALT GPU acceleration */\n"
    "\n"
    "typedef struct {\n"
    "    ulong compact_mask;\n"
    "    uint num_words;\n"
    "    uint num_salts;\n"
    "    uint salt_start;\n"
    "    uint max_probe;\n"
    "    uint hash_data_count;\n"
    "    uint max_hits;\n"
    "    uint overflow_count;\n"
    "    uint max_iter;\n"
    "} OCLParams;\n"
    "\n"
    "__constant uint K[64] = {\n"
    "    0xd76aa478,0xe8c7b756,0x242070db,0xc1bdceee,0xf57c0faf,0x4787c62a,0xa8304613,0xfd469501,\n"
    "    0x698098d8,0x8b44f7af,0xffff5bb1,0x895cd7be,0x6b901122,0xfd987193,0xa679438e,0x49b40821,\n"
    "    0xf61e2562,0xc040b340,0x265e5a51,0xe9b6c7aa,0xd62f105d,0x02441453,0xd8a1e681,0xe7d3fbc8,\n"
    "    0x21e1cde6,0xc33707d6,0xf4d50d87,0x455a14ed,0xa9e3e905,0xfcefa3f8,0x676f02d9,0x8d2a4c8a,\n"
    "    0xfffa3942,0x8771f681,0x6d9d6122,0xfde5380c,0xa4beea44,0x4bdecfa9,0xf6bb4b60,0xbebfbc70,\n"
    "    0x289b7ec6,0xeaa127fa,0xd4ef3085,0x04881d05,0xd9d4d039,0xe6db99e5,0x1fa27cf8,0xc4ac5665,\n"
    "    0xf4292244,0x432aff97,0xab9423a7,0xfc93a039,0x655b59c3,0x8f0ccc92,0xffeff47d,0x85845dd1,\n"
    "    0x6fa87e4f,0xfe2ce6e0,0xa3014314,0x4e0811a1,0xf7537e82,0xbd3af235,0x2ad7d2bb,0xeb86d391\n"
    "};\n"
    "\n"
    "#define FF(a,b,c,d,m,s,k) { a += ((b&c)|(~b&d)) + m + k; a = b + rotate(a,s); }\n"
    "#define GG(a,b,c,d,m,s,k) { a += ((d&b)|(~d&c)) + m + k; a = b + rotate(a,s); }\n"
    "#define HH(a,b,c,d,m,s,k) { a += (b^c^d) + m + k; a = b + rotate(a,s); }\n"
    "#define II(a,b,c,d,m,s,k) { a += (c^(~d|b)) + m + k; a = b + rotate(a,s); }\n"
    "\n"
    "void md5_block(uint *h0, uint *h1, uint *h2, uint *h3, uint *M) {\n"
    "    uint a = *h0, b = *h1, c = *h2, d = *h3;\n"
    "    FF(a,b,c,d,M[0],(uint)7,0xd76aa478u);  FF(d,a,b,c,M[1],(uint)12,0xe8c7b756u);\n"
    "    FF(c,d,a,b,M[2],(uint)17,0x242070dbu);  FF(b,c,d,a,M[3],(uint)22,0xc1bdceeeu);\n"
    "    FF(a,b,c,d,M[4],(uint)7,0xf57c0fafu);   FF(d,a,b,c,M[5],(uint)12,0x4787c62au);\n"
    "    FF(c,d,a,b,M[6],(uint)17,0xa8304613u);  FF(b,c,d,a,M[7],(uint)22,0xfd469501u);\n"
    "    FF(a,b,c,d,M[8],(uint)7,0x698098d8u);   FF(d,a,b,c,M[9],(uint)12,0x8b44f7afu);\n"
    "    FF(c,d,a,b,M[10],(uint)17,0xffff5bb1u); FF(b,c,d,a,M[11],(uint)22,0x895cd7beu);\n"
    "    FF(a,b,c,d,M[12],(uint)7,0x6b901122u);  FF(d,a,b,c,M[13],(uint)12,0xfd987193u);\n"
    "    FF(c,d,a,b,M[14],(uint)17,0xa679438eu); FF(b,c,d,a,M[15],(uint)22,0x49b40821u);\n"
    "    GG(a,b,c,d,M[1],(uint)5,0xf61e2562u);   GG(d,a,b,c,M[6],(uint)9,0xc040b340u);\n"
    "    GG(c,d,a,b,M[11],(uint)14,0x265e5a51u); GG(b,c,d,a,M[0],(uint)20,0xe9b6c7aau);\n"
    "    GG(a,b,c,d,M[5],(uint)5,0xd62f105du);   GG(d,a,b,c,M[10],(uint)9,0x02441453u);\n"
    "    GG(c,d,a,b,M[15],(uint)14,0xd8a1e681u); GG(b,c,d,a,M[4],(uint)20,0xe7d3fbc8u);\n"
    "    GG(a,b,c,d,M[9],(uint)5,0x21e1cde6u);   GG(d,a,b,c,M[14],(uint)9,0xc33707d6u);\n"
    "    GG(c,d,a,b,M[3],(uint)14,0xf4d50d87u);  GG(b,c,d,a,M[8],(uint)20,0x455a14edu);\n"
    "    GG(a,b,c,d,M[13],(uint)5,0xa9e3e905u);  GG(d,a,b,c,M[2],(uint)9,0xfcefa3f8u);\n"
    "    GG(c,d,a,b,M[7],(uint)14,0x676f02d9u);  GG(b,c,d,a,M[12],(uint)20,0x8d2a4c8au);\n"
    "    HH(a,b,c,d,M[5],(uint)4,0xfffa3942u);   HH(d,a,b,c,M[8],(uint)11,0x8771f681u);\n"
    "    HH(c,d,a,b,M[11],(uint)16,0x6d9d6122u); HH(b,c,d,a,M[14],(uint)23,0xfde5380cu);\n"
    "    HH(a,b,c,d,M[1],(uint)4,0xa4beea44u);   HH(d,a,b,c,M[4],(uint)11,0x4bdecfa9u);\n"
    "    HH(c,d,a,b,M[7],(uint)16,0xf6bb4b60u);  HH(b,c,d,a,M[10],(uint)23,0xbebfbc70u);\n"
    "    HH(a,b,c,d,M[13],(uint)4,0x289b7ec6u);  HH(d,a,b,c,M[0],(uint)11,0xeaa127fau);\n"
    "    HH(c,d,a,b,M[3],(uint)16,0xd4ef3085u);  HH(b,c,d,a,M[6],(uint)23,0x04881d05u);\n"
    "    HH(a,b,c,d,M[9],(uint)4,0xd9d4d039u);   HH(d,a,b,c,M[12],(uint)11,0xe6db99e5u);\n"
    "    HH(c,d,a,b,M[15],(uint)16,0x1fa27cf8u); HH(b,c,d,a,M[2],(uint)23,0xc4ac5665u);\n"
    "    II(a,b,c,d,M[0],(uint)6,0xf4292244u);   II(d,a,b,c,M[7],(uint)10,0x432aff97u);\n"
    "    II(c,d,a,b,M[14],(uint)15,0xab9423a7u); II(b,c,d,a,M[5],(uint)21,0xfc93a039u);\n"
    "    II(a,b,c,d,M[12],(uint)6,0x655b59c3u);  II(d,a,b,c,M[3],(uint)10,0x8f0ccc92u);\n"
    "    II(c,d,a,b,M[10],(uint)15,0xffeff47du); II(b,c,d,a,M[1],(uint)21,0x85845dd1u);\n"
    "    II(a,b,c,d,M[8],(uint)6,0x6fa87e4fu);   II(d,a,b,c,M[15],(uint)10,0xfe2ce6e0u);\n"
    "    II(c,d,a,b,M[6],(uint)15,0xa3014314u);  II(b,c,d,a,M[13],(uint)21,0x4e0811a1u);\n"
    "    II(a,b,c,d,M[4],(uint)6,0xf7537e82u);   II(d,a,b,c,M[11],(uint)10,0xbd3af235u);\n"
    "    II(c,d,a,b,M[2],(uint)15,0x2ad7d2bbu);  II(b,c,d,a,M[9],(uint)21,0xeb86d391u);\n"
    "    *h0 += a; *h1 += b; *h2 += c; *h3 += d;\n"
    "}\n"
    "\n"
    "ulong compact_mix(ulong k) { return k ^ (k >> 32); }\n"
    "\n"
    "int probe_compact(uint hx, uint hy, uint hz, uint hw,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count)\n"
    "{\n"
    "    ulong key = ((ulong)hy << 32) | hx;\n"
    "    uint fp = (uint)(key >> 32);\n"
    "    if (fp == 0) fp = 1;\n"
    "    ulong pos = compact_mix(key) & compact_mask;\n"
    "    for (int p = 0; p < (int)max_probe; p++) {\n"
    "        uint cfp = compact_fp[pos];\n"
    "        if (cfp == 0) break;\n"
    "        if (cfp == fp) {\n"
    "            uint idx = compact_idx[pos];\n"
    "            if (idx < hash_data_count) {\n"
    "                ulong off = hash_data_off[idx];\n"
    "                __global const uint *ref = (__global const uint *)(hash_data_buf + off);\n"
    "                if (hx == ref[0] && hy == ref[1] && hz == ref[2] && hw == ref[3])\n"
    "                    return 1;\n"
    "            }\n"
    "        }\n"
    "        pos = (pos + 1) & compact_mask;\n"
    "    }\n"
    "    if (overflow_count > 0) {\n"
    "        int lo = 0, hi = (int)overflow_count - 1;\n"
    "        while (lo <= hi) {\n"
    "            int mid = (lo + hi) / 2;\n"
    "            ulong mkey = overflow_keys[mid];\n"
    "            if (key < mkey) hi = mid - 1;\n"
    "            else if (key > mkey) lo = mid + 1;\n"
    "            else {\n"
    "                uint ooff = overflow_offsets[mid];\n"
    "                __global const uint *oref = (__global const uint *)(overflow_hashes + ooff);\n"
    "                if (hx == oref[0] && hy == oref[1] && hz == oref[2] && hw == oref[3]) return 1;\n"
    "                for (int d = mid-1; d >= 0 && overflow_keys[d] == key; d--) {\n"
    "                    oref = (__global const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (hx == oref[0] && hy == oref[1] && hz == oref[2] && hw == oref[3]) return 1;\n"
    "                }\n"
    "                for (int d = mid+1; d < (int)overflow_count && overflow_keys[d] == key; d++) {\n"
    "                    oref = (__global const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (hx == oref[0] && hy == oref[1] && hz == oref[2] && hw == oref[3]) return 1;\n"
    "                }\n"
    "                break;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "    return 0;\n"
    "}\n"
    "\n"
    "__kernel void md5salt_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off, __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    uint M[16];\n"
    "    __global const uint *mwords = (__global const uint *)(hexhashes + word_idx * 256);\n"
    "    for (int i = 0; i < 8; i++) M[i] = mwords[i];\n"
    "    for (int i = 8; i < 16; i++) M[i] = 0;\n"
    "\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = 32 + slen;\n"
    "    uchar *mbytes = (uchar *)M;\n"
    "    for (int i = 0; i < slen; i++)\n"
    "        mbytes[32 + i] = salts[soff + i];\n"
    "    mbytes[total_len] = 0x80;\n"
    "    M[14] = total_len * 8;\n"
    "\n"
    "    uint hx = 0x67452301, hy = 0xEFCDAB89, hz = 0x98BADCFE, hw = 0x10325476;\n"
    "    md5_block(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 6;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx;\n"
    "            hits[base+2] = hx; hits[base+3] = hy;\n"
    "            hits[base+4] = hz; hits[base+5] = hw;\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "__kernel void md5salt_sub8_24(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off, __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    uint M[16];\n"
    "    __global const uint *mwords = (__global const uint *)(hexhashes + word_idx * 256);\n"
    "    for (int i = 0; i < 4; i++) M[i] = mwords[i];\n"
    "    for (int i = 4; i < 16; i++) M[i] = 0;\n"
    "\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = 16 + slen;\n"
    "    uchar *mbytes = (uchar *)M;\n"
    "    for (int i = 0; i < slen; i++) mbytes[16 + i] = salts[soff + i];\n"
    "    mbytes[total_len] = 0x80;\n"
    "    M[14] = total_len * 8;\n"
    "\n"
    "    uint hx = 0x67452301, hy = 0xEFCDAB89, hz = 0x98BADCFE, hw = 0x10325476;\n"
    "    md5_block(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 6;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx;\n"
    "            hits[base+2] = hx; hits[base+3] = hy;\n"
    "            hits[base+4] = hz; hits[base+5] = hw;\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "__kernel void md5salt_iter(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off, __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    uint M[16];\n"
    "    __global const uint *mwords = (__global const uint *)(hexhashes + word_idx * 256);\n"
    "    for (int i = 0; i < 8; i++) M[i] = mwords[i];\n"
    "    for (int i = 8; i < 16; i++) M[i] = 0;\n"
    "\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = 32 + slen;\n"
    "    uchar *mbytes = (uchar *)M;\n"
    "    for (int i = 0; i < slen; i++) mbytes[32 + i] = salts[soff + i];\n"
    "    mbytes[total_len] = 0x80;\n"
    "    M[14] = total_len * 8;\n"
    "\n"
    "    uint hx = 0x67452301, hy = 0xEFCDAB89, hz = 0x98BADCFE, hw = 0x10325476;\n"
    "    md5_block(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "    for (uint iter = 0; iter < params.max_iter; iter++) {\n"
    "        if (iter > 0) {\n"
    "            uint hwords[4]; hwords[0]=hx; hwords[1]=hy; hwords[2]=hz; hwords[3]=hw;\n"
    "            uchar *hb = (uchar *)hwords;\n"
    "            uint Mi[16];\n"
    "            uchar *mb = (uchar *)Mi;\n"
    "            for (int i = 0; i < 16; i++) {\n"
    "                uchar hi = hb[i] >> 4, lo = hb[i] & 0xf;\n"
    "                mb[i*2]   = hi + (hi < 10 ? '0' : 'a' - 10);\n"
    "                mb[i*2+1] = lo + (lo < 10 ? '0' : 'a' - 10);\n"
    "            }\n"
    "            Mi[8] = 0x80; Mi[9]=0; Mi[10]=0; Mi[11]=0;\n"
    "            Mi[12]=0; Mi[13]=0; Mi[14]=256; Mi[15]=0;\n"
    "            hx = 0x67452301; hy = 0xEFCDAB89; hz = 0x98BADCFE; hw = 0x10325476;\n"
    "            md5_block(&hx, &hy, &hz, &hw, Mi);\n"
    "        }\n"
    "        if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                          params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                          hash_data_buf, hash_data_off,\n"
    "                          overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "            uint slot = atomic_add(hit_count, 1u);\n"
    "            if (slot < params.max_hits) {\n"
    "                uint base = slot * 7;\n"
    "                hits[base] = word_idx; hits[base+1] = salt_idx;\n"
    "                hits[base+2] = iter + 1;\n"
    "                hits[base+3] = hx; hits[base+4] = hy;\n"
    "                hits[base+5] = hz; hits[base+6] = hw;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- Hex conversion for MD5 iteration ---- */\n"
    "\n"
    "/* Convert one byte to 2 packed hex chars (lowercase) */\n"
    "uint hex_byte_lc(uint b) {\n"
    "    uint hi = (b >> 4) & 0xf;\n"
    "    uint lo = b & 0xf;\n"
    "    uint hc = hi + ((hi < 10) ? '0' : ('a' - 10));\n"
    "    uint lc = lo + ((lo < 10) ? '0' : ('a' - 10));\n"
    "    return hc | (lc << 8);\n"
    "}\n"
    "\n"
    "/* Convert one byte to 2 packed hex chars (uppercase) */\n"
    "uint hex_byte_uc(uint b) {\n"
    "    uint hi = (b >> 4) & 0xf;\n"
    "    uint lo = b & 0xf;\n"
    "    uint hc = hi + ((hi < 10) ? '0' : ('A' - 10));\n"
    "    uint lc = lo + ((lo < 10) ? '0' : ('A' - 10));\n"
    "    return hc | (lc << 8);\n"
    "}\n"
    "\n"
    "/* Convert 4 MD5 uint32s to 8 M[] words of hex text (lowercase) */\n"
    "void md5_to_hex_lc(uint hx, uint hy, uint hz, uint hw, uint *M) {\n"
    "    uint v[4]; v[0]=hx; v[1]=hy; v[2]=hz; v[3]=hw;\n"
    "    for (int i = 0; i < 4; i++) {\n"
    "        uint b0 = v[i] & 0xff, b1 = (v[i]>>8) & 0xff;\n"
    "        uint b2 = (v[i]>>16) & 0xff, b3 = (v[i]>>24) & 0xff;\n"
    "        M[i*2]   = hex_byte_lc(b0) | (hex_byte_lc(b1) << 16);\n"
    "        M[i*2+1] = hex_byte_lc(b2) | (hex_byte_lc(b3) << 16);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* Convert 4 MD5 uint32s to 8 M[] words of hex text (uppercase) */\n"
    "void md5_to_hex_uc(uint hx, uint hy, uint hz, uint hw, uint *M) {\n"
    "    uint v[4]; v[0]=hx; v[1]=hy; v[2]=hz; v[3]=hw;\n"
    "    for (int i = 0; i < 4; i++) {\n"
    "        uint b0 = v[i] & 0xff, b1 = (v[i]>>8) & 0xff;\n"
    "        uint b2 = (v[i]>>16) & 0xff, b3 = (v[i]>>24) & 0xff;\n"
    "        M[i*2]   = hex_byte_uc(b0) | (hex_byte_uc(b1) << 16);\n"
    "        M[i*2+1] = hex_byte_uc(b2) | (hex_byte_uc(b3) << 16);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- Bare MD5 iteration kernel (e1 lowercase, e2 uppercase) ----\n"
    " *\n"
    " * Input: hex(MD5(password)) pre-packed by CPU into M[] words.\n"
    " * GPU iterates: MD5(hex) -> check -> hex(result) -> MD5(hex) -> ...\n"
    " * One work item per word (no salt dimension).\n"
    " * Hit stride is always 7 (includes iteration number).\n"
    " */\n"
    "__kernel void md5_iter_lc(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts_unused, __global const uint *salt_off_unused,\n"
    "    __global const ushort *salt_len_unused,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    if (tid >= params.num_words) return;\n"
    "\n"
    "    uint M[16];\n"
    "    __global const uint *mwords = (__global const uint *)(hexhashes + tid * 256);\n"
    "    for (int i = 0; i < 8; i++) M[i] = mwords[i];\n"
    "\n"
    "    /* MD5 padding for 32-byte input -- constant across all iterations */\n"
    "    for (int i = 8; i < 16; i++) M[i] = 0;\n"
    "    M[8] = 0x80;\n"
    "    M[14] = 32 * 8;\n"
    "\n"
    "    for (uint iter = 1; iter <= params.max_iter; iter++) {\n"
    "        uint hx = 0x67452301, hy = 0xEFCDAB89, hz = 0x98BADCFE, hw = 0x10325476;\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "        if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                          params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                          hash_data_buf, hash_data_off,\n"
    "                          overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "            uint slot = atomic_add(hit_count, 1u);\n"
    "            if (slot < params.max_hits) {\n"
    "                uint base = slot * 7;\n"
    "                hits[base] = tid; hits[base+1] = 0;\n"
    "                hits[base+2] = iter + 1; /* +1: GPU iter 1 = mdxfind iter 2 */\n"
    "                hits[base+3] = hx; hits[base+4] = hy;\n"
    "                hits[base+5] = hz; hits[base+6] = hw;\n"
    "            }\n"
    "        }\n"
    "\n"
    "        if (iter < params.max_iter) {\n"
    "            md5_to_hex_lc(hx, hy, hz, hw, M);\n"
    "            /* M[8..15] unchanged: padding for 32-byte input */\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "__kernel void md5_iter_uc(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts_unused, __global const uint *salt_off_unused,\n"
    "    __global const ushort *salt_len_unused,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    if (tid >= params.num_words) return;\n"
    "\n"
    "    uint M[16];\n"
    "    __global const uint *mwords = (__global const uint *)(hexhashes + tid * 256);\n"
    "    for (int i = 0; i < 8; i++) M[i] = mwords[i];\n"
    "\n"
    "    for (int i = 8; i < 16; i++) M[i] = 0;\n"
    "    M[8] = 0x80;\n"
    "    M[14] = 32 * 8;\n"
    "\n"
    "    for (uint iter = 1; iter <= params.max_iter; iter++) {\n"
    "        uint hx = 0x67452301, hy = 0xEFCDAB89, hz = 0x98BADCFE, hw = 0x10325476;\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "        if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                          params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                          hash_data_buf, hash_data_off,\n"
    "                          overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "            uint slot = atomic_add(hit_count, 1u);\n"
    "            if (slot < params.max_hits) {\n"
    "                uint base = slot * 7;\n"
    "                hits[base] = tid; hits[base+1] = 0;\n"
    "                hits[base+2] = iter + 1; /* +1: GPU iter 1 = mdxfind iter 2 */\n"
    "                hits[base+3] = hx; hits[base+4] = hy;\n"
    "                hits[base+5] = hz; hits[base+6] = hw;\n"
    "            }\n"
    "        }\n"
    "\n"
    "        if (iter < params.max_iter) {\n"
    "            md5_to_hex_uc(hx, hy, hz, hw, M);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- Build M[] from byte stream ----\n"
    " * Copy 'len' bytes from global source into M[], starting at byte offset 'off'.\n"
    " * M[] must be pre-zeroed. Works by accumulating bytes into uint32 words. */\n"
    "void M_copy_bytes(uint *M, int off, __global const uchar *src, int len) {\n"
    "    for (int i = 0; i < len; i++) {\n"
    "        int pos = off + i;\n"
    "        int word = pos >> 2;\n"
    "        int shift = (pos & 3) << 3;\n"
    "        M[word] |= ((uint)src[i]) << shift;\n"
    "    }\n"
    "}\n"
    "\n"
    "/* Set a single byte in M[] */\n"
    "void M_set_byte(uint *M, int pos, uint val) {\n"
    "    M[pos >> 2] |= val << ((pos & 3) << 3);\n"
    "}\n"
    "\n"
    "/* ---- MD5(salt + password) kernel ----\n"
    " *\n"
    " * Input: raw password bytes in hexhashes buffer, length in hexlens.\n"
    " * GPU constructs salt + password, computes MD5, checks compact table.\n"
    " * Handles 1-block (total <= 55) and 2-block (55 < total <= 119) dynamically.\n"
    " * Hit stride is 7 (includes iteration number).\n"
    " */\n"
    "__kernel void md5saltpass_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    /* Read password bytes and length */\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "\n"
    "    /* Read salt offset and length */\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = slen + plen;\n"
    "\n"
    "    /* Build message = salt + password, compute MD5 */\n"
    "    uint hx = 0x67452301, hy = 0xEFCDAB89, hz = 0x98BADCFE, hw = 0x10325476;\n"
    "\n"
    "    { uint M[16];\n"
    "      for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "\n"
    "      if (total_len <= 55) {\n"
    "        M_copy_bytes(M, 0, salts + soff, slen);\n"
    "        M_copy_bytes(M, slen, pass, plen);\n"
    "        M_set_byte(M, total_len, 0x80);\n"
    "        M[14] = total_len * 8;\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "      } else {\n"
    "        /* Two blocks: fill first 64 bytes from salt+pass */\n"
    "        int salt_b1 = (slen < 64) ? slen : 64;\n"
    "        M_copy_bytes(M, 0, salts + soff, salt_b1);\n"
    "        int pass_b1 = 64 - salt_b1;\n"
    "        if (pass_b1 > plen) pass_b1 = plen;\n"
    "        if (pass_b1 > 0)\n"
    "            M_copy_bytes(M, salt_b1, pass, pass_b1);\n"
    "        if (total_len < 64)\n"
    "            M_set_byte(M, total_len, 0x80);\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "        /* Second block */\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int pos2 = 0;\n"
    "        int salt_b2 = slen - salt_b1;\n"
    "        if (salt_b2 > 0) {\n"
    "            M_copy_bytes(M, 0, salts + soff + salt_b1, salt_b2);\n"
    "            pos2 = salt_b2;\n"
    "        }\n"
    "        int pass_b2 = plen - pass_b1;\n"
    "        if (pass_b2 > 0) {\n"
    "            M_copy_bytes(M, pos2, pass + pass_b1, pass_b2);\n"
    "            pos2 += pass_b2;\n"
    "        }\n"
    "        if (total_len >= 64)\n"
    "            M_set_byte(M, pos2, 0x80);\n"
    "        M[14] = total_len * 8;\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 7;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx;\n"
    "            hits[base+2] = 1;\n"
    "            hits[base+3] = hx; hits[base+4] = hy;\n"
    "            hits[base+5] = hz; hits[base+6] = hw;\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- MD5(password + salt) kernel ---- */\n"
    "__kernel void md5passsalt_batch(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts, __global const uint *salt_offsets, __global const ushort *salt_lens,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    __global const uchar *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = plen + slen;\n"
    "\n"
    "    uint hx = 0x67452301, hy = 0xEFCDAB89, hz = 0x98BADCFE, hw = 0x10325476;\n"
    "    { uint M[16];\n"
    "      for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "\n"
    "      if (total_len <= 55) {\n"
    "        M_copy_bytes(M, 0, pass, plen);\n"
    "        M_copy_bytes(M, plen, salts + soff, slen);\n"
    "        M_set_byte(M, total_len, 0x80);\n"
    "        M[14] = total_len * 8;\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "      } else {\n"
    "        /* Two blocks: fill first 64 bytes from pass+salt */\n"
    "        int pass_b1 = (plen < 64) ? plen : 64;\n"
    "        M_copy_bytes(M, 0, pass, pass_b1);\n"
    "        int salt_b1 = 64 - pass_b1;\n"
    "        if (salt_b1 > slen) salt_b1 = slen;\n"
    "        if (salt_b1 > 0)\n"
    "            M_copy_bytes(M, pass_b1, salts + soff, salt_b1);\n"
    "        /* If all data fits in block 1, put 0x80 here */\n"
    "        if (total_len < 64)\n"
    "            M_set_byte(M, total_len, 0x80);\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "        /* Second block: remaining data + padding */\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int pos2 = 0;\n"
    "        int pass_b2 = plen - pass_b1;\n"
    "        if (pass_b2 > 0) {\n"
    "            M_copy_bytes(M, 0, pass + pass_b1, pass_b2);\n"
    "            pos2 = pass_b2;\n"
    "        }\n"
    "        int salt_b2 = slen - salt_b1;\n"
    "        if (salt_b2 > 0) {\n"
    "            M_copy_bytes(M, pos2, salts + soff + salt_b1, salt_b2);\n"
    "            pos2 += salt_b2;\n"
    "        }\n"
    "        if (total_len >= 64)\n"
    "            M_set_byte(M, pos2, 0x80);\n"
    "        M[14] = total_len * 8;\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 7;\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx;\n"
    "            hits[base+2] = 1;\n"
    "            hits[base+3] = hx; hits[base+4] = hy;\n"
    "            hits[base+5] = hz; hits[base+6] = hw;\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* Self-test kernel: each work item computes MD5(\"test\"), writes 1 if correct, 0 if not.\n"
    " * Used at init to probe the maximum reliable dispatch size for this GPU. */\n"
    "__kernel void gpu_selftest(__global uint *results) {\n"
    "    uint tid = get_global_id(0);\n"
    "    uint M[16];\n"
    "    M[0] = 0x74736574u;  /* \"test\" LE */\n"
    "    M[1] = 0x00000080u;  /* padding byte */\n"
    "    for (int i = 2; i < 14; i++) M[i] = 0;\n"
    "    M[14] = 32u;         /* 4 bytes * 8 bits */\n"
    "    M[15] = 0;\n"
    "    uint hx = 0x67452301u, hy = 0xEFCDAB89u, hz = 0x98BADCFEu, hw = 0x10325476u;\n"
    "    md5_block(&hx, &hy, &hz, &hw, M);\n"
    "    /* MD5(\"test\") = 098f6bcd... -> LE word0 = 0xcd6b8f09 */\n"
    "    results[tid] = (hx == 0xcd6b8f09u && hy == 0x73d32146u) ? 1u : 0u;\n"
    "}\n"
;
