/* Auto-generated from gpu_md6256unsalted.cl -- do not edit */
static const char gpu_md6256unsalted_str[] =
    "/* gpu_md6256unsalted.cl — Pre-packed unsalted MD6-256 with mask expansion\n"
    " *\n"
    " * Input: pre-packed N[89] (712-byte) blocks in passbuf.\n"
    " *   Host packs: Q[15] + K[8]=0 + U[1] + V[1] + B[64] with message in LE.\n"
    " *   Kernel byte-swaps B[64] portion to big-endian before compression.\n"
    " *   Mask positions fill B portion at doubled-and-swapped byte offsets.\n"
    " *\n"
    " * MD6-256: r=104 rounds, c=16, n=89, d=256.\n"
    " * Compression loop: 104*16 = 1664 steps.\n"
    " * Output: last 4 words of C[16] (= last d/w = 4 × uint64).\n"
    " *\n"
    " * Dispatch: num_words × num_masks threads.\n"
    " * Hit stride: 6 (word_idx, mask_idx, hx, hy, hz, hw)\n"
    " */\n"
    "\n"
    "\n"
    "/* bswap64 provided by gpu_common.cl */\n"
    "\n"
    "/* MD6 compression loop constants */\n"
    "#define MD6_n  89\n"
    "#define MD6_c  16\n"
    "#define MD6_r  104\n"
    "\n"
    "/* Tap positions for feedback shift register */\n"
    "#define MD6_t0  17\n"
    "#define MD6_t1  18\n"
    "#define MD6_t2  21\n"
    "#define MD6_t3  31\n"
    "#define MD6_t4  67\n"
    "#define MD6_t5  89\n"
    "\n"
    "/* Shift amounts for 16 steps per round (w=64) */\n"
    "__constant int RS[16] = {10, 5,13,10,11,12, 2, 7,14,15, 7,13,11, 7, 6,12};\n"
    "__constant int LS[16] = {11,24, 9,16,15, 9,27,15, 6, 2,29, 8,15, 5,31, 9};\n"
    "\n"
    "__constant ulong MD6_S0 = 0x0123456789abcdefUL;\n"
    "__constant ulong MD6_Smask = 0x7311c2812425cfa0UL;\n"
    "\n"
    "/* MD6 main compression loop — operates on array A of length r*c+n */\n"
    "void md6_compress_loop(ulong *A) {\n"
    "    ulong S = MD6_S0;\n"
    "    int i = MD6_n;\n"
    "    for (int j = 0; j < MD6_r * MD6_c; j += MD6_c) {\n"
    "        for (int step = 0; step < 16; step++) {\n"
    "            ulong x = S;\n"
    "            x ^= A[i + step - MD6_t5];\n"
    "            x ^= A[i + step - MD6_t0];\n"
    "            x ^= (A[i + step - MD6_t1] & A[i + step - MD6_t2]);\n"
    "            x ^= (A[i + step - MD6_t3] & A[i + step - MD6_t4]);\n"
    "            x ^= (x >> RS[step]);\n"
    "            A[i + step] = x ^ (x << LS[step]);\n"
    "        }\n"
    "        S = (S << 1) ^ (S >> 63) ^ (S & MD6_Smask);\n"
    "        i += 16;\n"
    "    }\n"
    "}\n"
    "\n"
    "__kernel void md6_256_unsalted_batch(\n"
    "    __global const uchar *words,         /* pre-packed N[89] blocks */\n"
    "    __global const ushort *unused_lens,\n"
    "    __global const uchar *mask_desc,\n"
    "    __global const uint *unused1, __global const ushort *unused2,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    ulong mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    /* Load pre-packed N[89] block.\n"
    "     * Host packs: N[0..24] = Q+K+U+V (fixed), N[25..88] = B (message in LE).\n"
    "     * word_stride stored in jobg, passed as upload size. */\n"
    "    __global const ulong *src = (__global const ulong *)(words + word_idx * 712);\n"
    "\n"
    "    /* We need a working array A of size r*c+n = 104*16+89 = 1753 words.\n"
    "     * Load N into the first 89 positions. */\n"
    "    ulong A[1753];\n"
    "    for (int i = 0; i < 89; i++) A[i] = src[i];\n"
    "\n"
    "    /* Fill mask positions into B portion (A[25..88]).\n"
    "     * B is in LE uint64 from host packer; mask fills at LE byte positions.\n"
    "     * We byte-swap B after mask fill. */\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint n_total_m = n_pre + n_app;\n"
    "\n"
    "        if (n_pre > 0) {\n"
    "            uint append_combos = 1;\n"
    "            for (uint i = 0; i < n_app; i++)\n"
    "                append_combos *= mask_desc[n_pre + i];\n"
    "            uint prepend_idx = (uint)(mask_idx / append_combos);\n"
    "            uint append_idx = (uint)(mask_idx % append_combos);\n"
    "\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                int wi = 25 + (i >> 3);\n"
    "                int bi = (i & 7) << 3;\n"
    "                A[wi] = (A[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "            }\n"
    "\n"
    "            if (n_app > 0) {\n"
    "                ulong V = A[24];\n"
    "                uint p_bits = (uint)((V >> 20) & 0xFFFFUL);\n"
    "                int total_len = (64*64 - (int)p_bits) / 8;\n"
    "                int app_start = total_len - (int)n_app;\n"
    "                uint aidx = append_idx;\n"
    "                for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                    int pos_idx = n_pre + i;\n"
    "                    uint sz = mask_desc[pos_idx];\n"
    "                    uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                    aidx /= sz;\n"
    "                    int pos = app_start + i;\n"
    "                    int wi = 25 + (pos >> 3);\n"
    "                    int bi = (pos & 7) << 3;\n"
    "                    A[wi] = (A[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "                }\n"
    "            }\n"
    "        } else {\n"
    "            /* Append-only (brute-force): host pre-decomposes mask_start into\n"
    "             * per-position base offsets. Kernel does fast uint32 local\n"
    "             * decomposition and adds to base with carry. */\n"
    "            ulong V = A[24];\n"
    "            uint p_bits = (uint)((V >> 20) & 0xFFFFUL);\n"
    "            int total_len = (64*64 - (int)p_bits) / 8;\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint local_idx = tid % params.num_masks;\n"
    "            uint aidx = local_idx;\n"
    "            uint carry = 0;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uint local_digit = aidx % sz;\n"
    "                aidx /= sz;\n"
    "                uint base_digit = (i < 8)\n"
    "                    ? (uint)((params.mask_base0 >> (i * 8)) & 0xFF)\n"
    "                    : (uint)((params.mask_base1 >> ((i - 8) * 8)) & 0xFF);\n"
    "                uint sum = base_digit + local_digit + carry;\n"
    "                carry = sum / sz;\n"
    "                uint final_digit = sum % sz;\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + final_digit];\n"
    "                int pos = app_start + i;\n"
    "                int wi = 25 + (pos >> 3);\n"
    "                int bi = (pos & 7) << 3;\n"
    "                A[wi] = (A[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Byte-swap B portion (A[25..88]) from LE to BE for MD6 compression */\n"
    "    for (int i = 25; i < 89; i++) A[i] = bswap64(A[i]);\n"
    "\n"
    "    /* Run MD6 compression */\n"
    "    md6_compress_loop(A);\n"
    "\n"
    "    /* Extract output: last c=16 words of A, then take last d/w=4 words.\n"
    "     * C[0..15] = A[r*c+n-c .. r*c+n-1] = A[1737..1752]\n"
    "     * Hash = C[12..15] (last 4 uint64 words = last 256 bits = 8 uint32) */\n"
    "    ulong C[4];\n"
    "    C[0] = A[1749]; C[1] = A[1750]; C[2] = A[1751]; C[3] = A[1752];\n"
    "\n"
    "    /* Byte-swap all 4 uint64 output words to LE, split into 8 uint32 */\n"
    "    uint h[8];\n"
    "    for (int i = 0; i < 4; i++) {\n"
    "        ulong s = bswap64(C[i]);\n"
    "        h[i*2]   = (uint)s;\n"
    "        h[i*2+1] = (uint)(s >> 32);\n"
    "    }\n"
    "\n"
    "    if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                      params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                      hash_data_buf, hash_data_off,\n"
    "                      overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "        uint slot = atomic_add(hit_count, 1u);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 10;  /* 2 + 8 */\n"
    "            hits[base]   = word_idx;\n"
    "            hits[base+1] = mask_idx;\n"
    "            for (int i = 0; i < 8; i++) hits[base+2+i] = h[i];\n"
    "            mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
    "        }\n"
    "    }\n"
    "}\n"
;
