/* Auto-generated from metal_phpbb3.metal -- do not edit */
static const char metal_phpbb3_str[] =
    "/* ---- PHPBB3/phpass kernel (e455): iterated MD5 with 8-byte salt ---- */\n"
    "/* Salt buffer has \"$H$Csalt8chr\" (12 bytes). C encodes log2(iteration count).\n"
    " * Algorithm: MD5(salt[4..11] + pass), then 2^C iterations of MD5(hash + pass).\n"
    " * Password max 39 bytes (16 + 39 = 55, single MD5 block for iteration). */\n"
    "kernel void phpbb3_batch(\n"
    "    device const uint8_t    *hexhashes   [[buffer(0)]],\n"
    "    device const ushort     *hex_lens    [[buffer(1)]],\n"
    "    device const ushort     *unused2     [[buffer(2)]],\n"
    "    device const uint8_t    *salts       [[buffer(3)]],\n"
    "    device const uint       *salt_offsets [[buffer(4)]],\n"
    "    device const ushort     *salt_lens   [[buffer(5)]],\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys   [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hex_lens[word_idx];\n"
    "    if (plen > 39) return;\n"
    "    device const uint8_t *pass = hexhashes + word_idx * 256;\n"
    "\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    device const uint8_t *sd = salts + soff;\n"
    "\n"
    "    /* Iteration count passed uniformly via params (salts sorted by count on CPU) */\n"
    "    uint count = params.iter_count;\n"
    "\n"
    "    /* Step 1: MD5(salt[4..11] + password) — 8-byte salt */\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    for (int i = 0; i < 8; i++)\n"
    "        M[i >> 2] |= ((uint)sd[4 + i]) << ((i & 3) << 3);\n"
    "    for (int i = 0; i < plen; i++) {\n"
    "        int pos = 8 + i;\n"
    "        M[pos >> 2] |= ((uint)pass[i]) << ((pos & 3) << 3);\n"
    "    }\n"
    "    int total = 8 + plen;\n"
    "    M[total >> 2] |= 0x80u << ((total & 3) << 3);\n"
    "    M[14] = total * 8;\n"
    "\n"
    "    uint4 h = uint4(0x67452301, 0xEFCDAB89, 0x98BADCFE, 0x10325476);\n"
    "    md5_block_full(h, M);\n"
    "\n"
    "    /* Step 2: count iterations of MD5(hash[16] + password) */\n"
    "    /* Pre-pack M[] with password, padding, length — constant across iterations */\n"
    "    total = 16 + plen;\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    for (int i = 0; i < plen; i++) {\n"
    "        int pos = 16 + i;\n"
    "        M[pos >> 2] |= ((uint)pass[i]) << ((pos & 3) << 3);\n"
    "    }\n"
    "    M[total >> 2] |= 0x80u << ((total & 3) << 3);\n"
    "    M[14] = total * 8;\n"
    "    /* Iteration loop: only M[0..3] change (the hash digest) */\n"
    "    for (uint it = 0; it < count; it++) {\n"
    "        M[0] = h.x; M[1] = h.y; M[2] = h.z; M[3] = h.w;\n"
    "        h = uint4(0x67452301, 0xEFCDAB89, 0x98BADCFE, 0x10325476);\n"
    "        md5_block_full(h, M);\n"
    "    }\n"
    "\n"
    "    PROBE6(h, word_idx, salt_idx)\n"
    "}\n"
;
