/* Auto-generated from metal_sha512unsalted.metal -- do not edit */
static const char metal_sha512unsalted_str[] =
    "/* metal_sha512unsalted.metal — Pre-padded unsalted SHA512/SHA384 with mask expansion\n"
    " *\n"
    " * Input: 2048 pre-padded 128-byte blocks in passbuf (word_stride=128).\n"
    " *   Packed by gpu_try_pack_unsalted() in little-endian format:\n"
    " *   password at offset n_prepend, 0x80 padding, bitlen as uint32 at byte offset 120.\n"
    " *   Kernel byte-swaps 16 x uint64 words to big-endian before SHA512 compress.\n"
    " *\n"
    " * Dispatch: num_words x num_masks threads.\n"
    " * Hit stride: 6 (word_idx, mask_idx, h0_lo, h0_hi, h1_lo, h1_hi) or\n"
    " *             7 (word_idx, mask_idx, iter, h0_lo, h0_hi, h1_lo, h1_hi) when max_iter > 1\n"
    " */\n"
    "\n"
    "/* K512[], sha512_block (aliased as sha512_compress below),\n"
    " * sha512_to_hex_lc, bswap64, rotr64, hex_byte_be64\n"
    " * all provided by metal_common.metal */\n"
    "#define sha512_compress sha512_block\n"
    "\n"
    "kernel void sha512_unsalted_batch(\n"
    "    device const uchar      *words       [[buffer(0)]],\n"
    "    device const ushort     *unused_lens [[buffer(1)]],\n"
    "    device const ushort     *unused2     [[buffer(2)]],\n"
    "    device const uint8_t    *mask_desc   [[buffer(3)]],\n"
    "    device const uint       *unused3     [[buffer(4)]],\n"
    "    device const ushort     *unused4     [[buffer(5)]],\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys   [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    uint mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    /* Load pre-padded block (16 uint64 = 128 bytes, little-endian from host) */\n"
    "    device const ulong *src = (device const ulong *)(words + word_idx * 128);\n"
    "    ulong M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    /* Fill mask positions -- LE bytes within uint64 words */\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint n_total_m = n_pre + n_app;\n"
    "        uint append_combos = 1;\n"
    "        for (uint i = 0; i < n_app; i++)\n"
    "            append_combos *= mask_desc[n_pre + i];\n"
    "\n"
    "        uint prepend_idx = mask_idx / append_combos;\n"
    "        uint append_idx = mask_idx % append_combos;\n"
    "\n"
    "        if (n_pre > 0) {\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                int wi = i >> 3;\n"
    "                int bi = (i & 7) << 3;\n"
    "                M[wi] = (M[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "            }\n"
    "        }\n"
    "\n"
    "        if (n_app > 0) {\n"
    "            /* Bit-length stored at byte offset 120 = low 32 bits of M[15] (LE) */\n"
    "            int total_len = (int)(M[15] & 0xFFFFFFFFUL);\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint aidx = append_idx;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                int pos_idx = n_pre + i;\n"
    "                uint sz = mask_desc[pos_idx];\n"
    "                uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                aidx /= sz;\n"
    "                int pos = app_start + i;\n"
    "                int wi = pos >> 3;\n"
    "                int bi = (pos & 7) << 3;\n"
    "                M[wi] = (M[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Save bit-length before byte-swap.\n"
    "     * Host stores bitlen as uint32 at byte offset 120 = low 32 bits of M[15] (LE). */\n"
    "    uint bitlen = (uint)(M[15] & 0xFFFFFFFFUL);\n"
    "\n"
    "    /* Convert M[] from little-endian to big-endian for SHA512 */\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap64(M[i]);\n"
    "\n"
    "    /* Fix up padding: SHA512 stores 128-bit big-endian bit count at M[14..15] */\n"
    "    M[14] = 0;\n"
    "    M[15] = (ulong)bitlen;\n"
    "\n"
    "    /* SHA512 compress */\n"
    "    ulong state[8] = {\n"
    "        0x6a09e667f3bcc908UL, 0xbb67ae8584caa73bUL,\n"
    "        0x3c6ef372fe94f82bUL, 0xa54ff53a5f1d36f1UL,\n"
    "        0x510e527fade682d1UL, 0x9b05688c2b3e6c1fUL,\n"
    "        0x1f83d9abfb41bd6bUL, 0x5be0cd19137e2179UL\n"
    "    };\n"
    "    sha512_compress(state, M);\n"
    "\n"
    "    uint max_iter = params.max_iter;\n"
    "    uint hit_stride = (max_iter > 1) ? 7 : 6;\n"
    "\n"
    "    for (uint iter = 1; iter <= max_iter; iter++) {\n"
    "        /* Byte-swap state to LE for compact table probe */\n"
    "        ulong s0 = bswap64(state[0]), s1 = bswap64(state[1]);\n"
    "        uint hx = (uint)s0, hy = (uint)(s0 >> 32);\n"
    "        uint hz = (uint)s1, hw = (uint)(s1 >> 32);\n"
    "\n"
    "        uint4 h = uint4(hx, hy, hz, hw);\n"
    "        ulong key = (ulong(h.y) << 32) | h.x;\n"
    "        uint fp = uint(key >> 32);\n"
    "        if (fp == 0) fp = 1;\n"
    "        ulong pos = (key ^ (key >> 32)) & params.compact_mask;\n"
    "        bool found = false;\n"
    "        for (uint p = 0; p < params.max_probe && !found; p++) {\n"
    "            uint cfp = compact_fp[pos];\n"
    "            if (cfp == 0) break;\n"
    "            if (cfp == fp) {\n"
    "                uint idx = compact_idx[pos];\n"
    "                if (idx < params.hash_data_count) {\n"
    "                    ulong off = hash_data_off[idx];\n"
    "                    device const uint *ref = (device const uint *)(hash_data_buf + off);\n"
    "                    if (h.x == ref[0] && h.y == ref[1] && h.z == ref[2] && h.w == ref[3])\n"
    "                        found = true;\n"
    "                }\n"
    "            }\n"
    "            pos = (pos + 1) & params.compact_mask;\n"
    "        }\n"
    "        if (!found && params.overflow_count > 0) {\n"
    "            int lo = 0, hi2 = int(params.overflow_count) - 1;\n"
    "            while (lo <= hi2 && !found) {\n"
    "                int mid = (lo + hi2) / 2;\n"
    "                ulong mkey = overflow_keys[mid];\n"
    "                if (key < mkey) hi2 = mid - 1;\n"
    "                else if (key > mkey) lo = mid + 1;\n"
    "                else {\n"
    "                    for (int d = mid; d >= 0 && overflow_keys[d] == key && !found; d--) {\n"
    "                        device const uint *oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                        if (h.x == oref[0] && h.y == oref[1] && h.z == oref[2] && h.w == oref[3])\n"
    "                            found = true;\n"
    "                    }\n"
    "                    for (int d = mid+1; d < int(params.overflow_count) && overflow_keys[d] == key && !found; d++) {\n"
    "                        device const uint *oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                        if (h.x == oref[0] && h.y == oref[1] && h.z == oref[2] && h.w == oref[3])\n"
    "                            found = true;\n"
    "                    }\n"
    "                    break;\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "        if (found) {\n"
    "            uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "            if (slot < params.max_hits) {\n"
    "                uint base = slot * hit_stride;\n"
    "                hits[base] = word_idx; hits[base+1] = mask_idx;\n"
    "                if (hit_stride == 7) {\n"
    "                    hits[base+2] = iter;\n"
    "                    hits[base+3] = h.x; hits[base+4] = h.y;\n"
    "                    hits[base+5] = h.z; hits[base+6] = h.w;\n"
    "                } else {\n"
    "                    hits[base+2] = h.x; hits[base+3] = h.y;\n"
    "                    hits[base+4] = h.z; hits[base+5] = h.w;\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "        if (iter < max_iter) {\n"
    "            /* Hex-encode 8 BE state words into M[0..15] (128 hex chars = full block) */\n"
    "            sha512_to_hex_lc(state, M);\n"
    "            /* First compress: data block */\n"
    "            state[0] = 0x6a09e667f3bcc908UL; state[1] = 0xbb67ae8584caa73bUL;\n"
    "            state[2] = 0x3c6ef372fe94f82bUL; state[3] = 0xa54ff53a5f1d36f1UL;\n"
    "            state[4] = 0x510e527fade682d1UL; state[5] = 0x9b05688c2b3e6c1fUL;\n"
    "            state[6] = 0x1f83d9abfb41bd6bUL; state[7] = 0x5be0cd19137e2179UL;\n"
    "            sha512_compress(state, M);\n"
    "            /* Second compress: padding block */\n"
    "            M[0] = 0x8000000000000000UL;\n"
    "            for (int i = 1; i < 15; i++) M[i] = 0;\n"
    "            M[15] = 128 * 8;  /* 128 hex bytes = 1024 bits */\n"
    "            sha512_compress(state, M);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* SHA384 -- same compress as SHA512, different IV, truncated output (48 bytes) */\n"
    "kernel void sha384_unsalted_batch(\n"
    "    device const uchar      *words       [[buffer(0)]],\n"
    "    device const ushort     *unused_lens [[buffer(1)]],\n"
    "    device const ushort     *unused2     [[buffer(2)]],\n"
    "    device const uint8_t    *mask_desc   [[buffer(3)]],\n"
    "    device const uint       *unused3     [[buffer(4)]],\n"
    "    device const ushort     *unused4     [[buffer(5)]],\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys   [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    uint mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    device const ulong *src = (device const ulong *)(words + word_idx * 128);\n"
    "    ulong M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint n_total_m = n_pre + n_app;\n"
    "        uint append_combos = 1;\n"
    "        for (uint i = 0; i < n_app; i++)\n"
    "            append_combos *= mask_desc[n_pre + i];\n"
    "        uint prepend_idx = mask_idx / append_combos;\n"
    "        uint append_idx = mask_idx % append_combos;\n"
    "        if (n_pre > 0) {\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                int wi = i >> 3;\n"
    "                int bi = (i & 7) << 3;\n"
    "                M[wi] = (M[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "            }\n"
    "        }\n"
    "        if (n_app > 0) {\n"
    "            int total_len = (int)(M[15] & 0xFFFFFFFFUL);\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint aidx = append_idx;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                int pos_idx = n_pre + i;\n"
    "                uint sz = mask_desc[pos_idx];\n"
    "                uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                aidx /= sz;\n"
    "                int pos = app_start + i;\n"
    "                int wi = pos >> 3;\n"
    "                int bi = (pos & 7) << 3;\n"
    "                M[wi] = (M[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    uint bitlen = (uint)(M[15] & 0xFFFFFFFFUL);\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap64(M[i]);\n"
    "    M[14] = 0;\n"
    "    M[15] = (ulong)bitlen;\n"
    "\n"
    "    /* SHA384 IV */\n"
    "    ulong state[8] = {\n"
    "        0xcbbb9d5dc1059ed8UL, 0x629a292a367cd507UL,\n"
    "        0x9159015a3070dd17UL, 0x152fecd8f70e5939UL,\n"
    "        0x67332667ffc00b31UL, 0x8eb44a8768581511UL,\n"
    "        0xdb0c2e0d64f98fa7UL, 0x47b5481dbefa4fa4UL\n"
    "    };\n"
    "    sha512_compress(state, M);\n"
    "\n"
    "    ulong s0 = bswap64(state[0]), s1 = bswap64(state[1]);\n"
    "    uint hx = (uint)s0, hy = (uint)(s0 >> 32);\n"
    "    uint hz = (uint)s1, hw = (uint)(s1 >> 32);\n"
    "\n"
    "    uint4 h = uint4(hx, hy, hz, hw);\n"
    "    ulong key = (ulong(h.y) << 32) | h.x;\n"
    "    uint fp = uint(key >> 32);\n"
    "    if (fp == 0) fp = 1;\n"
    "    ulong pos = (key ^ (key >> 32)) & params.compact_mask;\n"
    "    for (uint p = 0; p < params.max_probe; p++) {\n"
    "        uint cfp = compact_fp[pos];\n"
    "        if (cfp == 0) break;\n"
    "        if (cfp == fp) {\n"
    "            uint idx = compact_idx[pos];\n"
    "            if (idx < params.hash_data_count) {\n"
    "                ulong off = hash_data_off[idx];\n"
    "                device const uint *ref = (device const uint *)(hash_data_buf + off);\n"
    "                if (h.x == ref[0] && h.y == ref[1] && h.z == ref[2] && h.w == ref[3]) {\n"
    "                    uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                    if (slot < params.max_hits) {\n"
    "                        uint base = slot * 6;\n"
    "                        hits[base] = word_idx; hits[base+1] = mask_idx;\n"
    "                        hits[base+2] = h.x; hits[base+3] = h.y;\n"
    "                        hits[base+4] = h.z; hits[base+5] = h.w;\n"
    "                    }\n"
    "                    return;\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "        pos = (pos + 1) & params.compact_mask;\n"
    "    }\n"
    "    if (params.overflow_count > 0) {\n"
    "        int lo = 0, hi = int(params.overflow_count) - 1;\n"
    "        while (lo <= hi) {\n"
    "            int mid = (lo + hi) / 2;\n"
    "            ulong mkey = overflow_keys[mid];\n"
    "            if (key < mkey) hi = mid - 1;\n"
    "            else if (key > mkey) lo = mid + 1;\n"
    "            else {\n"
    "                uint ooff = overflow_offsets[mid];\n"
    "                device const uint *oref = (device const uint *)(overflow_hashes + ooff);\n"
    "                if (h.x == oref[0] && h.y == oref[1] && h.z == oref[2] && h.w == oref[3]) {\n"
    "                    uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                    if (slot < params.max_hits) {\n"
    "                        uint base = slot * 6;\n"
    "                        hits[base] = word_idx; hits[base+1] = mask_idx;\n"
    "                        hits[base+2] = h.x; hits[base+3] = h.y;\n"
    "                        hits[base+4] = h.z; hits[base+5] = h.w;\n"
    "                    }\n"
    "                    return;\n"
    "                }\n"
    "                for (int d = mid-1; d >= 0 && overflow_keys[d] == key; d--) {\n"
    "                    oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (h.x == oref[0] && h.y == oref[1] && h.z == oref[2] && h.w == oref[3]) {\n"
    "                        uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                        if (slot < params.max_hits) {\n"
    "                            uint base = slot * 6;\n"
    "                            hits[base] = word_idx; hits[base+1] = mask_idx;\n"
    "                            hits[base+2] = h.x; hits[base+3] = h.y;\n"
    "                            hits[base+4] = h.z; hits[base+5] = h.w;\n"
    "                        }\n"
    "                        return;\n"
    "                    }\n"
    "                }\n"
    "                for (int d = mid+1; d < int(params.overflow_count) && overflow_keys[d] == key; d++) {\n"
    "                    oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (h.x == oref[0] && h.y == oref[1] && h.z == oref[2] && h.w == oref[3]) {\n"
    "                        uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                        if (slot < params.max_hits) {\n"
    "                            uint base = slot * 6;\n"
    "                            hits[base] = word_idx; hits[base+1] = mask_idx;\n"
    "                            hits[base+2] = h.x; hits[base+3] = h.y;\n"
    "                            hits[base+4] = h.z; hits[base+5] = h.w;\n"
    "                        }\n"
    "                        return;\n"
    "                    }\n"
    "                }\n"
    "                break;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "}\n"
;
