/* Auto-generated from metal_keccakunsalted.metal -- do not edit */
static const char metal_keccakunsalted_str[] =
    "/* metal_keccakunsalted.metal — Keccak/SHA3 unsalted with mask expansion\n"
    " *\n"
    " * Keccak-f[1600] permutation. 8 entry points:\n"
    " * Keccak-224/256/384/512 (pad 0x01) and SHA3-224/256/384/512 (pad 0x06).\n"
    " * Natively little-endian -- no byte-swap needed.\n"
    " *\n"
    " * Hit stride: 6 (word_idx, mask_idx, hx, hy, hz, hw)\n"
    " */\n"
    "\n"
    "constant ulong RC[24] = {\n"
    "    0x0000000000000001UL, 0x0000000000008082UL, 0x800000000000808aUL,\n"
    "    0x8000000080008000UL, 0x000000000000808bUL, 0x0000000080000001UL,\n"
    "    0x8000000080008081UL, 0x8000000000008009UL, 0x000000000000008aUL,\n"
    "    0x0000000000000088UL, 0x0000000080008009UL, 0x000000008000000aUL,\n"
    "    0x000000008000808bUL, 0x800000000000008bUL, 0x8000000000008089UL,\n"
    "    0x8000000000008003UL, 0x8000000000008002UL, 0x8000000000000080UL,\n"
    "    0x000000000000800aUL, 0x800000008000000aUL, 0x8000000080008081UL,\n"
    "    0x8000000000008080UL, 0x0000000080000001UL, 0x8000000080008008UL\n"
    "};\n"
    "\n"
    "constant uint ROTC[25] = {\n"
    "     0,  1, 62, 28, 27,\n"
    "    36, 44,  6, 55, 20,\n"
    "     3, 10, 43, 25, 39,\n"
    "    41, 45, 15, 21,  8,\n"
    "    18,  2, 61, 56, 14\n"
    "};\n"
    "\n"
    "static void keccak_f1600(thread ulong *st) {\n"
    "    for (int round = 0; round < 24; round++) {\n"
    "        ulong C[5], D[5];\n"
    "        for (int x = 0; x < 5; x++)\n"
    "            C[x] = st[x] ^ st[x+5] ^ st[x+10] ^ st[x+15] ^ st[x+20];\n"
    "        for (int x = 0; x < 5; x++) {\n"
    "            D[x] = C[(x+4) % 5] ^ rotate(C[(x+1) % 5], (ulong)1);\n"
    "            for (int y = 0; y < 25; y += 5)\n"
    "                st[x+y] ^= D[x];\n"
    "        }\n"
    "        ulong B[25];\n"
    "        for (int x = 0; x < 5; x++)\n"
    "            for (int y = 0; y < 5; y++)\n"
    "                B[x + 5 * ((2*y + 3*x) % 5)] = rotate(st[x*5+y], (ulong)ROTC[x*5+y]);\n"
    "        for (int x = 0; x < 5; x++)\n"
    "            for (int y = 0; y < 25; y += 5)\n"
    "                st[x+y] = B[x+y] ^ (~B[((x+1)%5)+y] & B[((x+2)%5)+y]);\n"
    "        st[0] ^= RC[round];\n"
    "    }\n"
    "}\n"
    "\n"
    "/* Fill masks into LE uint64 block */\n"
    "static void keccak_fill_masks(thread ulong *block, uint n_pre, uint n_app, uint mask_idx,\n"
    "                               device const uint8_t *mask_desc, int rate,\n"
    "                               uint num_masks, ulong mask_base0, ulong mask_base1) {\n"
    "    uint n_total_m = n_pre + n_app;\n"
    "\n"
    "    if (n_pre > 0) {\n"
    "        uint append_combos = 1;\n"
    "        for (uint i = 0; i < n_app; i++)\n"
    "            append_combos *= mask_desc[n_pre + i];\n"
    "        uint prepend_idx = (uint)(mask_idx / append_combos);\n"
    "        uint append_idx = (uint)(mask_idx % append_combos);\n"
    "\n"
    "        uint pidx = prepend_idx;\n"
    "        for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "            uint sz = mask_desc[i];\n"
    "            uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "            pidx /= sz;\n"
    "            int wi = i >> 3;\n"
    "            int bi = (i & 7) << 3;\n"
    "            block[wi] = (block[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "        }\n"
    "\n"
    "        if (n_app > 0) {\n"
    "            thread uchar *bp = (thread uchar *)block;\n"
    "            int total_len = bp[rate] | (bp[rate+1] << 8);\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint aidx = append_idx;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                int pos_idx = n_pre + i;\n"
    "                uint sz = mask_desc[pos_idx];\n"
    "                uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                aidx /= sz;\n"
    "                int pos = app_start + i;\n"
    "                int wi = pos >> 3;\n"
    "                int bi = (pos & 7) << 3;\n"
    "                block[wi] = (block[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "            }\n"
    "        }\n"
    "    } else {\n"
    "        /* Append-only (brute-force): host pre-decomposes mask_start into\n"
    "         * per-position base offsets in mask_base0/mask_base1. Kernel does\n"
    "         * fast uint32 local decomposition and adds to base with carry. */\n"
    "        thread uchar *bp = (thread uchar *)block;\n"
    "        int total_len = bp[rate] | (bp[rate+1] << 8);\n"
    "        int app_start = total_len - (int)n_app;\n"
    "        uint local_idx = mask_idx % num_masks;\n"
    "        uint aidx = local_idx;\n"
    "        uint carry = 0;\n"
    "        for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "            uint sz = mask_desc[i];\n"
    "            uint local_digit = aidx % sz;\n"
    "            aidx /= sz;\n"
    "            uint base_digit = (i < 8)\n"
    "                ? (uint)((mask_base0 >> (i * 8)) & 0xFF)\n"
    "                : (uint)((mask_base1 >> ((i - 8) * 8)) & 0xFF);\n"
    "            uint sum = base_digit + local_digit + carry;\n"
    "            carry = sum / sz;\n"
    "            uint final_digit = sum % sz;\n"
    "            uchar ch = mask_desc[n_total_m + i * 256 + final_digit];\n"
    "            int pos = app_start + i;\n"
    "            int wi = pos >> 3;\n"
    "            int bi = (pos & 7) << 3;\n"
    "            block[wi] = (block[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* Macro-expanded Keccak kernels for each rate */\n"
    "\n"
    "#define KECCAK_METAL_KERNEL(name, rate, rate_words, hash_words, hash_ulongs) \\\n"
    "kernel void name( \\\n"
    "    device const uint8_t    *words       [[buffer(0)]], \\\n"
    "    device const ushort     *unused_lens [[buffer(1)]], \\\n"
    "    device const ushort     *unused2     [[buffer(2)]], \\\n"
    "    device const uint8_t    *mask_desc   [[buffer(3)]], \\\n"
    "    device const uint       *unused3     [[buffer(4)]], \\\n"
    "    device const ushort     *unused4     [[buffer(5)]], \\\n"
    "    device const uint       *compact_fp  [[buffer(6)]], \\\n"
    "    device const uint       *compact_idx [[buffer(7)]], \\\n"
    "    constant MetalParams    &params      [[buffer(8)]], \\\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]], \\\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]], \\\n"
    "    device const ushort     *hash_data_len [[buffer(11)]], \\\n"
    "    device uint             *hits         [[buffer(12)]], \\\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]], \\\n"
    "    device const uint64_t   *overflow_keys   [[buffer(14)]], \\\n"
    "    device const uint8_t    *overflow_hashes [[buffer(15)]], \\\n"
    "    device const uint       *overflow_offsets [[buffer(16)]], \\\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]], \\\n"
    "    uint                     tid          [[thread_position_in_grid]], \\\n"
    "    uint                     lid          [[thread_position_in_threadgroup]], \\\n"
    "    uint                     tgsize       [[threads_per_threadgroup]]) \\\n"
    "{ \\\n"
    "    uint word_idx = tid / params.num_masks; \\\n"
    "    ulong mask_idx = params.mask_start + (tid % params.num_masks); \\\n"
    "    if (word_idx >= params.num_words) return; \\\n"
    "    \\\n"
    "    int stride = rate + 8; \\\n"
    "    device const ulong *src = (device const ulong *)(words + word_idx * stride); \\\n"
    "    ulong block[rate_words]; \\\n"
    "    for (int i = 0; i < rate_words; i++) block[i] = src[i]; \\\n"
    "    \\\n"
    "    if (params.n_prepend > 0 || params.n_append > 0) \\\n"
    "        keccak_fill_masks(block, params.n_prepend, params.n_append, \\\n"
    "                          mask_idx, mask_desc, rate, \\\n"
    "                          params.num_masks, params.mask_base0, params.mask_base1); \\\n"
    "    \\\n"
    "    ulong st[25]; \\\n"
    "    for (int i = 0; i < 25; i++) st[i] = 0; \\\n"
    "    for (int i = 0; i < rate_words; i++) st[i] = block[i]; \\\n"
    "    keccak_f1600(st); \\\n"
    "    \\\n"
    "    /* Extract all hash words from state (LE, no swap needed) */ \\\n"
    "    uint h[hash_words]; \\\n"
    "    for (int i = 0; i < hash_ulongs; i++) { \\\n"
    "        h[i*2]   = (uint)st[i]; \\\n"
    "        if (i*2+1 < hash_words) h[i*2+1] = (uint)(st[i] >> 32); \\\n"
    "    } \\\n"
    "    \\\n"
    "    ulong key = (ulong(h[1]) << 32) | h[0]; \\\n"
    "    uint fp = uint(key >> 32); if (fp == 0) fp = 1; \\\n"
    "    ulong pos = (key ^ (key >> 32)) & params.compact_mask; \\\n"
    "    bool found = false; \\\n"
    "    for (uint p = 0; p < params.max_probe && !found; p++) { \\\n"
    "        uint cfp = compact_fp[pos]; if (cfp == 0) break; \\\n"
    "        if (cfp == fp) { uint idx = compact_idx[pos]; \\\n"
    "            if (idx < params.hash_data_count) { \\\n"
    "                ulong off = hash_data_off[idx]; \\\n"
    "                device const uint *ref = (device const uint *)(hash_data_buf + off); \\\n"
    "                if (h[0] == ref[0] && h[1] == ref[1] && h[2] == ref[2] && h[3] == ref[3]) \\\n"
    "                    found = true; \\\n"
    "            } } \\\n"
    "        pos = (pos + 1) & params.compact_mask; \\\n"
    "    } \\\n"
    "    if (!found && params.overflow_count > 0) { \\\n"
    "        int lo = 0, hi2 = int(params.overflow_count) - 1; \\\n"
    "        while (lo <= hi2 && !found) { \\\n"
    "            int mid = (lo + hi2) / 2; ulong mkey = overflow_keys[mid]; \\\n"
    "            if (key < mkey) hi2 = mid - 1; \\\n"
    "            else if (key > mkey) lo = mid + 1; \\\n"
    "            else { \\\n"
    "                for (int d = mid; d >= 0 && overflow_keys[d] == key && !found; d--) { \\\n"
    "                    device const uint *oref = (device const uint *)(overflow_hashes + overflow_offsets[d]); \\\n"
    "                    if (h[0] == oref[0] && h[1] == oref[1] && h[2] == oref[2] && h[3] == oref[3]) \\\n"
    "                        found = true; } \\\n"
    "                for (int d = mid+1; d < int(params.overflow_count) && overflow_keys[d] == key && !found; d++) { \\\n"
    "                    device const uint *oref = (device const uint *)(overflow_hashes + overflow_offsets[d]); \\\n"
    "                    if (h[0] == oref[0] && h[1] == oref[1] && h[2] == oref[2] && h[3] == oref[3]) \\\n"
    "                        found = true; } \\\n"
    "                break; } } } \\\n"
    "    if (found) { \\\n"
    "        uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed); \\\n"
    "        if (slot < params.max_hits) { \\\n"
    "            uint base = slot * HIT_STRIDE; \\\n"
    "            hits[base] = word_idx; hits[base+1] = mask_idx; \\\n"
    "            hits[base+2] = 1; \\\n"
    "            for (int i = 0; i < hash_words; i++) hits[base+3+i] = h[i]; \\\n"
    "            for (uint _z = 3+hash_words; _z < HIT_STRIDE; _z++) hits[base+_z] = 0; } } \\\n"
    "}\n"
    "\n"
    "/* Keccak variants (pad byte 0x01, applied by host) */\n"
    "KECCAK_METAL_KERNEL(keccak224_unsalted_batch, 144, 18, 7, 4)\n"
    "KECCAK_METAL_KERNEL(keccak256_unsalted_batch, 136, 17, 8, 4)\n"
    "KECCAK_METAL_KERNEL(keccak384_unsalted_batch, 104, 13, 12, 6)\n"
    "KECCAK_METAL_KERNEL(keccak512_unsalted_batch, 72, 9, 16, 8)\n"
    "\n"
    "/* SHA3 variants (pad byte 0x06, applied by host) */\n"
    "KECCAK_METAL_KERNEL(sha3_224_unsalted_batch, 144, 18, 7, 4)\n"
    "KECCAK_METAL_KERNEL(sha3_256_unsalted_batch, 136, 17, 8, 4)\n"
    "KECCAK_METAL_KERNEL(sha3_384_unsalted_batch, 104, 13, 12, 6)\n"
    "KECCAK_METAL_KERNEL(sha3_512_unsalted_batch, 72, 9, 16, 8)\n"
;
