/* Auto-generated from metal_hmac_sha512.metal -- do not edit */
static const char metal_hmac_sha512_str[] =
    "/* metal_hmac_sha512.metal — HMAC-SHA512/SHA384 + SHA512PASSSALT/SALTPASS\n"
    " * Hit stride: 19 (3 + 16) for SHA512, 15 (3 + 12) for SHA384\n"
    " */\n"
    "\n"
    "/* K512[], sha512_block, S512_copy_bytes, S512_copy_bytes_p, S512_set_byte,\n"
    " * SHA512_IV0..7, bswap64, rotr64, SALTED_PARAMS, PROBE7_NOOVF\n"
    " * all provided by metal_common.metal */\n"
    "\n"
    "/* Probe and emit full 16-word SHA512 hash from ostate[8] */\n"
    "#define PROBE_AND_HIT_SHA512(ostate_arr, word_idx, salt_idx) { \\\n"
    "    uint _h512[16]; \\\n"
    "    for (int _i = 0; _i < 8; _i++) { \\\n"
    "        ulong _s = bswap64(ostate_arr[_i]); \\\n"
    "        _h512[_i*2] = (uint)_s; _h512[_i*2+1] = (uint)(_s >> 32); } \\\n"
    "    ulong _key = (ulong(_h512[1]) << 32) | _h512[0]; \\\n"
    "    uint _fp = uint(_key >> 32); if (_fp == 0) _fp = 1; \\\n"
    "    ulong _pos = (_key ^ (_key >> 32)) & params.compact_mask; \\\n"
    "    for (uint _p = 0; _p < params.max_probe; _p++) { \\\n"
    "        uint _cfp = compact_fp[_pos]; if (_cfp == 0) break; \\\n"
    "        if (_cfp == _fp) { uint _idx = compact_idx[_pos]; \\\n"
    "            if (_idx < params.hash_data_count) { \\\n"
    "                ulong _off = hash_data_off[_idx]; \\\n"
    "                device const uint *_ref = (device const uint *)(hash_data_buf + _off); \\\n"
    "                if (_h512[0]==_ref[0] && _h512[1]==_ref[1] && _h512[2]==_ref[2] && _h512[3]==_ref[3]) { \\\n"
    "                    uint _slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed); \\\n"
    "                    if (_slot < params.max_hits) { uint _base = _slot * 19; \\\n"
    "                        hits[_base] = word_idx; hits[_base+1] = salt_idx; hits[_base+2] = 1; \\\n"
    "                        for (int _i2=0;_i2<16;_i2++) hits[_base+3+_i2]=_h512[_i2]; } return; } } } \\\n"
    "        _pos = (_pos + 1) & params.compact_mask; } }\n"
    "\n"
    "/* Probe and emit full 12-word SHA384 hash from ostate[8] */\n"
    "#define PROBE_AND_HIT_SHA384(ostate_arr, word_idx, salt_idx) { \\\n"
    "    uint _h384[12]; \\\n"
    "    for (int _i = 0; _i < 6; _i++) { \\\n"
    "        ulong _s = bswap64(ostate_arr[_i]); \\\n"
    "        _h384[_i*2] = (uint)_s; _h384[_i*2+1] = (uint)(_s >> 32); } \\\n"
    "    ulong _key = (ulong(_h384[1]) << 32) | _h384[0]; \\\n"
    "    uint _fp = uint(_key >> 32); if (_fp == 0) _fp = 1; \\\n"
    "    ulong _pos = (_key ^ (_key >> 32)) & params.compact_mask; \\\n"
    "    for (uint _p = 0; _p < params.max_probe; _p++) { \\\n"
    "        uint _cfp = compact_fp[_pos]; if (_cfp == 0) break; \\\n"
    "        if (_cfp == _fp) { uint _idx = compact_idx[_pos]; \\\n"
    "            if (_idx < params.hash_data_count) { \\\n"
    "                ulong _off = hash_data_off[_idx]; \\\n"
    "                device const uint *_ref = (device const uint *)(hash_data_buf + _off); \\\n"
    "                if (_h384[0]==_ref[0] && _h384[1]==_ref[1] && _h384[2]==_ref[2] && _h384[3]==_ref[3]) { \\\n"
    "                    uint _slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed); \\\n"
    "                    if (_slot < params.max_hits) { uint _base = _slot * 15; \\\n"
    "                        hits[_base] = word_idx; hits[_base+1] = salt_idx; hits[_base+2] = 1; \\\n"
    "                        for (int _i2=0;_i2<12;_i2++) hits[_base+3+_i2]=_h384[_i2]; } return; } } } \\\n"
    "        _pos = (_pos + 1) & params.compact_mask; } }\n"
    "\n"
    "/* HMAC core: prepares key_block, runs inner+outer hash, probes.\n"
    " * VARIANT: 0=ksalt (key=salt,msg=pass), 1=kpass (key=pass,msg=salt)\n"
    " * IV_ARRAY: SHA512 or SHA384 IV values */\n"
    "#define HMAC_SHA512_BODY(IV0,IV1,IV2,IV3,IV4,IV5,IV6,IV7,inner_bytes) \\\n"
    "    ulong key_block[16]; \\\n"
    "    for (int i=0;i<16;i++) key_block[i]=0; \\\n"
    "    if (klen > 128) { \\\n"
    "        ulong kst[8]={IV0,IV1,IV2,IV3,IV4,IV5,IV6,IV7}; \\\n"
    "        ulong M2[16]; for (int i=0;i<16;i++) M2[i]=0; \\\n"
    "        S512_copy_bytes(M2,0,kdata,klen<128?klen:128); \\\n"
    "        if (klen<=111) { S512_set_byte(M2,klen,0x80); M2[15]=(ulong)klen*8; } \\\n"
    "        sha512_block(kst,M2); \\\n"
    "        if (klen>111) { \\\n"
    "            for (int i=0;i<16;i++) M2[i]=0; \\\n"
    "            int rem=klen-128; if (rem>0) S512_copy_bytes(M2,0,kdata+128,rem); \\\n"
    "            S512_set_byte(M2,rem,0x80); M2[15]=(ulong)klen*8; sha512_block(kst,M2); \\\n"
    "        } \\\n"
    "        for (int i=0;i<8;i++) key_block[i]=bswap64(kst[i]); \\\n"
    "        klen=64; \\\n"
    "    } else { \\\n"
    "        for (int i=0;i<klen;i++) key_block[i>>3]|=((ulong)kdata[i])<<((i&7)<<3); \\\n"
    "    } \\\n"
    "    ulong ipad[16],M[16]; \\\n"
    "    for (int i=0;i<16;i++) ipad[i]=key_block[i]^0x3636363636363636UL; \\\n"
    "    for (int i=0;i<16;i++) M[i]=bswap64(ipad[i]); \\\n"
    "    ulong istate[8]={IV0,IV1,IV2,IV3,IV4,IV5,IV6,IV7}; \\\n"
    "    sha512_block(istate,M); \\\n"
    "    for (int i=0;i<16;i++) M[i]=0; \\\n"
    "    if (mlen<=111) { \\\n"
    "        S512_copy_bytes(M,0,mdata,mlen); S512_set_byte(M,mlen,0x80); \\\n"
    "        M[15]=(ulong)(128+mlen)*8; sha512_block(istate,M); \\\n"
    "    } else { \\\n"
    "        S512_copy_bytes(M,0,mdata,mlen<128?mlen:128); \\\n"
    "        if (mlen<128) S512_set_byte(M,mlen,0x80); \\\n"
    "        sha512_block(istate,M); for (int i=0;i<16;i++) M[i]=0; \\\n"
    "        int rem=mlen-128; if (rem>0) S512_copy_bytes(M,0,mdata+128,rem); \\\n"
    "        if (mlen>=128) S512_set_byte(M,rem>0?rem:0,0x80); \\\n"
    "        M[15]=(ulong)(128+mlen)*8; sha512_block(istate,M); \\\n"
    "    } \\\n"
    "    ulong opad2[16]; \\\n"
    "    for (int i=0;i<16;i++) opad2[i]=key_block[i]^0x5c5c5c5c5c5c5c5cUL; \\\n"
    "    for (int i=0;i<16;i++) M[i]=bswap64(opad2[i]); \\\n"
    "    ulong ostate[8]={IV0,IV1,IV2,IV3,IV4,IV5,IV6,IV7}; \\\n"
    "    sha512_block(ostate,M); \\\n"
    "    for (int i=0;i<(inner_bytes/8);i++) M[i]=istate[i]; \\\n"
    "    M[inner_bytes/8]=0x8000000000000000UL; \\\n"
    "    for (int i=(inner_bytes/8)+1;i<15;i++) M[i]=0; \\\n"
    "    M[15]=(ulong)(128+inner_bytes)*8; \\\n"
    "    sha512_block(ostate,M); \\\n"
    "    ulong ss0=bswap64(ostate[0]),ss1=bswap64(ostate[1]); \\\n"
    "    uint hx=(uint)ss0,hy=(uint)(ss0>>32),hz=(uint)ss1,hw=(uint)(ss1>>32);\n"
    "\n"
    "kernel void hmac_sha512_ksalt_batch(SALTED_PARAMS) {\n"
    "    uint word_idx=tid/params.num_salts; uint salt_idx=params.salt_start+(tid%params.num_salts);\n"
    "    if (word_idx>=params.num_words) return;\n"
    "    int mlen=hexlens[word_idx]; device const uint8_t *mdata=hexhashes+word_idx*256;\n"
    "    uint soff=salt_offsets[salt_idx]; int klen=salt_lens[salt_idx];\n"
    "    device const uint8_t *kdata=salts+soff;\n"
    "    HMAC_SHA512_BODY(SHA512_IV0,SHA512_IV1,SHA512_IV2,SHA512_IV3,SHA512_IV4,SHA512_IV5,SHA512_IV6,SHA512_IV7,64)\n"
    "    PROBE_AND_HIT_SHA512(ostate,word_idx,salt_idx)\n"
    "}\n"
    "\n"
    "kernel void hmac_sha512_kpass_batch(SALTED_PARAMS) {\n"
    "    uint word_idx=tid/params.num_salts; uint salt_idx=params.salt_start+(tid%params.num_salts);\n"
    "    if (word_idx>=params.num_words) return;\n"
    "    int klen=hexlens[word_idx]; device const uint8_t *kdata=hexhashes+word_idx*256;\n"
    "    uint soff=salt_offsets[salt_idx]; int mlen=salt_lens[salt_idx];\n"
    "    device const uint8_t *mdata=salts+soff;\n"
    "    HMAC_SHA512_BODY(SHA512_IV0,SHA512_IV1,SHA512_IV2,SHA512_IV3,SHA512_IV4,SHA512_IV5,SHA512_IV6,SHA512_IV7,64)\n"
    "    PROBE_AND_HIT_SHA512(ostate,word_idx,salt_idx)\n"
    "}\n"
    "\n"
    "#define SHA384_IV0 0xcbbb9d5dc1059ed8UL\n"
    "#define SHA384_IV1 0x629a292a367cd507UL\n"
    "#define SHA384_IV2 0x9159015a3070dd17UL\n"
    "#define SHA384_IV3 0x152fecd8f70e5939UL\n"
    "#define SHA384_IV4 0x67332667ffc00b31UL\n"
    "#define SHA384_IV5 0x8eb44a8768581511UL\n"
    "#define SHA384_IV6 0xdb0c2e0d64f98fa7UL\n"
    "#define SHA384_IV7 0x47b5481dbefa4fa4UL\n"
    "\n"
    "kernel void hmac_sha384_ksalt_batch(SALTED_PARAMS) {\n"
    "    uint word_idx=tid/params.num_salts; uint salt_idx=params.salt_start+(tid%params.num_salts);\n"
    "    if (word_idx>=params.num_words) return;\n"
    "    int mlen=hexlens[word_idx]; device const uint8_t *mdata=hexhashes+word_idx*256;\n"
    "    uint soff=salt_offsets[salt_idx]; int klen=salt_lens[salt_idx];\n"
    "    device const uint8_t *kdata=salts+soff;\n"
    "    HMAC_SHA512_BODY(SHA384_IV0,SHA384_IV1,SHA384_IV2,SHA384_IV3,SHA384_IV4,SHA384_IV5,SHA384_IV6,SHA384_IV7,48)\n"
    "    PROBE_AND_HIT_SHA384(ostate,word_idx,salt_idx)\n"
    "}\n"
    "\n"
    "kernel void hmac_sha384_kpass_batch(SALTED_PARAMS) {\n"
    "    uint word_idx=tid/params.num_salts; uint salt_idx=params.salt_start+(tid%params.num_salts);\n"
    "    if (word_idx>=params.num_words) return;\n"
    "    int klen=hexlens[word_idx]; device const uint8_t *kdata=hexhashes+word_idx*256;\n"
    "    uint soff=salt_offsets[salt_idx]; int mlen=salt_lens[salt_idx];\n"
    "    device const uint8_t *mdata=salts+soff;\n"
    "    HMAC_SHA512_BODY(SHA384_IV0,SHA384_IV1,SHA384_IV2,SHA384_IV3,SHA384_IV4,SHA384_IV5,SHA384_IV6,SHA384_IV7,48)\n"
    "    PROBE_AND_HIT_SHA384(ostate,word_idx,salt_idx)\n"
    "}\n"
    "\n"
    "/* SHA512(pass + salt) */\n"
    "kernel void sha512passsalt_batch(SALTED_PARAMS) {\n"
    "    uint word_idx=tid/params.num_salts; uint salt_idx=params.salt_start+(tid%params.num_salts);\n"
    "    if (word_idx>=params.num_words) return;\n"
    "    int plen=hexlens[word_idx]; device const uint8_t *pass=hexhashes+word_idx*256;\n"
    "    uint soff=salt_offsets[salt_idx]; int slen=salt_lens[salt_idx];\n"
    "    int total_len=plen+slen;\n"
    "    ulong state[8]={SHA512_IV0,SHA512_IV1,SHA512_IV2,SHA512_IV3,SHA512_IV4,SHA512_IV5,SHA512_IV6,SHA512_IV7};\n"
    "    ulong M[16]; for (int i=0;i<16;i++) M[i]=0;\n"
    "    if (total_len<=111) {\n"
    "        S512_copy_bytes(M,0,pass,plen); S512_copy_bytes(M,plen,salts+soff,slen);\n"
    "        S512_set_byte(M,total_len,0x80); M[15]=(ulong)total_len*8;\n"
    "        sha512_block(state,M);\n"
    "    } else {\n"
    "        int pb1=plen<128?plen:128; S512_copy_bytes(M,0,pass,pb1);\n"
    "        int sb1=128-pb1; if (sb1>slen) sb1=slen;\n"
    "        if (sb1>0) S512_copy_bytes(M,pb1,salts+soff,sb1);\n"
    "        if (total_len<128) S512_set_byte(M,total_len,0x80);\n"
    "        sha512_block(state,M); for (int i=0;i<16;i++) M[i]=0;\n"
    "        int p2=0; int pb2=plen-pb1;\n"
    "        if (pb2>0) { S512_copy_bytes(M,0,pass+pb1,pb2); p2=pb2; }\n"
    "        int sb2=slen-sb1; if (sb2>0) { S512_copy_bytes(M,p2,salts+soff+sb1,sb2); p2+=sb2; }\n"
    "        if (total_len>=128) S512_set_byte(M,p2,0x80);\n"
    "        M[15]=(ulong)total_len*8; sha512_block(state,M);\n"
    "    }\n"
    "    PROBE_AND_HIT_SHA512(state,word_idx,salt_idx)\n"
    "}\n"
    "\n"
    "/* SHA512(salt + pass) */\n"
    "kernel void sha512saltpass_batch(SALTED_PARAMS) {\n"
    "    uint word_idx=tid/params.num_salts; uint salt_idx=params.salt_start+(tid%params.num_salts);\n"
    "    if (word_idx>=params.num_words) return;\n"
    "    int plen=hexlens[word_idx]; device const uint8_t *pass=hexhashes+word_idx*256;\n"
    "    uint soff=salt_offsets[salt_idx]; int slen=salt_lens[salt_idx];\n"
    "    int total_len=slen+plen;\n"
    "    ulong state[8]={SHA512_IV0,SHA512_IV1,SHA512_IV2,SHA512_IV3,SHA512_IV4,SHA512_IV5,SHA512_IV6,SHA512_IV7};\n"
    "    ulong M[16]; for (int i=0;i<16;i++) M[i]=0;\n"
    "    if (total_len<=111) {\n"
    "        S512_copy_bytes(M,0,salts+soff,slen); S512_copy_bytes(M,slen,pass,plen);\n"
    "        S512_set_byte(M,total_len,0x80); M[15]=(ulong)total_len*8;\n"
    "        sha512_block(state,M);\n"
    "    } else {\n"
    "        int sb1=slen<128?slen:128; S512_copy_bytes(M,0,salts+soff,sb1);\n"
    "        int pb1=128-sb1; if (pb1>plen) pb1=plen;\n"
    "        if (pb1>0) S512_copy_bytes(M,sb1,pass,pb1);\n"
    "        if (total_len<128) S512_set_byte(M,total_len,0x80);\n"
    "        sha512_block(state,M); for (int i=0;i<16;i++) M[i]=0;\n"
    "        int p2=0; int sb2=slen-sb1;\n"
    "        if (sb2>0) { S512_copy_bytes(M,0,salts+soff+sb1,sb2); p2=sb2; }\n"
    "        int pb2=plen-pb1; if (pb2>0) { S512_copy_bytes(M,p2,pass+pb1,pb2); p2+=pb2; }\n"
    "        if (total_len>=128) S512_set_byte(M,p2,0x80);\n"
    "        M[15]=(ulong)total_len*8; sha512_block(state,M);\n"
    "    }\n"
    "    PROBE_AND_HIT_SHA512(state,word_idx,salt_idx)\n"
    "}\n"
;
