/* Auto-generated from metal_md4unsalted.metal -- do not edit */
static const char metal_md4unsalted_str[] =
    "/* metal_md4unsalted.metal — Pre-padded unsalted MD4 with mask expansion\n"
    " *\n"
    " * Input: 4096 pre-padded 64-byte M[] blocks (word_stride=64).\n"
    " * Dispatch: num_words × num_masks threads.\n"
    " * Hit stride: 6 (word_idx, mask_idx, hx, hy, hz, hw)\n"
    " */\n"
    "\n"
    "/* Fully unrolled MD4 compress — RFC 1320\n"
    " * Round 1: F(b,c,d) = (b&c)|(~b&d),       no constant\n"
    " * Round 2: G(b,c,d) = (b&c)|(b&d)|(c&d),  constant 0x5A827999\n"
    " * Round 3: H(b,c,d) = b^c^d,               constant 0x6ED9EBA1\n"
    " */\n"
    "static void md4_compress(thread uint *hx, thread uint *hy, thread uint *hz, thread uint *hw, thread uint *M) {\n"
    "    uint a = *hx, b = *hy, c = *hz, d = *hw;\n"
    "    /* Round 1: F(b,c,d) = (b&c)|(~b&d), rotations: 3,7,11,19 */\n"
    "    a += ((b&c)|(~b&d)) + M[ 0]; a = ((a<< 3)|(a>>29));\n"
    "    d += ((a&b)|(~a&c)) + M[ 1]; d = ((d<< 7)|(d>>25));\n"
    "    c += ((d&a)|(~d&b)) + M[ 2]; c = ((c<<11)|(c>>21));\n"
    "    b += ((c&d)|(~c&a)) + M[ 3]; b = ((b<<19)|(b>>13));\n"
    "    a += ((b&c)|(~b&d)) + M[ 4]; a = ((a<< 3)|(a>>29));\n"
    "    d += ((a&b)|(~a&c)) + M[ 5]; d = ((d<< 7)|(d>>25));\n"
    "    c += ((d&a)|(~d&b)) + M[ 6]; c = ((c<<11)|(c>>21));\n"
    "    b += ((c&d)|(~c&a)) + M[ 7]; b = ((b<<19)|(b>>13));\n"
    "    a += ((b&c)|(~b&d)) + M[ 8]; a = ((a<< 3)|(a>>29));\n"
    "    d += ((a&b)|(~a&c)) + M[ 9]; d = ((d<< 7)|(d>>25));\n"
    "    c += ((d&a)|(~d&b)) + M[10]; c = ((c<<11)|(c>>21));\n"
    "    b += ((c&d)|(~c&a)) + M[11]; b = ((b<<19)|(b>>13));\n"
    "    a += ((b&c)|(~b&d)) + M[12]; a = ((a<< 3)|(a>>29));\n"
    "    d += ((a&b)|(~a&c)) + M[13]; d = ((d<< 7)|(d>>25));\n"
    "    c += ((d&a)|(~d&b)) + M[14]; c = ((c<<11)|(c>>21));\n"
    "    b += ((c&d)|(~c&a)) + M[15]; b = ((b<<19)|(b>>13));\n"
    "    /* Round 2: G(b,c,d) = (b&c)|(b&d)|(c&d), constant 0x5A827999\n"
    "     * Message order: 0,4,8,12,1,5,9,13,2,6,10,14,3,7,11,15 */\n"
    "    a += ((b&c)|(b&d)|(c&d)) + M[ 0] + 0x5A827999u; a = ((a<< 3)|(a>>29));\n"
    "    d += ((a&b)|(a&c)|(b&c)) + M[ 4] + 0x5A827999u; d = ((d<< 5)|(d>>27));\n"
    "    c += ((d&a)|(d&b)|(a&b)) + M[ 8] + 0x5A827999u; c = ((c<< 9)|(c>>23));\n"
    "    b += ((c&d)|(c&a)|(d&a)) + M[12] + 0x5A827999u; b = ((b<<13)|(b>>19));\n"
    "    a += ((b&c)|(b&d)|(c&d)) + M[ 1] + 0x5A827999u; a = ((a<< 3)|(a>>29));\n"
    "    d += ((a&b)|(a&c)|(b&c)) + M[ 5] + 0x5A827999u; d = ((d<< 5)|(d>>27));\n"
    "    c += ((d&a)|(d&b)|(a&b)) + M[ 9] + 0x5A827999u; c = ((c<< 9)|(c>>23));\n"
    "    b += ((c&d)|(c&a)|(d&a)) + M[13] + 0x5A827999u; b = ((b<<13)|(b>>19));\n"
    "    a += ((b&c)|(b&d)|(c&d)) + M[ 2] + 0x5A827999u; a = ((a<< 3)|(a>>29));\n"
    "    d += ((a&b)|(a&c)|(b&c)) + M[ 6] + 0x5A827999u; d = ((d<< 5)|(d>>27));\n"
    "    c += ((d&a)|(d&b)|(a&b)) + M[10] + 0x5A827999u; c = ((c<< 9)|(c>>23));\n"
    "    b += ((c&d)|(c&a)|(d&a)) + M[14] + 0x5A827999u; b = ((b<<13)|(b>>19));\n"
    "    a += ((b&c)|(b&d)|(c&d)) + M[ 3] + 0x5A827999u; a = ((a<< 3)|(a>>29));\n"
    "    d += ((a&b)|(a&c)|(b&c)) + M[ 7] + 0x5A827999u; d = ((d<< 5)|(d>>27));\n"
    "    c += ((d&a)|(d&b)|(a&b)) + M[11] + 0x5A827999u; c = ((c<< 9)|(c>>23));\n"
    "    b += ((c&d)|(c&a)|(d&a)) + M[15] + 0x5A827999u; b = ((b<<13)|(b>>19));\n"
    "    /* Round 3: H(b,c,d) = b^c^d, constant 0x6ED9EBA1\n"
    "     * Message order: 0,8,4,12,2,10,6,14,1,9,5,13,3,11,7,15 */\n"
    "    a += (b^c^d) + M[ 0] + 0x6ED9EBA1u; a = ((a<< 3)|(a>>29));\n"
    "    d += (a^b^c) + M[ 8] + 0x6ED9EBA1u; d = ((d<< 9)|(d>>23));\n"
    "    c += (d^a^b) + M[ 4] + 0x6ED9EBA1u; c = ((c<<11)|(c>>21));\n"
    "    b += (c^d^a) + M[12] + 0x6ED9EBA1u; b = ((b<<15)|(b>>17));\n"
    "    a += (b^c^d) + M[ 2] + 0x6ED9EBA1u; a = ((a<< 3)|(a>>29));\n"
    "    d += (a^b^c) + M[10] + 0x6ED9EBA1u; d = ((d<< 9)|(d>>23));\n"
    "    c += (d^a^b) + M[ 6] + 0x6ED9EBA1u; c = ((c<<11)|(c>>21));\n"
    "    b += (c^d^a) + M[14] + 0x6ED9EBA1u; b = ((b<<15)|(b>>17));\n"
    "    a += (b^c^d) + M[ 1] + 0x6ED9EBA1u; a = ((a<< 3)|(a>>29));\n"
    "    d += (a^b^c) + M[ 9] + 0x6ED9EBA1u; d = ((d<< 9)|(d>>23));\n"
    "    c += (d^a^b) + M[ 5] + 0x6ED9EBA1u; c = ((c<<11)|(c>>21));\n"
    "    b += (c^d^a) + M[13] + 0x6ED9EBA1u; b = ((b<<15)|(b>>17));\n"
    "    a += (b^c^d) + M[ 3] + 0x6ED9EBA1u; a = ((a<< 3)|(a>>29));\n"
    "    d += (a^b^c) + M[11] + 0x6ED9EBA1u; d = ((d<< 9)|(d>>23));\n"
    "    c += (d^a^b) + M[ 7] + 0x6ED9EBA1u; c = ((c<<11)|(c>>21));\n"
    "    b += (c^d^a) + M[15] + 0x6ED9EBA1u; b = ((b<<15)|(b>>17));\n"
    "    *hx += a; *hy += b; *hz += c; *hw += d;\n"
    "}\n"
    "\n"
    "kernel void md4_unsalted_batch(\n"
    "    device const uint       *words       [[buffer(0)]],\n"
    "    device const ushort     *unused_lens [[buffer(1)]],\n"
    "    device const ushort     *unused2     [[buffer(2)]],\n"
    "    device const uint8_t    *mask_desc   [[buffer(3)]],\n"
    "    device const uint       *unused3     [[buffer(4)]],\n"
    "    device const ushort     *unused4     [[buffer(5)]],\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys   [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    uint mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    device const uint *src = words + word_idx * 16;\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint n_total_m = n_pre + n_app;\n"
    "        uint append_combos = 1;\n"
    "        for (uint i = 0; i < n_app; i++)\n"
    "            append_combos *= mask_desc[n_pre + i];\n"
    "\n"
    "        uint prepend_idx = mask_idx / append_combos;\n"
    "        uint append_idx = mask_idx % append_combos;\n"
    "\n"
    "        if (n_pre > 0) {\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                M[i >> 2] = (M[i >> 2] & ~(0xFFu << ((i & 3) << 3)))\n"
    "                           | ((uint)ch << ((i & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "\n"
    "        if (n_app > 0) {\n"
    "            int total_len = M[14] >> 3;\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint aidx = append_idx;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                int pos_idx = n_pre + i;\n"
    "                uint sz = mask_desc[pos_idx];\n"
    "                uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                aidx /= sz;\n"
    "                int pos = app_start + i;\n"
    "                M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                             | ((uint)ch << ((pos & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* MD4 compress (single block, fully unrolled) */\n"
    "    uint hx = 0x67452301u, hy = 0xEFCDAB89u, hz = 0x98BADCFEu, hw = 0x10325476u;\n"
    "    md4_compress(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "    /* Probe compact table — inline (same as md5unsalted) */\n"
    "    uint4 h = uint4(hx, hy, hz, hw);\n"
    "    ulong key = (ulong(h.y) << 32) | h.x;\n"
    "    uint fp = uint(key >> 32);\n"
    "    if (fp == 0) fp = 1;\n"
    "    ulong pos = (key ^ (key >> 32)) & params.compact_mask;\n"
    "    for (uint p = 0; p < params.max_probe; p++) {\n"
    "        uint cfp = compact_fp[pos];\n"
    "        if (cfp == 0) break;\n"
    "        if (cfp == fp) {\n"
    "            uint idx = compact_idx[pos];\n"
    "            if (idx < params.hash_data_count) {\n"
    "                ulong off = hash_data_off[idx];\n"
    "                device const uint *ref = (device const uint *)(hash_data_buf + off);\n"
    "                if (h.x == ref[0] && h.y == ref[1] && h.z == ref[2] && h.w == ref[3]) {\n"
    "                    uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                    if (slot < params.max_hits) {\n"
    "                        uint base = slot * 6;\n"
    "                        hits[base] = word_idx; hits[base+1] = mask_idx;\n"
    "                        hits[base+2] = h.x; hits[base+3] = h.y;\n"
    "                        hits[base+4] = h.z; hits[base+5] = h.w;\n"
    "                    }\n"
    "                    return;\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "        pos = (pos + 1) & params.compact_mask;\n"
    "    }\n"
    "    if (params.overflow_count > 0) {\n"
    "        int lo = 0, hi = int(params.overflow_count) - 1;\n"
    "        while (lo <= hi) {\n"
    "            int mid = (lo + hi) / 2;\n"
    "            ulong mkey = overflow_keys[mid];\n"
    "            if (key < mkey) hi = mid - 1;\n"
    "            else if (key > mkey) lo = mid + 1;\n"
    "            else {\n"
    "                uint ooff = overflow_offsets[mid];\n"
    "                device const uint *oref = (device const uint *)(overflow_hashes + ooff);\n"
    "                if (h.x == oref[0] && h.y == oref[1] && h.z == oref[2] && h.w == oref[3]) {\n"
    "                    uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                    if (slot < params.max_hits) {\n"
    "                        uint base = slot * 6;\n"
    "                        hits[base] = word_idx; hits[base+1] = mask_idx;\n"
    "                        hits[base+2] = h.x; hits[base+3] = h.y;\n"
    "                        hits[base+4] = h.z; hits[base+5] = h.w;\n"
    "                    }\n"
    "                    return;\n"
    "                }\n"
    "                for (int d = mid-1; d >= 0 && overflow_keys[d] == key; d--) {\n"
    "                    oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (h.x == oref[0] && h.y == oref[1] && h.z == oref[2] && h.w == oref[3]) {\n"
    "                        uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                        if (slot < params.max_hits) {\n"
    "                            uint base = slot * 6;\n"
    "                            hits[base] = word_idx; hits[base+1] = mask_idx;\n"
    "                            hits[base+2] = h.x; hits[base+3] = h.y;\n"
    "                            hits[base+4] = h.z; hits[base+5] = h.w;\n"
    "                        }\n"
    "                        return;\n"
    "                    }\n"
    "                }\n"
    "                for (int d = mid+1; d < int(params.overflow_count) && overflow_keys[d] == key; d++) {\n"
    "                    oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (h.x == oref[0] && h.y == oref[1] && h.z == oref[2] && h.w == oref[3]) {\n"
    "                        uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                        if (slot < params.max_hits) {\n"
    "                            uint base = slot * 6;\n"
    "                            hits[base] = word_idx; hits[base+1] = mask_idx;\n"
    "                            hits[base+2] = h.x; hits[base+3] = h.y;\n"
    "                            hits[base+4] = h.z; hits[base+5] = h.w;\n"
    "                        }\n"
    "                        return;\n"
    "                    }\n"
    "                }\n"
    "                break;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* MD4UTF16 (NTLM-style): MD4 of UTF-16LE zero-extended password.\n"
    " * Host packs UTF-16LE (each byte → byte,0x00) with doubled offsets.\n"
    " * Mask positions are doubled: logical char i → byte 2*i in the block. */\n"
    "kernel void md4utf16_unsalted_batch(\n"
    "    device const uint       *words       [[buffer(0)]],\n"
    "    device const ushort     *unused_lens [[buffer(1)]],\n"
    "    device const ushort     *unused2     [[buffer(2)]],\n"
    "    device const uint8_t    *mask_desc   [[buffer(3)]],\n"
    "    device const uint       *unused3     [[buffer(4)]],\n"
    "    device const ushort     *unused4     [[buffer(5)]],\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys   [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    uint mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    device const uint *src = words + word_idx * 16;\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint n_total_m = n_pre + n_app;\n"
    "        uint append_combos = 1;\n"
    "        for (uint i = 0; i < n_app; i++)\n"
    "            append_combos *= mask_desc[n_pre + i];\n"
    "\n"
    "        uint prepend_idx = mask_idx / append_combos;\n"
    "        uint append_idx = mask_idx % append_combos;\n"
    "\n"
    "        /* Fill prepend: logical char i → UTF-16LE byte 2*i */\n"
    "        if (n_pre > 0) {\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                int pos = 2 * i;\n"
    "                M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                             | ((uint)ch << ((pos & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "\n"
    "        /* Fill append: total UTF-16LE byte length from M[14]/8,\n"
    "         * append starts at total_bytes - 2*n_app */\n"
    "        if (n_app > 0) {\n"
    "            int total_bytes = M[14] >> 3;\n"
    "            int app_start = total_bytes - 2 * (int)n_app;\n"
    "            uint aidx = append_idx;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                int pos_idx = n_pre + i;\n"
    "                uint sz = mask_desc[pos_idx];\n"
    "                uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                aidx /= sz;\n"
    "                int pos = app_start + 2 * i;\n"
    "                M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                             | ((uint)ch << ((pos & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    uint hx = 0x67452301u, hy = 0xEFCDAB89u, hz = 0x98BADCFEu, hw = 0x10325476u;\n"
    "    md4_compress(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "    uint4 h = uint4(hx, hy, hz, hw);\n"
    "    ulong key = (ulong(h.y) << 32) | h.x;\n"
    "    uint fp = uint(key >> 32);\n"
    "    if (fp == 0) fp = 1;\n"
    "    ulong pos = (key ^ (key >> 32)) & params.compact_mask;\n"
    "    for (uint p = 0; p < params.max_probe; p++) {\n"
    "        uint cfp = compact_fp[pos];\n"
    "        if (cfp == 0) break;\n"
    "        if (cfp == fp) {\n"
    "            uint idx = compact_idx[pos];\n"
    "            if (idx < params.hash_data_count) {\n"
    "                ulong off = hash_data_off[idx];\n"
    "                device const uint *ref = (device const uint *)(hash_data_buf + off);\n"
    "                if (h.x == ref[0] && h.y == ref[1] && h.z == ref[2] && h.w == ref[3]) {\n"
    "                    uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                    if (slot < params.max_hits) {\n"
    "                        uint base = slot * 6;\n"
    "                        hits[base] = word_idx; hits[base+1] = mask_idx;\n"
    "                        hits[base+2] = h.x; hits[base+3] = h.y;\n"
    "                        hits[base+4] = h.z; hits[base+5] = h.w;\n"
    "                    }\n"
    "                    return;\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "        pos = (pos + 1) & params.compact_mask;\n"
    "    }\n"
    "    if (params.overflow_count > 0) {\n"
    "        int lo = 0, hi = int(params.overflow_count) - 1;\n"
    "        while (lo <= hi) {\n"
    "            int mid = (lo + hi) / 2;\n"
    "            ulong mkey = overflow_keys[mid];\n"
    "            if (key < mkey) hi = mid - 1;\n"
    "            else if (key > mkey) lo = mid + 1;\n"
    "            else {\n"
    "                uint ooff = overflow_offsets[mid];\n"
    "                device const uint *oref = (device const uint *)(overflow_hashes + ooff);\n"
    "                if (h.x == oref[0] && h.y == oref[1] && h.z == oref[2] && h.w == oref[3]) {\n"
    "                    uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                    if (slot < params.max_hits) {\n"
    "                        uint base = slot * 6;\n"
    "                        hits[base] = word_idx; hits[base+1] = mask_idx;\n"
    "                        hits[base+2] = h.x; hits[base+3] = h.y;\n"
    "                        hits[base+4] = h.z; hits[base+5] = h.w;\n"
    "                    }\n"
    "                    return;\n"
    "                }\n"
    "                for (int d = mid-1; d >= 0 && overflow_keys[d] == key; d--) {\n"
    "                    oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (h.x == oref[0] && h.y == oref[1] && h.z == oref[2] && h.w == oref[3]) {\n"
    "                        uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                        if (slot < params.max_hits) {\n"
    "                            uint base = slot * 6;\n"
    "                            hits[base] = word_idx; hits[base+1] = mask_idx;\n"
    "                            hits[base+2] = h.x; hits[base+3] = h.y;\n"
    "                            hits[base+4] = h.z; hits[base+5] = h.w;\n"
    "                        }\n"
    "                        return;\n"
    "                    }\n"
    "                }\n"
    "                for (int d = mid+1; d < int(params.overflow_count) && overflow_keys[d] == key; d++) {\n"
    "                    oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (h.x == oref[0] && h.y == oref[1] && h.z == oref[2] && h.w == oref[3]) {\n"
    "                        uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                        if (slot < params.max_hits) {\n"
    "                            uint base = slot * 6;\n"
    "                            hits[base] = word_idx; hits[base+1] = mask_idx;\n"
    "                            hits[base+2] = h.x; hits[base+3] = h.y;\n"
    "                            hits[base+4] = h.z; hits[base+5] = h.w;\n"
    "                        }\n"
    "                        return;\n"
    "                    }\n"
    "                }\n"
    "                break;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "}\n"
;
