/* Auto-generated from metal_blake2s256unsalted.metal -- do not edit */
static const char metal_blake2s256unsalted_str[] =
    "/* metal_blake2s256unsalted.metal — Pre-padded unsalted BLAKE2S-256 with mask expansion\n"
    " *\n"
    " * Input: 4096 pre-padded 64-byte blocks in passbuf (word_stride=64).\n"
    " *   Packed by gpu_try_pack_unsalted(): password bytes at offset n_prepend,\n"
    " *   total_len stored as bitlen at M[14] (extract byte len = M[14]>>3).\n"
    " *   BLAKE2S uses its own padding (no 0x80/bitlen), so the packer just stores\n"
    " *   the password and length — the kernel handles BLAKE2S-specific finalization.\n"
    " *\n"
    " * Dispatch: num_words x num_masks threads.\n"
    " * Hit stride: 6 (word_idx, mask_idx, h0, h1, h2, h3)\n"
    " */\n"
    "\n"
    "constant uint B2S_IV[8] = {\n"
    "    0x6A09E667u, 0xBB67AE85u, 0x3C6EF372u, 0xA54FF53Au,\n"
    "    0x510E527Fu, 0x9B05688Cu, 0x1F83D9ABu, 0x5BE0CD19u\n"
    "};\n"
    "\n"
    "constant uchar B2S_SIGMA[10][16] = {\n"
    "    { 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15 },\n"
    "    { 14,10,4,8,9,15,13,6,1,12,0,2,11,7,5,3 },\n"
    "    { 11,8,12,0,5,2,15,13,10,14,3,6,7,1,9,4 },\n"
    "    { 7,9,3,1,13,12,11,14,2,6,5,10,4,0,15,8 },\n"
    "    { 9,0,5,7,2,4,10,15,14,1,11,12,6,8,3,13 },\n"
    "    { 2,12,6,10,0,11,8,3,4,13,7,5,15,14,1,9 },\n"
    "    { 12,5,1,15,14,13,4,10,0,7,6,3,9,2,8,11 },\n"
    "    { 13,11,7,14,12,1,3,9,5,0,15,4,8,6,2,10 },\n"
    "    { 6,15,14,9,11,3,0,8,12,2,13,7,1,4,10,5 },\n"
    "    { 10,2,8,4,7,6,1,5,15,11,9,14,3,12,13,0 }\n"
    "};\n"
    "\n"
    "static void b2s_compress(thread uint *h, thread const uchar *block, ulong counter, int last) {\n"
    "    uint v[16], m[16];\n"
    "    for (int i = 0; i < 8; i++) { v[i] = h[i]; v[i+8] = B2S_IV[i]; }\n"
    "    v[12] ^= (uint)counter;\n"
    "    v[13] ^= (uint)(counter >> 32);\n"
    "    if (last) v[14] = ~v[14];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        m[i] = ((uint)block[i*4]) | ((uint)block[i*4+1]<<8) |\n"
    "               ((uint)block[i*4+2]<<16) | ((uint)block[i*4+3]<<24);\n"
    "    for (int r = 0; r < 10; r++) {\n"
    "        constant const uchar *s = B2S_SIGMA[r];\n"
    "        v[0]+=v[4]+m[s[0]]; v[12]=rotate(v[12]^v[0],16u); v[8]+=v[12]; v[4]=rotate(v[4]^v[8],20u);\n"
    "        v[0]+=v[4]+m[s[1]]; v[12]=rotate(v[12]^v[0],24u); v[8]+=v[12]; v[4]=rotate(v[4]^v[8],25u);\n"
    "        v[1]+=v[5]+m[s[2]]; v[13]=rotate(v[13]^v[1],16u); v[9]+=v[13]; v[5]=rotate(v[5]^v[9],20u);\n"
    "        v[1]+=v[5]+m[s[3]]; v[13]=rotate(v[13]^v[1],24u); v[9]+=v[13]; v[5]=rotate(v[5]^v[9],25u);\n"
    "        v[2]+=v[6]+m[s[4]]; v[14]=rotate(v[14]^v[2],16u); v[10]+=v[14]; v[6]=rotate(v[6]^v[10],20u);\n"
    "        v[2]+=v[6]+m[s[5]]; v[14]=rotate(v[14]^v[2],24u); v[10]+=v[14]; v[6]=rotate(v[6]^v[10],25u);\n"
    "        v[3]+=v[7]+m[s[6]]; v[15]=rotate(v[15]^v[3],16u); v[11]+=v[15]; v[7]=rotate(v[7]^v[11],20u);\n"
    "        v[3]+=v[7]+m[s[7]]; v[15]=rotate(v[15]^v[3],24u); v[11]+=v[15]; v[7]=rotate(v[7]^v[11],25u);\n"
    "        v[0]+=v[5]+m[s[8]]; v[15]=rotate(v[15]^v[0],16u); v[10]+=v[15]; v[5]=rotate(v[5]^v[10],20u);\n"
    "        v[0]+=v[5]+m[s[9]]; v[15]=rotate(v[15]^v[0],24u); v[10]+=v[15]; v[5]=rotate(v[5]^v[10],25u);\n"
    "        v[1]+=v[6]+m[s[10]]; v[12]=rotate(v[12]^v[1],16u); v[11]+=v[12]; v[6]=rotate(v[6]^v[11],20u);\n"
    "        v[1]+=v[6]+m[s[11]]; v[12]=rotate(v[12]^v[1],24u); v[11]+=v[12]; v[6]=rotate(v[6]^v[11],25u);\n"
    "        v[2]+=v[7]+m[s[12]]; v[13]=rotate(v[13]^v[2],16u); v[8]+=v[13]; v[7]=rotate(v[7]^v[8],20u);\n"
    "        v[2]+=v[7]+m[s[13]]; v[13]=rotate(v[13]^v[2],24u); v[8]+=v[13]; v[7]=rotate(v[7]^v[8],25u);\n"
    "        v[3]+=v[4]+m[s[14]]; v[14]=rotate(v[14]^v[3],16u); v[9]+=v[14]; v[4]=rotate(v[4]^v[9],20u);\n"
    "        v[3]+=v[4]+m[s[15]]; v[14]=rotate(v[14]^v[3],24u); v[9]+=v[14]; v[4]=rotate(v[4]^v[9],25u);\n"
    "    }\n"
    "    for (int i = 0; i < 8; i++) h[i] ^= v[i] ^ v[i+8];\n"
    "}\n"
    "\n"
    "kernel void blake2s256_unsalted_batch(\n"
    "    device const uint       *words       [[buffer(0)]],\n"
    "    device const ushort     *unused_lens [[buffer(1)]],\n"
    "    device const ushort     *unused2     [[buffer(2)]],\n"
    "    device const uint8_t    *mask_desc   [[buffer(3)]],\n"
    "    device const uint       *unused3     [[buffer(4)]],\n"
    "    device const ushort     *unused4     [[buffer(5)]],\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys   [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    uint mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    /* Load pre-packed block (16 uint32 = 64 bytes).\n"
    "     * Password bytes start at n_prepend. Total length at M[14] bits [7:0] and [15:8]. */\n"
    "    device const uint *src = words + word_idx * 16;\n"
    "    uchar buf[64];\n"
    "    for (int i = 0; i < 64; i++)\n"
    "        buf[i] = ((device const uchar *)src)[i];\n"
    "\n"
    "    /* Fill mask positions */\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "\n"
    "    /* Read total_len from packed M[14] (stored as bitlen by packer, extract byte len) */\n"
    "    uint M14 = src[14];\n"
    "    int total_len = M14 >> 3;\n"
    "\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint n_total_m = n_pre + n_app;\n"
    "        uint append_combos = 1;\n"
    "        for (uint i = 0; i < n_app; i++)\n"
    "            append_combos *= mask_desc[n_pre + i];\n"
    "\n"
    "        uint prepend_idx = mask_idx / append_combos;\n"
    "        uint append_idx = mask_idx % append_combos;\n"
    "\n"
    "        if (n_pre > 0) {\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                buf[i] = ch;\n"
    "            }\n"
    "        }\n"
    "\n"
    "        if (n_app > 0) {\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint aidx = append_idx;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                int pos_idx = n_pre + i;\n"
    "                uint sz = mask_desc[pos_idx];\n"
    "                uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                aidx /= sz;\n"
    "                buf[app_start + i] = ch;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* BLAKE2S-256: single-block hash (password <= 55 bytes fits in one 64-byte block).\n"
    "     * Init: IV ^ parameter block (outlen=32, keylen=0, fanout=1, depth=1). */\n"
    "    uint h[8];\n"
    "    for (int i = 0; i < 8; i++) h[i] = B2S_IV[i];\n"
    "    h[0] ^= 0x01010020u;\n"
    "\n"
    "    /* Zero bytes after password */\n"
    "    for (int i = total_len; i < 64; i++) buf[i] = 0;\n"
    "\n"
    "    /* Single compress with last=1, counter=total_len */\n"
    "    b2s_compress(h, buf, (ulong)total_len, 1);\n"
    "\n"
    "    /* BLAKE2S output is LE — no bswap */\n"
    "    uint hx = h[0], hy = h[1], hz = h[2], hw = h[3];\n"
    "\n"
    "    /* Probe compact table — inline */\n"
    "    uint4 hv = uint4(hx, hy, hz, hw);\n"
    "    ulong key = (ulong(hv.y) << 32) | hv.x;\n"
    "    uint fp = uint(key >> 32);\n"
    "    if (fp == 0) fp = 1;\n"
    "    ulong pos = (key ^ (key >> 32)) & params.compact_mask;\n"
    "    for (uint p = 0; p < params.max_probe; p++) {\n"
    "        uint cfp = compact_fp[pos];\n"
    "        if (cfp == 0) break;\n"
    "        if (cfp == fp) {\n"
    "            uint idx = compact_idx[pos];\n"
    "            if (idx < params.hash_data_count) {\n"
    "                ulong off = hash_data_off[idx];\n"
    "                device const uint *ref = (device const uint *)(hash_data_buf + off);\n"
    "                if (hv.x == ref[0] && hv.y == ref[1] && hv.z == ref[2] && hv.w == ref[3]) {\n"
    "                    uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                    if (slot < params.max_hits) {\n"
    "                        uint base = slot * 6;\n"
    "                        hits[base] = word_idx; hits[base+1] = mask_idx;\n"
    "                        hits[base+2] = hv.x; hits[base+3] = hv.y;\n"
    "                        hits[base+4] = hv.z; hits[base+5] = hv.w;\n"
    "                    }\n"
    "                    return;\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "        pos = (pos + 1) & params.compact_mask;\n"
    "    }\n"
    "    if (params.overflow_count > 0) {\n"
    "        int lo = 0, hi = int(params.overflow_count) - 1;\n"
    "        while (lo <= hi) {\n"
    "            int mid = (lo + hi) / 2;\n"
    "            ulong mkey = overflow_keys[mid];\n"
    "            if (key < mkey) hi = mid - 1;\n"
    "            else if (key > mkey) lo = mid + 1;\n"
    "            else {\n"
    "                uint ooff = overflow_offsets[mid];\n"
    "                device const uint *oref = (device const uint *)(overflow_hashes + ooff);\n"
    "                if (hv.x == oref[0] && hv.y == oref[1] && hv.z == oref[2] && hv.w == oref[3]) {\n"
    "                    uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                    if (slot < params.max_hits) {\n"
    "                        uint base = slot * 6;\n"
    "                        hits[base] = word_idx; hits[base+1] = mask_idx;\n"
    "                        hits[base+2] = hv.x; hits[base+3] = hv.y;\n"
    "                        hits[base+4] = hv.z; hits[base+5] = hv.w;\n"
    "                    }\n"
    "                    return;\n"
    "                }\n"
    "                for (int d = mid-1; d >= 0 && overflow_keys[d] == key; d--) {\n"
    "                    oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (hv.x == oref[0] && hv.y == oref[1] && hv.z == oref[2] && hv.w == oref[3]) {\n"
    "                        uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                        if (slot < params.max_hits) {\n"
    "                            uint base = slot * 6;\n"
    "                            hits[base] = word_idx; hits[base+1] = mask_idx;\n"
    "                            hits[base+2] = hv.x; hits[base+3] = hv.y;\n"
    "                            hits[base+4] = hv.z; hits[base+5] = hv.w;\n"
    "                        }\n"
    "                        return;\n"
    "                    }\n"
    "                }\n"
    "                for (int d = mid+1; d < int(params.overflow_count) && overflow_keys[d] == key; d++) {\n"
    "                    oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (hv.x == oref[0] && hv.y == oref[1] && hv.z == oref[2] && hv.w == oref[3]) {\n"
    "                        uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                        if (slot < params.max_hits) {\n"
    "                            uint base = slot * 6;\n"
    "                            hits[base] = word_idx; hits[base+1] = mask_idx;\n"
    "                            hits[base+2] = hv.x; hits[base+3] = hv.y;\n"
    "                            hits[base+4] = hv.z; hits[base+5] = hv.w;\n"
    "                        }\n"
    "                        return;\n"
    "                    }\n"
    "                }\n"
    "                break;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "}\n"
;
