/* Auto-generated from metal_md5salt.metal -- do not edit */
static const char metal_md5salt_str[] =
    "kernel void md5salt_probe(\n"
    "    device const uint8_t    *words        [[buffer(0)]],\n"
    "    device const uint       *word_offsets [[buffer(1)]],\n"
    "    device const ushort     *word_lens    [[buffer(2)]],\n"
    "    device const uint8_t    *salts        [[buffer(3)]],\n"
    "    device const uint       *salt_offsets [[buffer(4)]],\n"
    "    device const ushort     *salt_lens    [[buffer(5)]],\n"
    "    device const uint       *compact_fp   [[buffer(6)]],\n"
    "    device const uint       *compact_idx  [[buffer(7)]],\n"
    "    constant MetalParams    &params       [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits          [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count     [[buffer(13)]],\n"
    "    uint                     tid           [[thread_position_in_grid]])\n"
    "{\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    /* Step 1: Read word */\n"
    "    uint woff = word_offsets[word_idx];\n"
    "    int wlen = word_lens[word_idx];\n"
    "    uint8_t word[256];\n"
    "    for (int i = 0; i < wlen && i < 255; i++)\n"
    "        word[i] = words[woff + i];\n"
    "\n"
    "    /* Step 2: MD5(word) */\n"
    "    uint4 h1;\n"
    "    if (wlen <= 55)\n"
    "        md5_short(word, wlen, h1);\n"
    "    else\n"
    "        md5_two(word, wlen, h1);\n"
    "\n"
    "    /* Step 3: Hex-encode to 32 chars */\n"
    "    uint8_t hexbuf[128];\n"
    "    thread uint8_t *bin = (thread uint8_t *)&h1;\n"
    "    hex_encode(bin, hexbuf);\n"
    "\n"
    "    /* Step 4: Append salt */\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    for (int i = 0; i < slen && i < 90; i++)\n"
    "        hexbuf[32 + i] = salts[soff + i];\n"
    "    int total_len = 32 + slen;\n"
    "\n"
    "    /* Step 5: MD5(hex + salt) */\n"
    "    uint4 h2;\n"
    "    if (total_len <= 55)\n"
    "        md5_short(hexbuf, total_len, h2);\n"
    "    else\n"
    "        md5_two(hexbuf, total_len, h2);\n"
    "\n"
    "    /* Step 6: Compact table probe */\n"
    "    thread uint8_t *hashbytes = (thread uint8_t *)&h2;\n"
    "    uint64_t key = *(thread const uint64_t *)hashbytes;\n"
    "    uint fp = (uint)(key >> 32);\n"
    "    if (fp == 0) fp = 1;\n"
    "    uint64_t pos = compact_mix(key) & params.compact_mask;\n"
    "\n"
    "    for (int p = 0; p < (int)params.max_probe; p++) {\n"
    "        uint cfp = compact_fp[pos];\n"
    "        if (cfp == 0) return;  /* empty slot = miss */\n"
    "        if (cfp == fp) {\n"
    "            /* fingerprint match — compare full hash */\n"
    "            uint idx = compact_idx[pos];\n"
    "            if (idx < params.hash_data_count) {\n"
    "                int hlen = hash_data_len[idx];\n"
    "                if (hlen > 16) hlen = 16;\n"
    "                uint64_t off = hash_data_off[idx];\n"
    "                bool match = true;\n"
    "                for (int i = 0; i < hlen; i++) {\n"
    "                    if (hashbytes[i] != hash_data_buf[off + i]) {\n"
    "                        match = false;\n"
    "                        break;\n"
    "                    }\n"
    "                }\n"
    "                if (match) {\n"
    "                    uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                    if (slot < 65536) {\n"
    "                        hits[slot * 2]     = word_idx;\n"
    "                        hits[slot * 2 + 1] = salt_idx;\n"
    "                    }\n"
    "                    return;\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "        pos = (pos + 1) & params.compact_mask;\n"
    "    }\n"
    "    /* Max probe exhausted — possible overflow. Report as hit for CPU validation. */\n"
    "    {\n"
    "        uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 5;\n"
    "            hits[base]     = tid;\n"
    "            hits[base + 1] = h2.x;\n"
    "            hits[base + 2] = h2.y;\n"
    "            hits[base + 3] = h2.z;\n"
    "            hits[base + 4] = h2.w;\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* Second kernel: pre-hashed input. \"words\" buffer contains the 32-char hex hash\n"
    " * already computed by CPU. GPU just appends each salt and does one MD5 + probe.\n"
    " * num_words is always 1, num_salts GPU threads. */\n"
    "kernel void md5salt_salts_only(\n"
    "    device const uint8_t    *hexhash      [[buffer(0)]],\n"
    "    device const uint       *word_offsets [[buffer(1)]],\n"
    "    device const ushort     *word_lens    [[buffer(2)]],\n"
    "    device const uint8_t    *salts        [[buffer(3)]],\n"
    "    device const uint       *salt_offsets [[buffer(4)]],\n"
    "    device const ushort     *salt_lens    [[buffer(5)]],\n"
    "    device const uint       *compact_fp   [[buffer(6)]],\n"
    "    device const uint       *compact_idx  [[buffer(7)]],\n"
    "    constant MetalParams    &params       [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits          [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count     [[buffer(13)]],\n"
    "    uint                     tid           [[thread_position_in_grid]])\n"
    "{\n"
    "    if (tid >= params.num_salts) return;\n"
    "\n"
    "    /* Copy pre-computed 32-char hex hash */\n"
    "    uint8_t buf[128];\n"
    "    int hlen = word_lens[0];\n"
    "    for (int i = 0; i < hlen && i < 55; i++)\n"
    "        buf[i] = hexhash[i];\n"
    "\n"
    "    /* Append salt */\n"
    "    uint soff = salt_offsets[tid];\n"
    "    int slen = salt_lens[tid];\n"
    "    for (int i = 0; i < slen && i < 90; i++)\n"
    "        buf[hlen + i] = salts[soff + i];\n"
    "    int total_len = hlen + slen;\n"
    "\n"
    "    /* MD5(hex + salt) */\n"
    "    uint4 h2;\n"
    "    if (total_len <= 55)\n"
    "        md5_short(buf, total_len, h2);\n"
    "    else\n"
    "        md5_two(buf, total_len, h2);\n"
    "\n"
    "    /* Compact table probe */\n"
    "    thread uint8_t *hashbytes = (thread uint8_t *)&h2;\n"
    "    uint64_t key = *(thread const uint64_t *)hashbytes;\n"
    "    uint fp = (uint)(key >> 32);\n"
    "    if (fp == 0) fp = 1;\n"
    "    uint64_t pos = compact_mix(key) & params.compact_mask;\n"
    "\n"
    "    for (int p = 0; p < (int)params.max_probe; p++) {\n"
    "        uint cfp = compact_fp[pos];\n"
    "        if (cfp == 0) return;\n"
    "        if (cfp == fp) {\n"
    "            uint idx = compact_idx[pos];\n"
    "            if (idx < params.hash_data_count) {\n"
    "                int dlen = hash_data_len[idx];\n"
    "                if (dlen > 16) dlen = 16;\n"
    "                uint64_t off = hash_data_off[idx];\n"
    "                bool match = true;\n"
    "                for (int i = 0; i < dlen; i++) {\n"
    "                    if (hashbytes[i] != hash_data_buf[off + i]) {\n"
    "                        match = false;\n"
    "                        break;\n"
    "                    }\n"
    "                }\n"
    "                if (match) {\n"
    "                    uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                    if (slot < params.max_hits) {\n"
    "                        uint base = slot * 5;\n"
    "                        hits[base]     = tid;\n"
    "                        hits[base + 1] = h2.x;\n"
    "                        hits[base + 2] = h2.y;\n"
    "                        hits[base + 3] = h2.z;\n"
    "                        hits[base + 4] = h2.w;\n"
    "                    }\n"
    "                    return;\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "        pos = (pos + 1) & params.compact_mask;\n"
    "    }\n"
    "    /* Max probe exhausted — possible overflow. Report as hit for CPU validation. */\n"
    "    {\n"
    "        uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 5;\n"
    "            hits[base]     = tid;\n"
    "            hits[base + 1] = h2.x;\n"
    "            hits[base + 2] = h2.y;\n"
    "            hits[base + 3] = h2.z;\n"
    "            hits[base + 4] = h2.w;\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* Third kernel: batch of pre-hashed words × all salts.\n"
    " * Grid: num_words * num_salts threads.\n"
    " * hexhashes buffer: 256 bytes per word, packed contiguously. */\n"
    "kernel void md5salt_batch_prehashed(\n"
    "    device const uint8_t    *hexhashes   [[buffer(0)]],\n"
    "    device const ushort     *hex_lens    [[buffer(1)]],\n"
    "    device const ushort     *unused2     [[buffer(2)]],\n"
    "    device const uint8_t    *salts       [[buffer(3)]],\n"
    "    device const uint       *salt_offsets [[buffer(4)]],\n"
    "    device const ushort     *salt_lens   [[buffer(5)]],\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys   [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    /* Shared prestate: thread 0 computes MD5 rounds 0-7 for its word.\n"
    "     * Other threads use it ONLY if they share the same word_idx.\n"
    "     * At threadgroup boundaries (num_salts % tgsize != 0), some threads\n"
    "     * may have a different word_idx and must compute their own. */\n"
    "    threadgroup uint shared_M[8];\n"
    "    threadgroup uint4 shared_prestate;\n"
    "    threadgroup uint shared_word_idx;\n"
    "\n"
    "    if (lid == 0) {\n"
    "        shared_word_idx = word_idx;\n"
    "        uint hoff = word_idx * 256;\n"
    "        device const uint *mwords = (device const uint *)(hexhashes + hoff);\n"
    "        for (int i = 0; i < 8; i++)\n"
    "            shared_M[i] = mwords[i];\n"
    "\n"
    "        uint a = 0x67452301, b = 0xEFCDAB89, c = 0x98BADCFE, d = 0x10325476;\n"
    "        for (int i = 0; i < 8; i++) {\n"
    "            uint f = (b & c) | (~b & d);\n"
    "            f = f + a + K[i] + shared_M[i];\n"
    "            a = d; d = c; c = b;\n"
    "            b = b + ((f << S[i]) | (f >> (32 - S[i])));\n"
    "        }\n"
    "        shared_prestate = uint4(a, b, c, d);\n"
    "    }\n"
    "    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
    "\n"
    "    /* Load M[0..7] — use shared if same word, else load own */\n"
    "    uint M[16];\n"
    "    bool use_shared = (word_idx == shared_word_idx);\n"
    "    if (use_shared) {\n"
    "        for (int i = 0; i < 8; i++)\n"
    "            M[i] = shared_M[i];\n"
    "    } else {\n"
    "        uint hoff = word_idx * 256;\n"
    "        device const uint *mwords = (device const uint *)(hexhashes + hoff);\n"
    "        for (int i = 0; i < 8; i++)\n"
    "            M[i] = mwords[i];\n"
    "    }\n"
    "\n"
    "    /* Append salt into M[8..] at byte position 32 */\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = 32 + slen;\n"
    "\n"
    "    uint4 h2;\n"
    "    if (slen <= 23) {\n"
    "        /* Single block: fill M[8..15] with salt + padding + bitlen. */\n"
    "        for (int i = 8; i < 16; i++) M[i] = 0;\n"
    "        thread uint8_t *mbytes = (thread uint8_t *)M;\n"
    "        for (int i = 0; i < slen; i++)\n"
    "            mbytes[32 + i] = salts[soff + i];\n"
    "        mbytes[total_len] = 0x80;\n"
    "        M[14] = total_len * 8;\n"
    "        if (use_shared) {\n"
    "            h2 = shared_prestate;\n"
    "            md5_block_from8(h2, M);\n"
    "        } else {\n"
    "            /* Full md5_block for boundary threads */\n"
    "            h2 = uint4(0x67452301, 0xEFCDAB89, 0x98BADCFE, 0x10325476);\n"
    "            md5_block_full(h2, M);\n"
    "        }\n"
    "    } else {\n"
    "        /* Two-block: fall back to full computation */\n"
    "        uint8_t buf[128];\n"
    "        thread uint *buf32 = (thread uint *)buf;\n"
    "        for (int i = 0; i < 8; i++)\n"
    "            buf32[i] = M[i];\n"
    "        for (int i = 0; i < slen && i < 90; i++)\n"
    "            buf[32 + i] = salts[soff + i];\n"
    "        if (total_len <= 55)\n"
    "            md5_short(buf, total_len, h2);\n"
    "        else\n"
    "            md5_two(buf, total_len, h2);\n"
    "    }\n"
    "\n"
    "    /* Compact table probe — use wide compares */\n"
    "    uint64_t key = ((thread const uint64_t *)&h2)[0];\n"
    "    uint fp = (uint)(key >> 32);\n"
    "    if (fp == 0) fp = 1;\n"
    "    uint64_t pos = compact_mix(key) & params.compact_mask;\n"
    "\n"
    "    for (int p = 0; p < (int)params.max_probe; p++) {\n"
    "        uint cfp = compact_fp[pos];\n"
    "        if (cfp == 0) break;\n"
    "        if (cfp == fp) {\n"
    "            uint idx = compact_idx[pos];\n"
    "            if (idx < params.hash_data_count) {\n"
    "                uint64_t off = hash_data_off[idx];\n"
    "                device const uint *ref = (device const uint *)(hash_data_buf + off);\n"
    "                if (h2.x == ref[0] && h2.y == ref[1] &&\n"
    "                    h2.z == ref[2] && h2.w == ref[3]) {\n"
    "                    uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                    if (slot < params.max_hits) {\n"
    "                        uint base = slot * 6;\n"
    "                        hits[base]     = word_idx;\n"
    "                        hits[base + 1] = salt_idx;\n"
    "                        hits[base + 2] = h2.x;\n"
    "                        hits[base + 3] = h2.y;\n"
    "                        hits[base + 4] = h2.z;\n"
    "                        hits[base + 5] = h2.w;\n"
    "                    }\n"
    "                    return;\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "        pos = (pos + 1) & params.compact_mask;\n"
    "    }\n"
    "    /* Binary search the overflow table */\n"
    "    if (params.overflow_count == 0) return;\n"
    "    {\n"
    "        int lo = 0, hi = (int)params.overflow_count - 1;\n"
    "        while (lo <= hi) {\n"
    "            int mid = (lo + hi) / 2;\n"
    "            uint64_t mkey = overflow_keys[mid];\n"
    "            if (key < mkey) hi = mid - 1;\n"
    "            else if (key > mkey) lo = mid + 1;\n"
    "            else {\n"
    "                /* Key match — compare full hash as 4 uint32 */\n"
    "                uint ooff = overflow_offsets[mid];\n"
    "                device const uint *oref = (device const uint *)(overflow_hashes + ooff);\n"
    "                bool match = (h2.x == oref[0] && h2.y == oref[1] &&\n"
    "                              h2.z == oref[2] && h2.w == oref[3]);\n"
    "                if (match) {\n"
    "                    uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                    if (slot < params.max_hits) {\n"
    "                        uint base = slot * 6;\n"
    "                        hits[base]     = word_idx;\n"
    "                        hits[base + 1] = salt_idx;\n"
    "                        hits[base + 2] = h2.x;\n"
    "                        hits[base + 3] = h2.y;\n"
    "                        hits[base + 4] = h2.z;\n"
    "                        hits[base + 5] = h2.w;\n"
    "                    }\n"
    "                    return;\n"
    "                }\n"
    "                /* Key matched but hash didn't — search duplicates both directions */\n"
    "                for (int d = mid - 1; d >= 0 && overflow_keys[d] == key; d--) {\n"
    "                    oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (h2.x == oref[0] && h2.y == oref[1] &&\n"
    "                        h2.z == oref[2] && h2.w == oref[3]) {\n"
    "                        uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                        if (slot < params.max_hits) {\n"
    "                            uint base = slot * 6;\n"
    "                            hits[base] = word_idx; hits[base+1] = salt_idx;\n"
    "                            hits[base+2] = h2.x; hits[base+3] = h2.y;\n"
    "                            hits[base+4] = h2.z; hits[base+5] = h2.w;\n"
    "                        }\n"
    "                        return;\n"
    "                    }\n"
    "                }\n"
    "                for (int d = mid + 1; d < (int)params.overflow_count && overflow_keys[d] == key; d++) {\n"
    "                    oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (h2.x == oref[0] && h2.y == oref[1] &&\n"
    "                        h2.z == oref[2] && h2.w == oref[3]) {\n"
    "                        uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                        if (slot < params.max_hits) {\n"
    "                            uint base = slot * 6;\n"
    "                            hits[base] = word_idx; hits[base+1] = salt_idx;\n"
    "                            hits[base+2] = h2.x; hits[base+3] = h2.y;\n"
    "                            hits[base+4] = h2.z; hits[base+5] = h2.w;\n"
    "                        }\n"
    "                        return;\n"
    "                    }\n"
    "                }\n"
    "                return;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* Iterating batch kernel: MD5(hex+salt), then MD5(hex(result)) for each iteration.\n"
    " * Identical setup to md5salt_batch_prehashed, but probes at each iteration. */\n"
    "kernel void md5salt_batch_iter(\n"
    "    device const uint8_t    *hexhashes   [[buffer(0)]],\n"
    "    device const ushort     *hex_lens    [[buffer(1)]],\n"
    "    device const ushort     *unused2     [[buffer(2)]],\n"
    "    device const uint8_t    *salts       [[buffer(3)]],\n"
    "    device const uint       *salt_offsets [[buffer(4)]],\n"
    "    device const ushort     *salt_lens   [[buffer(5)]],\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys   [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    threadgroup uint shared_M[8];\n"
    "    threadgroup uint4 shared_prestate;\n"
    "    threadgroup uint shared_word_idx;\n"
    "\n"
    "    if (lid == 0) {\n"
    "        shared_word_idx = word_idx;\n"
    "        uint hoff = word_idx * 256;\n"
    "        device const uint *mwords = (device const uint *)(hexhashes + hoff);\n"
    "        for (int i = 0; i < 8; i++)\n"
    "            shared_M[i] = mwords[i];\n"
    "\n"
    "        uint a = 0x67452301, b = 0xEFCDAB89, c = 0x98BADCFE, d = 0x10325476;\n"
    "        for (int i = 0; i < 8; i++) {\n"
    "            uint f = (b & c) | (~b & d);\n"
    "            f = f + a + K[i] + shared_M[i];\n"
    "            a = d; d = c; c = b;\n"
    "            b = b + ((f << S[i]) | (f >> (32 - S[i])));\n"
    "        }\n"
    "        shared_prestate = uint4(a, b, c, d);\n"
    "    }\n"
    "    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
    "\n"
    "    uint M[16];\n"
    "    bool use_shared = (word_idx == shared_word_idx);\n"
    "    if (use_shared) {\n"
    "        for (int i = 0; i < 8; i++)\n"
    "            M[i] = shared_M[i];\n"
    "    } else {\n"
    "        uint hoff = word_idx * 256;\n"
    "        device const uint *mwords = (device const uint *)(hexhashes + hoff);\n"
    "        for (int i = 0; i < 8; i++)\n"
    "            M[i] = mwords[i];\n"
    "    }\n"
    "\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = 32 + slen;\n"
    "\n"
    "    uint4 h2;\n"
    "    if (slen <= 23) {\n"
    "        for (int i = 8; i < 16; i++) M[i] = 0;\n"
    "        thread uint8_t *mbytes = (thread uint8_t *)M;\n"
    "        for (int i = 0; i < slen; i++)\n"
    "            mbytes[32 + i] = salts[soff + i];\n"
    "        mbytes[total_len] = 0x80;\n"
    "        M[14] = total_len * 8;\n"
    "        if (use_shared) {\n"
    "            h2 = shared_prestate;\n"
    "            md5_block_from8(h2, M);\n"
    "        } else {\n"
    "            h2 = uint4(0x67452301, 0xEFCDAB89, 0x98BADCFE, 0x10325476);\n"
    "            md5_block_full(h2, M);\n"
    "        }\n"
    "    } else {\n"
    "        uint8_t buf[128];\n"
    "        thread uint *buf32 = (thread uint *)buf;\n"
    "        for (int i = 0; i < 8; i++)\n"
    "            buf32[i] = M[i];\n"
    "        for (int i = 0; i < slen && i < 90; i++)\n"
    "            buf[32 + i] = salts[soff + i];\n"
    "        if (total_len <= 55)\n"
    "            md5_short(buf, total_len, h2);\n"
    "        else\n"
    "            md5_two(buf, total_len, h2);\n"
    "    }\n"
    "\n"
    "    /* Iterate: probe at each iteration, then MD5(hex(h2)) for next */\n"
    "    for (uint iter = 0; iter < params.max_iter; iter++) {\n"
    "        /* If not first iteration, compute MD5(hex(h2)) */\n"
    "        if (iter > 0) {\n"
    "            uint Mi[16];\n"
    "            hash_to_hex_M(h2, Mi);\n"
    "            Mi[8] = 0x80;\n"
    "            Mi[9] = 0; Mi[10] = 0; Mi[11] = 0;\n"
    "            Mi[12] = 0; Mi[13] = 0;\n"
    "            Mi[14] = 256; /* 32 * 8 bits */\n"
    "            Mi[15] = 0;\n"
    "            h2 = uint4(0x67452301, 0xEFCDAB89, 0x98BADCFE, 0x10325476);\n"
    "            md5_block_full(h2, Mi);\n"
    "        }\n"
    "\n"
    "        /* Compact table probe — record hit but continue iterating */\n"
    "        uint64_t key = ((thread const uint64_t *)&h2)[0];\n"
    "        uint fp = (uint)(key >> 32);\n"
    "        if (fp == 0) fp = 1;\n"
    "        uint64_t pos = compact_mix(key) & params.compact_mask;\n"
    "        bool found = false;\n"
    "\n"
    "        for (int p = 0; p < (int)params.max_probe; p++) {\n"
    "            uint cfp = compact_fp[pos];\n"
    "            if (cfp == 0) break;\n"
    "            if (cfp == fp) {\n"
    "                uint idx = compact_idx[pos];\n"
    "                if (idx < params.hash_data_count) {\n"
    "                    uint64_t off = hash_data_off[idx];\n"
    "                    device const uint *ref = (device const uint *)(hash_data_buf + off);\n"
    "                    if (h2.x == ref[0] && h2.y == ref[1] &&\n"
    "                        h2.z == ref[2] && h2.w == ref[3]) {\n"
    "                        uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                        if (slot < params.max_hits) {\n"
    "                            uint base = slot * 7;\n"
    "                            hits[base]     = word_idx;\n"
    "                            hits[base + 1] = salt_idx;\n"
    "                            hits[base + 2] = iter + 1;\n"
    "                            hits[base + 3] = h2.x;\n"
    "                            hits[base + 4] = h2.y;\n"
    "                            hits[base + 5] = h2.z;\n"
    "                            hits[base + 6] = h2.w;\n"
    "                        }\n"
    "                        found = true;\n"
    "                        break;\n"
    "                    }\n"
    "                }\n"
    "            }\n"
    "            pos = (pos + 1) & params.compact_mask;\n"
    "        }\n"
    "\n"
    "        /* Binary search overflow */\n"
    "        if (!found && params.overflow_count > 0) {\n"
    "            int lo = 0, hi = (int)params.overflow_count - 1;\n"
    "            while (lo <= hi) {\n"
    "                int mid = (lo + hi) / 2;\n"
    "                uint64_t mkey = overflow_keys[mid];\n"
    "                if (key < mkey) hi = mid - 1;\n"
    "                else if (key > mkey) lo = mid + 1;\n"
    "                else {\n"
    "                    uint ooff = overflow_offsets[mid];\n"
    "                    device const uint *oref = (device const uint *)(overflow_hashes + ooff);\n"
    "                    if (h2.x == oref[0] && h2.y == oref[1] &&\n"
    "                        h2.z == oref[2] && h2.w == oref[3]) {\n"
    "                        uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                        if (slot < params.max_hits) {\n"
    "                            uint base = slot * 7;\n"
    "                            hits[base] = word_idx; hits[base+1] = salt_idx;\n"
    "                            hits[base+2] = iter + 1;\n"
    "                            hits[base+3] = h2.x; hits[base+4] = h2.y;\n"
    "                            hits[base+5] = h2.z; hits[base+6] = h2.w;\n"
    "                        }\n"
    "                        break;\n"
    "                    }\n"
    "                    for (int d = mid - 1; d >= 0 && overflow_keys[d] == key; d--) {\n"
    "                        oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                        if (h2.x == oref[0] && h2.y == oref[1] &&\n"
    "                            h2.z == oref[2] && h2.w == oref[3]) {\n"
    "                            uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                            if (slot < params.max_hits) {\n"
    "                                uint base = slot * 7;\n"
    "                                hits[base] = word_idx; hits[base+1] = salt_idx;\n"
    "                                hits[base+2] = iter + 1;\n"
    "                                hits[base+3] = h2.x; hits[base+4] = h2.y;\n"
    "                                hits[base+5] = h2.z; hits[base+6] = h2.w;\n"
    "                            }\n"
    "                            found = true; break;\n"
    "                        }\n"
    "                    }\n"
    "                    if (!found) {\n"
    "                        for (int d = mid + 1; d < (int)params.overflow_count && overflow_keys[d] == key; d++) {\n"
    "                            oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                            if (h2.x == oref[0] && h2.y == oref[1] &&\n"
    "                                h2.z == oref[2] && h2.w == oref[3]) {\n"
    "                                uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                                if (slot < params.max_hits) {\n"
    "                                    uint base = slot * 7;\n"
    "                                    hits[base] = word_idx; hits[base+1] = salt_idx;\n"
    "                                    hits[base+2] = iter + 1;\n"
    "                                    hits[base+3] = h2.x; hits[base+4] = h2.y;\n"
    "                                    hits[base+5] = h2.z; hits[base+6] = h2.w;\n"
    "                                }\n"
    "                                break;\n"
    "                            }\n"
    "                        }\n"
    "                    }\n"
    "                    break;\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "    } /* end iteration loop */\n"
    "}\n"
    "\n"
    "/* Sub8-24 batch kernel: hexlen=16 (chars 8-23 of MD5 hex), 4-word prestate.\n"
    " * Identical buffer layout to batch_prehashed, but constant 16-byte hex input. */\n"
    "kernel void md5salt_batch_sub8_24(\n"
    "    device const uint8_t    *hexhashes   [[buffer(0)]],\n"
    "    device const ushort     *hex_lens    [[buffer(1)]],\n"
    "    device const ushort     *unused2     [[buffer(2)]],\n"
    "    device const uint8_t    *salts       [[buffer(3)]],\n"
    "    device const uint       *salt_offsets [[buffer(4)]],\n"
    "    device const ushort     *salt_lens   [[buffer(5)]],\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys   [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    /* Shared prestate: 4 M words, 4 prestate rounds for hexlen=16 */\n"
    "    threadgroup uint shared_M[4];\n"
    "    threadgroup uint4 shared_prestate;\n"
    "    threadgroup uint shared_word_idx;\n"
    "\n"
    "    if (lid == 0) {\n"
    "        shared_word_idx = word_idx;\n"
    "        uint hoff = word_idx * 256;\n"
    "        device const uint *mwords = (device const uint *)(hexhashes + hoff);\n"
    "        for (int i = 0; i < 4; i++)\n"
    "            shared_M[i] = mwords[i];\n"
    "\n"
    "        uint a = 0x67452301, b = 0xEFCDAB89, c = 0x98BADCFE, d = 0x10325476;\n"
    "        for (int i = 0; i < 4; i++) {\n"
    "            uint f = (b & c) | (~b & d);\n"
    "            f = f + a + K[i] + shared_M[i];\n"
    "            a = d; d = c; c = b;\n"
    "            b = b + ((f << S[i]) | (f >> (32 - S[i])));\n"
    "        }\n"
    "        shared_prestate = uint4(a, b, c, d);\n"
    "    }\n"
    "    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
    "\n"
    "    /* Load M[0..3] — use shared if same word, else load own */\n"
    "    uint M[16];\n"
    "    bool use_shared = (word_idx == shared_word_idx);\n"
    "    if (use_shared) {\n"
    "        for (int i = 0; i < 4; i++)\n"
    "            M[i] = shared_M[i];\n"
    "    } else {\n"
    "        uint hoff = word_idx * 256;\n"
    "        device const uint *mwords = (device const uint *)(hexhashes + hoff);\n"
    "        for (int i = 0; i < 4; i++)\n"
    "            M[i] = mwords[i];\n"
    "    }\n"
    "\n"
    "    /* Append salt at byte position 16 */\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = 16 + slen;\n"
    "\n"
    "    uint4 h2;\n"
    "    if (total_len <= 55) {\n"
    "        /* Single block: fill M[4..15] with salt + padding + bitlen */\n"
    "        for (int i = 4; i < 16; i++) M[i] = 0;\n"
    "        thread uint8_t *mbytes = (thread uint8_t *)M;\n"
    "        for (int i = 0; i < slen; i++)\n"
    "            mbytes[16 + i] = salts[soff + i];\n"
    "        mbytes[total_len] = 0x80;\n"
    "        M[14] = total_len * 8;\n"
    "        /* Use full md5_block for now — prestate optimization can be added later */\n"
    "        h2 = uint4(0x67452301, 0xEFCDAB89, 0x98BADCFE, 0x10325476);\n"
    "        md5_block_full(h2, M);\n"
    "    } else {\n"
    "        /* Two-block: fall back to full computation */\n"
    "        uint8_t buf[128];\n"
    "        thread uint *buf32 = (thread uint *)buf;\n"
    "        for (int i = 0; i < 4; i++)\n"
    "            buf32[i] = M[i];\n"
    "        for (int i = 0; i < slen && i < 106; i++)\n"
    "            buf[16 + i] = salts[soff + i];\n"
    "        if (total_len <= 55)\n"
    "            md5_short(buf, total_len, h2);\n"
    "        else\n"
    "            md5_two(buf, total_len, h2);\n"
    "    }\n"
    "\n"
    "    /* Compact table probe — use wide compares */\n"
    "    uint64_t key = ((thread const uint64_t *)&h2)[0];\n"
    "    uint fp = (uint)(key >> 32);\n"
    "    if (fp == 0) fp = 1;\n"
    "    uint64_t pos = compact_mix(key) & params.compact_mask;\n"
    "\n"
    "    for (int p = 0; p < (int)params.max_probe; p++) {\n"
    "        uint cfp = compact_fp[pos];\n"
    "        if (cfp == 0) break;\n"
    "        if (cfp == fp) {\n"
    "            uint idx = compact_idx[pos];\n"
    "            if (idx < params.hash_data_count) {\n"
    "                uint64_t off = hash_data_off[idx];\n"
    "                device const uint *ref = (device const uint *)(hash_data_buf + off);\n"
    "                if (h2.x == ref[0] && h2.y == ref[1] &&\n"
    "                    h2.z == ref[2] && h2.w == ref[3]) {\n"
    "                    uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                    if (slot < params.max_hits) {\n"
    "                        uint base = slot * 6;\n"
    "                        hits[base]     = word_idx;\n"
    "                        hits[base + 1] = salt_idx;\n"
    "                        hits[base + 2] = h2.x;\n"
    "                        hits[base + 3] = h2.y;\n"
    "                        hits[base + 4] = h2.z;\n"
    "                        hits[base + 5] = h2.w;\n"
    "                    }\n"
    "                    return;\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "        pos = (pos + 1) & params.compact_mask;\n"
    "    }\n"
    "    /* Binary search the overflow table */\n"
    "    if (params.overflow_count == 0) return;\n"
    "    {\n"
    "        int lo = 0, hi = (int)params.overflow_count - 1;\n"
    "        while (lo <= hi) {\n"
    "            int mid = (lo + hi) / 2;\n"
    "            uint64_t mkey = overflow_keys[mid];\n"
    "            if (key < mkey) hi = mid - 1;\n"
    "            else if (key > mkey) lo = mid + 1;\n"
    "            else {\n"
    "                uint ooff = overflow_offsets[mid];\n"
    "                device const uint *oref = (device const uint *)(overflow_hashes + ooff);\n"
    "                bool match = (h2.x == oref[0] && h2.y == oref[1] &&\n"
    "                              h2.z == oref[2] && h2.w == oref[3]);\n"
    "                if (match) {\n"
    "                    uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                    if (slot < params.max_hits) {\n"
    "                        uint base = slot * 6;\n"
    "                        hits[base]     = word_idx;\n"
    "                        hits[base + 1] = salt_idx;\n"
    "                        hits[base + 2] = h2.x;\n"
    "                        hits[base + 3] = h2.y;\n"
    "                        hits[base + 4] = h2.z;\n"
    "                        hits[base + 5] = h2.w;\n"
    "                    }\n"
    "                    return;\n"
    "                }\n"
    "                for (int d = mid - 1; d >= 0 && overflow_keys[d] == key; d--) {\n"
    "                    oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (h2.x == oref[0] && h2.y == oref[1] &&\n"
    "                        h2.z == oref[2] && h2.w == oref[3]) {\n"
    "                        uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                        if (slot < params.max_hits) {\n"
    "                            uint base = slot * 6;\n"
    "                            hits[base] = word_idx; hits[base+1] = salt_idx;\n"
    "                            hits[base+2] = h2.x; hits[base+3] = h2.y;\n"
    "                            hits[base+4] = h2.z; hits[base+5] = h2.w;\n"
    "                        }\n"
    "                        return;\n"
    "                    }\n"
    "                }\n"
    "                for (int d = mid + 1; d < (int)params.overflow_count && overflow_keys[d] == key; d++) {\n"
    "                    oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (h2.x == oref[0] && h2.y == oref[1] &&\n"
    "                        h2.z == oref[2] && h2.w == oref[3]) {\n"
    "                        uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                        if (slot < params.max_hits) {\n"
    "                            uint base = slot * 6;\n"
    "                            hits[base] = word_idx; hits[base+1] = salt_idx;\n"
    "                            hits[base+2] = h2.x; hits[base+3] = h2.y;\n"
    "                            hits[base+4] = h2.z; hits[base+5] = h2.w;\n"
    "                        }\n"
    "                        return;\n"
    "                    }\n"
    "                }\n"
    "                return;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
;
