/* Auto-generated from metal_md6256unsalted.metal -- do not edit */
static const char metal_md6256unsalted_str[] =
    "/* metal_md6256unsalted.metal — Pre-packed unsalted MD6-256 with mask expansion\n"
    " *\n"
    " * MD6-256: r=104 rounds, c=16, n=89, d=256.\n"
    " * Input: pre-packed N[89] (712-byte) blocks.\n"
    " * Hit stride: 6 (word_idx, mask_idx, hx, hy, hz, hw)\n"
    " */\n"
    "\n"
    "/* bswap64 provided by metal_common.metal */\n"
    "\n"
    "#define MD6_n  89\n"
    "#define MD6_c  16\n"
    "#define MD6_r  104\n"
    "#define MD6_t0  17\n"
    "#define MD6_t1  18\n"
    "#define MD6_t2  21\n"
    "#define MD6_t3  31\n"
    "#define MD6_t4  67\n"
    "#define MD6_t5  89\n"
    "\n"
    "constant int RS[16] = {10, 5,13,10,11,12, 2, 7,14,15, 7,13,11, 7, 6,12};\n"
    "constant int LS[16] = {11,24, 9,16,15, 9,27,15, 6, 2,29, 8,15, 5,31, 9};\n"
    "\n"
    "constant ulong MD6_S0 = 0x0123456789abcdefUL;\n"
    "constant ulong MD6_Smask = 0x7311c2812425cfa0UL;\n"
    "\n"
    "static void md6_compress_loop(thread ulong *A) {\n"
    "    ulong S = MD6_S0;\n"
    "    int i = MD6_n;\n"
    "    for (int j = 0; j < MD6_r * MD6_c; j += MD6_c) {\n"
    "        for (int step = 0; step < 16; step++) {\n"
    "            ulong x = S;\n"
    "            x ^= A[i + step - MD6_t5];\n"
    "            x ^= A[i + step - MD6_t0];\n"
    "            x ^= (A[i + step - MD6_t1] & A[i + step - MD6_t2]);\n"
    "            x ^= (A[i + step - MD6_t3] & A[i + step - MD6_t4]);\n"
    "            x ^= (x >> RS[step]);\n"
    "            A[i + step] = x ^ (x << LS[step]);\n"
    "        }\n"
    "        S = (S << 1) ^ (S >> 63) ^ (S & MD6_Smask);\n"
    "        i += 16;\n"
    "    }\n"
    "}\n"
    "\n"
    "kernel void md6_256_unsalted_batch(\n"
    "    device const uint8_t    *words       [[buffer(0)]],\n"
    "    device const ushort     *unused_lens [[buffer(1)]],\n"
    "    device const ushort     *unused2     [[buffer(2)]],\n"
    "    device const uint8_t    *mask_desc   [[buffer(3)]],\n"
    "    device const uint       *unused3     [[buffer(4)]],\n"
    "    device const ushort     *unused4     [[buffer(5)]],\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys   [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    uint mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    device const ulong *src = (device const ulong *)(words + word_idx * 712);\n"
    "    ulong A[1753];\n"
    "    for (int i = 0; i < 89; i++) A[i] = src[i];\n"
    "\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint n_total_m = n_pre + n_app;\n"
    "        uint append_combos = 1;\n"
    "        for (uint i = 0; i < n_app; i++)\n"
    "            append_combos *= mask_desc[n_pre + i];\n"
    "        uint prepend_idx = mask_idx / append_combos;\n"
    "        uint append_idx = mask_idx % append_combos;\n"
    "\n"
    "        if (n_pre > 0) {\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                int wi = 25 + (i >> 3);\n"
    "                int bi = (i & 7) << 3;\n"
    "                A[wi] = (A[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "            }\n"
    "        }\n"
    "\n"
    "        if (n_app > 0) {\n"
    "            ulong V = A[24];\n"
    "            uint p_bits = (uint)((V >> 20) & 0xFFFFUL);\n"
    "            int total_len = (64*64 - (int)p_bits) / 8;\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint aidx = append_idx;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                int pos_idx = n_pre + i;\n"
    "                uint sz = mask_desc[pos_idx];\n"
    "                uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                aidx /= sz;\n"
    "                int pos = app_start + i;\n"
    "                int wi = 25 + (pos >> 3);\n"
    "                int bi = (pos & 7) << 3;\n"
    "                A[wi] = (A[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Byte-swap B portion (A[25..88]) from LE to BE */\n"
    "    for (int i = 25; i < 89; i++) A[i] = bswap64(A[i]);\n"
    "\n"
    "    md6_compress_loop(A);\n"
    "\n"
    "    /* Extract output: last 4 words = A[1749..1752] */\n"
    "    ulong C12 = A[1749], C13 = A[1750];\n"
    "    C12 = bswap64(C12); C13 = bswap64(C13);\n"
    "\n"
    "    uint4 hv = uint4((uint)C12, (uint)(C12 >> 32), (uint)C13, (uint)(C13 >> 32));\n"
    "\n"
    "    PROBE6(hv, word_idx, mask_idx)\n"
    "}\n"
;
