/* Auto-generated from metal_sha256crypt.metal -- do not edit */
static const char metal_sha256crypt_str[] =
    "/* metal_sha256crypt.metal -- SHA256CRYPT (e512, hashcat 7400)\n"
    " * glibc crypt-sha256: $5$[rounds=N$]salt$hash\n"
    " * Default 5000 rounds, salt up to 16 chars, SHA256 (32-byte digest).\n"
    " * Hit stride: 11 (word_idx, salt_idx, iter, h[0..7])\n"
    " */\n"
    "\n"
    "constant uint K256_SC[64] = {\n"
    "    0x428a2f98u,0x71374491u,0xb5c0fbcfu,0xe9b5dba5u,0x3956c25bu,0x59f111f1u,0x923f82a4u,0xab1c5ed5u,\n"
    "    0xd807aa98u,0x12835b01u,0x243185beu,0x550c7dc3u,0x72be5d74u,0x80deb1feu,0x9bdc06a7u,0xc19bf174u,\n"
    "    0xe49b69c1u,0xefbe4786u,0x0fc19dc6u,0x240ca1ccu,0x2de92c6fu,0x4a7484aau,0x5cb0a9dcu,0x76f988dau,\n"
    "    0x983e5152u,0xa831c66du,0xb00327c8u,0xbf597fc7u,0xc6e00bf3u,0xd5a79147u,0x06ca6351u,0x14292967u,\n"
    "    0x27b70a85u,0x2e1b2138u,0x4d2c6dfcu,0x53380d13u,0x650a7354u,0x766a0abbu,0x81c2c92eu,0x92722c85u,\n"
    "    0xa2bfe8a1u,0xa81a664bu,0xc24b8b70u,0xc76c51a3u,0xd192e819u,0xd6990624u,0xf40e3585u,0x106aa070u,\n"
    "    0x19a4c116u,0x1e376c08u,0x2748774cu,0x34b0bcb5u,0x391c0cb3u,0x4ed8aa4au,0x5b9cca4fu,0x682e6ff3u,\n"
    "    0x748f82eeu,0x78a5636fu,0x84c87814u,0x8cc70208u,0x90befffau,0xa4506cebu,0xbef9a3f7u,0xc67178f2u\n"
    "};\n"
    "\n"
    "static void sc_sha256_block(thread uint *state, thread uint *M) {\n"
    "    uint W[64];\n"
    "    for (int i = 0; i < 16; i++) W[i] = M[i];\n"
    "    for (int i = 16; i < 64; i++) {\n"
    "        uint x = W[i-15]; uint s0 = ((x>>7)|(x<<25))^((x>>18)|(x<<14))^(x>>3);\n"
    "        x = W[i-2]; uint s1 = ((x>>17)|(x<<15))^((x>>19)|(x<<13))^(x>>10);\n"
    "        W[i] = W[i-16] + s0 + W[i-7] + s1;\n"
    "    }\n"
    "    uint a=state[0],b=state[1],c=state[2],d=state[3],e=state[4],f=state[5],g=state[6],h=state[7];\n"
    "    for (int i = 0; i < 64; i++) {\n"
    "        uint S1=((e>>6)|(e<<26))^((e>>11)|(e<<21))^((e>>25)|(e<<7));\n"
    "        uint ch=(e&f)^(~e&g); uint t1=h+S1+ch+K256_SC[i]+W[i];\n"
    "        uint S0=((a>>2)|(a<<30))^((a>>13)|(a<<19))^((a>>22)|(a<<10));\n"
    "        uint maj=(a&b)^(a&c)^(b&c); uint t2=S0+maj;\n"
    "        h=g;g=f;f=e;e=d+t1;d=c;c=b;b=a;a=t1+t2;\n"
    "    }\n"
    "    state[0]+=a;state[1]+=b;state[2]+=c;state[3]+=d;state[4]+=e;state[5]+=f;state[6]+=g;state[7]+=h;\n"
    "}\n"
    "\n"
    "static void sc_buf_set_byte(thread uint *buf, int pos, uchar val) {\n"
    "    int wi = pos >> 2; int bi = (3 - (pos & 3)) << 3;\n"
    "    buf[wi] = (buf[wi] & ~(0xffu << bi)) | ((uint)val << bi);\n"
    "}\n"
    "\n"
    "static void sc_sha256_init(thread uint *state) {\n"
    "    state[0]=0x6a09e667u;state[1]=0xbb67ae85u;state[2]=0x3c6ef372u;state[3]=0xa54ff53au;\n"
    "    state[4]=0x510e527fu;state[5]=0x9b05688cu;state[6]=0x1f83d9abu;state[7]=0x5be0cd19u;\n"
    "}\n"
    "\n"
    "static void sc_sha256_update(thread uint *state, thread uint *buf, thread int *bufpos,\n"
    "                              thread uint *counter, thread const uchar *data, int len) {\n"
    "    *counter += (uint)len;\n"
    "    int bp = *bufpos;\n"
    "    for (int i = 0; i < len; i++) {\n"
    "        sc_buf_set_byte(buf, bp, data[i]); bp++;\n"
    "        if (bp == 64) { sc_sha256_block(state, buf); for (int j=0;j<16;j++) buf[j]=0; bp=0; }\n"
    "    }\n"
    "    *bufpos = bp;\n"
    "}\n"
    "\n"
    "static void sc_sha256_update_g(thread uint *state, thread uint *buf, thread int *bufpos,\n"
    "                                thread uint *counter, device const uint8_t *data, int len) {\n"
    "    *counter += (uint)len;\n"
    "    int bp = *bufpos;\n"
    "    for (int i = 0; i < len; i++) {\n"
    "        sc_buf_set_byte(buf, bp, data[i]); bp++;\n"
    "        if (bp == 64) { sc_sha256_block(state, buf); for (int j=0;j<16;j++) buf[j]=0; bp=0; }\n"
    "    }\n"
    "    *bufpos = bp;\n"
    "}\n"
    "\n"
    "static void sc_sha256_final(thread uint *state, thread uint *buf, int bufpos,\n"
    "                             uint counter, thread uchar *out) {\n"
    "    sc_buf_set_byte(buf, bufpos, 0x80); bufpos++;\n"
    "    if (bufpos > 56) {\n"
    "        for (int i=bufpos;i<64;i++) sc_buf_set_byte(buf,i,0);\n"
    "        sc_sha256_block(state,buf); for (int j=0;j<16;j++) buf[j]=0; bufpos=0;\n"
    "    }\n"
    "    for (int i=bufpos;i<56;i++) sc_buf_set_byte(buf,i,0);\n"
    "    buf[14]=0; buf[15]=counter*8;\n"
    "    sc_sha256_block(state,buf);\n"
    "    for (int i=0;i<8;i++) {\n"
    "        uint w=state[i];\n"
    "        out[i*4]=(uchar)(w>>24); out[i*4+1]=(uchar)(w>>16);\n"
    "        out[i*4+2]=(uchar)(w>>8); out[i*4+3]=(uchar)(w);\n"
    "    }\n"
    "}\n"
    "\n"
    "static void sc_sha256_oneshot(thread const uchar *data, int len, thread uchar *out) {\n"
    "    uint state[8],buf[16]; int bufpos=0; uint counter=0;\n"
    "    sc_sha256_init(state); for (int j=0;j<16;j++) buf[j]=0;\n"
    "    sc_sha256_update(state,buf,&bufpos,&counter,data,len);\n"
    "    sc_sha256_final(state,buf,bufpos,counter,out);\n"
    "}\n"
    "\n"
    "kernel void sha256crypt_batch(\n"
    "    device const uint8_t    *hexhashes   [[buffer(0)]],\n"
    "    device const ushort     *hexlens     [[buffer(1)]],\n"
    "    device const ushort     *unused2     [[buffer(2)]],\n"
    "    device const uint8_t    *salts       [[buffer(3)]],\n"
    "    device const uint       *salt_offsets [[buffer(4)]],\n"
    "    device const ushort     *salt_lens   [[buffer(5)]],\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys   [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    device const uint8_t *pass = hexhashes + word_idx * 256;\n"
    "    uchar pw[256];\n"
    "    for (int i = 0; i < plen; i++) pw[i] = pass[i];\n"
    "\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen_full = salt_lens[salt_idx];\n"
    "    device const uint8_t *salt_str = salts + soff;\n"
    "\n"
    "    int spos = 3; int rounds = 5000;\n"
    "    if (slen_full > 10 && salt_str[3]=='r' && salt_str[4]=='o' && salt_str[5]=='u' &&\n"
    "        salt_str[6]=='n' && salt_str[7]=='d' && salt_str[8]=='s' && salt_str[9]=='=') {\n"
    "        rounds = 0; spos = 10;\n"
    "        while (spos < slen_full && salt_str[spos] >= '0' && salt_str[spos] <= '9') {\n"
    "            rounds = rounds * 10 + (salt_str[spos] - '0'); spos++;\n"
    "        }\n"
    "        if (rounds < 1000) rounds = 1000;\n"
    "        if (rounds > 999999999) rounds = 999999999;\n"
    "        if (spos < slen_full && salt_str[spos] == '$') spos++;\n"
    "    }\n"
    "    uchar raw_salt[16]; int saltlen = 0;\n"
    "    for (int i = spos; i < slen_full && saltlen < 16; i++) {\n"
    "        if (salt_str[i] == '$') break;\n"
    "        raw_salt[saltlen++] = salt_str[i];\n"
    "    }\n"
    "    if (saltlen == 0) return;\n"
    "\n"
    "    uint state[8], ctx_buf[16]; int ctx_bufpos; uint ctx_counter;\n"
    "    uchar tmp[256], digest_a[32], digest_b[32];\n"
    "\n"
    "    /* Step 1 */\n"
    "    { int tlen=0; for (int i=0;i<plen;i++) tmp[tlen++]=pw[i];\n"
    "      for (int i=0;i<saltlen;i++) tmp[tlen++]=raw_salt[i];\n"
    "      for (int i=0;i<plen;i++) tmp[tlen++]=pw[i];\n"
    "      sc_sha256_oneshot(tmp,tlen,digest_a); }\n"
    "\n"
    "    /* Step 2 */\n"
    "    sc_sha256_init(state); for (int j=0;j<16;j++) ctx_buf[j]=0; ctx_bufpos=0; ctx_counter=0;\n"
    "    sc_sha256_update(state,ctx_buf,&ctx_bufpos,&ctx_counter,pw,plen);\n"
    "    sc_sha256_update(state,ctx_buf,&ctx_bufpos,&ctx_counter,raw_salt,saltlen);\n"
    "    for (int x=plen;x>32;x-=32) sc_sha256_update(state,ctx_buf,&ctx_bufpos,&ctx_counter,digest_a,32);\n"
    "    { int x=plen; while(x>32) x-=32; sc_sha256_update(state,ctx_buf,&ctx_bufpos,&ctx_counter,digest_a,x); }\n"
    "    for (int x=plen;x!=0;x>>=1) {\n"
    "        if (x&1) sc_sha256_update(state,ctx_buf,&ctx_bufpos,&ctx_counter,digest_a,32);\n"
    "        else sc_sha256_update(state,ctx_buf,&ctx_bufpos,&ctx_counter,pw,plen);\n"
    "    }\n"
    "    uchar curin[32];\n"
    "    sc_sha256_final(state,ctx_buf,ctx_bufpos,ctx_counter,curin);\n"
    "\n"
    "    /* Step 3: Hash P */\n"
    "    sc_sha256_init(state); for (int j=0;j<16;j++) ctx_buf[j]=0; ctx_bufpos=0; ctx_counter=0;\n"
    "    for (int x=0;x<plen;x++) sc_sha256_update(state,ctx_buf,&ctx_bufpos,&ctx_counter,pw,plen);\n"
    "    sc_sha256_final(state,ctx_buf,ctx_bufpos,ctx_counter,digest_b);\n"
    "    uchar p_bytes[256]; for (int i=0;i<plen;i++) p_bytes[i]=digest_b[i%32];\n"
    "\n"
    "    /* Step 4: Hash S */\n"
    "    sc_sha256_init(state); for (int j=0;j<16;j++) ctx_buf[j]=0; ctx_bufpos=0; ctx_counter=0;\n"
    "    int s_repeats = 16 + (uint)curin[0];\n"
    "    for (int x=0;x<s_repeats;x++) sc_sha256_update(state,ctx_buf,&ctx_bufpos,&ctx_counter,raw_salt,saltlen);\n"
    "    sc_sha256_final(state,ctx_buf,ctx_bufpos,ctx_counter,digest_b);\n"
    "    uchar s_bytes[16]; for (int i=0;i<saltlen;i++) s_bytes[i]=digest_b[i];\n"
    "\n"
    "    /* Step 5: Main loop */\n"
    "    for (int r=0;r<rounds;r++) {\n"
    "        sc_sha256_init(state); for (int j=0;j<16;j++) ctx_buf[j]=0; ctx_bufpos=0; ctx_counter=0;\n"
    "        if (r&1) sc_sha256_update(state,ctx_buf,&ctx_bufpos,&ctx_counter,p_bytes,plen);\n"
    "        else sc_sha256_update(state,ctx_buf,&ctx_bufpos,&ctx_counter,curin,32);\n"
    "        if (r%3) sc_sha256_update(state,ctx_buf,&ctx_bufpos,&ctx_counter,s_bytes,saltlen);\n"
    "        if (r%7) sc_sha256_update(state,ctx_buf,&ctx_bufpos,&ctx_counter,p_bytes,plen);\n"
    "        if (r&1) sc_sha256_update(state,ctx_buf,&ctx_bufpos,&ctx_counter,curin,32);\n"
    "        else sc_sha256_update(state,ctx_buf,&ctx_bufpos,&ctx_counter,p_bytes,plen);\n"
    "        sc_sha256_final(state,ctx_buf,ctx_bufpos,ctx_counter,curin);\n"
    "    }\n"
    "\n"
    "    uint hx=(uint)curin[0]|((uint)curin[1]<<8)|((uint)curin[2]<<16)|((uint)curin[3]<<24);\n"
    "    uint hy=(uint)curin[4]|((uint)curin[5]<<8)|((uint)curin[6]<<16)|((uint)curin[7]<<24);\n"
    "    uint hz=(uint)curin[8]|((uint)curin[9]<<8)|((uint)curin[10]<<16)|((uint)curin[11]<<24);\n"
    "    uint hw=(uint)curin[12]|((uint)curin[13]<<8)|((uint)curin[14]<<16)|((uint)curin[15]<<24);\n"
    "\n"
    "    uint4 h = uint4(hx, hy, hz, hw);\n"
    "    ulong key = (ulong(h.y) << 32) | h.x;\n"
    "    uint fp = uint(key >> 32); if (fp == 0) fp = 1;\n"
    "    ulong pos = (key ^ (key >> 32)) & params.compact_mask;\n"
    "    for (uint p = 0; p < params.max_probe; p++) {\n"
    "        uint cfp = compact_fp[pos]; if (cfp == 0) break;\n"
    "        if (cfp == fp) {\n"
    "            uint idx = compact_idx[pos];\n"
    "            if (idx < params.hash_data_count) {\n"
    "                ulong off = hash_data_off[idx];\n"
    "                device const uint *ref = (device const uint *)(hash_data_buf + off);\n"
    "                if (h.x==ref[0]&&h.y==ref[1]&&h.z==ref[2]&&h.w==ref[3]) {\n"
    "                    uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                    if (slot < params.max_hits) {\n"
    "                        uint base = slot * HIT_STRIDE;\n"
    "                        hits[base]=word_idx; hits[base+1]=salt_idx; hits[base+2]=1;\n"
    "                        hits[base+3]=hx; hits[base+4]=hy; hits[base+5]=hz; hits[base+6]=hw;\n"
    "                        hits[base+7]=(uint)curin[16]|((uint)curin[17]<<8)|((uint)curin[18]<<16)|((uint)curin[19]<<24);\n"
    "                        hits[base+8]=(uint)curin[20]|((uint)curin[21]<<8)|((uint)curin[22]<<16)|((uint)curin[23]<<24);\n"
    "                        hits[base+9]=(uint)curin[24]|((uint)curin[25]<<8)|((uint)curin[26]<<16)|((uint)curin[27]<<24);\n"
    "                        hits[base+10]=(uint)curin[28]|((uint)curin[29]<<8)|((uint)curin[30]<<16)|((uint)curin[31]<<24);\n"
    "                        for (uint _z = 11; _z < HIT_STRIDE; _z++) hits[base+_z] = 0;\n"
    "                    }\n"
    "                    return;\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "        pos = (pos + 1) & params.compact_mask;\n"
    "    }\n"
    "}\n"
;
