/* Auto-generated from metal_sha512unsalted.metal -- do not edit */
static const char metal_sha512unsalted_str[] =
    "/* metal_sha512unsalted.metal — Pre-padded unsalted SHA512/SHA384 with mask expansion\n"
    " *\n"
    " * SELF-CONTAINED: This file includes its own Metal preamble, MetalParams,\n"
    " * and SHA512 functions. It is NOT concatenated with metal_common.metal\n"
    " * because the combined source exceeds the Metal JIT compiler's memory limits.\n"
    " */\n"
    "#include <metal_stdlib>\n"
    "using namespace metal;\n"
    "\n"
    "constant uint HIT_STRIDE = 19;\n"
    "\n"
    "struct MetalParams {\n"
    "    uint64_t compact_mask;\n"
    "    uint     num_words;\n"
    "    uint     num_salts;\n"
    "    uint     salt_start;\n"
    "    uint     max_probe;\n"
    "    uint     hash_data_count;\n"
    "    uint     max_hits;\n"
    "    uint     overflow_count;\n"
    "    uint     max_iter;\n"
    "    uint     num_masks;\n"
    "    uint64_t mask_start;\n"
    "    uint     n_prepend;\n"
    "    uint     n_append;\n"
    "    uint     iter_count;\n"
    "    uint64_t mask_base0;\n"
    "    uint64_t mask_base1;\n"
    "};\n"
    "\n"
    "static inline ulong bswap64(ulong x) {\n"
    "    return ((x >> 56) & 0xffUL) | ((x >> 40) & 0xff00UL) |\n"
    "           ((x >> 24) & 0xff0000UL) | ((x >> 8) & 0xff000000UL) |\n"
    "           ((x << 8) & 0xff00000000UL) | ((x << 24) & 0xff0000000000UL) |\n"
    "           ((x << 40) & 0xff000000000000UL) | ((x << 56) & 0xff00000000000000UL);\n"
    "}\n"
    "\n"
    "static inline ulong rotr64(ulong x, uint n) { return (x >> n) | (x << (64 - n)); }\n"
    "\n"
    "static ulong hex_byte_be64(uint b) {\n"
    "    uint lo = b & 0xf, hi = b >> 4;\n"
    "    return ((ulong)(hi < 10 ? hi + '0' : hi - 10 + 'a') << 8)\n"
    "         | (lo < 10 ? lo + '0' : lo - 10 + 'a');\n"
    "}\n"
    "\n"
    "constant ulong K512[80] = {\n"
    "    0x428a2f98d728ae22UL,0x7137449123ef65cdUL,0xb5c0fbcfec4d3b2fUL,0xe9b5dba58189dbbcUL,\n"
    "    0x3956c25bf348b538UL,0x59f111f1b605d019UL,0x923f82a4af194f9bUL,0xab1c5ed5da6d8118UL,\n"
    "    0xd807aa98a3030242UL,0x12835b0145706fbeUL,0x243185be4ee4b28cUL,0x550c7dc3d5ffb4e2UL,\n"
    "    0x72be5d74f27b896fUL,0x80deb1fe3b1696b1UL,0x9bdc06a725c71235UL,0xc19bf174cf692694UL,\n"
    "    0xe49b69c19ef14ad2UL,0xefbe4786384f25e3UL,0x0fc19dc68b8cd5b5UL,0x240ca1cc77ac9c65UL,\n"
    "    0x2de92c6f592b0275UL,0x4a7484aa6ea6e483UL,0x5cb0a9dcbd41fbd4UL,0x76f988da831153b5UL,\n"
    "    0x983e5152ee66dfabUL,0xa831c66d2db43210UL,0xb00327c898fb213fUL,0xbf597fc7beef0ee4UL,\n"
    "    0xc6e00bf33da88fc2UL,0xd5a79147930aa725UL,0x06ca6351e003826fUL,0x142929670a0e6e70UL,\n"
    "    0x27b70a8546d22ffcUL,0x2e1b21385c26c926UL,0x4d2c6dfc5ac42aedUL,0x53380d139d95b3dfUL,\n"
    "    0x650a73548baf63deUL,0x766a0abb3c77b2a8UL,0x81c2c92e47edaee6UL,0x92722c851482353bUL,\n"
    "    0xa2bfe8a14cf10364UL,0xa81a664bbc423001UL,0xc24b8b70d0f89791UL,0xc76c51a30654be30UL,\n"
    "    0xd192e819d6ef5218UL,0xd69906245565a910UL,0xf40e35855771202aUL,0x106aa07032bbd1b8UL,\n"
    "    0x19a4c116b8d2d0c8UL,0x1e376c085141ab53UL,0x2748774cdf8eeb99UL,0x34b0bcb5e19b48a8UL,\n"
    "    0x391c0cb3c5c95a63UL,0x4ed8aa4ae3418acbUL,0x5b9cca4f7763e373UL,0x682e6ff3d6b2b8a3UL,\n"
    "    0x748f82ee5defb2fcUL,0x78a5636f43172f60UL,0x84c87814a1f0ab72UL,0x8cc702081a6439ecUL,\n"
    "    0x90befffa23631e28UL,0xa4506cebde82bde9UL,0xbef9a3f7b2c67915UL,0xc67178f2e372532bUL,\n"
    "    0xca273eceea26619cUL,0xd186b8c721c0c207UL,0xeada7dd6cde0eb1eUL,0xf57d4f7fee6ed178UL,\n"
    "    0x06f067aa72176fbaUL,0x0a637dc5a2c898a6UL,0x113f9804bef90daeUL,0x1b710b35131c471bUL,\n"
    "    0x28db77f523047d84UL,0x32caab7b40c72493UL,0x3c9ebe0a15c9bebcUL,0x431d67c49c100d4cUL,\n"
    "    0x4cc5d4becb3e42b6UL,0x597f299cfc657e2aUL,0x5fcb6fab3ad6faecUL,0x6c44198c4a475817UL\n"
    "};\n"
    "\n"
    "static void __attribute__((noinline)) sha512_compress(thread ulong *state, thread ulong *M) {\n"
    "    ulong W[16];\n"
    "    for (int i=0;i<16;i++) W[i]=M[i];\n"
    "    ulong a=state[0],b=state[1],c=state[2],d=state[3],\n"
    "          e=state[4],f=state[5],g=state[6],h=state[7];\n"
    "    #define S5R(i,wi) { \\\n"
    "        ulong S1=rotr64(e,14)^rotr64(e,18)^rotr64(e,41); \\\n"
    "        ulong ch=(e&f)^(~e&g); ulong t1=h+S1+ch+K512[i]+(wi); \\\n"
    "        ulong S0=rotr64(a,28)^rotr64(a,34)^rotr64(a,39); \\\n"
    "        ulong maj=(a&b)^(a&c)^(b&c); ulong t2=S0+maj; \\\n"
    "        h=g;g=f;f=e;e=d+t1;d=c;c=b;b=a;a=t1+t2; }\n"
    "    #define S5W(i) { int j=(i)&15; \\\n"
    "        ulong x=W[((i)-15)&15]; ulong s0=rotr64(x,1)^rotr64(x,8)^(x>>7); \\\n"
    "        x=W[((i)-2)&15]; ulong s1=rotr64(x,19)^rotr64(x,61)^(x>>6); \\\n"
    "        W[j]=W[j]+s0+W[((i)-7)&15]+s1; }\n"
    "    S5R(0,W[0]);S5R(1,W[1]);S5R(2,W[2]);S5R(3,W[3]);\n"
    "    S5R(4,W[4]);S5R(5,W[5]);S5R(6,W[6]);S5R(7,W[7]);\n"
    "    S5R(8,W[8]);S5R(9,W[9]);S5R(10,W[10]);S5R(11,W[11]);\n"
    "    S5R(12,W[12]);S5R(13,W[13]);S5R(14,W[14]);S5R(15,W[15]);\n"
    "    S5W(16);S5R(16,W[0]);S5W(17);S5R(17,W[1]);S5W(18);S5R(18,W[2]);S5W(19);S5R(19,W[3]);\n"
    "    S5W(20);S5R(20,W[4]);S5W(21);S5R(21,W[5]);S5W(22);S5R(22,W[6]);S5W(23);S5R(23,W[7]);\n"
    "    S5W(24);S5R(24,W[8]);S5W(25);S5R(25,W[9]);S5W(26);S5R(26,W[10]);S5W(27);S5R(27,W[11]);\n"
    "    S5W(28);S5R(28,W[12]);S5W(29);S5R(29,W[13]);S5W(30);S5R(30,W[14]);S5W(31);S5R(31,W[15]);\n"
    "    S5W(32);S5R(32,W[0]);S5W(33);S5R(33,W[1]);S5W(34);S5R(34,W[2]);S5W(35);S5R(35,W[3]);\n"
    "    S5W(36);S5R(36,W[4]);S5W(37);S5R(37,W[5]);S5W(38);S5R(38,W[6]);S5W(39);S5R(39,W[7]);\n"
    "    S5W(40);S5R(40,W[8]);S5W(41);S5R(41,W[9]);S5W(42);S5R(42,W[10]);S5W(43);S5R(43,W[11]);\n"
    "    S5W(44);S5R(44,W[12]);S5W(45);S5R(45,W[13]);S5W(46);S5R(46,W[14]);S5W(47);S5R(47,W[15]);\n"
    "    S5W(48);S5R(48,W[0]);S5W(49);S5R(49,W[1]);S5W(50);S5R(50,W[2]);S5W(51);S5R(51,W[3]);\n"
    "    S5W(52);S5R(52,W[4]);S5W(53);S5R(53,W[5]);S5W(54);S5R(54,W[6]);S5W(55);S5R(55,W[7]);\n"
    "    S5W(56);S5R(56,W[8]);S5W(57);S5R(57,W[9]);S5W(58);S5R(58,W[10]);S5W(59);S5R(59,W[11]);\n"
    "    S5W(60);S5R(60,W[12]);S5W(61);S5R(61,W[13]);S5W(62);S5R(62,W[14]);S5W(63);S5R(63,W[15]);\n"
    "    S5W(64);S5R(64,W[0]);S5W(65);S5R(65,W[1]);S5W(66);S5R(66,W[2]);S5W(67);S5R(67,W[3]);\n"
    "    S5W(68);S5R(68,W[4]);S5W(69);S5R(69,W[5]);S5W(70);S5R(70,W[6]);S5W(71);S5R(71,W[7]);\n"
    "    S5W(72);S5R(72,W[8]);S5W(73);S5R(73,W[9]);S5W(74);S5R(74,W[10]);S5W(75);S5R(75,W[11]);\n"
    "    S5W(76);S5R(76,W[12]);S5W(77);S5R(77,W[13]);S5W(78);S5R(78,W[14]);S5W(79);S5R(79,W[15]);\n"
    "    #undef S5R\n"
    "    #undef S5W\n"
    "    state[0]+=a;state[1]+=b;state[2]+=c;state[3]+=d;\n"
    "    state[4]+=e;state[5]+=f;state[6]+=g;state[7]+=h;\n"
    "}\n"
    "\n"
    "static void sha512_to_hex_lc(thread ulong *state, thread ulong *M) {\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        ulong s = state[i];\n"
    "        uint b0=(s>>56)&0xff,b1=(s>>48)&0xff,b2=(s>>40)&0xff,b3=(s>>32)&0xff;\n"
    "        uint b4=(s>>24)&0xff,b5=(s>>16)&0xff,b6=(s>>8)&0xff,b7=s&0xff;\n"
    "        M[i*2]=(hex_byte_be64(b0)<<48)|(hex_byte_be64(b1)<<32)|(hex_byte_be64(b2)<<16)|hex_byte_be64(b3);\n"
    "        M[i*2+1]=(hex_byte_be64(b4)<<48)|(hex_byte_be64(b5)<<32)|(hex_byte_be64(b6)<<16)|hex_byte_be64(b7);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* Compact probe-and-emit for SHA512 family. Probes compact table with first\n"
    " * 128 bits, writes full hash (nwords uint32 from state) on hit. */\n"
    "static void __attribute__((noinline)) sha512_probe_emit(\n"
    "    thread ulong *state, int nwords, uint word_idx, uint mask_idx,\n"
    "    uint iter, uint max_iter,\n"
    "    device const uint *compact_fp, device const uint *compact_idx,\n"
    "    uint64_t compact_mask, uint max_probe, uint hash_data_count, uint max_hits,\n"
    "    device const uint8_t *hash_data_buf, device const uint64_t *hash_data_off,\n"
    "    device const uint64_t *overflow_keys, device const uint8_t *overflow_hashes,\n"
    "    device const uint *overflow_offsets, uint overflow_count,\n"
    "    device uint *hits, device atomic_uint *hit_count)\n"
    "{\n"
    "    ulong s0 = bswap64(state[0]), s1 = bswap64(state[1]);\n"
    "    uint hx = (uint)s0, hy = (uint)(s0 >> 32);\n"
    "    uint hz = (uint)s1, hw = (uint)(s1 >> 32);\n"
    "    ulong key = (ulong(hy) << 32) | hx;\n"
    "    uint fp = uint(key >> 32); if (fp == 0) fp = 1;\n"
    "    ulong pos = (key ^ (key >> 32)) & compact_mask;\n"
    "    bool found = false;\n"
    "    for (uint p = 0; p < max_probe && !found; p++) {\n"
    "        uint cfp = compact_fp[pos]; if (cfp == 0) break;\n"
    "        if (cfp == fp) { uint idx = compact_idx[pos];\n"
    "            if (idx < hash_data_count) {\n"
    "                ulong off = hash_data_off[idx];\n"
    "                device const uint *ref = (device const uint *)(hash_data_buf + off);\n"
    "                if (hx == ref[0] && hy == ref[1] && hz == ref[2] && hw == ref[3]) found = true;\n"
    "            } }\n"
    "        pos = (pos + 1) & compact_mask;\n"
    "    }\n"
    "    if (!found && overflow_count > 0) {\n"
    "        int lo = 0, hi2 = int(overflow_count) - 1;\n"
    "        while (lo <= hi2 && !found) {\n"
    "            int mid = (lo + hi2) / 2; ulong mkey = overflow_keys[mid];\n"
    "            if (key < mkey) hi2 = mid - 1; else if (key > mkey) lo = mid + 1;\n"
    "            else {\n"
    "                for (int d = mid; d >= 0 && overflow_keys[d] == key && !found; d--) {\n"
    "                    device const uint *r = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (hx == r[0] && hy == r[1] && hz == r[2] && hw == r[3]) found = true; }\n"
    "                for (int d = mid+1; d < int(overflow_count) && overflow_keys[d] == key && !found; d++) {\n"
    "                    device const uint *r = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (hx == r[0] && hy == r[1] && hz == r[2] && hw == r[3]) found = true; }\n"
    "                break; } } }\n"
    "    if (found) {\n"
    "        uint slot = atomic_fetch_add_explicit(hit_count, 1u, memory_order_relaxed);\n"
    "        if (slot < max_hits) {\n"
    "            uint base = slot * HIT_STRIDE;\n"
    "            hits[base] = word_idx; hits[base+1] = mask_idx; hits[base+2] = iter;\n"
    "            for (int i = 0; i < nwords / 2; i++) {\n"
    "                ulong sw = bswap64(state[i]);\n"
    "                hits[base+3+i*2] = (uint)sw;\n"
    "                hits[base+3+i*2+1] = (uint)(sw >> 32);\n"
    "            }\n"
    "            for (uint _z = 3 + nwords; _z < HIT_STRIDE; _z++) hits[base+_z] = 0;\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "kernel void sha512_unsalted_batch(\n"
    "    device const uchar      *words       [[buffer(0)]],\n"
    "    device const ushort     *unused_lens [[buffer(1)]],\n"
    "    device const ushort     *unused2     [[buffer(2)]],\n"
    "    device const uint8_t    *mask_desc   [[buffer(3)]],\n"
    "    device const uint       *unused3     [[buffer(4)]],\n"
    "    device const ushort     *unused4     [[buffer(5)]],\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys   [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    ulong mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    /* Load pre-padded block (16 uint64 = 128 bytes, little-endian from host) */\n"
    "    device const ulong *src = (device const ulong *)(words + word_idx * 128);\n"
    "    ulong M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    /* Fill mask positions -- LE bytes within uint64 words */\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint n_total_m = n_pre + n_app;\n"
    "\n"
    "        if (n_pre > 0) {\n"
    "            uint append_combos = 1;\n"
    "            for (uint i = 0; i < n_app; i++)\n"
    "                append_combos *= mask_desc[n_pre + i];\n"
    "            uint prepend_idx = (uint)(mask_idx / append_combos);\n"
    "            uint append_idx = (uint)(mask_idx % append_combos);\n"
    "\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                int wi = i >> 3;\n"
    "                int bi = (i & 7) << 3;\n"
    "                M[wi] = (M[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "            }\n"
    "\n"
    "            if (n_app > 0) {\n"
    "                int total_len = (int)(M[15] & 0xFFFFFFFFUL);\n"
    "                int app_start = total_len - (int)n_app;\n"
    "                uint aidx = append_idx;\n"
    "                for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                    int pos_idx = n_pre + i;\n"
    "                    uint sz = mask_desc[pos_idx];\n"
    "                    uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                    aidx /= sz;\n"
    "                    int pos = app_start + i;\n"
    "                    int wi = pos >> 3;\n"
    "                    int bi = (pos & 7) << 3;\n"
    "                    M[wi] = (M[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "                }\n"
    "            }\n"
    "        } else {\n"
    "            /* Append-only (brute-force): host pre-decomposes mask_start into\n"
    "             * per-position base offsets in mask_base0/mask_base1. Kernel does\n"
    "             * fast uint32 local decomposition and adds to base with carry. */\n"
    "            int total_len = (int)(M[15] & 0xFFFFFFFFUL);\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint local_idx = tid % params.num_masks;\n"
    "            uint aidx = local_idx;\n"
    "            uint carry = 0;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uint local_digit = aidx % sz;\n"
    "                aidx /= sz;\n"
    "                uint base_digit = (i < 8)\n"
    "                    ? (uint)((params.mask_base0 >> (i * 8)) & 0xFF)\n"
    "                    : (uint)((params.mask_base1 >> ((i - 8) * 8)) & 0xFF);\n"
    "                uint sum = base_digit + local_digit + carry;\n"
    "                carry = sum / sz;\n"
    "                uint final_digit = sum % sz;\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + final_digit];\n"
    "                int pos = app_start + i;\n"
    "                int wi = pos >> 3;\n"
    "                int bi = (pos & 7) << 3;\n"
    "                M[wi] = (M[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Save bit-length before byte-swap.\n"
    "     * Host stores bitlen as uint32 at byte offset 120 = low 32 bits of M[15] (LE). */\n"
    "    uint bitlen = (uint)(M[15] & 0xFFFFFFFFUL);\n"
    "\n"
    "    /* Convert M[] from little-endian to big-endian for SHA512 */\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap64(M[i]);\n"
    "\n"
    "    /* Fix up padding: SHA512 stores 128-bit big-endian bit count at M[14..15] */\n"
    "    M[14] = 0;\n"
    "    M[15] = (ulong)bitlen;\n"
    "\n"
    "    /* SHA512 compress */\n"
    "    ulong state[8] = {\n"
    "        0x6a09e667f3bcc908UL, 0xbb67ae8584caa73bUL,\n"
    "        0x3c6ef372fe94f82bUL, 0xa54ff53a5f1d36f1UL,\n"
    "        0x510e527fade682d1UL, 0x9b05688c2b3e6c1fUL,\n"
    "        0x1f83d9abfb41bd6bUL, 0x5be0cd19137e2179UL\n"
    "    };\n"
    "    sha512_compress(state, M);\n"
    "\n"
    "    uint max_iter = params.max_iter;\n"
    "\n"
    "    for (uint iter = 1; iter <= max_iter; iter++) {\n"
    "        sha512_probe_emit(state, 16, word_idx, mask_idx, iter, max_iter,\n"
    "            compact_fp, compact_idx, params.compact_mask, params.max_probe,\n"
    "            params.hash_data_count, params.max_hits,\n"
    "            hash_data_buf, hash_data_off, overflow_keys, overflow_hashes,\n"
    "            overflow_offsets, params.overflow_count, hits, hit_count);\n"
    "        if (iter < max_iter) {\n"
    "            /* Hex-encode 8 BE state words into M[0..15] (128 hex chars = full block) */\n"
    "            sha512_to_hex_lc(state, M);\n"
    "            /* First compress: data block */\n"
    "            state[0] = 0x6a09e667f3bcc908UL; state[1] = 0xbb67ae8584caa73bUL;\n"
    "            state[2] = 0x3c6ef372fe94f82bUL; state[3] = 0xa54ff53a5f1d36f1UL;\n"
    "            state[4] = 0x510e527fade682d1UL; state[5] = 0x9b05688c2b3e6c1fUL;\n"
    "            state[6] = 0x1f83d9abfb41bd6bUL; state[7] = 0x5be0cd19137e2179UL;\n"
    "            sha512_compress(state, M);\n"
    "            /* Second compress: padding block */\n"
    "            M[0] = 0x8000000000000000UL;\n"
    "            for (int i = 1; i < 15; i++) M[i] = 0;\n"
    "            M[15] = 128 * 8;  /* 128 hex bytes = 1024 bits */\n"
    "            sha512_compress(state, M);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* SHA384 -- same compress as SHA512, different IV, truncated output (48 bytes) */\n"
    "kernel void sha384_unsalted_batch(\n"
    "    device const uchar      *words       [[buffer(0)]],\n"
    "    device const ushort     *unused_lens [[buffer(1)]],\n"
    "    device const ushort     *unused2     [[buffer(2)]],\n"
    "    device const uint8_t    *mask_desc   [[buffer(3)]],\n"
    "    device const uint       *unused3     [[buffer(4)]],\n"
    "    device const ushort     *unused4     [[buffer(5)]],\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys   [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    ulong mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    device const ulong *src = (device const ulong *)(words + word_idx * 128);\n"
    "    ulong M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint n_total_m = n_pre + n_app;\n"
    "\n"
    "        if (n_pre > 0) {\n"
    "            uint append_combos = 1;\n"
    "            for (uint i = 0; i < n_app; i++)\n"
    "                append_combos *= mask_desc[n_pre + i];\n"
    "            uint prepend_idx = (uint)(mask_idx / append_combos);\n"
    "            uint append_idx = (uint)(mask_idx % append_combos);\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                int wi = i >> 3;\n"
    "                int bi = (i & 7) << 3;\n"
    "                M[wi] = (M[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "            }\n"
    "            if (n_app > 0) {\n"
    "                int total_len = (int)(M[15] & 0xFFFFFFFFUL);\n"
    "                int app_start = total_len - (int)n_app;\n"
    "                uint aidx = append_idx;\n"
    "                for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                    int pos_idx = n_pre + i;\n"
    "                    uint sz = mask_desc[pos_idx];\n"
    "                    uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                    aidx /= sz;\n"
    "                    int pos = app_start + i;\n"
    "                    int wi = pos >> 3;\n"
    "                    int bi = (pos & 7) << 3;\n"
    "                    M[wi] = (M[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "                }\n"
    "            }\n"
    "        } else {\n"
    "            /* Append-only (brute-force): host pre-decomposes mask_start into\n"
    "             * per-position base offsets in mask_base0/mask_base1. Kernel does\n"
    "             * fast uint32 local decomposition and adds to base with carry. */\n"
    "            int total_len = (int)(M[15] & 0xFFFFFFFFUL);\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint local_idx = tid % params.num_masks;\n"
    "            uint aidx = local_idx;\n"
    "            uint carry = 0;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uint local_digit = aidx % sz;\n"
    "                aidx /= sz;\n"
    "                uint base_digit = (i < 8)\n"
    "                    ? (uint)((params.mask_base0 >> (i * 8)) & 0xFF)\n"
    "                    : (uint)((params.mask_base1 >> ((i - 8) * 8)) & 0xFF);\n"
    "                uint sum = base_digit + local_digit + carry;\n"
    "                carry = sum / sz;\n"
    "                uint final_digit = sum % sz;\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + final_digit];\n"
    "                int pos = app_start + i;\n"
    "                int wi = pos >> 3;\n"
    "                int bi = (pos & 7) << 3;\n"
    "                M[wi] = (M[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    uint bitlen = (uint)(M[15] & 0xFFFFFFFFUL);\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap64(M[i]);\n"
    "    M[14] = 0;\n"
    "    M[15] = (ulong)bitlen;\n"
    "\n"
    "    /* SHA384 IV */\n"
    "    ulong state[8] = {\n"
    "        0xcbbb9d5dc1059ed8UL, 0x629a292a367cd507UL,\n"
    "        0x9159015a3070dd17UL, 0x152fecd8f70e5939UL,\n"
    "        0x67332667ffc00b31UL, 0x8eb44a8768581511UL,\n"
    "        0xdb0c2e0d64f98fa7UL, 0x47b5481dbefa4fa4UL\n"
    "    };\n"
    "    sha512_compress(state, M);\n"
    "\n"
    "    sha512_probe_emit(state, 12, word_idx, mask_idx, 1, 1,\n"
    "        compact_fp, compact_idx, params.compact_mask, params.max_probe,\n"
    "        params.hash_data_count, params.max_hits,\n"
    "        hash_data_buf, hash_data_off, overflow_keys, overflow_hashes,\n"
    "        overflow_offsets, params.overflow_count, hits, hit_count);\n"
    "}\n"
;
