/* Auto-generated from metal_hmac_blake2s.metal -- do not edit */
static const char metal_hmac_blake2s_str[] =
    "/* metal_hmac_blake2s.metal — HMAC-BLAKE2S GPU kernel (e828, hashcat 33300)\n"
    " * BLAKE2s: 64-byte block, 32-byte output, little-endian, no tables.\n"
    " * HMAC key=$pass: BLAKE2S((K^opad) || BLAKE2S((K^ipad) || salt))\n"
    " * Hit stride: 7 (word_idx, salt_idx, iter, hx, hy, hz, hw)\n"
    " */\n"
    "\n"
    "/* B2S_IV, B2S_SIGMA, b2s_compress all provided by metal_common.metal */\n"
    "\n"
    "static void blake2s_hash(thread uint *out, thread const uchar *data, int datalen) {\n"
    "    uint h[8];\n"
    "    for (int i = 0; i < 8; i++) h[i] = B2S_IV[i];\n"
    "    h[0] ^= 0x01010020u;\n"
    "\n"
    "    uchar buf[64];\n"
    "    ulong counter = 0;\n"
    "    int pos = 0;\n"
    "    thread const uchar *p = data;\n"
    "    int remaining = datalen;\n"
    "\n"
    "    while (remaining > 0) {\n"
    "        if (pos == 64) {\n"
    "            counter += 64;\n"
    "            b2s_compress(h, buf, counter, 0);\n"
    "            pos = 0;\n"
    "        }\n"
    "        int take = 64 - pos;\n"
    "        if (take > remaining) take = remaining;\n"
    "        for (int i = 0; i < take; i++) buf[pos + i] = p[i];\n"
    "        pos += take; p += take; remaining -= take;\n"
    "    }\n"
    "    counter += pos;\n"
    "    for (int i = pos; i < 64; i++) buf[i] = 0;\n"
    "    b2s_compress(h, buf, counter, 1);\n"
    "    for (int i = 0; i < 8; i++) out[i] = h[i];\n"
    "}\n"
    "\n"
    "kernel void hmac_blake2s_kpass_batch(\n"
    "    device const uint8_t    *hexhashes   [[buffer(0)]],\n"
    "    device const ushort     *hexlens     [[buffer(1)]],\n"
    "    device const ushort     *unused2     [[buffer(2)]],\n"
    "    device const uint8_t    *salts       [[buffer(3)]],\n"
    "    device const uint       *salt_offsets [[buffer(4)]],\n"
    "    device const ushort     *salt_lens   [[buffer(5)]],\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys   [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int klen = hexlens[word_idx];\n"
    "    device const uint8_t *key = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int mlen = salt_lens[salt_idx];\n"
    "    device const uint8_t *msg = salts + soff;\n"
    "\n"
    "    uchar kpad[64];\n"
    "    if (klen > 64) {\n"
    "        uint kh[8];\n"
    "        uchar kb[256];\n"
    "        for (int i = 0; i < klen; i++) kb[i] = key[i];\n"
    "        blake2s_hash(kh, kb, klen);\n"
    "        for (int i = 0; i < 32; i++) kpad[i] = ((thread uchar *)kh)[i];\n"
    "        for (int i = 32; i < 64; i++) kpad[i] = 0;\n"
    "    } else {\n"
    "        for (int i = 0; i < klen; i++) kpad[i] = key[i];\n"
    "        for (int i = klen; i < 64; i++) kpad[i] = 0;\n"
    "    }\n"
    "\n"
    "    /* Inner: BLAKE2S((K ^ ipad) || salt) */\n"
    "    uchar ibuf[192];\n"
    "    for (int i = 0; i < 64; i++) ibuf[i] = kpad[i] ^ 0x36;\n"
    "    for (int i = 0; i < mlen; i++) ibuf[64 + i] = msg[i];\n"
    "    uint inner[8];\n"
    "    blake2s_hash(inner, ibuf, 64 + mlen);\n"
    "\n"
    "    /* Outer: BLAKE2S((K ^ opad) || inner_hash) */\n"
    "    uchar obuf[96];\n"
    "    for (int i = 0; i < 64; i++) obuf[i] = kpad[i] ^ 0x5c;\n"
    "    for (int i = 0; i < 32; i++) obuf[64 + i] = ((thread uchar *)inner)[i];\n"
    "    uint outer[8];\n"
    "    blake2s_hash(outer, obuf, 96);\n"
    "\n"
    "    uint hx = outer[0], hy = outer[1], hz = outer[2], hw = outer[3];\n"
    "\n"
    "    uint4 h = uint4(hx, hy, hz, hw);\n"
    "    ulong key2 = (ulong(h.y) << 32) | h.x;\n"
    "    uint fp = uint(key2 >> 32);\n"
    "    if (fp == 0) fp = 1;\n"
    "    ulong pos = (key2 ^ (key2 >> 32)) & params.compact_mask;\n"
    "    for (uint p = 0; p < params.max_probe; p++) {\n"
    "        uint cfp = compact_fp[pos];\n"
    "        if (cfp == 0) break;\n"
    "        if (cfp == fp) {\n"
    "            uint idx = compact_idx[pos];\n"
    "            if (idx < params.hash_data_count) {\n"
    "                ulong off = hash_data_off[idx];\n"
    "                device const uint *ref = (device const uint *)(hash_data_buf + off);\n"
    "                if (h.x == ref[0] && h.y == ref[1] && h.z == ref[2] && h.w == ref[3]) {\n"
    "                    uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                    if (slot < params.max_hits) {\n"
    "                        uint base = slot * HIT_STRIDE;\n"
    "                        hits[base] = word_idx; hits[base+1] = salt_idx; hits[base+2] = 1;\n"
    "                        hits[base+3] = h.x; hits[base+4] = h.y;\n"
    "                        hits[base+5] = h.z; hits[base+6] = h.w;\n"
    "                        for (uint _z = 7; _z < HIT_STRIDE; _z++) hits[base+_z] = 0;\n"
    "                    }\n"
    "                    return;\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "        pos = (pos + 1) & params.compact_mask;\n"
    "    }\n"
    "    if (params.overflow_count > 0) {\n"
    "        int lo = 0, hi = int(params.overflow_count) - 1;\n"
    "        while (lo <= hi) {\n"
    "            int mid = (lo + hi) / 2;\n"
    "            ulong mkey = overflow_keys[mid];\n"
    "            if (key2 < mkey) hi = mid - 1;\n"
    "            else if (key2 > mkey) lo = mid + 1;\n"
    "            else {\n"
    "                uint ooff = overflow_offsets[mid];\n"
    "                device const uint *oref = (device const uint *)(overflow_hashes + ooff);\n"
    "                if (h.x == oref[0] && h.y == oref[1] && h.z == oref[2] && h.w == oref[3]) {\n"
    "                    uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                    if (slot < params.max_hits) {\n"
    "                        uint base = slot * HIT_STRIDE;\n"
    "                        hits[base] = word_idx; hits[base+1] = salt_idx; hits[base+2] = 1;\n"
    "                        hits[base+3] = h.x; hits[base+4] = h.y;\n"
    "                        hits[base+5] = h.z; hits[base+6] = h.w;\n"
    "                        for (uint _z = 7; _z < HIT_STRIDE; _z++) hits[base+_z] = 0;\n"
    "                    }\n"
    "                    return;\n"
    "                }\n"
    "                break;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "}\n"
;
