/* Auto-generated from metal_md5saltpass.metal -- do not edit */
static const char metal_md5saltpass_str[] =
    "/* ---- MD5(salt + password) kernel ---- */\n"
    "kernel void md5saltpass_batch(\n"
    "    device const uint8_t    *hexhashes   [[buffer(0)]],\n"
    "    device const ushort     *hex_lens    [[buffer(1)]],\n"
    "    device const ushort     *unused2     [[buffer(2)]],\n"
    "    device const uint8_t    *salts       [[buffer(3)]],\n"
    "    device const uint       *salt_offsets [[buffer(4)]],\n"
    "    device const ushort     *salt_lens   [[buffer(5)]],\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys   [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hex_lens[word_idx];\n"
    "    device const uint8_t *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = slen + plen;\n"
    "\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "\n"
    "    uint hx = 0x67452301, hy = 0xEFCDAB89, hz = 0x98BADCFE, hw = 0x10325476;\n"
    "\n"
    "    if (total_len <= 55) {\n"
    "        for (int i = 0; i < slen; i++)\n"
    "            M[i >> 2] |= ((uint)salts[soff + i]) << ((i & 3) << 3);\n"
    "        for (int i = 0; i < plen; i++) {\n"
    "            int pos = slen + i;\n"
    "            M[pos >> 2] |= ((uint)pass[i]) << ((pos & 3) << 3);\n"
    "        }\n"
    "        M[total_len >> 2] |= 0x80u << ((total_len & 3) << 3);\n"
    "        M[14] = total_len * 8;\n"
    "        for (int i = 0; i < 64; i++) {\n"
    "            uint f, g;\n"
    "            if (i < 16)      { f = (hy & hz) | (~hy & hw); g = i; }\n"
    "            else if (i < 32) { f = (hw & hy) | (~hw & hz); g = (5*i+1) & 15; }\n"
    "            else if (i < 48) { f = hy ^ hz ^ hw;            g = (3*i+5) & 15; }\n"
    "            else              { f = hz ^ (~hw | hy);         g = (7*i)   & 15; }\n"
    "            f = f + hx + K[i] + M[g];\n"
    "            hx = hw; hw = hz; hz = hy;\n"
    "            hy = hy + ((f << S[i]) | (f >> (32 - S[i])));\n"
    "        }\n"
    "        hx += 0x67452301; hy += 0xEFCDAB89; hz += 0x98BADCFE; hw += 0x10325476;\n"
    "    } else {\n"
    "        /* Two blocks */\n"
    "        /* Fill first 64 bytes from salt+pass */\n"
    "        int salt_b1 = (slen < 64) ? slen : 64;\n"
    "        for (int i = 0; i < salt_b1; i++)\n"
    "            M[i >> 2] |= ((uint)salts[soff + i]) << ((i & 3) << 3);\n"
    "        int pass_b1 = 64 - salt_b1;\n"
    "        if (pass_b1 > plen) pass_b1 = plen;\n"
    "        for (int i = 0; i < pass_b1; i++) {\n"
    "            int pos = salt_b1 + i;\n"
    "            M[pos >> 2] |= ((uint)pass[i]) << ((pos & 3) << 3);\n"
    "        }\n"
    "        if (total_len < 64)\n"
    "            M[total_len >> 2] |= 0x80u << ((total_len & 3) << 3);\n"
    "        for (int i = 0; i < 64; i++) {\n"
    "            uint f, g;\n"
    "            if (i < 16)      { f = (hy & hz) | (~hy & hw); g = i; }\n"
    "            else if (i < 32) { f = (hw & hy) | (~hw & hz); g = (5*i+1) & 15; }\n"
    "            else if (i < 48) { f = hy ^ hz ^ hw;            g = (3*i+5) & 15; }\n"
    "            else              { f = hz ^ (~hw | hy);         g = (7*i)   & 15; }\n"
    "            f = f + hx + K[i] + M[g];\n"
    "            hx = hw; hw = hz; hz = hy;\n"
    "            hy = hy + ((f << S[i]) | (f >> (32 - S[i])));\n"
    "        }\n"
    "        hx += 0x67452301; hy += 0xEFCDAB89; hz += 0x98BADCFE; hw += 0x10325476;\n"
    "        /* Second block */\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int pos2 = 0;\n"
    "        int salt_b2 = slen - salt_b1;\n"
    "        for (int i = 0; i < salt_b2; i++, pos2++)\n"
    "            M[pos2 >> 2] |= ((uint)salts[soff + salt_b1 + i]) << ((pos2 & 3) << 3);\n"
    "        int pass_b2 = plen - pass_b1;\n"
    "        for (int i = 0; i < pass_b2; i++, pos2++)\n"
    "            M[pos2 >> 2] |= ((uint)pass[pass_b1 + i]) << ((pos2 & 3) << 3);\n"
    "        if (total_len >= 64)\n"
    "            M[pos2 >> 2] |= 0x80u << ((pos2 & 3) << 3);\n"
    "        M[14] = total_len * 8;\n"
    "        uint sx = hx, sy = hy, sz = hz, sw = hw;\n"
    "        for (int i = 0; i < 64; i++) {\n"
    "            uint f, g;\n"
    "            if (i < 16)      { f = (hy & hz) | (~hy & hw); g = i; }\n"
    "            else if (i < 32) { f = (hw & hy) | (~hw & hz); g = (5*i+1) & 15; }\n"
    "            else if (i < 48) { f = hy ^ hz ^ hw;            g = (3*i+5) & 15; }\n"
    "            else              { f = hz ^ (~hw | hy);         g = (7*i)   & 15; }\n"
    "            f = f + hx + K[i] + M[g];\n"
    "            hx = hw; hw = hz; hz = hy;\n"
    "            hy = hy + ((f << S[i]) | (f >> (32 - S[i])));\n"
    "        }\n"
    "        hx += sx; hy += sy; hz += sz; hw += sw;\n"
    "    }\n"
    "\n"
    "    /* Compact table probe */\n"
    "    uint4 h = uint4(hx, hy, hz, hw);\n"
    "    ulong key = (ulong(h.y) << 32) | h.x;\n"
    "    uint fp = uint(key >> 32);\n"
    "    if (fp == 0) fp = 1;\n"
    "    ulong pos = (key ^ (key >> 32)) & params.compact_mask;\n"
    "    for (uint p = 0; p < params.max_probe; p++) {\n"
    "        uint cfp = compact_fp[pos];\n"
    "        if (cfp == 0) break;\n"
    "        if (cfp == fp) {\n"
    "            uint idx = compact_idx[pos];\n"
    "            if (idx < params.hash_data_count) {\n"
    "                ulong off = hash_data_off[idx];\n"
    "                device const uint *ref = (device const uint *)(hash_data_buf + off);\n"
    "                if (h.x == ref[0] && h.y == ref[1] && h.z == ref[2] && h.w == ref[3]) {\n"
    "                    uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                    if (slot < params.max_hits) {\n"
    "                        uint base = slot * 6;\n"
    "                        hits[base] = word_idx; hits[base+1] = salt_idx;\n"
    "                        hits[base+2] = h.x; hits[base+3] = h.y;\n"
    "                        hits[base+4] = h.z; hits[base+5] = h.w;\n"
    "                    }\n"
    "                    return;\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "        pos = (pos + 1) & params.compact_mask;\n"
    "    }\n"
    "    /* Overflow binary search */\n"
    "    if (params.overflow_count > 0) {\n"
    "        int lo = 0, hi = int(params.overflow_count) - 1;\n"
    "        while (lo <= hi) {\n"
    "            int mid = (lo + hi) / 2;\n"
    "            ulong mkey = overflow_keys[mid];\n"
    "            if (key < mkey) hi = mid - 1;\n"
    "            else if (key > mkey) lo = mid + 1;\n"
    "            else {\n"
    "                uint ooff = overflow_offsets[mid];\n"
    "                device const uint *oref = (device const uint *)(overflow_hashes + ooff);\n"
    "                if (h.x == oref[0] && h.y == oref[1] && h.z == oref[2] && h.w == oref[3]) {\n"
    "                    uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                    if (slot < params.max_hits) {\n"
    "                        uint base = slot * 6;\n"
    "                        hits[base] = word_idx; hits[base+1] = salt_idx;\n"
    "                        hits[base+2] = h.x; hits[base+3] = h.y;\n"
    "                        hits[base+4] = h.z; hits[base+5] = h.w;\n"
    "                    }\n"
    "                    return;\n"
    "                }\n"
    "                for (int d = mid-1; d >= 0 && overflow_keys[d] == key; d--) {\n"
    "                    oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (h.x == oref[0] && h.y == oref[1] && h.z == oref[2] && h.w == oref[3]) {\n"
    "                        uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                        if (slot < params.max_hits) {\n"
    "                            uint base = slot * 6;\n"
    "                            hits[base] = word_idx; hits[base+1] = salt_idx;\n"
    "                            hits[base+2] = h.x; hits[base+3] = h.y;\n"
    "                            hits[base+4] = h.z; hits[base+5] = h.w;\n"
    "                        }\n"
    "                        return;\n"
    "                    }\n"
    "                }\n"
    "                for (int d = mid+1; d < int(params.overflow_count) && overflow_keys[d] == key; d++) {\n"
    "                    oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (h.x == oref[0] && h.y == oref[1] && h.z == oref[2] && h.w == oref[3]) {\n"
    "                        uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                        if (slot < params.max_hits) {\n"
    "                            uint base = slot * 6;\n"
    "                            hits[base] = word_idx; hits[base+1] = salt_idx;\n"
    "                            hits[base+2] = h.x; hits[base+3] = h.y;\n"
    "                            hits[base+4] = h.z; hits[base+5] = h.w;\n"
    "                        }\n"
    "                        return;\n"
    "                    }\n"
    "                }\n"
    "                break;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- MD5(password + salt) kernel ---- */\n"
    "kernel void md5passsalt_batch(\n"
    "    device const uint8_t    *hexhashes   [[buffer(0)]],\n"
    "    device const ushort     *hex_lens    [[buffer(1)]],\n"
    "    device const ushort     *unused2     [[buffer(2)]],\n"
    "    device const uint8_t    *salts       [[buffer(3)]],\n"
    "    device const uint       *salt_offsets [[buffer(4)]],\n"
    "    device const ushort     *salt_lens   [[buffer(5)]],\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys   [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hex_lens[word_idx];\n"
    "    device const uint8_t *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = plen + slen;\n"
    "\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "\n"
    "    uint hx = 0x67452301, hy = 0xEFCDAB89, hz = 0x98BADCFE, hw = 0x10325476;\n"
    "\n"
    "    if (total_len <= 55) {\n"
    "        for (int i = 0; i < plen; i++)\n"
    "            M[i >> 2] |= ((uint)pass[i]) << ((i & 3) << 3);\n"
    "        for (int i = 0; i < slen; i++) {\n"
    "            int pos = plen + i;\n"
    "            M[pos >> 2] |= ((uint)salts[soff + i]) << ((pos & 3) << 3);\n"
    "        }\n"
    "        M[total_len >> 2] |= 0x80u << ((total_len & 3) << 3);\n"
    "        M[14] = total_len * 8;\n"
    "        for (int i = 0; i < 64; i++) {\n"
    "            uint f, g;\n"
    "            if (i < 16)      { f = (hy & hz) | (~hy & hw); g = i; }\n"
    "            else if (i < 32) { f = (hw & hy) | (~hw & hz); g = (5*i+1) & 15; }\n"
    "            else if (i < 48) { f = hy ^ hz ^ hw;            g = (3*i+5) & 15; }\n"
    "            else              { f = hz ^ (~hw | hy);         g = (7*i)   & 15; }\n"
    "            f = f + hx + K[i] + M[g];\n"
    "            hx = hw; hw = hz; hz = hy;\n"
    "            hy = hy + ((f << S[i]) | (f >> (32 - S[i])));\n"
    "        }\n"
    "        hx += 0x67452301; hy += 0xEFCDAB89; hz += 0x98BADCFE; hw += 0x10325476;\n"
    "    } else {\n"
    "        /* Two blocks: fill first 64 bytes from pass+salt */\n"
    "        int pass_b1 = (plen < 64) ? plen : 64;\n"
    "        for (int i = 0; i < pass_b1; i++)\n"
    "            M[i >> 2] |= ((uint)pass[i]) << ((i & 3) << 3);\n"
    "        int salt_b1 = 64 - pass_b1;\n"
    "        if (salt_b1 > slen) salt_b1 = slen;\n"
    "        for (int i = 0; i < salt_b1; i++) {\n"
    "            int pos = pass_b1 + i;\n"
    "            M[pos >> 2] |= ((uint)salts[soff + i]) << ((pos & 3) << 3);\n"
    "        }\n"
    "        if (total_len < 64)\n"
    "            M[total_len >> 2] |= 0x80u << ((total_len & 3) << 3);\n"
    "        for (int i = 0; i < 64; i++) {\n"
    "            uint f, g;\n"
    "            if (i < 16)      { f = (hy & hz) | (~hy & hw); g = i; }\n"
    "            else if (i < 32) { f = (hw & hy) | (~hw & hz); g = (5*i+1) & 15; }\n"
    "            else if (i < 48) { f = hy ^ hz ^ hw;            g = (3*i+5) & 15; }\n"
    "            else              { f = hz ^ (~hw | hy);         g = (7*i)   & 15; }\n"
    "            f = f + hx + K[i] + M[g];\n"
    "            hx = hw; hw = hz; hz = hy;\n"
    "            hy = hy + ((f << S[i]) | (f >> (32 - S[i])));\n"
    "        }\n"
    "        hx += 0x67452301; hy += 0xEFCDAB89; hz += 0x98BADCFE; hw += 0x10325476;\n"
    "        /* Second block */\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int pos2 = 0;\n"
    "        int pass_b2 = plen - pass_b1;\n"
    "        for (int i = 0; i < pass_b2; i++, pos2++)\n"
    "            M[pos2 >> 2] |= ((uint)pass[pass_b1 + i]) << ((pos2 & 3) << 3);\n"
    "        int salt_b2 = slen - salt_b1;\n"
    "        for (int i = 0; i < salt_b2; i++, pos2++)\n"
    "            M[pos2 >> 2] |= ((uint)salts[soff + salt_b1 + i]) << ((pos2 & 3) << 3);\n"
    "        if (total_len >= 64)\n"
    "            M[pos2 >> 2] |= 0x80u << ((pos2 & 3) << 3);\n"
    "        M[14] = total_len * 8;\n"
    "        uint sx = hx, sy = hy, sz = hz, sw = hw;\n"
    "        for (int i = 0; i < 64; i++) {\n"
    "            uint f, g;\n"
    "            if (i < 16)      { f = (hy & hz) | (~hy & hw); g = i; }\n"
    "            else if (i < 32) { f = (hw & hy) | (~hw & hz); g = (5*i+1) & 15; }\n"
    "            else if (i < 48) { f = hy ^ hz ^ hw;            g = (3*i+5) & 15; }\n"
    "            else              { f = hz ^ (~hw | hy);         g = (7*i)   & 15; }\n"
    "            f = f + hx + K[i] + M[g];\n"
    "            hx = hw; hw = hz; hz = hy;\n"
    "            hy = hy + ((f << S[i]) | (f >> (32 - S[i])));\n"
    "        }\n"
    "        hx += sx; hy += sy; hz += sz; hw += sw;\n"
    "    }\n"
    "\n"
    "    uint4 h = uint4(hx, hy, hz, hw);\n"
    "    ulong key = (ulong(h.y) << 32) | h.x;\n"
    "    uint fp = uint(key >> 32);\n"
    "    if (fp == 0) fp = 1;\n"
    "    ulong pos = (key ^ (key >> 32)) & params.compact_mask;\n"
    "    for (uint p = 0; p < params.max_probe; p++) {\n"
    "        uint cfp = compact_fp[pos];\n"
    "        if (cfp == 0) break;\n"
    "        if (cfp == fp) {\n"
    "            uint idx = compact_idx[pos];\n"
    "            if (idx < params.hash_data_count) {\n"
    "                ulong off = hash_data_off[idx];\n"
    "                device const uint *ref = (device const uint *)(hash_data_buf + off);\n"
    "                if (h.x == ref[0] && h.y == ref[1] && h.z == ref[2] && h.w == ref[3]) {\n"
    "                    uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                    if (slot < params.max_hits) {\n"
    "                        uint base = slot * 6;\n"
    "                        hits[base] = word_idx; hits[base+1] = salt_idx;\n"
    "                        hits[base+2] = h.x; hits[base+3] = h.y;\n"
    "                        hits[base+4] = h.z; hits[base+5] = h.w;\n"
    "                    }\n"
    "                    return;\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "        pos = (pos + 1) & params.compact_mask;\n"
    "    }\n"
    "    if (params.overflow_count > 0) {\n"
    "        int lo = 0, hi = int(params.overflow_count) - 1;\n"
    "        while (lo <= hi) {\n"
    "            int mid = (lo + hi) / 2;\n"
    "            ulong mkey = overflow_keys[mid];\n"
    "            if (key < mkey) hi = mid - 1;\n"
    "            else if (key > mkey) lo = mid + 1;\n"
    "            else {\n"
    "                uint ooff = overflow_offsets[mid];\n"
    "                device const uint *oref = (device const uint *)(overflow_hashes + ooff);\n"
    "                if (h.x == oref[0] && h.y == oref[1] && h.z == oref[2] && h.w == oref[3]) {\n"
    "                    uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                    if (slot < params.max_hits) {\n"
    "                        uint base = slot * 6;\n"
    "                        hits[base] = word_idx; hits[base+1] = salt_idx;\n"
    "                        hits[base+2] = h.x; hits[base+3] = h.y;\n"
    "                        hits[base+4] = h.z; hits[base+5] = h.w;\n"
    "                    }\n"
    "                    return;\n"
    "                }\n"
    "                break;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
;
