/* Auto-generated from metal_md5unsalted.metal -- do not edit */
static const char metal_md5unsalted_str[] =
    "/* metal_md5unsalted.metal — Pre-padded unsalted MD5 with mask expansion\n"
    " *\n"
    " * Input: 4096 pre-padded 64-byte M[] blocks (word_stride=64).\n"
    " * Dispatch: num_words × num_masks threads.\n"
    " * Hit stride: 6 (word_idx, mask_idx, hx, hy, hz, hw) or\n"
    " *             7 (word_idx, mask_idx, iter, hx, hy, hz, hw) when max_iter > 1\n"
    " */\n"
    "\n"
    "/* hex_byte_lc, md5_to_hex_lc provided by metal_common.metal */\n"
    "\n"
    "static void md5_compress(thread uint *hx, thread uint *hy, thread uint *hz, thread uint *hw, thread uint *M) {\n"
    "    uint a = *hx, b = *hy, c = *hz, d = *hw;\n"
    "    a += ((b&c)|(~b&d)) + M[ 0] + 0xd76aa478u; a = b + ((a<< 7)|(a>>25));\n"
    "    d += ((a&b)|(~a&c)) + M[ 1] + 0xe8c7b756u; d = a + ((d<<12)|(d>>20));\n"
    "    c += ((d&a)|(~d&b)) + M[ 2] + 0x242070dbu; c = d + ((c<<17)|(c>>15));\n"
    "    b += ((c&d)|(~c&a)) + M[ 3] + 0xc1bdceeeu; b = c + ((b<<22)|(b>>10));\n"
    "    a += ((b&c)|(~b&d)) + M[ 4] + 0xf57c0fafu; a = b + ((a<< 7)|(a>>25));\n"
    "    d += ((a&b)|(~a&c)) + M[ 5] + 0x4787c62au; d = a + ((d<<12)|(d>>20));\n"
    "    c += ((d&a)|(~d&b)) + M[ 6] + 0xa8304613u; c = d + ((c<<17)|(c>>15));\n"
    "    b += ((c&d)|(~c&a)) + M[ 7] + 0xfd469501u; b = c + ((b<<22)|(b>>10));\n"
    "    a += ((b&c)|(~b&d)) + M[ 8] + 0x698098d8u; a = b + ((a<< 7)|(a>>25));\n"
    "    d += ((a&b)|(~a&c)) + M[ 9] + 0x8b44f7afu; d = a + ((d<<12)|(d>>20));\n"
    "    c += ((d&a)|(~d&b)) + M[10] + 0xffff5bb1u; c = d + ((c<<17)|(c>>15));\n"
    "    b += ((c&d)|(~c&a)) + M[11] + 0x895cd7beu; b = c + ((b<<22)|(b>>10));\n"
    "    a += ((b&c)|(~b&d)) + M[12] + 0x6b901122u; a = b + ((a<< 7)|(a>>25));\n"
    "    d += ((a&b)|(~a&c)) + M[13] + 0xfd987193u; d = a + ((d<<12)|(d>>20));\n"
    "    c += ((d&a)|(~d&b)) + M[14] + 0xa679438eu; c = d + ((c<<17)|(c>>15));\n"
    "    b += ((c&d)|(~c&a)) + M[15] + 0x49b40821u; b = c + ((b<<22)|(b>>10));\n"
    "    a += ((d&b)|(~d&c)) + M[ 1] + 0xf61e2562u; a = b + ((a<< 5)|(a>>27));\n"
    "    d += ((c&a)|(~c&b)) + M[ 6] + 0xc040b340u; d = a + ((d<< 9)|(d>>23));\n"
    "    c += ((b&d)|(~b&a)) + M[11] + 0x265e5a51u; c = d + ((c<<14)|(c>>18));\n"
    "    b += ((a&c)|(~a&d)) + M[ 0] + 0xe9b6c7aau; b = c + ((b<<20)|(b>>12));\n"
    "    a += ((d&b)|(~d&c)) + M[ 5] + 0xd62f105du; a = b + ((a<< 5)|(a>>27));\n"
    "    d += ((c&a)|(~c&b)) + M[10] + 0x02441453u; d = a + ((d<< 9)|(d>>23));\n"
    "    c += ((b&d)|(~b&a)) + M[15] + 0xd8a1e681u; c = d + ((c<<14)|(c>>18));\n"
    "    b += ((a&c)|(~a&d)) + M[ 4] + 0xe7d3fbc8u; b = c + ((b<<20)|(b>>12));\n"
    "    a += ((d&b)|(~d&c)) + M[ 9] + 0x21e1cde6u; a = b + ((a<< 5)|(a>>27));\n"
    "    d += ((c&a)|(~c&b)) + M[14] + 0xc33707d6u; d = a + ((d<< 9)|(d>>23));\n"
    "    c += ((b&d)|(~b&a)) + M[ 3] + 0xf4d50d87u; c = d + ((c<<14)|(c>>18));\n"
    "    b += ((a&c)|(~a&d)) + M[ 8] + 0x455a14edu; b = c + ((b<<20)|(b>>12));\n"
    "    a += ((d&b)|(~d&c)) + M[13] + 0xa9e3e905u; a = b + ((a<< 5)|(a>>27));\n"
    "    d += ((c&a)|(~c&b)) + M[ 2] + 0xfcefa3f8u; d = a + ((d<< 9)|(d>>23));\n"
    "    c += ((b&d)|(~b&a)) + M[ 7] + 0x676f02d9u; c = d + ((c<<14)|(c>>18));\n"
    "    b += ((a&c)|(~a&d)) + M[12] + 0x8d2a4c8au; b = c + ((b<<20)|(b>>12));\n"
    "    a += (b^c^d) + M[ 5] + 0xfffa3942u; a = b + ((a<< 4)|(a>>28));\n"
    "    d += (a^b^c) + M[ 8] + 0x8771f681u; d = a + ((d<<11)|(d>>21));\n"
    "    c += (d^a^b) + M[11] + 0x6d9d6122u; c = d + ((c<<16)|(c>>16));\n"
    "    b += (c^d^a) + M[14] + 0xfde5380cu; b = c + ((b<<23)|(b>> 9));\n"
    "    a += (b^c^d) + M[ 1] + 0xa4beea44u; a = b + ((a<< 4)|(a>>28));\n"
    "    d += (a^b^c) + M[ 4] + 0x4bdecfa9u; d = a + ((d<<11)|(d>>21));\n"
    "    c += (d^a^b) + M[ 7] + 0xf6bb4b60u; c = d + ((c<<16)|(c>>16));\n"
    "    b += (c^d^a) + M[10] + 0xbebfbc70u; b = c + ((b<<23)|(b>> 9));\n"
    "    a += (b^c^d) + M[13] + 0x289b7ec6u; a = b + ((a<< 4)|(a>>28));\n"
    "    d += (a^b^c) + M[ 0] + 0xeaa127fau; d = a + ((d<<11)|(d>>21));\n"
    "    c += (d^a^b) + M[ 3] + 0xd4ef3085u; c = d + ((c<<16)|(c>>16));\n"
    "    b += (c^d^a) + M[ 6] + 0x04881d05u; b = c + ((b<<23)|(b>> 9));\n"
    "    a += (b^c^d) + M[ 9] + 0xd9d4d039u; a = b + ((a<< 4)|(a>>28));\n"
    "    d += (a^b^c) + M[12] + 0xe6db99e5u; d = a + ((d<<11)|(d>>21));\n"
    "    c += (d^a^b) + M[15] + 0x1fa27cf8u; c = d + ((c<<16)|(c>>16));\n"
    "    b += (c^d^a) + M[ 2] + 0xc4ac5665u; b = c + ((b<<23)|(b>> 9));\n"
    "    a += (c^(~d|b)) + M[ 0] + 0xf4292244u; a = b + ((a<< 6)|(a>>26));\n"
    "    d += (b^(~c|a)) + M[ 7] + 0x432aff97u; d = a + ((d<<10)|(d>>22));\n"
    "    c += (a^(~b|d)) + M[14] + 0xab9423a7u; c = d + ((c<<15)|(c>>17));\n"
    "    b += (d^(~a|c)) + M[ 5] + 0xfc93a039u; b = c + ((b<<21)|(b>>11));\n"
    "    a += (c^(~d|b)) + M[12] + 0x655b59c3u; a = b + ((a<< 6)|(a>>26));\n"
    "    d += (b^(~c|a)) + M[ 3] + 0x8f0ccc92u; d = a + ((d<<10)|(d>>22));\n"
    "    c += (a^(~b|d)) + M[10] + 0xffeff47du; c = d + ((c<<15)|(c>>17));\n"
    "    b += (d^(~a|c)) + M[ 1] + 0x85845dd1u; b = c + ((b<<21)|(b>>11));\n"
    "    a += (c^(~d|b)) + M[ 8] + 0x6fa87e4fu; a = b + ((a<< 6)|(a>>26));\n"
    "    d += (b^(~c|a)) + M[15] + 0xfe2ce6e0u; d = a + ((d<<10)|(d>>22));\n"
    "    c += (a^(~b|d)) + M[ 6] + 0xa3014314u; c = d + ((c<<15)|(c>>17));\n"
    "    b += (d^(~a|c)) + M[13] + 0x4e0811a1u; b = c + ((b<<21)|(b>>11));\n"
    "    a += (c^(~d|b)) + M[ 4] + 0xf7537e82u; a = b + ((a<< 6)|(a>>26));\n"
    "    d += (b^(~c|a)) + M[11] + 0xbd3af235u; d = a + ((d<<10)|(d>>22));\n"
    "    c += (a^(~b|d)) + M[ 2] + 0x2ad7d2bbu; c = d + ((c<<15)|(c>>17));\n"
    "    b += (d^(~a|c)) + M[ 9] + 0xeb86d391u; b = c + ((b<<21)|(b>>11));\n"
    "    *hx += a; *hy += b; *hz += c; *hw += d;\n"
    "}\n"
    "\n"
    "kernel void md5_unsalted_batch(\n"
    "    device const uint       *words       [[buffer(0)]],\n"
    "    device const ushort     *unused_lens [[buffer(1)]],\n"
    "    device const ushort     *unused2     [[buffer(2)]],\n"
    "    device const uint8_t    *mask_desc   [[buffer(3)]],\n"
    "    device const uint       *unused3     [[buffer(4)]],\n"
    "    device const ushort     *unused4     [[buffer(5)]],\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys   [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    uint mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    device const uint *src = words + word_idx * 16;\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint n_total_m = n_pre + n_app;\n"
    "        uint append_combos = 1;\n"
    "        for (uint i = 0; i < n_app; i++)\n"
    "            append_combos *= mask_desc[n_pre + i];\n"
    "\n"
    "        uint prepend_idx = mask_idx / append_combos;\n"
    "        uint append_idx = mask_idx % append_combos;\n"
    "\n"
    "        if (n_pre > 0) {\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                M[i >> 2] = (M[i >> 2] & ~(0xFFu << ((i & 3) << 3)))\n"
    "                           | ((uint)ch << ((i & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "\n"
    "        if (n_app > 0) {\n"
    "            int total_len = M[14] >> 3;\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint aidx = append_idx;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                int pos_idx = n_pre + i;\n"
    "                uint sz = mask_desc[pos_idx];\n"
    "                uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                aidx /= sz;\n"
    "                int pos = app_start + i;\n"
    "                M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                             | ((uint)ch << ((pos & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    uint hx = 0x67452301u, hy = 0xEFCDAB89u, hz = 0x98BADCFEu, hw = 0x10325476u;\n"
    "    md5_compress(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "    uint max_iter = params.max_iter;\n"
    "    uint hit_stride = (max_iter > 1) ? 7 : 6;\n"
    "\n"
    "    for (uint iter = 1; iter <= max_iter; iter++) {\n"
    "        uint4 h = uint4(hx, hy, hz, hw);\n"
    "        ulong key = (ulong(h.y) << 32) | h.x;\n"
    "        uint fp = uint(key >> 32);\n"
    "        if (fp == 0) fp = 1;\n"
    "        ulong pos = (key ^ (key >> 32)) & params.compact_mask;\n"
    "        bool found = false;\n"
    "        for (uint p = 0; p < params.max_probe && !found; p++) {\n"
    "            uint cfp = compact_fp[pos];\n"
    "            if (cfp == 0) break;\n"
    "            if (cfp == fp) {\n"
    "                uint idx = compact_idx[pos];\n"
    "                if (idx < params.hash_data_count) {\n"
    "                    ulong off = hash_data_off[idx];\n"
    "                    device const uint *ref = (device const uint *)(hash_data_buf + off);\n"
    "                    if (h.x == ref[0] && h.y == ref[1] && h.z == ref[2] && h.w == ref[3])\n"
    "                        found = true;\n"
    "                }\n"
    "            }\n"
    "            pos = (pos + 1) & params.compact_mask;\n"
    "        }\n"
    "        if (!found && params.overflow_count > 0) {\n"
    "            int lo = 0, hi2 = int(params.overflow_count) - 1;\n"
    "            while (lo <= hi2 && !found) {\n"
    "                int mid = (lo + hi2) / 2;\n"
    "                ulong mkey = overflow_keys[mid];\n"
    "                if (key < mkey) hi2 = mid - 1;\n"
    "                else if (key > mkey) lo = mid + 1;\n"
    "                else {\n"
    "                    for (int d = mid; d >= 0 && overflow_keys[d] == key && !found; d--) {\n"
    "                        device const uint *oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                        if (h.x == oref[0] && h.y == oref[1] && h.z == oref[2] && h.w == oref[3])\n"
    "                            found = true;\n"
    "                    }\n"
    "                    for (int d = mid+1; d < int(params.overflow_count) && overflow_keys[d] == key && !found; d++) {\n"
    "                        device const uint *oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                        if (h.x == oref[0] && h.y == oref[1] && h.z == oref[2] && h.w == oref[3])\n"
    "                            found = true;\n"
    "                    }\n"
    "                    break;\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "        if (found) {\n"
    "            uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "            if (slot < params.max_hits) {\n"
    "                uint base = slot * hit_stride;\n"
    "                hits[base] = word_idx; hits[base+1] = mask_idx;\n"
    "                if (hit_stride == 7) {\n"
    "                    hits[base+2] = iter;\n"
    "                    hits[base+3] = h.x; hits[base+4] = h.y;\n"
    "                    hits[base+5] = h.z; hits[base+6] = h.w;\n"
    "                } else {\n"
    "                    hits[base+2] = h.x; hits[base+3] = h.y;\n"
    "                    hits[base+4] = h.z; hits[base+5] = h.w;\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "        if (iter < max_iter) {\n"
    "            md5_to_hex_lc(hx, hy, hz, hw, M);\n"
    "            M[8] = 0x80;\n"
    "            for (int i = 9; i < 14; i++) M[i] = 0;\n"
    "            M[14] = 32 * 8; M[15] = 0;\n"
    "            hx = 0x67452301u; hy = 0xEFCDAB89u; hz = 0x98BADCFEu; hw = 0x10325476u;\n"
    "            md5_compress(&hx, &hy, &hz, &hw, M);\n"
    "        }\n"
    "    }\n"
    "}\n"
;
