/* Auto-generated from metal_sha1unsalted.metal -- do not edit */
static const char metal_sha1unsalted_str[] =
    "/* metal_sha1unsalted.metal — Pre-padded unsalted SHA1 with mask expansion\n"
    " *\n"
    " * Input: 4096 pre-padded 64-byte M[] blocks (word_stride=64).\n"
    " *   Packed in little-endian by host; kernel byte-swaps to big-endian.\n"
    " * Dispatch: num_words × num_masks threads.\n"
    " * Hit stride: 6 (word_idx, mask_idx, h0, h1, h2, h3) or\n"
    " *             7 (word_idx, mask_idx, iter, h0, h1, h2, h3) when max_iter > 1\n"
    " */\n"
    "\n"
    "/* bswap32, hex_byte_be, sha1_to_hex_lc, sha1_compress\n"
    " * all provided by metal_common.metal */\n"
    "\n"
    "kernel void sha1_unsalted_batch(\n"
    "    device const uint       *words       [[buffer(0)]],\n"
    "    device const ushort     *unused_lens [[buffer(1)]],\n"
    "    device const ushort     *unused2     [[buffer(2)]],\n"
    "    device const uint8_t    *mask_desc   [[buffer(3)]],\n"
    "    device const uint       *unused3     [[buffer(4)]],\n"
    "    device const ushort     *unused4     [[buffer(5)]],\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys   [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    ulong mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    device const uint *src = words + word_idx * 16;\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    /* Fill mask positions — operates on LE words (same as MD5 kernel) */\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint n_total_m = n_pre + n_app;\n"
    "\n"
    "        if (n_pre > 0) {\n"
    "            uint append_combos = 1;\n"
    "            for (uint i = 0; i < n_app; i++)\n"
    "                append_combos *= mask_desc[n_pre + i];\n"
    "            uint prepend_idx = (uint)(mask_idx / append_combos);\n"
    "            uint append_idx = (uint)(mask_idx % append_combos);\n"
    "\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                M[i >> 2] = (M[i >> 2] & ~(0xFFu << ((i & 3) << 3)))\n"
    "                           | ((uint)ch << ((i & 3) << 3));\n"
    "            }\n"
    "\n"
    "            if (n_app > 0) {\n"
    "                int total_len = M[14] >> 3;\n"
    "                int app_start = total_len - (int)n_app;\n"
    "                uint aidx = append_idx;\n"
    "                for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                    int pos_idx = n_pre + i;\n"
    "                    uint sz = mask_desc[pos_idx];\n"
    "                    uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                    aidx /= sz;\n"
    "                    int pos = app_start + i;\n"
    "                    M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                                 | ((uint)ch << ((pos & 3) << 3));\n"
    "                }\n"
    "            }\n"
    "        } else {\n"
    "            /* Append-only (brute-force): host pre-decomposes mask_start into\n"
    "             * per-position base offsets in mask_base0/mask_base1. Kernel does\n"
    "             * fast uint32 local decomposition and adds to base with carry. */\n"
    "            int total_len = M[14] >> 3;\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint local_idx = tid % params.num_masks;  /* uint32, fast */\n"
    "            uint aidx = local_idx;\n"
    "            uint carry = 0;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uint local_digit = aidx % sz;\n"
    "                aidx /= sz;\n"
    "                /* Extract pre-decomposed base digit from packed mask_base */\n"
    "                uint base_digit = (i < 8)\n"
    "                    ? (uint)((params.mask_base0 >> (i * 8)) & 0xFF)\n"
    "                    : (uint)((params.mask_base1 >> ((i - 8) * 8)) & 0xFF);\n"
    "                uint sum = base_digit + local_digit + carry;\n"
    "                carry = sum / sz;\n"
    "                uint final_digit = sum % sz;\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + final_digit];\n"
    "                int pos = app_start + i;\n"
    "                M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                             | ((uint)ch << ((pos & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Save bit-length from LE M[14] before byte-swap */\n"
    "    uint bitlen = M[14];\n"
    "\n"
    "    /* Convert M[] from little-endian to big-endian for SHA1 */\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap32(M[i]);\n"
    "\n"
    "    /* Fix up padding: SHA1 stores 64-bit big-endian bit count at M[14..15] */\n"
    "    M[14] = 0;\n"
    "    M[15] = bitlen;\n"
    "\n"
    "    /* SHA1 compress */\n"
    "    uint state[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "    sha1_compress(state, M);\n"
    "\n"
    "    uint max_iter = params.max_iter;\n"
    "    /* SHA1: 5 hash words. hit_stride = 2 + 5 = 7, or 3 + 5 = 8 with iter */\n"
    "    uint hit_stride = (max_iter > 1) ? 8 : 7;\n"
    "\n"
    "    for (uint iter = 1; iter <= max_iter; iter++) {\n"
    "        /* Byte-swap state to LE for compact table probe */\n"
    "        uint h[5];\n"
    "        for (int i = 0; i < 5; i++) h[i] = bswap32(state[i]);\n"
    "\n"
    "        ulong key = (ulong(h[1]) << 32) | h[0];\n"
    "        uint fp = uint(key >> 32);\n"
    "        if (fp == 0) fp = 1;\n"
    "        ulong pos = (key ^ (key >> 32)) & params.compact_mask;\n"
    "        bool found = false;\n"
    "        for (uint p = 0; p < params.max_probe && !found; p++) {\n"
    "            uint cfp = compact_fp[pos];\n"
    "            if (cfp == 0) break;\n"
    "            if (cfp == fp) {\n"
    "                uint idx = compact_idx[pos];\n"
    "                if (idx < params.hash_data_count) {\n"
    "                    ulong off = hash_data_off[idx];\n"
    "                    device const uint *ref = (device const uint *)(hash_data_buf + off);\n"
    "                    if (h[0] == ref[0] && h[1] == ref[1] && h[2] == ref[2] && h[3] == ref[3])\n"
    "                        found = true;\n"
    "                }\n"
    "            }\n"
    "            pos = (pos + 1) & params.compact_mask;\n"
    "        }\n"
    "        if (!found && params.overflow_count > 0) {\n"
    "            int lo = 0, hi2 = int(params.overflow_count) - 1;\n"
    "            while (lo <= hi2 && !found) {\n"
    "                int mid = (lo + hi2) / 2;\n"
    "                ulong mkey = overflow_keys[mid];\n"
    "                if (key < mkey) hi2 = mid - 1;\n"
    "                else if (key > mkey) lo = mid + 1;\n"
    "                else {\n"
    "                    for (int d = mid; d >= 0 && overflow_keys[d] == key && !found; d--) {\n"
    "                        device const uint *oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                        if (h[0] == oref[0] && h[1] == oref[1] && h[2] == oref[2] && h[3] == oref[3])\n"
    "                            found = true;\n"
    "                    }\n"
    "                    for (int d = mid+1; d < int(params.overflow_count) && overflow_keys[d] == key && !found; d++) {\n"
    "                        device const uint *oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                        if (h[0] == oref[0] && h[1] == oref[1] && h[2] == oref[2] && h[3] == oref[3])\n"
    "                            found = true;\n"
    "                    }\n"
    "                    break;\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "        if (found) {\n"
    "            uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "            if (slot < params.max_hits) {\n"
    "                uint base = slot * hit_stride;\n"
    "                hits[base] = word_idx; hits[base+1] = mask_idx;\n"
    "                if (max_iter > 1) {\n"
    "                    hits[base+2] = iter;\n"
    "                    for (int i = 0; i < 5; i++) hits[base+3+i] = h[i];\n"
    "                } else {\n"
    "                    for (int i = 0; i < 5; i++) hits[base+2+i] = h[i];\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "        if (iter < max_iter) {\n"
    "            /* Hex-encode BE state into BE M[0..9] (40 hex chars), set padding */\n"
    "            sha1_to_hex_lc(state, M);\n"
    "            M[10] = 0x80000000u;\n"
    "            for (int i = 11; i < 15; i++) M[i] = 0;\n"
    "            M[15] = 40 * 8;  /* 40 hex bytes = 320 bits */\n"
    "            state[0] = 0x67452301u; state[1] = 0xEFCDAB89u;\n"
    "            state[2] = 0x98BADCFEu; state[3] = 0x10325476u; state[4] = 0xC3D2E1F0u;\n"
    "            sha1_compress(state, M);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- SQL5: sha1(sha1(pass)) — hashcat mode 300 ---- */\n"
    "kernel void sql5_unsalted_batch(\n"
    "    device const uint       *words       [[buffer(0)]],\n"
    "    device const ushort     *unused_lens [[buffer(1)]],\n"
    "    device const ushort     *unused2     [[buffer(2)]],\n"
    "    device const uint8_t    *mask_desc   [[buffer(3)]],\n"
    "    device const uint       *unused3     [[buffer(4)]],\n"
    "    device const ushort     *unused4     [[buffer(5)]],\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys   [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    ulong mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    device const uint *src = words + word_idx * 16;\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint n_total_m = n_pre + n_app;\n"
    "        uint append_combos = 1;\n"
    "        for (uint i = 0; i < n_app; i++)\n"
    "            append_combos *= mask_desc[n_pre + i];\n"
    "        uint prepend_idx = (uint)(mask_idx / append_combos);\n"
    "        uint append_idx = (uint)(mask_idx % append_combos);\n"
    "        if (n_pre > 0) {\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                M[i >> 2] = (M[i >> 2] & ~(0xFFu << ((i & 3) << 3)))\n"
    "                           | ((uint)ch << ((i & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "        if (n_app > 0) {\n"
    "            int total_len = M[14] >> 3;\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint aidx = append_idx;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                int pos_idx = n_pre + i;\n"
    "                uint sz = mask_desc[pos_idx];\n"
    "                uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                aidx /= sz;\n"
    "                int pos = app_start + i;\n"
    "                M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                             | ((uint)ch << ((pos & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* First SHA1(password) */\n"
    "    uint bitlen = M[14];\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap32(M[i]);\n"
    "    M[14] = 0; M[15] = bitlen;\n"
    "\n"
    "    uint state[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "    sha1_compress(state, M);\n"
    "\n"
    "    /* Second SHA1(20-byte binary): fixed padding block */\n"
    "    for (int i = 0; i < 5; i++) M[i] = state[i];  /* already BE */\n"
    "    M[5] = 0x80000000u;\n"
    "    for (int i = 6; i < 15; i++) M[i] = 0;\n"
    "    M[15] = 160;  /* 20 bytes * 8 bits */\n"
    "\n"
    "    state[0] = 0x67452301u; state[1] = 0xEFCDAB89u;\n"
    "    state[2] = 0x98BADCFEu; state[3] = 0x10325476u; state[4] = 0xC3D2E1F0u;\n"
    "    sha1_compress(state, M);\n"
    "\n"
    "    /* SQL5: 5 hash words */\n"
    "    uint h[5];\n"
    "    for (int i = 0; i < 5; i++) h[i] = bswap32(state[i]);\n"
    "\n"
    "    ulong key = (ulong(h[1]) << 32) | h[0];\n"
    "    uint fp = uint(key >> 32);\n"
    "    if (fp == 0) fp = 1;\n"
    "    ulong pos = (key ^ (key >> 32)) & params.compact_mask;\n"
    "    bool found = false;\n"
    "    for (uint p = 0; p < params.max_probe && !found; p++) {\n"
    "        uint cfp = compact_fp[pos];\n"
    "        if (cfp == 0) break;\n"
    "        if (cfp == fp) {\n"
    "            uint idx = compact_idx[pos];\n"
    "            if (idx < params.hash_data_count) {\n"
    "                ulong off = hash_data_off[idx];\n"
    "                device const uint *ref = (device const uint *)(hash_data_buf + off);\n"
    "                if (h[0] == ref[0] && h[1] == ref[1] && h[2] == ref[2] && h[3] == ref[3])\n"
    "                    found = true;\n"
    "            }\n"
    "        }\n"
    "        pos = (pos + 1) & params.compact_mask;\n"
    "    }\n"
    "    if (!found && params.overflow_count > 0) {\n"
    "        int lo = 0, hi2 = int(params.overflow_count) - 1;\n"
    "        while (lo <= hi2 && !found) {\n"
    "            int mid = (lo + hi2) / 2;\n"
    "            ulong mkey = overflow_keys[mid];\n"
    "            if (key < mkey) hi2 = mid - 1;\n"
    "            else if (key > mkey) lo = mid + 1;\n"
    "            else {\n"
    "                for (int d = mid; d >= 0 && overflow_keys[d] == key && !found; d--) {\n"
    "                    device const uint *oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (h[0] == oref[0] && h[1] == oref[1] && h[2] == oref[2] && h[3] == oref[3])\n"
    "                        found = true;\n"
    "                }\n"
    "                for (int d = mid+1; d < int(params.overflow_count) && overflow_keys[d] == key && !found; d++) {\n"
    "                    device const uint *oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (h[0] == oref[0] && h[1] == oref[1] && h[2] == oref[2] && h[3] == oref[3])\n"
    "                        found = true;\n"
    "                }\n"
    "                break;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "    if (found) {\n"
    "        uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 7;  /* 2 + 5 */\n"
    "            hits[base] = word_idx; hits[base+1] = mask_idx;\n"
    "            for (int i = 0; i < 5; i++) hits[base+2+i] = h[i];\n"
    "        }\n"
    "    }\n"
    "}\n"
;
