/* Auto-generated from metal_md6256unsalted.metal -- do not edit */
static const char metal_md6256unsalted_str[] =
    "/* metal_md6256unsalted.metal — Pre-packed unsalted MD6-256 with mask expansion\n"
    " *\n"
    " * MD6-256: r=104 rounds, c=16, n=89, d=256.\n"
    " * Input: pre-packed N[89] (712-byte) blocks.\n"
    " * Hit stride: 6 (word_idx, mask_idx, hx, hy, hz, hw)\n"
    " */\n"
    "\n"
    "/* bswap64 provided by metal_common.metal */\n"
    "\n"
    "#define MD6_n  89\n"
    "#define MD6_c  16\n"
    "#define MD6_r  104\n"
    "#define MD6_t0  17\n"
    "#define MD6_t1  18\n"
    "#define MD6_t2  21\n"
    "#define MD6_t3  31\n"
    "#define MD6_t4  67\n"
    "#define MD6_t5  89\n"
    "\n"
    "constant int RS[16] = {10, 5,13,10,11,12, 2, 7,14,15, 7,13,11, 7, 6,12};\n"
    "constant int LS[16] = {11,24, 9,16,15, 9,27,15, 6, 2,29, 8,15, 5,31, 9};\n"
    "\n"
    "constant ulong MD6_S0 = 0x0123456789abcdefUL;\n"
    "constant ulong MD6_Smask = 0x7311c2812425cfa0UL;\n"
    "\n"
    "static void md6_compress_loop(thread ulong *A) {\n"
    "    ulong S = MD6_S0;\n"
    "    int i = MD6_n;\n"
    "    for (int j = 0; j < MD6_r * MD6_c; j += MD6_c) {\n"
    "        for (int step = 0; step < 16; step++) {\n"
    "            ulong x = S;\n"
    "            x ^= A[i + step - MD6_t5];\n"
    "            x ^= A[i + step - MD6_t0];\n"
    "            x ^= (A[i + step - MD6_t1] & A[i + step - MD6_t2]);\n"
    "            x ^= (A[i + step - MD6_t3] & A[i + step - MD6_t4]);\n"
    "            x ^= (x >> RS[step]);\n"
    "            A[i + step] = x ^ (x << LS[step]);\n"
    "        }\n"
    "        S = (S << 1) ^ (S >> 63) ^ (S & MD6_Smask);\n"
    "        i += 16;\n"
    "    }\n"
    "}\n"
    "\n"
    "kernel void md6_256_unsalted_batch(\n"
    "    device const uint8_t    *words       [[buffer(0)]],\n"
    "    device const ushort     *unused_lens [[buffer(1)]],\n"
    "    device const ushort     *unused2     [[buffer(2)]],\n"
    "    device const uint8_t    *mask_desc   [[buffer(3)]],\n"
    "    device const uint       *unused3     [[buffer(4)]],\n"
    "    device const ushort     *unused4     [[buffer(5)]],\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys   [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    ulong mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    device const ulong *src = (device const ulong *)(words + word_idx * 712);\n"
    "    ulong A[1753];\n"
    "    for (int i = 0; i < 89; i++) A[i] = src[i];\n"
    "\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint n_total_m = n_pre + n_app;\n"
    "\n"
    "        if (n_pre > 0) {\n"
    "            uint append_combos = 1;\n"
    "            for (uint i = 0; i < n_app; i++)\n"
    "                append_combos *= mask_desc[n_pre + i];\n"
    "            uint prepend_idx = (uint)(mask_idx / append_combos);\n"
    "            uint append_idx = (uint)(mask_idx % append_combos);\n"
    "\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                int wi = 25 + (i >> 3);\n"
    "                int bi = (i & 7) << 3;\n"
    "                A[wi] = (A[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "            }\n"
    "\n"
    "            if (n_app > 0) {\n"
    "                ulong V = A[24];\n"
    "                uint p_bits = (uint)((V >> 20) & 0xFFFFUL);\n"
    "                int total_len = (64*64 - (int)p_bits) / 8;\n"
    "                int app_start = total_len - (int)n_app;\n"
    "                uint aidx = append_idx;\n"
    "                for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                    int pos_idx = n_pre + i;\n"
    "                    uint sz = mask_desc[pos_idx];\n"
    "                    uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                    aidx /= sz;\n"
    "                    int pos = app_start + i;\n"
    "                    int wi = 25 + (pos >> 3);\n"
    "                    int bi = (pos & 7) << 3;\n"
    "                    A[wi] = (A[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "                }\n"
    "            }\n"
    "        } else {\n"
    "            /* Append-only (brute-force): host pre-decomposes mask_start into\n"
    "             * per-position base offsets in mask_base0/mask_base1. Kernel does\n"
    "             * fast uint32 local decomposition and adds to base with carry. */\n"
    "            ulong V = A[24];\n"
    "            uint p_bits = (uint)((V >> 20) & 0xFFFFUL);\n"
    "            int total_len = (64*64 - (int)p_bits) / 8;\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint local_idx = tid % params.num_masks;\n"
    "            uint aidx = local_idx;\n"
    "            uint carry = 0;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uint local_digit = aidx % sz;\n"
    "                aidx /= sz;\n"
    "                uint base_digit = (i < 8)\n"
    "                    ? (uint)((params.mask_base0 >> (i * 8)) & 0xFF)\n"
    "                    : (uint)((params.mask_base1 >> ((i - 8) * 8)) & 0xFF);\n"
    "                uint sum = base_digit + local_digit + carry;\n"
    "                carry = sum / sz;\n"
    "                uint final_digit = sum % sz;\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + final_digit];\n"
    "                int pos = app_start + i;\n"
    "                int wi = 25 + (pos >> 3);\n"
    "                int bi = (pos & 7) << 3;\n"
    "                A[wi] = (A[wi] & ~(0xFFUL << bi)) | ((ulong)ch << bi);\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Byte-swap B portion (A[25..88]) from LE to BE */\n"
    "    for (int i = 25; i < 89; i++) A[i] = bswap64(A[i]);\n"
    "\n"
    "    md6_compress_loop(A);\n"
    "\n"
    "    /* Extract output: last 4 uint64 words = A[1749..1752] = 256 bits = 8 uint32 */\n"
    "    uint h[8];\n"
    "    for (int i = 0; i < 4; i++) {\n"
    "        ulong s = bswap64(A[1749 + i]);\n"
    "        h[i*2]   = (uint)s;\n"
    "        h[i*2+1] = (uint)(s >> 32);\n"
    "    }\n"
    "\n"
    "    ulong key = (ulong(h[1]) << 32) | h[0];\n"
    "    uint fp = uint(key >> 32); if (fp == 0) fp = 1;\n"
    "    ulong pos = (key ^ (key >> 32)) & params.compact_mask;\n"
    "    bool found = false;\n"
    "    for (uint p = 0; p < params.max_probe && !found; p++) {\n"
    "        uint cfp = compact_fp[pos]; if (cfp == 0) break;\n"
    "        if (cfp == fp) { uint idx = compact_idx[pos];\n"
    "            if (idx < params.hash_data_count) {\n"
    "                ulong off = hash_data_off[idx];\n"
    "                device const uint *ref = (device const uint *)(hash_data_buf + off);\n"
    "                if (h[0] == ref[0] && h[1] == ref[1] && h[2] == ref[2] && h[3] == ref[3])\n"
    "                    found = true;\n"
    "            } }\n"
    "        pos = (pos + 1) & params.compact_mask;\n"
    "    }\n"
    "    if (!found && params.overflow_count > 0) {\n"
    "        int lo = 0, hi2 = int(params.overflow_count) - 1;\n"
    "        while (lo <= hi2 && !found) {\n"
    "            int mid = (lo + hi2) / 2; ulong mkey = overflow_keys[mid];\n"
    "            if (key < mkey) hi2 = mid - 1;\n"
    "            else if (key > mkey) lo = mid + 1;\n"
    "            else {\n"
    "                for (int d = mid; d >= 0 && overflow_keys[d] == key && !found; d--) {\n"
    "                    device const uint *oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (h[0] == oref[0] && h[1] == oref[1] && h[2] == oref[2] && h[3] == oref[3])\n"
    "                        found = true; }\n"
    "                for (int d = mid+1; d < int(params.overflow_count) && overflow_keys[d] == key && !found; d++) {\n"
    "                    device const uint *oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (h[0] == oref[0] && h[1] == oref[1] && h[2] == oref[2] && h[3] == oref[3])\n"
    "                        found = true; }\n"
    "                break; } } }\n"
    "    if (found) {\n"
    "        uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * HIT_STRIDE;\n"
    "            hits[base] = word_idx; hits[base+1] = mask_idx;\n"
    "            hits[base+2] = 1;\n"
    "            for (int i = 0; i < 8; i++) hits[base+3+i] = h[i];\n"
    "            for (uint _z = 11; _z < HIT_STRIDE; _z++) hits[base+_z] = 0; } }\n"
    "}\n"
;
