/* Auto-generated from metal_md5_md5saltmd5pass.metal -- do not edit */
static const char metal_md5_md5saltmd5pass_str[] =
    "/* ---- MD5(MD5(salt).MD5(pass)) kernel (e367) ---- */\n"
    "/* Salt buffer has hex(MD5(salt)) [32 bytes], hexhash has hex(MD5(pass)) [32 bytes].\n"
    " * Always 64 bytes → deterministic 2-block MD5. */\n"
    "kernel void md5_md5saltmd5pass_batch(\n"
    "    device const uint8_t    *hexhashes   [[buffer(0)]],\n"
    "    device const ushort     *hex_lens    [[buffer(1)]],\n"
    "    device const ushort     *unused2     [[buffer(2)]],\n"
    "    device const uint8_t    *salts       [[buffer(3)]],\n"
    "    device const uint       *salt_offsets [[buffer(4)]],\n"
    "    device const ushort     *salt_lens   [[buffer(5)]],\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys   [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    uint M[16];\n"
    "    /* Load hex(MD5(salt)) [32 bytes] into M[0..7] */\n"
    "    device const uint *sw = (device const uint *)(salts + salt_offsets[salt_idx]);\n"
    "    for (int i = 0; i < 8; i++) M[i] = sw[i];\n"
    "    /* Load hex(MD5(pass)) [32 bytes] into M[8..15] */\n"
    "    device const uint *pw = (device const uint *)(hexhashes + word_idx * 256);\n"
    "    for (int i = 0; i < 8; i++) M[8+i] = pw[i];\n"
    "\n"
    "    uint4 h = uint4(0x67452301, 0xEFCDAB89, 0x98BADCFE, 0x10325476);\n"
    "    md5_block_full(h, M);\n"
    "\n"
    "    md5_block_pad64(h);\n"
    "\n"
    "    PROBE6(h, word_idx, salt_idx)\n"
    "}\n"
    "\n"
;
