/* Auto-generated from metal_sha256.metal -- do not edit */
static const char metal_sha256_str[] =
    "/* SHA256 K256[], sha256_block(), S_copy_bytes, S_set_byte, bswap32\n"
    " * all provided by metal_common.metal */\n"
    "\n"
    "/* ---- SHA256(password + salt) kernel (e413) ---- */\n"
    "kernel void sha256passsalt_batch(\n"
    "    device const uint8_t    *hexhashes   [[buffer(0)]],\n"
    "    device const ushort     *hex_lens    [[buffer(1)]],\n"
    "    device const ushort     *unused2     [[buffer(2)]],\n"
    "    device const uint8_t    *salts       [[buffer(3)]],\n"
    "    device const uint       *salt_offsets [[buffer(4)]],\n"
    "    device const ushort     *salt_lens   [[buffer(5)]],\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys   [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hex_lens[word_idx];\n"
    "    device const uint8_t *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = plen + slen;\n"
    "\n"
    "    uint state[8] = { 0x6a09e667u, 0xbb67ae85u, 0x3c6ef372u, 0xa54ff53au,\n"
    "                      0x510e527fu, 0x9b05688cu, 0x1f83d9abu, 0x5be0cd19u };\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "\n"
    "    if (total_len <= 55) {\n"
    "        S_copy_bytes(M, 0, pass, plen);\n"
    "        S_copy_bytes(M, plen, salts + soff, slen);\n"
    "        S_set_byte(M, total_len, 0x80);\n"
    "        M[15] = total_len * 8;\n"
    "        sha256_block(state, M);\n"
    "    } else {\n"
    "        int pass_b1 = (plen < 64) ? plen : 64;\n"
    "        S_copy_bytes(M, 0, pass, pass_b1);\n"
    "        int salt_b1 = 64 - pass_b1;\n"
    "        if (salt_b1 > slen) salt_b1 = slen;\n"
    "        if (salt_b1 > 0) S_copy_bytes(M, pass_b1, salts + soff, salt_b1);\n"
    "        if (total_len < 64) S_set_byte(M, total_len, 0x80);\n"
    "        sha256_block(state, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int pos2 = 0;\n"
    "        int pass_b2 = plen - pass_b1;\n"
    "        if (pass_b2 > 0) { S_copy_bytes(M, 0, pass + pass_b1, pass_b2); pos2 = pass_b2; }\n"
    "        int salt_b2 = slen - salt_b1;\n"
    "        if (salt_b2 > 0) { S_copy_bytes(M, pos2, salts + soff + salt_b1, salt_b2); pos2 += salt_b2; }\n"
    "        if (total_len >= 64) S_set_byte(M, pos2, 0x80);\n"
    "        M[15] = total_len * 8;\n"
    "        sha256_block(state, M);\n"
    "    }\n"
    "\n"
    "    /* SHA256: 8 hash words */\n"
    "    uint h[8];\n"
    "    for (int i = 0; i < 8; i++) h[i] = bswap32(state[i]);\n"
    "\n"
    "    /* Probe compact table with first 4 words */\n"
    "    ulong key = (ulong(h[1]) << 32) | h[0];\n"
    "    uint fp = uint(key >> 32); if (fp == 0) fp = 1;\n"
    "    ulong pos = (key ^ (key >> 32)) & params.compact_mask;\n"
    "    bool found = false;\n"
    "    for (uint p = 0; p < params.max_probe && !found; p++) {\n"
    "        uint cfp = compact_fp[pos]; if (cfp == 0) break;\n"
    "        if (cfp == fp) { uint idx = compact_idx[pos];\n"
    "            if (idx < params.hash_data_count) {\n"
    "                ulong off = hash_data_off[idx];\n"
    "                device const uint *ref = (device const uint *)(hash_data_buf + off);\n"
    "                if (h[0] == ref[0] && h[1] == ref[1] && h[2] == ref[2] && h[3] == ref[3])\n"
    "                    found = true;\n"
    "            } }\n"
    "        pos = (pos + 1) & params.compact_mask;\n"
    "    }\n"
    "    if (!found && params.overflow_count > 0) {\n"
    "        int lo = 0, hi2 = int(params.overflow_count) - 1;\n"
    "        while (lo <= hi2 && !found) {\n"
    "            int mid = (lo + hi2) / 2; ulong mkey = overflow_keys[mid];\n"
    "            if (key < mkey) hi2 = mid - 1;\n"
    "            else if (key > mkey) lo = mid + 1;\n"
    "            else {\n"
    "                for (int d = mid; d >= 0 && overflow_keys[d] == key && !found; d--) {\n"
    "                    device const uint *oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (h[0] == oref[0] && h[1] == oref[1] && h[2] == oref[2] && h[3] == oref[3])\n"
    "                        found = true; }\n"
    "                for (int d = mid+1; d < int(params.overflow_count) && overflow_keys[d] == key && !found; d++) {\n"
    "                    device const uint *oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (h[0] == oref[0] && h[1] == oref[1] && h[2] == oref[2] && h[3] == oref[3])\n"
    "                        found = true; }\n"
    "                break; } } }\n"
    "    if (found) {\n"
    "        uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 11;  /* 3 + 8 */\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx; hits[base+2] = 1;\n"
    "            for (int i = 0; i < 8; i++) hits[base+3+i] = h[i]; } }\n"
    "}\n"
    "\n"
    "/* ---- SHA256(salt + password) kernel (e412) ---- */\n"
    "kernel void sha256saltpass_batch(\n"
    "    device const uint8_t    *hexhashes   [[buffer(0)]],\n"
    "    device const ushort     *hex_lens    [[buffer(1)]],\n"
    "    device const ushort     *unused2     [[buffer(2)]],\n"
    "    device const uint8_t    *salts       [[buffer(3)]],\n"
    "    device const uint       *salt_offsets [[buffer(4)]],\n"
    "    device const ushort     *salt_lens   [[buffer(5)]],\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys   [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hex_lens[word_idx];\n"
    "    device const uint8_t *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = slen + plen;\n"
    "\n"
    "    uint state[8] = { 0x6a09e667u, 0xbb67ae85u, 0x3c6ef372u, 0xa54ff53au,\n"
    "                      0x510e527fu, 0x9b05688cu, 0x1f83d9abu, 0x5be0cd19u };\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "\n"
    "    if (total_len <= 55) {\n"
    "        S_copy_bytes(M, 0, salts + soff, slen);\n"
    "        S_copy_bytes(M, slen, pass, plen);\n"
    "        S_set_byte(M, total_len, 0x80);\n"
    "        M[15] = total_len * 8;\n"
    "        sha256_block(state, M);\n"
    "    } else {\n"
    "        int salt_b1 = (slen < 64) ? slen : 64;\n"
    "        S_copy_bytes(M, 0, salts + soff, salt_b1);\n"
    "        int pass_b1 = 64 - salt_b1;\n"
    "        if (pass_b1 > plen) pass_b1 = plen;\n"
    "        if (pass_b1 > 0) S_copy_bytes(M, salt_b1, pass, pass_b1);\n"
    "        if (total_len < 64) S_set_byte(M, total_len, 0x80);\n"
    "        sha256_block(state, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int pos2 = 0;\n"
    "        int salt_b2 = slen - salt_b1;\n"
    "        if (salt_b2 > 0) { S_copy_bytes(M, 0, salts + soff + salt_b1, salt_b2); pos2 = salt_b2; }\n"
    "        int pass_b2 = plen - pass_b1;\n"
    "        if (pass_b2 > 0) { S_copy_bytes(M, pos2, pass + pass_b1, pass_b2); pos2 += pass_b2; }\n"
    "        if (total_len >= 64) S_set_byte(M, pos2, 0x80);\n"
    "        M[15] = total_len * 8;\n"
    "        sha256_block(state, M);\n"
    "    }\n"
    "\n"
    "    /* SHA256: 8 hash words */\n"
    "    uint h[8];\n"
    "    for (int i = 0; i < 8; i++) h[i] = bswap32(state[i]);\n"
    "\n"
    "    ulong key = (ulong(h[1]) << 32) | h[0];\n"
    "    uint fp = uint(key >> 32); if (fp == 0) fp = 1;\n"
    "    ulong pos = (key ^ (key >> 32)) & params.compact_mask;\n"
    "    bool found = false;\n"
    "    for (uint p = 0; p < params.max_probe && !found; p++) {\n"
    "        uint cfp = compact_fp[pos]; if (cfp == 0) break;\n"
    "        if (cfp == fp) { uint idx = compact_idx[pos];\n"
    "            if (idx < params.hash_data_count) {\n"
    "                ulong off = hash_data_off[idx];\n"
    "                device const uint *ref = (device const uint *)(hash_data_buf + off);\n"
    "                if (h[0] == ref[0] && h[1] == ref[1] && h[2] == ref[2] && h[3] == ref[3])\n"
    "                    found = true;\n"
    "            } }\n"
    "        pos = (pos + 1) & params.compact_mask;\n"
    "    }\n"
    "    if (!found && params.overflow_count > 0) {\n"
    "        int lo = 0, hi2 = int(params.overflow_count) - 1;\n"
    "        while (lo <= hi2 && !found) {\n"
    "            int mid = (lo + hi2) / 2; ulong mkey = overflow_keys[mid];\n"
    "            if (key < mkey) hi2 = mid - 1;\n"
    "            else if (key > mkey) lo = mid + 1;\n"
    "            else {\n"
    "                for (int d = mid; d >= 0 && overflow_keys[d] == key && !found; d--) {\n"
    "                    device const uint *oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (h[0] == oref[0] && h[1] == oref[1] && h[2] == oref[2] && h[3] == oref[3])\n"
    "                        found = true; }\n"
    "                for (int d = mid+1; d < int(params.overflow_count) && overflow_keys[d] == key && !found; d++) {\n"
    "                    device const uint *oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (h[0] == oref[0] && h[1] == oref[1] && h[2] == oref[2] && h[3] == oref[3])\n"
    "                        found = true; }\n"
    "                break; } } }\n"
    "    if (found) {\n"
    "        uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 11;  /* 3 + 8 */\n"
    "            hits[base] = word_idx; hits[base+1] = salt_idx; hits[base+2] = 1;\n"
    "            for (int i = 0; i < 8; i++) hits[base+3+i] = h[i]; } }\n"
    "}\n"
    "\n"
;
