/* Auto-generated from metal_blake2s256unsalted.metal -- do not edit */
static const char metal_blake2s256unsalted_str[] =
    "/* metal_blake2s256unsalted.metal — Pre-padded unsalted BLAKE2S-256 with mask expansion\n"
    " *\n"
    " * Input: 4096 pre-padded 64-byte blocks in passbuf (word_stride=64).\n"
    " *   Packed by gpu_try_pack_unsalted(): password bytes at offset n_prepend,\n"
    " *   total_len stored as bitlen at M[14] (extract byte len = M[14]>>3).\n"
    " *   BLAKE2S uses its own padding (no 0x80/bitlen), so the packer just stores\n"
    " *   the password and length — the kernel handles BLAKE2S-specific finalization.\n"
    " *\n"
    " * Dispatch: num_words x num_masks threads.\n"
    " * Hit stride: 6 (word_idx, mask_idx, h0, h1, h2, h3)\n"
    " */\n"
    "\n"
    "/* B2S_IV, B2S_SIGMA, b2s_compress all provided by metal_common.metal */\n"
    "\n"
    "kernel void blake2s256_unsalted_batch(\n"
    "    device const uint       *words       [[buffer(0)]],\n"
    "    device const ushort     *unused_lens [[buffer(1)]],\n"
    "    device const ushort     *unused2     [[buffer(2)]],\n"
    "    device const uint8_t    *mask_desc   [[buffer(3)]],\n"
    "    device const uint       *unused3     [[buffer(4)]],\n"
    "    device const ushort     *unused4     [[buffer(5)]],\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys   [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    ulong mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    /* Load pre-packed block (16 uint32 = 64 bytes).\n"
    "     * Password bytes start at n_prepend. Total length at M[14] bits [7:0] and [15:8]. */\n"
    "    device const uint *src = words + word_idx * 16;\n"
    "    uchar buf[64];\n"
    "    for (int i = 0; i < 64; i++)\n"
    "        buf[i] = ((device const uchar *)src)[i];\n"
    "\n"
    "    /* Fill mask positions */\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "\n"
    "    /* Read total_len from packed M[14] (stored as bitlen by packer, extract byte len) */\n"
    "    uint M14 = src[14];\n"
    "    int total_len = M14 >> 3;\n"
    "\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint n_total_m = n_pre + n_app;\n"
    "\n"
    "        if (n_pre > 0) {\n"
    "            uint append_combos = 1;\n"
    "            for (uint i = 0; i < n_app; i++)\n"
    "                append_combos *= mask_desc[n_pre + i];\n"
    "            uint prepend_idx = (uint)(mask_idx / append_combos);\n"
    "            uint append_idx = (uint)(mask_idx % append_combos);\n"
    "\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                buf[i] = ch;\n"
    "            }\n"
    "\n"
    "            if (n_app > 0) {\n"
    "                int app_start = total_len - (int)n_app;\n"
    "                uint aidx = append_idx;\n"
    "                for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                    int pos_idx = n_pre + i;\n"
    "                    uint sz = mask_desc[pos_idx];\n"
    "                    uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                    aidx /= sz;\n"
    "                    buf[app_start + i] = ch;\n"
    "                }\n"
    "            }\n"
    "        } else {\n"
    "            /* Append-only (brute-force): host pre-decomposes mask_start into\n"
    "             * per-position base offsets in mask_base0/mask_base1. Kernel does\n"
    "             * fast uint32 local decomposition and adds to base with carry. */\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint local_idx = tid % params.num_masks;\n"
    "            uint aidx = local_idx;\n"
    "            uint carry = 0;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uint local_digit = aidx % sz;\n"
    "                aidx /= sz;\n"
    "                uint base_digit = (i < 8)\n"
    "                    ? (uint)((params.mask_base0 >> (i * 8)) & 0xFF)\n"
    "                    : (uint)((params.mask_base1 >> ((i - 8) * 8)) & 0xFF);\n"
    "                uint sum = base_digit + local_digit + carry;\n"
    "                carry = sum / sz;\n"
    "                uint final_digit = sum % sz;\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + final_digit];\n"
    "                buf[app_start + i] = ch;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* BLAKE2S-256: single-block hash (password <= 55 bytes fits in one 64-byte block).\n"
    "     * Init: IV ^ parameter block (outlen=32, keylen=0, fanout=1, depth=1). */\n"
    "    uint h[8];\n"
    "    for (int i = 0; i < 8; i++) h[i] = B2S_IV[i];\n"
    "    h[0] ^= 0x01010020u;\n"
    "\n"
    "    /* Zero bytes after password */\n"
    "    for (int i = total_len; i < 64; i++) buf[i] = 0;\n"
    "\n"
    "    /* Single compress with last=1, counter=total_len */\n"
    "    b2s_compress(h, buf, (ulong)total_len, 1);\n"
    "\n"
    "    /* BLAKE2S-256: 8 hash words, output is LE — no bswap.\n"
    "     * h[0..7] already contains the full hash. */\n"
    "    ulong key = (ulong(h[1]) << 32) | h[0];\n"
    "    uint fp = uint(key >> 32); if (fp == 0) fp = 1;\n"
    "    ulong pos = (key ^ (key >> 32)) & params.compact_mask;\n"
    "    bool found = false;\n"
    "    for (uint p = 0; p < params.max_probe && !found; p++) {\n"
    "        uint cfp = compact_fp[pos]; if (cfp == 0) break;\n"
    "        if (cfp == fp) { uint idx = compact_idx[pos];\n"
    "            if (idx < params.hash_data_count) {\n"
    "                ulong off = hash_data_off[idx];\n"
    "                device const uint *ref = (device const uint *)(hash_data_buf + off);\n"
    "                if (h[0] == ref[0] && h[1] == ref[1] && h[2] == ref[2] && h[3] == ref[3])\n"
    "                    found = true;\n"
    "            } }\n"
    "        pos = (pos + 1) & params.compact_mask;\n"
    "    }\n"
    "    if (!found && params.overflow_count > 0) {\n"
    "        int lo = 0, hi2 = int(params.overflow_count) - 1;\n"
    "        while (lo <= hi2 && !found) {\n"
    "            int mid = (lo + hi2) / 2; ulong mkey = overflow_keys[mid];\n"
    "            if (key < mkey) hi2 = mid - 1;\n"
    "            else if (key > mkey) lo = mid + 1;\n"
    "            else {\n"
    "                for (int d = mid; d >= 0 && overflow_keys[d] == key && !found; d--) {\n"
    "                    device const uint *oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (h[0] == oref[0] && h[1] == oref[1] && h[2] == oref[2] && h[3] == oref[3])\n"
    "                        found = true; }\n"
    "                for (int d = mid+1; d < int(params.overflow_count) && overflow_keys[d] == key && !found; d++) {\n"
    "                    device const uint *oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (h[0] == oref[0] && h[1] == oref[1] && h[2] == oref[2] && h[3] == oref[3])\n"
    "                        found = true; }\n"
    "                break; } } }\n"
    "    if (found) {\n"
    "        uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "        if (slot < params.max_hits) {\n"
    "            uint base = slot * 10;  /* 2 + 8 */\n"
    "            hits[base] = word_idx; hits[base+1] = mask_idx;\n"
    "            for (int i = 0; i < 8; i++) hits[base+2+i] = h[i]; } }\n"
    "}\n"
;
