/* Auto-generated from metal_sha1.metal -- do not edit */
static const char metal_sha1_str[] =
    "/* metal_sha1.metal — SHA1 salted GPU kernels for Apple Metal\n"
    " *\n"
    " * Kernels:\n"
    " *   sha1passsalt_batch  — sha1($pass.$salt)         (e405)\n"
    " *   sha1saltpass_batch  — sha1($salt.$pass)         (e385)\n"
    " *   sha1dru_batch       — SHA1DRU (1M iterations)   (e404)\n"
    " *   hmac_sha1_ksalt_batch — HMAC-SHA1 key=$salt     (e215)\n"
    " *   hmac_sha1_kpass_batch — HMAC-SHA1 key=$pass     (e793)\n"
    " *\n"
    " * Hit stride: 8 (word_idx, salt_idx, iter_num, h0, h1, h2, h3, h4)\n"
    " */\n"
    "\n"
    "/* bswap32, sha1_compress, S_copy_bytes, S_set_byte, S_copy_bytes_priv,\n"
    " * S_set_byte_priv, SALTED_PARAMS, PROBE8 all provided by metal_common.metal */\n"
    "\n"
    "/* ---- SHA1(password + salt) kernel (e405) ---- */\n"
    "kernel void sha1passsalt_batch(SALTED_PARAMS) {\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    device const uint8_t *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = plen + slen;\n"
    "\n"
    "    uint state[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "\n"
    "    if (total_len <= 55) {\n"
    "        S_copy_bytes(M, 0, pass, plen);\n"
    "        S_copy_bytes(M, plen, salts + soff, slen);\n"
    "        S_set_byte(M, total_len, 0x80);\n"
    "        M[15] = total_len * 8;\n"
    "        sha1_compress(state, M);\n"
    "    } else {\n"
    "        int pass_b1 = (plen < 64) ? plen : 64;\n"
    "        S_copy_bytes(M, 0, pass, pass_b1);\n"
    "        int salt_b1 = 64 - pass_b1;\n"
    "        if (salt_b1 > slen) salt_b1 = slen;\n"
    "        if (salt_b1 > 0) S_copy_bytes(M, pass_b1, salts + soff, salt_b1);\n"
    "        if (total_len < 64) S_set_byte(M, total_len, 0x80);\n"
    "        sha1_compress(state, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int pos2 = 0;\n"
    "        int pass_b2 = plen - pass_b1;\n"
    "        if (pass_b2 > 0) { S_copy_bytes(M, 0, pass + pass_b1, pass_b2); pos2 = pass_b2; }\n"
    "        int salt_b2 = slen - salt_b1;\n"
    "        if (salt_b2 > 0) { S_copy_bytes(M, pos2, salts + soff + salt_b1, salt_b2); pos2 += salt_b2; }\n"
    "        if (total_len >= 64) S_set_byte(M, pos2, 0x80);\n"
    "        M[15] = total_len * 8;\n"
    "        sha1_compress(state, M);\n"
    "    }\n"
    "\n"
    "    uint h[5];\n"
    "    for (int i = 0; i < 5; i++) h[i] = bswap32(state[i]);\n"
    "\n"
    "    PROBE8(h, word_idx, salt_idx)\n"
    "}\n"
    "\n"
    "/* ---- SHA1(salt + password) kernel (e385) ---- */\n"
    "kernel void sha1saltpass_batch(SALTED_PARAMS) {\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    device const uint8_t *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen = salt_lens[salt_idx];\n"
    "    int total_len = slen + plen;\n"
    "\n"
    "    uint state[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "\n"
    "    if (total_len <= 55) {\n"
    "        S_copy_bytes(M, 0, salts + soff, slen);\n"
    "        S_copy_bytes(M, slen, pass, plen);\n"
    "        S_set_byte(M, total_len, 0x80);\n"
    "        M[15] = total_len * 8;\n"
    "        sha1_compress(state, M);\n"
    "    } else {\n"
    "        int salt_b1 = (slen < 64) ? slen : 64;\n"
    "        S_copy_bytes(M, 0, salts + soff, salt_b1);\n"
    "        int pass_b1 = 64 - salt_b1;\n"
    "        if (pass_b1 > plen) pass_b1 = plen;\n"
    "        if (pass_b1 > 0) S_copy_bytes(M, salt_b1, pass, pass_b1);\n"
    "        if (total_len < 64) S_set_byte(M, total_len, 0x80);\n"
    "        sha1_compress(state, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int pos2 = 0;\n"
    "        int salt_b2 = slen - salt_b1;\n"
    "        if (salt_b2 > 0) { S_copy_bytes(M, 0, salts + soff + salt_b1, salt_b2); pos2 = salt_b2; }\n"
    "        int pass_b2 = plen - pass_b1;\n"
    "        if (pass_b2 > 0) { S_copy_bytes(M, pos2, pass + pass_b1, pass_b2); pos2 += pass_b2; }\n"
    "        if (total_len >= 64) S_set_byte(M, pos2, 0x80);\n"
    "        M[15] = total_len * 8;\n"
    "        sha1_compress(state, M);\n"
    "    }\n"
    "\n"
    "    uint h[5];\n"
    "    for (int i = 0; i < 5; i++) h[i] = bswap32(state[i]);\n"
    "\n"
    "    PROBE8(h, word_idx, salt_idx)\n"
    "}\n"
    "\n"
    "/* ---- SHA1DRU kernel (e404): SHA1 iterated 1,000,001 times ---- */\n"
    "/* SHA1(pass) already done on CPU. hexhashes[tid*256..+39] = hex(SHA1(pass)),\n"
    " * password at offset 40. hexlens[tid] = 40 + plen.\n"
    " * GPU_CAT_ITER: dispatched as num_words work items (no salts). */\n"
    "kernel void sha1dru_batch(SALTED_PARAMS) {\n"
    "    if (tid >= params.num_words) return;\n"
    "\n"
    "    device const uint8_t *wordbuf = hexhashes + tid * 256;\n"
    "    int total_packed = hexlens[tid];\n"
    "    int plen = total_packed - 40;\n"
    "    device const uint8_t *pass = wordbuf + 40;\n"
    "\n"
    "    /* Decode hex ASCII at wordbuf[0..39] back to 5 big-endian state words */\n"
    "    uint state[5];\n"
    "    for (int w = 0; w < 5; w++) {\n"
    "        uint val = 0;\n"
    "        for (int j = 0; j < 8; j++) {\n"
    "            uint8_t c = wordbuf[w * 8 + j];\n"
    "            uint nibble = (c >= 'a') ? (c - 'a' + 10) : (c - '0');\n"
    "            val = (val << 4) | nibble;\n"
    "        }\n"
    "        state[w] = val;\n"
    "    }\n"
    "\n"
    "    uint8_t hexlut[16] = {'0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f'};\n"
    "\n"
    "    /* 1,000,000 iterations of SHA1(hex(hash) + pass) */\n"
    "    for (int iter = 0; iter < 1000000; iter++) {\n"
    "        uint8_t hexbuf[96];\n"
    "        for (int w = 0; w < 5; w++) {\n"
    "            uint sv = state[w];\n"
    "            hexbuf[w*8+0] = hexlut[(sv >> 28) & 0xf];\n"
    "            hexbuf[w*8+1] = hexlut[(sv >> 24) & 0xf];\n"
    "            hexbuf[w*8+2] = hexlut[(sv >> 20) & 0xf];\n"
    "            hexbuf[w*8+3] = hexlut[(sv >> 16) & 0xf];\n"
    "            hexbuf[w*8+4] = hexlut[(sv >> 12) & 0xf];\n"
    "            hexbuf[w*8+5] = hexlut[(sv >> 8) & 0xf];\n"
    "            hexbuf[w*8+6] = hexlut[(sv >> 4) & 0xf];\n"
    "            hexbuf[w*8+7] = hexlut[sv & 0xf];\n"
    "        }\n"
    "        for (int i = 0; i < plen; i++) hexbuf[40 + i] = pass[i];\n"
    "        int total = 40 + plen;\n"
    "\n"
    "        state[0] = 0x67452301u; state[1] = 0xEFCDAB89u;\n"
    "        state[2] = 0x98BADCFEu; state[3] = 0x10325476u; state[4] = 0xC3D2E1F0u;\n"
    "        uint M[16];\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        if (total <= 55) {\n"
    "            S_copy_bytes_priv(M, 0, hexbuf, total);\n"
    "            S_set_byte_priv(M, total, 0x80);\n"
    "            M[15] = total * 8;\n"
    "            sha1_compress(state, M);\n"
    "        } else {\n"
    "            S_copy_bytes_priv(M, 0, hexbuf, 64);\n"
    "            sha1_compress(state, M);\n"
    "            for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "            int rem = total - 64;\n"
    "            if (rem > 0) S_copy_bytes_priv(M, 0, hexbuf + 64, rem);\n"
    "            S_set_byte_priv(M, rem, 0x80);\n"
    "            M[15] = total * 8;\n"
    "            sha1_compress(state, M);\n"
    "        }\n"
    "    }\n"
    "\n"
    "    uint h[5];\n"
    "    for (int i = 0; i < 5; i++) h[i] = bswap32(state[i]);\n"
    "\n"
    "    PROBE8(h, tid, 0)\n"
    "}\n"
    "\n"
    "/* ---- HMAC-SHA1 key=$salt (e215, hashcat 160) ---- */\n"
    "/* Key = salt, Message = password */\n"
    "kernel void hmac_sha1_ksalt_batch(SALTED_PARAMS) {\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hexlens[word_idx];\n"
    "    device const uint8_t *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int klen = salt_lens[salt_idx];\n"
    "    device const uint8_t *key = salts + soff;\n"
    "\n"
    "    /* Prepare key block (LE byte order). If key > 64 bytes, hash it first. */\n"
    "    uint key_block[16];\n"
    "    for (int i = 0; i < 16; i++) key_block[i] = 0;\n"
    "\n"
    "    if (klen > 64) {\n"
    "        uint kstate[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "        uint KM[16];\n"
    "        for (int i = 0; i < 16; i++) KM[i] = 0;\n"
    "        S_copy_bytes(KM, 0, key, 64);\n"
    "        sha1_compress(kstate, KM);\n"
    "        for (int i = 0; i < 16; i++) KM[i] = 0;\n"
    "        int rem = klen - 64;\n"
    "        if (rem > 0) S_copy_bytes(KM, 0, key + 64, rem);\n"
    "        S_set_byte(KM, rem, 0x80);\n"
    "        KM[15] = klen * 8;\n"
    "        sha1_compress(kstate, KM);\n"
    "        for (int i = 0; i < 5; i++) key_block[i] = bswap32(kstate[i]);\n"
    "        klen = 20;\n"
    "    } else {\n"
    "        for (int i = 0; i < klen; i++) {\n"
    "            int wi = i >> 2;\n"
    "            int bi = (i & 3) << 3;\n"
    "            key_block[wi] |= ((uint)key[i]) << bi;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Inner hash = SHA1((key ^ ipad) || message) */\n"
    "    uint ipad_blk[16], M[16];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        ipad_blk[i] = key_block[i] ^ 0x36363636u;\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap32(ipad_blk[i]);\n"
    "\n"
    "    uint istate[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "    sha1_compress(istate, M);\n"
    "\n"
    "    /* Message = password */\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    int mlen = plen;\n"
    "    if (mlen <= 55) {\n"
    "        S_copy_bytes(M, 0, pass, mlen);\n"
    "        S_set_byte(M, mlen, 0x80);\n"
    "        M[15] = (64 + mlen) * 8;\n"
    "        sha1_compress(istate, M);\n"
    "    } else {\n"
    "        S_copy_bytes(M, 0, pass, (mlen < 64) ? mlen : 64);\n"
    "        if (mlen < 64) S_set_byte(M, mlen, 0x80);\n"
    "        sha1_compress(istate, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int rem = mlen - 64;\n"
    "        if (rem > 0) S_copy_bytes(M, 0, pass + 64, rem);\n"
    "        if (mlen >= 64) S_set_byte(M, (rem > 0) ? rem : 0, 0x80);\n"
    "        M[15] = (64 + mlen) * 8;\n"
    "        sha1_compress(istate, M);\n"
    "    }\n"
    "\n"
    "    /* Outer hash = SHA1((key ^ opad) || inner_hash) */\n"
    "    uint opad_blk[16];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        opad_blk[i] = key_block[i] ^ 0x5c5c5c5cu;\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap32(opad_blk[i]);\n"
    "\n"
    "    uint ostate[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "    sha1_compress(ostate, M);\n"
    "\n"
    "    /* Inner hash result (20 bytes BE in istate) + padding */\n"
    "    for (int i = 0; i < 5; i++) M[i] = istate[i];\n"
    "    M[5] = 0x80000000u;\n"
    "    for (int i = 6; i < 15; i++) M[i] = 0;\n"
    "    M[15] = (64 + 20) * 8;\n"
    "    sha1_compress(ostate, M);\n"
    "\n"
    "    uint h[5];\n"
    "    for (int i = 0; i < 5; i++) h[i] = bswap32(ostate[i]);\n"
    "\n"
    "    PROBE8(h, word_idx, salt_idx)\n"
    "}\n"
    "\n"
    "/* ---- HMAC-SHA1 key=$pass (e793, hashcat 150) ---- */\n"
    "/* Key = password, Message = salt */\n"
    "kernel void hmac_sha1_kpass_batch(SALTED_PARAMS) {\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int klen = hexlens[word_idx];\n"
    "    device const uint8_t *key = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int mlen = salt_lens[salt_idx];\n"
    "    device const uint8_t *msg = salts + soff;\n"
    "\n"
    "    /* Prepare key block from password */\n"
    "    uint key_block[16];\n"
    "    for (int i = 0; i < 16; i++) key_block[i] = 0;\n"
    "\n"
    "    if (klen > 64) {\n"
    "        uint kstate[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "        uint KM[16];\n"
    "        for (int i = 0; i < 16; i++) KM[i] = 0;\n"
    "        S_copy_bytes(KM, 0, key, 64);\n"
    "        sha1_compress(kstate, KM);\n"
    "        for (int i = 0; i < 16; i++) KM[i] = 0;\n"
    "        int rem = klen - 64;\n"
    "        if (rem > 0) S_copy_bytes(KM, 0, key + 64, rem);\n"
    "        S_set_byte(KM, rem, 0x80);\n"
    "        KM[15] = klen * 8;\n"
    "        sha1_compress(kstate, KM);\n"
    "        for (int i = 0; i < 5; i++) key_block[i] = bswap32(kstate[i]);\n"
    "        klen = 20;\n"
    "    } else {\n"
    "        for (int i = 0; i < klen; i++) {\n"
    "            int wi = i >> 2;\n"
    "            int bi = (i & 3) << 3;\n"
    "            key_block[wi] |= ((uint)key[i]) << bi;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Inner hash = SHA1((key ^ ipad) || salt) */\n"
    "    uint ipad_blk[16], M[16];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        ipad_blk[i] = key_block[i] ^ 0x36363636u;\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap32(ipad_blk[i]);\n"
    "\n"
    "    uint istate[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "    sha1_compress(istate, M);\n"
    "\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    if (mlen <= 55) {\n"
    "        S_copy_bytes(M, 0, msg, mlen);\n"
    "        S_set_byte(M, mlen, 0x80);\n"
    "        M[15] = (64 + mlen) * 8;\n"
    "        sha1_compress(istate, M);\n"
    "    } else {\n"
    "        S_copy_bytes(M, 0, msg, (mlen < 64) ? mlen : 64);\n"
    "        if (mlen < 64) S_set_byte(M, mlen, 0x80);\n"
    "        sha1_compress(istate, M);\n"
    "        for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "        int rem = mlen - 64;\n"
    "        if (rem > 0) S_copy_bytes(M, 0, msg + 64, rem);\n"
    "        if (mlen >= 64) S_set_byte(M, (rem > 0) ? rem : 0, 0x80);\n"
    "        M[15] = (64 + mlen) * 8;\n"
    "        sha1_compress(istate, M);\n"
    "    }\n"
    "\n"
    "    /* Outer hash */\n"
    "    uint opad_blk[16];\n"
    "    for (int i = 0; i < 16; i++)\n"
    "        opad_blk[i] = key_block[i] ^ 0x5c5c5c5cu;\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap32(opad_blk[i]);\n"
    "\n"
    "    uint ostate[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "    sha1_compress(ostate, M);\n"
    "\n"
    "    for (int i = 0; i < 5; i++) M[i] = istate[i];\n"
    "    M[5] = 0x80000000u;\n"
    "    for (int i = 6; i < 15; i++) M[i] = 0;\n"
    "    M[15] = (64 + 20) * 8;\n"
    "    sha1_compress(ostate, M);\n"
    "\n"
    "    uint h[5];\n"
    "    for (int i = 0; i < 5; i++) h[i] = bswap32(ostate[i]);\n"
    "\n"
    "    PROBE8(h, word_idx, salt_idx)\n"
    "}\n"
;
