/* Auto-generated from metal_md5crypt.metal -- do not edit */
static const char metal_md5crypt_str[] =
    "/* metal_md5crypt.metal — MD5CRYPT ($1$) kernel for Metal\n"
    " *\n"
    " * Algorithm: $1$salt$hash — 1000 rounds of MD5 with alternating password/salt mixing.\n"
    " * Hit stride: 6 (word_idx, salt_idx, hx, hy, hz, hw).\n"
    " * Uses md5_block_full from metal_common.metal (included via common_str concatenation).\n"
    " */\n"
    "\n"
    "/* md5_oneshot: compute MD5 of up to 128 bytes (1 or 2 blocks).\n"
    " * data[] is a thread-local byte buffer, len is the message length. */\n"
    "static void md5_oneshot(thread const uint8_t *data, int len, thread uint4 &hash) {\n"
    "    uint M[16];\n"
    "    hash = uint4(0x67452301, 0xEFCDAB89, 0x98BADCFE, 0x10325476);\n"
    "\n"
    "    int pos = 0;\n"
    "    /* Process full 64-byte blocks */\n"
    "    while (pos + 64 <= len) {\n"
    "        for (int i = 0; i < 16; i++)\n"
    "            M[i] = (uint)data[pos+i*4] | ((uint)data[pos+i*4+1]<<8) |\n"
    "                   ((uint)data[pos+i*4+2]<<16) | ((uint)data[pos+i*4+3]<<24);\n"
    "        md5_block_full(hash, M);\n"
    "        pos += 64;\n"
    "    }\n"
    "    /* Final block(s) with padding */\n"
    "    int rem = len - pos;\n"
    "    uint8_t pad[128];\n"
    "    for (int i = 0; i < 128; i++) pad[i] = 0;\n"
    "    for (int i = 0; i < rem; i++) pad[i] = data[pos + i];\n"
    "    pad[rem] = 0x80;\n"
    "    int blocks = (rem < 56) ? 1 : 2;\n"
    "    int lenoff = (blocks == 1) ? 56 : 120;\n"
    "    pad[lenoff]   = (uint8_t)((len * 8) & 0xff);\n"
    "    pad[lenoff+1] = (uint8_t)(((len * 8) >> 8) & 0xff);\n"
    "    pad[lenoff+2] = (uint8_t)(((len * 8) >> 16) & 0xff);\n"
    "    pad[lenoff+3] = (uint8_t)(((len * 8) >> 24) & 0xff);\n"
    "    for (int b = 0; b < blocks; b++) {\n"
    "        for (int i = 0; i < 16; i++)\n"
    "            M[i] = (uint)pad[b*64+i*4] | ((uint)pad[b*64+i*4+1]<<8) |\n"
    "                   ((uint)pad[b*64+i*4+2]<<16) | ((uint)pad[b*64+i*4+3]<<24);\n"
    "        md5_block_full(hash, M);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- MD5CRYPT kernel (e511): $1$salt$hash, 1000 MD5 iterations ---- */\n"
    "kernel void md5crypt_batch(\n"
    "    device const uint8_t    *hexhashes   [[buffer(0)]],\n"
    "    device const ushort     *hex_lens    [[buffer(1)]],\n"
    "    device const ushort     *unused2     [[buffer(2)]],\n"
    "    device const uint8_t    *salts       [[buffer(3)]],\n"
    "    device const uint       *salt_offsets [[buffer(4)]],\n"
    "    device const ushort     *salt_lens   [[buffer(5)]],\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys   [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_idx = tid / params.num_salts;\n"
    "    uint salt_idx = params.salt_start + (tid % params.num_salts);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    int plen = hex_lens[word_idx];\n"
    "    device const uint8_t *pass = hexhashes + word_idx * 256;\n"
    "    uint soff = salt_offsets[salt_idx];\n"
    "    int slen_full = salt_lens[salt_idx];\n"
    "\n"
    "    /* Salt buffer has \"$1$salt$\" -- extract raw salt (skip \"$1$\", stop before trailing \"$\") */\n"
    "    device const uint8_t *salt_raw = salts + soff + 3; /* skip \"$1$\" */\n"
    "    int saltlen = slen_full - 4; /* remove \"$1$\" prefix and trailing \"$\" */\n"
    "    if (saltlen < 0) saltlen = 0;\n"
    "    if (saltlen > 8) saltlen = 8;\n"
    "\n"
    "    /* Local buffers */\n"
    "    uint8_t buf[256];\n"
    "    uint4 digest;\n"
    "\n"
    "    /* Step 1: digest_b = MD5(password + salt + password) */\n"
    "    int blen = 0;\n"
    "    for (int i = 0; i < plen; i++) buf[blen++] = pass[i];\n"
    "    for (int i = 0; i < saltlen; i++) buf[blen++] = salt_raw[i];\n"
    "    for (int i = 0; i < plen; i++) buf[blen++] = pass[i];\n"
    "    md5_oneshot(buf, blen, digest);\n"
    "    uint8_t digest_b[16];\n"
    "    for (int i = 0; i < 4; i++) {\n"
    "        uint w = ((thread uint *)&digest)[i];\n"
    "        digest_b[i*4]   = w & 0xff;\n"
    "        digest_b[i*4+1] = (w >> 8) & 0xff;\n"
    "        digest_b[i*4+2] = (w >> 16) & 0xff;\n"
    "        digest_b[i*4+3] = (w >> 24) & 0xff;\n"
    "    }\n"
    "\n"
    "    /* Step 2: digest_a = MD5(password + \"$1$\" + salt + digest_b_chunks + bit_bytes) */\n"
    "    blen = 0;\n"
    "    for (int i = 0; i < plen; i++) buf[blen++] = pass[i];\n"
    "    buf[blen++] = '$'; buf[blen++] = '1'; buf[blen++] = '$';\n"
    "    for (int i = 0; i < saltlen; i++) buf[blen++] = salt_raw[i];\n"
    "    /* Append digest_b for password length bytes */\n"
    "    for (int x = plen; x > 0; x -= 16) {\n"
    "        int n = (x > 16) ? 16 : x;\n"
    "        for (int i = 0; i < n; i++) buf[blen++] = digest_b[i];\n"
    "    }\n"
    "    /* Bit-dependent bytes */\n"
    "    for (int x = plen; x != 0; x >>= 1)\n"
    "        buf[blen++] = (x & 1) ? 0 : pass[0];\n"
    "    md5_oneshot(buf, blen, digest);\n"
    "\n"
    "    /* Step 3: 1000 iterations */\n"
    "    uint8_t dig[16];\n"
    "    for (int i = 0; i < 4; i++) {\n"
    "        uint w = ((thread uint *)&digest)[i];\n"
    "        dig[i*4]   = w & 0xff;\n"
    "        dig[i*4+1] = (w >> 8) & 0xff;\n"
    "        dig[i*4+2] = (w >> 16) & 0xff;\n"
    "        dig[i*4+3] = (w >> 24) & 0xff;\n"
    "    }\n"
    "    for (int x = 0; x < 1000; x++) {\n"
    "        blen = 0;\n"
    "        if (x & 1) { for (int i = 0; i < plen; i++) buf[blen++] = pass[i]; }\n"
    "        else       { for (int i = 0; i < 16; i++) buf[blen++] = dig[i]; }\n"
    "        if (x % 3) { for (int i = 0; i < saltlen; i++) buf[blen++] = salt_raw[i]; }\n"
    "        if (x % 7) { for (int i = 0; i < plen; i++) buf[blen++] = pass[i]; }\n"
    "        if (x & 1) { for (int i = 0; i < 16; i++) buf[blen++] = dig[i]; }\n"
    "        else       { for (int i = 0; i < plen; i++) buf[blen++] = pass[i]; }\n"
    "        md5_oneshot(buf, blen, digest);\n"
    "        for (int i = 0; i < 4; i++) {\n"
    "            uint w = ((thread uint *)&digest)[i];\n"
    "            dig[i*4]   = w & 0xff;\n"
    "            dig[i*4+1] = (w >> 8) & 0xff;\n"
    "            dig[i*4+2] = (w >> 16) & 0xff;\n"
    "            dig[i*4+3] = (w >> 24) & 0xff;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    PROBE6(digest, word_idx, salt_idx)\n"
    "}\n"
;
