/* Auto-generated from metal_mysql3unsalted.metal -- do not edit */
static const char metal_mysql3unsalted_str[] =
    "/* metal_mysql3unsalted.metal — MySQL OLD_PASSWORD() hash (e456, hashcat 200)\n"
    " *\n"
    " * Simple arithmetic hash: nr/nr2 accumulator loop over password bytes.\n"
    " * Skips spaces and tabs. Output: 8 bytes BE = nr(4) || nr2(4).\n"
    " * Hit stride: 6 (word_idx, mask_idx, hx, hy, hz, hw)\n"
    " */\n"
    "\n"
    "kernel void mysql3_unsalted_batch(\n"
    "    device const uint       *words       [[buffer(0)]],\n"
    "    device const ushort     *unused_lens [[buffer(1)]],\n"
    "    device const ushort     *unused2     [[buffer(2)]],\n"
    "    device const uint8_t    *mask_desc   [[buffer(3)]],\n"
    "    device const uint       *unused3     [[buffer(4)]],\n"
    "    device const ushort     *unused4     [[buffer(5)]],\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys   [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    uint mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    device const uint *src = words + word_idx * 16;\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint n_total_m = n_pre + n_app;\n"
    "        uint append_combos = 1;\n"
    "        for (uint i = 0; i < n_app; i++)\n"
    "            append_combos *= mask_desc[n_pre + i];\n"
    "        uint prepend_idx = mask_idx / append_combos;\n"
    "        uint append_idx = mask_idx % append_combos;\n"
    "        if (n_pre > 0) {\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                M[i >> 2] = (M[i >> 2] & ~(0xFFu << ((i & 3) << 3)))\n"
    "                           | ((uint)ch << ((i & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "        if (n_app > 0) {\n"
    "            int total_len = M[14] >> 3;\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint aidx = append_idx;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                int pos_idx = n_pre + i;\n"
    "                uint sz = mask_desc[pos_idx];\n"
    "                uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                aidx /= sz;\n"
    "                int pos = app_start + i;\n"
    "                M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                             | ((uint)ch << ((pos & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* MySQL3 hash: arithmetic loop over password bytes */\n"
    "    int passlen = M[14] >> 3;\n"
    "    uint nr = 1345345333u, add = 7u, nr2 = 0x12345671u;\n"
    "\n"
    "    for (int i = 0; i < passlen; i++) {\n"
    "        uchar c = (uchar)((M[i >> 2] >> ((i & 3) << 3)) & 0xFFu);\n"
    "        if (c == ' ' || c == '\\t') continue;\n"
    "        uint tmp = (uint)c;\n"
    "        nr ^= (((nr & 63u) + add) * tmp) + (nr << 8);\n"
    "        nr2 += (nr2 << 8) ^ nr;\n"
    "        add += tmp;\n"
    "    }\n"
    "    nr &= 0x7fffffffu;\n"
    "    nr2 &= 0x7fffffffu;\n"
    "\n"
    "    /* Output: bswap nr and nr2 for compact table probe */\n"
    "    uint hx = ((nr >> 24) & 0xff) | ((nr >> 8) & 0xff00) |\n"
    "              ((nr << 8) & 0xff0000) | ((nr << 24) & 0xff000000u);\n"
    "    uint hy = ((nr2 >> 24) & 0xff) | ((nr2 >> 8) & 0xff00) |\n"
    "              ((nr2 << 8) & 0xff0000) | ((nr2 << 24) & 0xff000000u);\n"
    "    uint hz = 0, hw = 0;\n"
    "\n"
    "    uint4 h = uint4(hx, hy, hz, hw);\n"
    "    ulong key = (ulong(h.y) << 32) | h.x;\n"
    "    uint fp = uint(key >> 32);\n"
    "    if (fp == 0) fp = 1;\n"
    "    ulong pos = (key ^ (key >> 32)) & params.compact_mask;\n"
    "    for (uint p = 0; p < params.max_probe; p++) {\n"
    "        uint cfp = compact_fp[pos];\n"
    "        if (cfp == 0) break;\n"
    "        if (cfp == fp) {\n"
    "            uint idx = compact_idx[pos];\n"
    "            if (idx < params.hash_data_count) {\n"
    "                ulong off = hash_data_off[idx];\n"
    "                device const uint *ref = (device const uint *)(hash_data_buf + off);\n"
    "                if (h.x == ref[0] && h.y == ref[1] && h.z == ref[2] && h.w == ref[3]) {\n"
    "                    uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                    if (slot < params.max_hits) {\n"
    "                        uint base = slot * 6;\n"
    "                        hits[base] = word_idx; hits[base+1] = mask_idx;\n"
    "                        hits[base+2] = h.x; hits[base+3] = h.y;\n"
    "                        hits[base+4] = h.z; hits[base+5] = h.w;\n"
    "                    }\n"
    "                    return;\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "        pos = (pos + 1) & params.compact_mask;\n"
    "    }\n"
    "    if (params.overflow_count > 0) {\n"
    "        int lo = 0, hi = int(params.overflow_count) - 1;\n"
    "        while (lo <= hi) {\n"
    "            int mid = (lo + hi) / 2;\n"
    "            ulong mkey = overflow_keys[mid];\n"
    "            if (key < mkey) hi = mid - 1;\n"
    "            else if (key > mkey) lo = mid + 1;\n"
    "            else {\n"
    "                uint ooff = overflow_offsets[mid];\n"
    "                device const uint *oref = (device const uint *)(overflow_hashes + ooff);\n"
    "                if (h.x == oref[0] && h.y == oref[1] && h.z == oref[2] && h.w == oref[3]) {\n"
    "                    uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                    if (slot < params.max_hits) {\n"
    "                        uint base = slot * 6;\n"
    "                        hits[base] = word_idx; hits[base+1] = mask_idx;\n"
    "                        hits[base+2] = h.x; hits[base+3] = h.y;\n"
    "                        hits[base+4] = h.z; hits[base+5] = h.w;\n"
    "                    }\n"
    "                    return;\n"
    "                }\n"
    "                for (int d = mid-1; d >= 0 && overflow_keys[d] == key; d--) {\n"
    "                    oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (h.x == oref[0] && h.y == oref[1] && h.z == oref[2] && h.w == oref[3]) {\n"
    "                        uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                        if (slot < params.max_hits) {\n"
    "                            uint base = slot * 6;\n"
    "                            hits[base] = word_idx; hits[base+1] = mask_idx;\n"
    "                            hits[base+2] = h.x; hits[base+3] = h.y;\n"
    "                            hits[base+4] = h.z; hits[base+5] = h.w;\n"
    "                        }\n"
    "                        return;\n"
    "                    }\n"
    "                }\n"
    "                for (int d = mid+1; d < int(params.overflow_count) && overflow_keys[d] == key; d++) {\n"
    "                    oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                    if (h.x == oref[0] && h.y == oref[1] && h.z == oref[2] && h.w == oref[3]) {\n"
    "                        uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "                        if (slot < params.max_hits) {\n"
    "                            uint base = slot * 6;\n"
    "                            hits[base] = word_idx; hits[base+1] = mask_idx;\n"
    "                            hits[base+2] = h.x; hits[base+3] = h.y;\n"
    "                            hits[base+4] = h.z; hits[base+5] = h.w;\n"
    "                        }\n"
    "                        return;\n"
    "                    }\n"
    "                }\n"
    "                break;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "}\n"
;
